// NotSanTrainer 2025 - Prüfungsfälle (Teil 3/3, Fälle 101-150)
EXAM_CASES = EXAM_CASES.concat([
{id:"exam_anaph_e",bpr:"anaphylaxie",caseId:101,
meldung:"Gärtner, 45J, Wespenstich, Atembeschwerden, Hautröte",
ankunft:"Mann im Garten, generalisiertes Erythem, fasst sich an den Hals, Giemen hörbar.",
findings:{
vitalzeichen:"RR: 110/70 mmHg | HF: 105/min | SpO₂: 93% | AF: 22/min",
anamnese:"S: 'Wespe hat mich gestochen, kenne das schon, wird immer schlimmer.' A: Wespengift (bekannt). M: Ramipril. P: Z.n. Wespenstichallergie Grad II. L: unbekannt. E: Stich vor 15 min, progressive Symptome",
inspektion:"Generalisiertes Erythem, Stichstelle linker Unterarm geschwollen, kein Angioödem sichtbar, Engegefühl in der Brust",
auskultation:"Giemen beidseits exspiratorisch, kein Stridor",
ekg:"Sinustachykardie 105/min",
neurologie:"GCS 15, aufgeregt",
palpation:"Pulse tachykard, gut tastbar"
},
xabcde:{c:"Keine Blutung",a:"Aktuell frei, ABER: Progression möglich → engmaschig überwachen!",b:"SpO₂ 93%, Giemen → Bronchospasmus → Salbutamol + O₂",c2:"RR 110/70 → noch stabil, aber Anaphylaxie kann rasch eskalieren!",d:"GCS 15",e:"Generalisiertes Erythem, Wespenstich li Unterarm, ACE-Hemmer = Risiko für Angioödem!"},
spezial:{name:"Anaphylaxie Grad II-III",result:"Anaphylaxie Grad II (Haut + Bronchospasmus, kein Schock noch):\n→ Adrenalin 0,5 mg i.m. – Indikation ab Grad II!\n→ O₂ hochdosiert\n→ Salbutamol 4-8 Hübe bei Bronchospasmus\n→ Prednisolon 250 mg i.v.\n→ Dimetinden 4 mg i.v.\n→ VEL prophylaktisch (500 ml)\n CAVE: ACE-Hemmer erhöht Risiko für Angioödem!\n Engmaschiges Monitoring – Eskalation jederzeit möglich!"},
diagnoseOptionen:["Anaphylaxie Grad II bei Wespengiftallergie","Lokale allergische Reaktion","Panikattacke nach Wespenstich","Asthmaanfall ohne allergische Genese"],
correctDiagnose:0,
diagnoseErklaerung:"Wespenstich + bekannte Allergie + generalisiertes Erythem + Bronchospasmus = Anaphylaxie Grad II. Adrenalin 0,5 mg i.m. ist ab Grad II indiziert! CAVE: ACE-Hemmer-Einnahme."},
{id:"exam_acs_d",bpr:"acs",caseId:102,
meldung:"Retrosternaler Druck, 62J Mann, Übelkeit, Schwitzen, seit 45 min",
ankunft:"Mann sitzt in Küche, blass, schweißnass, hält sich die Brust, Übelkeit.",
findings:{
vitalzeichen:"RR: 100/60 mmHg | HF: 50/min | SpO₂: 96% | AF: 18/min",
anamnese:"S: 'Drückt in der Brust, mir ist schlecht, kalter Schweiß.' A: keine. M: ASS 100, Metoprolol 47,5. P: Hypertonie, Hyperlipidämie. L: Frühstück vor 2h. E: seit 45 min retrosternaler Druck, Beginn in Ruhe",
inspektion:"Blass, kaltschweißig, hält sich Brustbein, würgt gelegentlich",
auskultation:"Herztöne bradykard, leise. Lunge frei",
ekg:"ST-Hebung in II, III, aVF. Reziproke ST-Senkung I, aVL. Sinusbradykardie 50/min. Rechtsversorgungstyp",
neurologie:"GCS 15, ängstlich",
palpation:"Pulse bradykard, peripher kühl"
},
xabcde:{c:"Keine Blutung",a:"Frei",b:"SpO₂ 96% → O₂ nur bei <90%",c2:"RR 100/60 + HF 50 → Hinterwand-STEMI oft mit Bradykardie + Hypotonie! KEIN Nitro!",d:"GCS 15",e:"Kaltschweißig, Übelkeit → vagale Symptome typisch für Hinterwand-MI"},
spezial:{name:"STEMI Hinterwand",result:"STEMI Hinterwand (II, III, aVF):\n→ Besonderheiten:\n  • Oft Bradykardie (AV-Knoten-Versorgung!)\n  • Oft Hypotonie + Übelkeit (Vagusreiz)\n  • KEIN Nitroglycerin bei RRsyst <100!\n  • Atropin 0,5 mg bei symptom. Bradykardie\n→ Heparin 5.000 IE i.v.\n→ ASS 250 mg i.v.\n→ Morphin 3-5 mg i.v. titriert bei Schmerzen\n→ IMMER Rechtsherzinfarkt ausschließen! (V3R-V6R)\n Kein Nitro, kein Betablocker bei Hypotonie!"},
diagnoseOptionen:["STEMI Hinterwand","NSTEMI und drohender Dekompensation","Perikarditis","Aortendissektion"],
correctDiagnose:0,
diagnoseErklaerung:"ST-Hebung II, III, aVF + reziproke Senkung I, aVL + Bradykardie + Übelkeit = Hinterwand-STEMI. Kein Nitro bei RRsyst <100! Atropin bei Bradykardie. Sofort Herzkatheter!"},
{id:"exam_acs_e",bpr:"acs",caseId:103,
meldung:"Brustschmerz, 55J Raucherin, Ausstrahlung linker Arm, seit 2h",
ankunft:"Frau im Wohnzimmer, hält sich linken Arm, schmerzverzerrtes Gesicht.",
findings:{
vitalzeichen:"RR: 150/90 mmHg | HF: 88/min | SpO₂: 97% | AF: 18/min",
anamnese:"S: 'Brennen in der Brust seit 2h, zieht in den linken Arm.' A: keine. M: keine. P: 30 Pack-Years, pos. FA für KHK (Vater MI mit 52). L: Kaffee vor 1h. E: schleichend begonnen vor 2h, zunehmend",
inspektion:"Schmerzverzerrtes Gesicht, greift sich an linke Brust und Arm, leichtes Schwitzen",
auskultation:"Herztöne rein, rhythmisch. Lunge frei",
ekg:"ST-Senkung V1-V4, T-Negativierung V2-V5. Sinusrhythmus 88/min",
neurologie:"GCS 15",
palpation:"Pulse regelmäßig, gut tastbar"
},
xabcde:{c:"Keine Blutung",a:"Frei",b:"SpO₂ 97% → keine O₂-Gabe nötig",c2:"RR 150/90 → Nitro möglich. ST-Senkung anterior → NSTEMI/instabile AP!",d:"GCS 15",e:"Raucherin, pos. FA → hohes kardiovaskuläres Risiko"},
spezial:{name:"ACS – NSTEMI/instabile AP",result:"ST-Senkung + Troponin? = NSTEMI oder instabile AP:\n→ ASS 250 mg i.v.\n→ Heparin 5.000 IE i.v.\n→ Nitro 0,4 mg s.l. (RRsyst >100!)\n→ Morphin 3-5 mg i.v. titriert bei Schmerzen\n→ Ticagrelor 180 mg p.o. (Rücksprache Klinik!)\n→ Kein ST-Hebung → KEIN sofortiges Katheterlabor\n→ Aber: Hochrisiko-NSTEMI → Herzkatheter <2h!\n ST-Senkung anterior kann posterioren STEMI maskieren!"},
diagnoseOptionen:["ACS – NSTEMI mit anteriorer ST-Senkung","Stabile Angina pectoris","Muskuloskelettaler Brustschmerz","Lungenembolie bei bestehender Medikation"],
correctDiagnose:0,
diagnoseErklaerung:"Brustschmerz + Ausstrahlung li Arm + ST-Senkung V1-V4 + Risikofaktoren (Rauchen, FA) = hochgradig V.a. NSTEMI. ASS + Heparin + Nitro + Analgesie. Transport Chest Pain Unit!"},
{id:"exam_brady_d",bpr:"bradykardie",caseId:104,
meldung:"78J Frau, Schwindel, Synkope, Metoprolol-Einnahme",
ankunft:"Frau liegt am Boden, gerade wieder wach. Blass, schwindelig.",
findings:{
vitalzeichen:"RR: 75/40 mmHg | HF: 35/min | SpO₂: 94% | AF: 14/min",
anamnese:"S: 'Bin umgekippt, alles dreht sich.' A: Penicillin. M: Metoprolol 100mg 2x/d (versehentlich doppelt genommen!). P: VHF, Hypertonie. L: wenig getrunken. E: Schwindel seit 1h, dann Synkope",
inspektion:"Blass, schwindelig, orientiert, liegt am Boden neben Tisch",
auskultation:"Herztöne bradykard, rhythmisch. Lunge frei",
ekg:"Sinusbradykardie 35/min, verlängerte PQ-Zeit 280ms",
neurologie:"GCS 14 (postsynkopal), orientiert",
palpation:"Pulse bradykard 35, peripher schwach"
},
xabcde:{c:"Keine Blutung",a:"Frei",b:"SpO₂ 94% → O₂-Gabe",c2:"HF 35 + RR 75/40 → SYMPTOMATISCHE BRADYKARDIE → Atropin!",d:"GCS 14, postsynkopal",e:"Medikamentenanamnese: Betablocker-Überdosierung!"},
spezial:{name:"Bradykardie-Algorithmus",result:"Symptomatische Bradykardie:\n→ Atropin 0,5 mg i.v. (max. 3 mg)\n→ Wiederholung alle 3-5 min\n→ CAVE: bei AV-Block III° kann Atropin wirkungslos sein!\n→ Wenn Atropin unwirksam: Adrenalin 2-10 µg/min\n→ Alternativ: transkutaner Schrittmacher\n Hier: Betablocker-Überdosierung als Ursache!\n→ Glucagon 2-5 mg i.v. als spezifisches Antidot!"},
diagnoseOptionen:["Symptomatische Bradykardie bei Betablocker-Überdosierung","Vasovagale Synkope mit progredientem Verlauf","AV-Block III° bei unklarer Bewusstseinslage","Hypothyreose und vegetativer Begleitsymptomatik, bei persistierenden Symptomen trotz initialer Maßnahmen"],
correctDiagnose:0,
diagnoseErklaerung:"HF 35 + Hypotonie + Synkope + doppelte Metoprolol-Dosis = symptomatische Bradykardie durch Betablocker-Überdosierung. Atropin + ggf. Glucagon als Antidot!"},
{id:"exam_brady_e",bpr:"bradykardie",caseId:105,
meldung:"82J Mann, Schwindel, EKG: AV-Block III°",
ankunft:"Mann sitzt im Sessel, schwindelig, blass. Ehefrau besorgt.",
findings:{
vitalzeichen:"RR: 90/55 mmHg | HF: 32/min | SpO₂: 93% | AF: 16/min",
anamnese:"S: 'Mir ist seit heute morgen schwindelig, alles dreht sich.' A: keine. M: Ramipril, Amlodipine. P: Hypertonie, keine Herzerkrankung bekannt. L: Frühstück. E: Schwindel seit 4h, zunehmend",
inspektion:"Blass, schwindelig, aufrecht sitzend, kein Schweiß",
auskultation:"Herztöne bradykard, wechselnde Lautstärke, Lunge frei",
ekg:"AV-Block III° – P-Wellen und QRS-Komplexe dissoziiert. Ventrikulärer Ersatzrhythmus 32/min, breite QRS",
neurologie:"GCS 15, orientiert",
palpation:"Pulse bradykard 32, regelmäßig"
},
xabcde:{c:"Keine Blutung",a:"Frei",b:"SpO₂ 93% → O₂-Gabe",c2:"HF 32 + RR 90/55 → AV-Block III°! Atropin oft wirkungslos → Schrittmacher!",d:"GCS 15",e:"Keine äußeren Auffälligkeiten"},
spezial:{name:"AV-Block III°",result:"AV-Block III° – totale Dissoziation:\n→ Atropin 0,5 mg i.v. – kann wirken, muss aber nicht!\n→ CAVE: Atropin wirkt am AV-Knoten, nicht am Ventrikel\n→ Bei breitem QRS-Ersatzrhythmus: Atropin oft unwirksam!\n→ Adrenalin 2-10 µg/min als Brückentherapie\n→ Transkutaner Schrittmacher bereithalten!\n→ Transport mit SM-Bereitschaft\n Wechselnde HT-Lautstärke = Hinweis auf AV-Dissoziation!"},
diagnoseOptionen:["AV-Block III° mit ventrikulärem Ersatzrhythmus","Sinusbradykardie mit akuter Kreislaufdekompensation","AV-Block II° Typ Mobitz bei vorbestehender Grunderkrankung","Sick-Sinus-Syndrom mit begleitender Bewusstseinstrübung"],
correctDiagnose:0,
diagnoseErklaerung:"P-Wellen und QRS dissoziiert + ventrikulärer Ersatzrhythmus 32/min + breite QRS = AV-Block III°. Atropin versuchen, aber Schrittmacher bereithalten!"},
{id:"exam_tachy_d",bpr:"tachykardie",caseId:106,
meldung:"Herzrasen seit 3h, 67J Mann, Schwindel",
ankunft:"Mann sitzt im Sessel, blass, schwindelig, greift sich an die Brust.",
findings:{
vitalzeichen:"RR: 95/60 mmHg | HF: 160/min | SpO₂: 95% | AF: 20/min",
anamnese:"S: 'Herz rast seit Stunden, mir wird schwarz vor Augen.' A: keine. M: Apixaban, Bisoprolol (heute vergessen!). P: VHF bekannt, Hypertonie. L: Kaffee. E: Herzrasen seit 3h, Schwindel zunehmend",
inspektion:"Blass, ängstlich, im Sessel sitzend, leicht dyspnoisch",
auskultation:"Herztöne arrhythmisch, frequenzbeschleunigt, Lunge frei",
ekg:"Tachyarrhythmia absoluta bei Vorhofflimmern, HF 160/min, schmale QRS, unregelm. RR-Abstände",
neurologie:"GCS 15, schwindelig",
palpation:"Pulse arrhythmisch, tachykard, peripher schwach"
},
xabcde:{c:"Keine Blutung",a:"Frei",b:"SpO₂ 95%",c2:"HF 160 + RR 95/60 + Schwindel → INSTABIL! Frequenzkontrolle!",d:"GCS 15, Schwindel",e:"Bisoprolol vergessen → Trigger für tachykardes VHF"},
spezial:{name:"Tachykardes Vorhofflimmern",result:"Tachyarrhythmia absoluta bei VHF:\nInstabil (Hypotonie, Schwindel):\n→ Frequenzkontrolle: Amiodaron 300 mg i.v. über 20 min\n→ ODER: bei schwerer Instabilität: Kardioversion synch. 120-200J\n→ VEL 500 ml\n→ O₂ bei Bedarf\n KEIN Adenosin! (wirkt nur bei SVT, nicht bei VHF!)\n CAVE: Betablocker bei Hypotonie kontraindiziert!\n Patient nimmt Apixaban → antikoaguliert → Kardioversion möglich"},
diagnoseOptionen:["Tachykardes Vorhofflimmern","Supraventrikuläre Tachykardie","Vorhofflattern","Ventrikuläre Tachykardie"],
correctDiagnose:0,
diagnoseErklaerung:"Bekanntes VHF + arrhythmische Herzaktion + schmale QRS + irreguläre RR-Abstände + HF 160 = tachykardes Vorhofflimmern. Frequenzkontrolle mit Amiodaron, bei Instabilität Kardioversion."},
{id:"exam_tachy_e",bpr:"tachykardie",caseId:107,
meldung:"Herzrasen, 58J Mann, Z.n. Herzinfarkt, Präsynkope",
ankunft:"Mann liegt auf Sofa, blass, schweißnass, klagt über Herzrasen.",
findings:{
vitalzeichen:"RR: 80/50 mmHg | HF: 180/min | SpO₂: 92% | AF: 22/min",
anamnese:"S: 'Herz rast, mir ist schwarz geworden.' A: Kontrastmittel. M: ASS, Bisoprolol, Ramipril, Atorvastatin. P: Z.n. MI 2020, 2 Stents LAD. L: Mittagessen. E: plötzlich Herzrasen vor 20 min",
inspektion:"Blass, schweißnass, liegt, ängstlich",
auskultation:"Herztöne tachykard, rhythmisch, Lunge frei",
ekg:"Breitkomplex-Tachykardie 180/min, monomorph, AV-Dissoziation sichtbar",
neurologie:"GCS 14, benommen",
palpation:"Pulse tachykard 180, regelmäßig, peripher kaum tastbar"
},
xabcde:{c:"Keine Blutung",a:"Frei",b:"SpO₂ 92% → O₂-Gabe",c2:"HF 180 + RR 80/50 + breite QRS → VT! INSTABIL → KARDIOVERSION!",d:"GCS 14, Präsynkope",e:"Z.n. MI → VT bei ischämischer Kardiomyopathie!"},
spezial:{name:"Ventrikuläre Tachykardie",result:"VT bei instabilem Patient:\n→ SOFORT synchronisierte Kardioversion!\n→ Beginn 120J biphasisch\n→ Sedierung: Midazolam 2-3 mg i.v. oder Esketamin\n→ Bei Misserfolg: Amiodaron 300 mg i.v. über 20 min\n→ Defibrillationsbereitschaft!\n CAVE: Breitkomplex-Tachykardie = VT bis Gegenteil bewiesen!\n AV-Dissoziation = BEWEIS für VT!\n KEIN Adenosin bei Breitkomplex-Tachykardie!"},
diagnoseOptionen:["Ventrikuläre Tachykardie","SVT mit Schenkelblock","Vorhofflimmern mit Präexzitation","Torsade de Pointes"],
correctDiagnose:0,
diagnoseErklaerung:"Z.n. MI + Breitkomplex + HF 180 + AV-Dissoziation = ventrikuläre Tachykardie. Instabil → sofort synchronisierte Kardioversion! AV-Dissoziation beweist VT."},
{id:"exam_apoplex_d",bpr:"schlaganfall",caseId:108,
meldung:"Plötzliche Sprachstörung, 71J Frau, Schwäche rechter Arm",
ankunft:"Frau sitzt am Küchentisch, kann nicht sprechen, rechter Arm hängt herab.",
findings:{
vitalzeichen:"RR: 190/100 mmHg | HF: 82/min | SpO₂: 97% | AF: 16/min | BZ: 95 mg/dl",
anamnese:"S: Ehemann: 'Plötzlich konnte sie nicht mehr sprechen, Arm bewegt sich nicht.' A: keine. M: Apixaban, Amlodipin. P: VHF, Hypertonie. L: Frühstück. E: Symptombeginn vor 90 min, plötzlich",
inspektion:"Sitzt aufrecht, Blickdeviation nach links, globale Aphasie, hängendes Gesicht rechts",
auskultation:"Herztöne arrhythmisch (VHF), Lunge frei",
ekg:"Vorhofflimmern 82/min, keine ST-Veränderungen",
neurologie:"GCS 12 (A4V2M6), globale Aphasie, Hemiparese rechts (Arm 0/5, Bein 3/5), Fazialisparese rechts, Blickdeviation links, BE-FAST positiv",
palpation:"Pulse arrhythmisch"
},
xabcde:{c:"Keine Blutung",a:"Frei, aber Aspirationsgefahr bei Aphasie!",b:"SpO₂ 97%",c2:"RR 190/100 → NICHT senken! Erst in Stroke Unit!",d:"Aphasie + Hemiparese re + Blickdeviation → großes Mediainfarkt-Syndrom",e:"VHF als Emboliequelle!"},
spezial:{name:"Schlaganfall-Management",result:"Akuter Schlaganfall (ischämisch wahrscheinlich):\n→ BE-FAST positiv → Stroke Unit anmelden!\n→ Symptombeginn dokumentieren: vor 90 min → Lyse-Fenster!\n→ RR NICHT senken (erst ab >220 systolisch!)\n→ BZ kontrollieren (Hypoglykämie ausschließen!)\n→ Oberkörper 30° Hochlagerung\n→ Antikoagulation unter Apixaban → Klinik informieren!\n→ Monitoring, O₂ nur bei SpO₂ <94%\n Lysefenster: <4,5h! CT-Angiographie entscheidend!"},
diagnoseOptionen:["Akuter ischämischer Schlaganfall (Mediainfarkt links)","Intrazerebrale Blutung und hämodynamischer Instabilität","Epileptischer Anfall mit Todd'scher Parese","Migräne mit Aura mit respiratorischer Insuffizienz"],
correctDiagnose:0,
diagnoseErklaerung:"Plötzliche Aphasie + Hemiparese rechts + Blickdeviation links + VHF als Emboliequelle = hochgradig V.a. ischämischer Mediainfarkt links. Symptombeginn 90 min → Lysefenster offen!"},
{id:"exam_apoplex_e",bpr:"schlaganfall",caseId:109,
meldung:"Verwirrtheit, 64J Diabetiker, Hemiparese links, Schwitzen",
ankunft:"Mann am Boden, verwirrt, schwitzt, linke Körperseite schwach.",
findings:{
vitalzeichen:"RR: 160/90 mmHg | HF: 100/min | SpO₂: 96% | AF: 18/min | BZ: 38 mg/dl",
anamnese:"S: Ehefrau: 'War plötzlich verwirrt, Arm und Bein links bewegen sich kaum.' A: keine. M: Insulin, Metformin, ASS. P: Diabetes Typ 2, Hypertonie. L: hat Mittagessen ausgelassen. E: vor 30 min plötzlich aufgetreten",
inspektion:"Am Boden, schweißnass, verwirrt, greift mit rechter Hand umher",
auskultation:"Herztöne tachykard, Lunge frei",
ekg:"Sinustachykardie 100/min",
neurologie:"GCS 12 (A3V3M6), verwirrt, Hemiparese links (Arm 2/5, Bein 3/5), kein Meningismus",
palpation:"Pulse tachykard, Haut feucht-warm"
},
xabcde:{c:"Keine Blutung",a:"Frei",b:"SpO₂ 96%",c2:"RR 160/90, HF 100",d:"GCS 12 + Hemiparese links + BZ 38! → HYPOGLYKÄMIE als Stroke Mimic!",e:"Schweißnass, Diabetiker, Mahlzeit ausgelassen"},
spezial:{name:"Stroke Mimic – Hypoglykämie",result:"Hypoglykämie als Stroke Mimic!\n→ BZ 38 mg/dl → ZUERST Hypoglykämie behandeln!\n→ Glucose 40% 10-20 ml i.v. (= 4-8 g Glucose)\n→ Nach BZ-Korrektur: Neurologie re-evaluieren!\n→ Wenn Symptome persistieren → doch Schlaganfall → Stroke Unit!\n→ Wenn Symptome sich bessern → Hypoglykämie war Ursache\n IMMER BZ messen bei V.a. Schlaganfall!\n Hypoglykämie kann JEDES neurologische Defizit imitieren!"},
diagnoseOptionen:["Stroke Mimic – Hypoglykämie","Akuter ischämischer Schlaganfall","Intrazerebrale Blutung","Epileptischer Anfall"],
correctDiagnose:0,
diagnoseErklaerung:"Hemiparese + Verwirrtheit ABER BZ 38 mg/dl + Schwitzen + Mahlzeit ausgelassen = Hypoglykämie als Stroke Mimic. Erst Glucose geben, dann re-evaluieren! IMMER BZ messen bei V.a. Schlaganfall!"},
{id:"exam_bronch_d",bpr:"bronchial",caseId:110,
meldung:"22J Frau, schwerer Asthmaanfall, kann nur Einzelworte sprechen",
ankunft:"Junge Frau sitzt aufrecht auf Bettkante, kämpft um Luft, kann nur Einzelworte sprechen.",
findings:{
vitalzeichen:"RR: 130/80 mmHg | HF: 130/min | SpO₂: 86% | AF: 35/min",
anamnese:"S: Mitbewohnerin: 'Hat ihr Asthmaspray benutzt, hilft nicht mehr!' A: keine. M: Salbutamol DA, Budesonid DA (unregelmäßig). P: Asthma seit Kindheit, 2x Intensivstation. L: unbekannt. E: Atemnot seit 2h, rapide Verschlechterung letzte 30 min",
inspektion:"Aufrecht, Orthopnoe, Einsatz der Atemhilfsmuskulatur, Einziehungen interkostal und jugulär, kann nur Einzelworte",
auskultation:"Giemen beidseits massiv exspiratorisch, verlängertes Exspirium, teilweise Silent Chest basal!",
ekg:"Sinustachykardie 130/min",
neurologie:"GCS 14, erschöpft, agitiert",
palpation:"Pulse tachykard, Haut feucht"
},
xabcde:{c:"Keine Blutung",a:"Frei, aber drohende Erschöpfung!",b:"SpO₂ 86%, AF 35, Silent Chest → LEBENSBEDROHLICH!",c2:"Tachykardie reaktiv",d:"GCS 14, agitiert → Erschöpfung droht",e:"2x ICU-Aufenthalte → Hochrisikopatientin!"},
spezial:{name:"Lebensbedrohlicher Asthmaanfall",result:"Lebensbedrohlich (Silent Chest, SpO₂ <92%):\n→ O₂ hochdosiert (15L Maske mit Reservoir)\n→ Salbutamol 4-8 Hübe alle 10 min (oder Vernebler)\n→ Ipratropiumbromid 4 Hübe\n→ Prednisolon 100 mg i.v.\n→ Magnesiumsulfat 2 g i.v. über 20 min\n→ Adrenalin vernebelt 3-5 mg ODER i.m. 0,5 mg\n→ Bei Erschöpfung: Intubation vorbereiten!\n Silent Chest = KEIN gutes Zeichen → Luft bewegt sich kaum!"},
diagnoseOptionen:["Lebensbedrohlicher Asthmaanfall","Pneumothorax bei unklarer Ätiologie","Lungenembolie mit neurologischem Defizit","Fremdkörperaspiration"],
correctDiagnose:0,
diagnoseErklaerung:"Bekanntes Asthma + Einzelworte + SpO₂ 86% + Silent Chest basal + Atemhilfsmuskulatur = lebensbedrohlicher Asthmaanfall. Sofort: O₂, Salbutamol, Prednisolon, Magnesium!"},
{id:"exam_bronch_e",bpr:"bronchial",caseId:111,
meldung:"72J COPD-Patient, Atemnot, Lippenzyanose, Giemen",
ankunft:"Mann sitzt am Bettrand, Lippenzyanose, pfeifende Atmung hörbar.",
findings:{
vitalzeichen:"RR: 150/90 mmHg | HF: 110/min | SpO₂: 82% | AF: 28/min",
anamnese:"S: 'Bekomme seit gestern immer schlechter Luft, Auswurf ist gelb-grünlich.' A: keine. M: Tiotropium, Formoterol/Budesonid, Prednisolon 5mg. P: COPD GOLD IV, 2 Exazerbationen/Jahr, O₂-Langzeittherapie. L: kaum gegessen. E: zunehmende Atemnot seit 24h, heute akut verschlechtert",
inspektion:"Fassthorax, Lippenzyanose, Einsatz Atemhilfsmuskulatur, eitriger Auswurf",
auskultation:"Giemen beidseits, verlängertes Exspirium, basal abgeschwächtes Atemgeräusch",
ekg:"Sinustachykardie 110/min, P-pulmonale",
neurologie:"GCS 14, erschöpft, spricht in kurzen Sätzen",
palpation:"Pulse tachykard"
},
xabcde:{c:"Keine Blutung",a:"Frei",b:"SpO₂ 82% → O₂ titriert! Ziel 88-92% bei COPD! NICHT zu viel!",c2:"Tachykardie reaktiv",d:"GCS 14, erschöpft",e:"Eitriger Auswurf → infektexazerbierte COPD"},
spezial:{name:"COPD-Exazerbation",result:"Akute COPD-Exazerbation:\n→ O₂: Ziel SpO₂ 88-92% (CAVE: CO₂-Narkose!)\n→ Salbutamol 4-8 Hübe\n→ Ipratropiumbromid 4 Hübe\n→ Prednisolon 40-50 mg i.v.\n→ Bei schwerer Dyspnoe: CPAP/NIV erwägen!\n→ Eitriger Auswurf → Antibiotikum klinisch\n CAVE bei COPD: O₂ nicht über 92%!\n Hypoxischer Atemantrieb → CO₂-Narkose bei Hyperoxie!"},
diagnoseOptionen:["Infektexazerbierte COPD","Pneumonie ohne COPD","Lungenembolie","Herzinsuffizienz mit Lungenstauung"],
correctDiagnose:0,
diagnoseErklaerung:"COPD GOLD IV + zunehmende Dyspnoe + eitriger Auswurf + Giemen + SpO₂ 82% = infektexazerbierte COPD. O₂ titriert auf 88-92%! Salbutamol + Ipratropium + Prednisolon."},
{id:"exam_krampf_d",bpr:"krampf_erw",caseId:112,
meldung:"35J Mann, Epilepsie, Krampfanfall seit 8 min, zyanotisch",
ankunft:"Mann am Boden, generalisiert tonisch-klonischer Krampfanfall, Schaumbildung vor dem Mund.",
findings:{
vitalzeichen:"RR: 180/100 mmHg | HF: 140/min | SpO₂: 78% | AF: unregelmäßig",
anamnese:"S: Partnerin: 'Hat Epilepsie, krampft seit 8 Minuten, hört nicht auf!' A: keine. M: Levetiracetam (unregelmäßig eingenommen). P: Epilepsie seit 10 Jahren, letzter Anfall 3 Monate. L: unbekannt. E: plötzlich begonnen, generalisiert",
inspektion:"Tonisch-klonischer Anfall, Schaum vor Mund (blutig), Zyanose, Einnässen, Verletzung an Stirn",
auskultation:"Nicht beurteilbar bei aktivem Krampfanfall",
ekg:"Sinustachykardie 140/min (Artefakte durch Krampf)",
neurologie:"GCS 3 (während Krampf), generalisierte tonisch-klonische Aktivität",
palpation:"Nicht beurteilbar bei Krampf"
},
xabcde:{c:"Blutung an Stirn (Bagatelle)",a:"Gefährdet durch Schaum/Blut → Absaugbereitschaft, Seitenlage nach Anfall",b:"SpO₂ 78% → O₂ + Beatmungsbereitschaft",c2:"Tachykardie + Hypertonie reaktiv",d:"Status epilepticus! >5 min → Benzodiazepin!",e:"Lateraler Zungenbiss, Einnässen = typisch generalisiert"},
spezial:{name:"Status epilepticus",result:"Status epilepticus (>5 min oder Serie ohne Aufklaren):\n→ Midazolam 10 mg intranasal/bukkal/i.m.\n→ ODER: Diazepam 10 mg i.v.\n→ O₂ hochdosiert\n→ Wenn nach 5 min keine Besserung: 2. Dosis\n→ BZ messen! (Hypoglykämie als Ursache?)\n→ Atemwegssicherung vorbereiten\n→ Kein Beißkeil! Nichts in den Mund!\n Blutiger Schaum = Zungenbiss, NICHT Lungenödem!"},
diagnoseOptionen:["Status epilepticus bei bekannter Epilepsie","Hypoglykämischer Krampfanfall","Synkope mit Konvulsionen bei Z.n. Trauma ohne relevante Vorerkrankungen in der Eigenanamnese","Psychogener nicht-epileptischer Anfall"],
correctDiagnose:0,
diagnoseErklaerung:"Bekannte Epilepsie + generalisierter tonisch-klonischer Krampf >5 min + Zungenbiss + Einnässen = Status epilepticus. Midazolam 10 mg intranasal sofort!"},
{id:"exam_krampf_e",bpr:"krampf_erw",caseId:113,
meldung:"16J Schüler, erstmaliger Krampfanfall im Klassenzimmer",
ankunft:"Jugendlicher liegt am Boden, postiktal, Mitschüler aufgeregt. Anfall hat 2 min gedauert.",
findings:{
vitalzeichen:"RR: 140/85 mmHg | HF: 100/min | SpO₂: 96% | AF: 18/min | BZ: 110 mg/dl",
anamnese:"S: Lehrerin: 'Ist plötzlich umgefallen, hat gezuckt, ca. 2 min.' A: keine. M: keine. P: keine bekannt, war heute Nacht auf Party (wenig Schlaf). L: kein Frühstück. E: plötzlich im Unterricht, generalisiert, 2 min, spontan sistiert",
inspektion:"Postiktal, verlangsamt, desorientiert, lateraler Zungenbiss rechts, kein Einnässen",
auskultation:"Herztöne rhythmisch, Lunge frei",
ekg:"Sinusrhythmus 100/min",
neurologie:"GCS 10 (A3V3M4) postiktal, keine fokalen Defizite erkennbar, Pupillen isokor, Meningismus negativ",
palpation:"Pulse regelmäßig, keine Auffälligkeiten"
},
xabcde:{c:"Keine Blutung",a:"Frei, stabile Seitenlage",b:"SpO₂ 96%",c2:"RR und HF leicht erhöht (postikal normal)",d:"GCS 10, postiktal → Re-Evaluation in 10-15 min!",e:"Zungenbiss lateral = typisch epileptisch. Schlafmangel als Trigger?"},
spezial:{name:"Erstmaliger Krampfanfall",result:"Erstmaliger Krampfanfall bei Jugendlichem:\n→ Kein Benzodiazepin nötig (Anfall bereits sistiert!)\n→ BZ messen (✓ 110 mg/dl → normal)\n→ O₂ bei Bedarf\n→ Monitoring bis postiktale Phase abklingt\n→ Stabile Seitenlage\n→ GCS-Verlauf dokumentieren\n→ Kliniktransport zur Erstdiagnostik (EEG, MRT)\n Lateraler Zungenbiss = hohe Spezifität für epileptischen Anfall!\n Schlafmangel = häufiger Trigger!"},
diagnoseOptionen:["Erstmaliger epileptischer Krampfanfall","Synkope mit Konvulsionen","Drogenintoxikation mit metabolischer Entgleisung","Psychogener Anfall und sekundärer Organbeteiligung"],
correctDiagnose:0,
diagnoseErklaerung:"Erstmalig + generalisiert tonisch-klonisch + lateraler Zungenbiss + Schlafmangel als Trigger + postiktale Verwirrtheit = erstmaliger epileptischer Krampfanfall. Transport zur Erstdiagnostik."},
{id:"exam_krampf_kind_d",bpr:"krampf_kind",caseId:114,
meldung:"18 Monate, Fieber 39,8°C, generalisierter Krampf seit 3 min",
ankunft:"Kleinkind krampft auf dem Arm der Mutter, generalisierte Zuckungen, Fieber.",
findings:{
vitalzeichen:"HF: 160/min | SpO₂: 91% | AF: 30/min | Temp: 39,8°C | BZ: 100 mg/dl",
anamnese:"S: Mutter: 'Hatte Fieber, plötzlich angefangen zu zucken!' A: keine. M: Ibuprofen-Saft. P: gesund, Impfungen aktuell. L: wenig getrunken. E: Krampf seit 3 min",
inspektion:"Generalisierte tonisch-klonische Zuckungen, gerötet, heiß",
auskultation:"Herztöne tachykard, Lunge frei",
ekg:"Sinustachykardie",
neurologie:"GCS nicht beurteilbar (krampfend)",
palpation:"Haut heiß, gerötet"
},
xabcde:{c:"Keine Blutung",a:"Sichern, Seitenlage wenn möglich",b:"SpO₂ 91% → O₂-Gabe",c2:"HF 160 bei Fieber und Krampf → reaktiv",d:"Aktiver Krampfanfall → wenn >5 min: Midazolam!",e:"Temp 39,8°C → Fieberkrampf!"},
spezial:{name:"Fieberkrampf",result:"Fieberkrampf (unkompliziert wenn <15 min, generalisiert, 6M-5J):\n→ Meist selbstlimitierend in 2-5 min\n→ Wenn >5 min: Midazolam 0,2 mg/kg bukkal/intranasal\n→ O₂-Gabe\n→ Fiebersenkung: Paracetamol 15 mg/kg rektal\n→ Kein Festhalten, nichts in den Mund!\n→ BZ messen!\n→ Transport zur pädiatrischen Abklärung\n Eltern beruhigen! Fieberkrämpfe sind meist harmlos!"},
diagnoseOptionen:["Einfacher Fieberkrampf","Status epilepticus","Meningitis mit Krampfanfall","Intoxikation"],
correctDiagnose:0,
diagnoseErklaerung:"18 Monate + Fieber 39,8°C + generalisierter Krampf + zuvor gesund = einfacher Fieberkrampf. Abwarten ob selbstlimitierend, ab 5 min Midazolam. Fiebersenkung!"},
{id:"exam_krampf_kind_e",bpr:"krampf_kind",caseId:115,
meldung:"6 Monate Säugling, subtile Zuckungen, Blickdeviation, Apnoe",
ankunft:"Säugling auf dem Wickeltisch, subtile rhythmische Zuckungen, starrer Blick nach oben.",
findings:{
vitalzeichen:"HF: 180/min | SpO₂: 85% | AF: 8/min (Apnoephasen) | Temp: 38,2°C",
anamnese:"S: Mutter: 'Zuckt komisch, atmet manchmal nicht, Augen verdreht.' A: keine. M: keine. P: gesund, Frühgeboren 34. SSW. L: vor 2h gestillt. E: seit 10 min intermittierend",
inspektion:"Subtile rhythmische Lidzuckungen, Blickdeviation nach oben, Apnoephasen, gelegentlich Ruderbewegungen der Arme",
auskultation:"Herztöne tachykard, Lunge frei",
ekg:"Sinustachykardie 180/min",
neurologie:"Reduzierter Muskeltonus, Blickdeviation, rhythmische subtile Myoklonien, Fontanelle nicht vorgewölbt",
palpation:"Haut warm, HF tachykard"
},
xabcde:{c:"Keine Blutung",a:"Apnoephasen! → Beatmungsbereitschaft!",b:"SpO₂ 85% + Apnoe → O₂, stimulieren, ggf. Beutelbeatmung!",c2:"HF 180 bei Säugling → Stress/Hypoxie",d:"Subtile Krampfzeichen beim Säugling! Leicht zu übersehen!",e:"Frühgeboren + Temp 38,2°C → Meningitis/Sepsis ausschließen!"},
spezial:{name:"Neonatale/infantile Krampfanfälle",result:"Subtile Krampfanfälle beim Säugling:\n→ Oft NICHT tonisch-klonisch!\n→ Zeichen: Blickdeviation, Lidzuckungen, Ruderbewegungen, Apnoe!\n→ Midazolam 0,1-0,2 mg/kg i.v./i.o./intranasal\n→ O₂, Beatmungsbereitschaft!\n→ BZ messen!\n→ DRINGEND Klinik → Meningitis, Sepsis, Hirnblutung ausschließen!\n→ Frühgeboren → erhöhtes Risiko für zerebrale Pathologie!\n Apnoe beim Säugling kann Krampfäquivalent sein!"},
diagnoseOptionen:["Subtiler Krampfanfall beim Säugling","Apnoe durch Reflux bei infektiöser Genese","Fieberkrampf mit kardialer Beteiligung","Normales Säuglingsverhalten"],
correctDiagnose:0,
diagnoseErklaerung:"Säugling + rhythmische subtile Zuckungen + Blickdeviation + Apnoephasen = subtiler Krampfanfall. Bei Säuglingen oft NICHT klassisch tonisch-klonisch! Sofort Klinik, Meningitis ausschließen!"},
{id:"exam_hypoglyk_d",bpr:"hypoglyk",caseId:116,
meldung:"Bewusstloser Diabetiker, 52J, Insulinpumpe, Schwitzen",
ankunft:"Mann liegt am Boden im Büro, bewusstlos, schweißnass, Insulinpumpe sichtbar.",
findings:{
vitalzeichen:"RR: 150/90 mmHg | HF: 110/min | SpO₂: 97% | AF: 20/min | BZ: 22 mg/dl",
anamnese:"S: Kollege: 'War heute morgen schon komisch, dann umgefallen.' A: keine. M: Insulinpumpe (Typ 1 Diabetes). P: DM Typ 1 seit 20 Jahren. L: Frühstück ausgelassen. E: zunehmend verwirrt, dann Bewusstlosigkeit",
inspektion:"Bewusstlos, schweißnass, blass, Tremor, Insulinpumpe am Bauch",
auskultation:"Herztöne tachykard, Lunge frei",
ekg:"Sinustachykardie 110/min",
neurologie:"GCS 6 (A1V2M3), Pupillen isokor, keine fokalen Defizite, Babinski negativ bds.",
palpation:"Haut feucht, kalt"
},
xabcde:{c:"Keine Blutung",a:"Bei GCS 6 → Atemweg gefährdet! Seitenlage!",b:"SpO₂ 97%",c2:"Tachykardie + Hypertonie → adrenerge Gegenregulation",d:"GCS 6 + BZ 22 mg/dl → SCHWERE HYPOGLYKÄMIE!",e:"Schweißnass, Tremor, Insulinpumpe → Insulinüberdosierung?"},
spezial:{name:"Schwere Hypoglykämie",result:"Schwere Hypoglykämie (BZ <40 mg/dl, bewusstlos):\n→ Glucose 40% 10-20 ml i.v. (= 4-8 g)\n→ Wenn kein i.v.-Zugang: Glucagon 1 mg i.m.\n→ Insulinpumpe stoppen/entfernen!\n→ BZ-Kontrolle alle 5 min\n→ Nach Aufwachen: Langwirksame KH (Brot, Saft)\n→ Ursache klären: Mahlzeit ausgelassen? Pumpendefekt?\n CAVE: Hypoglykämie kann fokale Neurologie imitieren!"},
diagnoseOptionen:["Schwere Hypoglykämie bei Insulinpumpen-Überdosierung","Epileptischer Anfall und drohender Dekompensation","Schlaganfall bei bestehender Medikation","Intoxikation mit progredientem Verlauf mit Notwendigkeit der sofortigen klinischen Abklärung"],
correctDiagnose:0,
diagnoseErklaerung:"Diabetiker + Insulinpumpe + BZ 22 mg/dl + bewusstlos + Schwitzen = schwere Hypoglykämie. Glucose 40% i.v. sofort! Insulinpumpe stoppen!"},
{id:"exam_hypoglyk_e",bpr:"hypoglyk",caseId:117,
meldung:"4J Kind, plötzlich schlapp und verwirrt, Schwitzen, BZ 35",
ankunft:"Kind liegt auf Sofa, schlapp, verwirrt, schwitzt, Mutter besorgt.",
findings:{
vitalzeichen:"HF: 120/min | SpO₂: 98% | AF: 22/min | BZ: 35 mg/dl | Temp: 36,5°C",
anamnese:"S: Mutter: 'War den ganzen Tag normal, plötzlich komisch und schlapp.' A: keine. M: keine. P: gesund, kein Diabetes bekannt. L: Mittagessen normal. E: plötzlich vor 20 min",
inspektion:"Kind schlapp, verwirrt, blass, schweißnass",
auskultation:"Herztöne tachykard, Lunge frei",
ekg:"Sinustachykardie",
neurologie:"GCS 13, verwirrt, reagiert auf Ansprache, keine fokalen Defizite",
palpation:"Haut feucht, kühl"
},
xabcde:{c:"Keine Blutung",a:"Frei",b:"SpO₂ 98%",c2:"HF 120 → Stressreaktion",d:"GCS 13, verwirrt + BZ 35 → Hypoglykämie!",e:"Kein bekannter Diabetes → Ursache abklären!"},
spezial:{name:"Hypoglykämie beim Kind",result:"Hypoglykämie Kind (BZ <50 mg/dl):\n→ Bei wachem Kind: Traubenzucker oral, Saft\n→ Bei eingeschränktem Bewusstsein:\n  Glucose 10% 2 ml/kg i.v. (= 0,2 g/kg)\n  KEIN Glucose 40% beim Kind (Venenreizung!)\n→ BZ-Kontrolle alle 5 min\n→ Kein bekannter Diabetes → Ursache klären in Klinik!\n  (Insulinom, Stoffwechselerkrankung, Intoxikation?)\n Dosis: 16 kg × 2 ml/kg = 32 ml G10% i.v."},
diagnoseOptionen:["Hypoglykämie unklarer Genese","Epileptischer Anfall","Meningitis","Intoxikation mit Süßungsmittel"],
correctDiagnose:0,
diagnoseErklaerung:"Kind + BZ 35 mg/dl + Verwirrtheit + Schwitzen = Hypoglykämie. Kein bekannter Diabetes → Klinikabklärung zwingend! Glucose 10% 2 ml/kg i.v."},
{id:"exam_hyperglyk_d",bpr:"hyperglyk",caseId:118,
meldung:"24J Typ-1-Diabetikerin, BZ 450, Kussmaul-Atmung, Acetongeruch",
ankunft:"Junge Frau liegt auf Sofa, riecht nach Aceton, atmet tief und schnell.",
findings:{
vitalzeichen:"RR: 90/55 mmHg | HF: 120/min | SpO₂: 98% | AF: 30/min (Kussmaul) | BZ: 450 mg/dl",
anamnese:"S: Mitbewohnerin: 'Hat seit 2 Tagen Magen-Darm, konnte nicht essen, hat kein Insulin gespritzt.' A: keine. M: Insulin Aspart/Glargin (seit 2 Tagen pausiert). P: DM Typ 1 seit Kindheit. L: Erbrechen seit 2 Tagen. E: zunehmend schwächer, heute Kussmaul-Atmung",
inspektion:"Exsikkiert, eingefallene Augen, trockene Schleimhäute, Kussmaul-Atmung, Acetongeruch",
auskultation:"Herztöne tachykard, Lunge frei",
ekg:"Sinustachykardie 120/min, evtl. T-Wellen-Veränderungen (Kalium?)",
neurologie:"GCS 12 (A3V4M5), verlangsamt, desorientiert zu Zeit",
palpation:"Stehende Hautfalten, Pulse tachykard, peripher schwach"
},
xabcde:{c:"Keine Blutung",a:"Frei (Kussmaul ≠ Atemnot, sondern Kompensation!)",b:"AF 30, Kussmaul → metabolische Azidose → KEIN CPAP!",c2:"RR 90/55 → VOLUMENMANGELSCHOCK! VEL aggressiv!",d:"GCS 12, desorientiert",e:"Exsikkiert, Acetongeruch, BZ 450 → DKA!"},
spezial:{name:"Diabetische Ketoazidose",result:"Diabetische Ketoazidose (DKA):\n→ VEL: NaCl 0,9% 1000 ml Bolus, dann 500 ml/h\n→ KEIN Insulin präklinisch! (Kaliumverschiebung!)\n→ Kussmaul-Atmung ist Kompensation → NICHT unterdrücken!\n→ Keine Intubation wenn möglich (CO₂-Abatmung!)\n→ O₂ bei Bedarf\n→ Monitoring: BZ, GCS, Vitalzeichen\n→ Transport mit Voranmeldung (Intensivstation)\n Insulin erst in Klinik nach Kalium-Kontrolle!"},
diagnoseOptionen:["Diabetische Ketoazidose","Sepsis mit Hyperglykämie","Hyperosmolares Koma","Alkoholische Ketoazidose"],
correctDiagnose:0,
diagnoseErklaerung:"DM Typ 1 + Insulin pausiert + BZ 450 + Kussmaul + Acetongeruch + Exsikkose = Diabetische Ketoazidose. VEL aggressiv, KEIN Insulin präklinisch!"},
{id:"exam_hyperglyk_e",bpr:"hyperglyk",caseId:119,
meldung:"10J Kind, Diabetes Typ 1, BZ 380, Erbrechen, Polyurie",
ankunft:"Kind liegt im Bett, schlapp, Erbrechen seit Stunden.",
findings:{
vitalzeichen:"HF: 130/min | SpO₂: 99% | AF: 26/min | BZ: 380 mg/dl | Temp: 37,2°C",
anamnese:"S: Mutter: 'Seit 2 Tagen viel Durst und Pipi, heute Erbrechen, immer schlapper.' A: keine. M: Insulin (Pen). P: DM Typ 1 seit 4 Jahren. L: Erbrechen. E: zunehmend",
inspektion:"Schlapp, blass, trockene Lippen, vertiefte Atmung",
auskultation:"Herztöne tachykard, Lunge frei",
ekg:"Sinustachykardie",
neurologie:"GCS 14, müde aber orientiert",
palpation:"Stehende Hautfalten, Haut trocken"
},
xabcde:{c:"Keine Blutung",a:"Frei",b:"AF 26 → beginnende Kompensation der Azidose",c2:"HF 130 → Volumenmangel",d:"GCS 14",e:"Dehydriert, BZ 380 → DKA beim Kind"},
spezial:{name:"DKA beim Kind",result:"DKA beim Kind – Besonderheiten:\n→ VEL: NaCl 0,9% 10-20 ml/kg über 1h (VORSICHTIG!)\n→ CAVE: Zu schnelle Rehydrierung → Hirnödem beim Kind!\n→ KEIN Insulin präklinisch!\n→ KEIN Bicarbonat!\n→ Monitoring: BZ, GCS engmaschig\n→ Transport Kinderklinik mit Intensivstation\n Kinder mit DKA: Hirnödem ist die gefährlichste Komplikation!"},
diagnoseOptionen:["Diabetische Ketoazidose beim Kind","Gastroenteritis bei unklarer Bewusstseinslage","Appendizitis mit Erbrechen","Harnwegsinfektion und vegetativer Begleitsymptomatik"],
correctDiagnose:0,
diagnoseErklaerung:"Kind + DM Typ 1 + BZ 380 + Erbrechen + Dehydrierung + vertiefte Atmung = DKA. Vorsichtige VEL (Hirnödem-Risiko!), kein Insulin präklinisch."},
{id:"exam_sepsis_d",bpr:"sepsis",caseId:120,
meldung:"76J Frau, Pflegeheim, Fieber 39,5°C, verwirrt, Dauerkatheter",
ankunft:"Frau im Pflegebett, verwirrt, Schüttelfrost, Dauerkatheter mit trübem Urin.",
findings:{
vitalzeichen:"RR: 85/55 mmHg | HF: 120/min | SpO₂: 92% | AF: 24/min | Temp: 39,5°C | BZ: 160 mg/dl",
anamnese:"S: Pflege: 'Seit heute morgen Fieber, verwirrt, Urin stinkt.' A: Ciprofloxacin. M: Ramipril, Metformin, Torasemid. P: DM Typ 2, Herzinsuffizienz, rez. HWI, Dauerkatheter. L: verweigert Essen. E: akut seit heute morgen",
inspektion:"Im Bett, Schüttelfrost, verwirrt, blass-marmoriert, Dauerkatheter mit trüb-eitrigem Urin",
auskultation:"Herztöne tachykard, Lunge: basale feuchte RG beidseits",
ekg:"Sinustachykardie 120/min",
neurologie:"GCS 13 (A4V3M6), desorientiert, keine fokalen Defizite",
palpation:"Suprapubisch nicht schmerzhaft, Flanken klopfempfindlich bds., Rekapzeit >4s, peripher kühl"
},
xabcde:{c:"Keine Blutung",a:"Frei",b:"SpO₂ 92%, AF 24 → O₂-Gabe",c2:"RR 85/55 + HF 120 + Rekapzeit >4s → SEPTISCHER SCHOCK!",d:"GCS 13, verwirrt → qSOFA ≥2",e:"Fieber + trüber DK-Urin + Schüttelfrost → Urosepsis!"},
spezial:{name:"qSOFA + Sepsistherapie",result:"qSOFA: AF ≥22 ✓, Bewusstseinsänderung ✓, RRsyst ≤100 ✓ = 3/3\n→ Sepsis hochwahrscheinlich!\nTherapie:\n→ VEL: 500-1000 ml NaCl 0,9% i.v. schnell!\n→ O₂-Gabe\n→ BZ-Kontrolle (Hyperglykämie bei Sepsis häufig)\n→ Monitoring eng\n→ Transport mit Voranmeldung (Schockraum/Intensiv)\n→ Ziel in Klinik: Antibiotikum <1h!\n DK als Infektfokus → bei Urosepsis Klinik informieren!"},
diagnoseOptionen:["Septischer Schock bei Urosepsis","Exazerbierte Herzinsuffizienz","Harnwegsinfekt ohne Sepsis","Dehydrierung im Pflegeheim"],
correctDiagnose:0,
diagnoseErklaerung:"Dauerkatheter + trüber Urin + Fieber 39,5°C + Verwirrtheit + RR 85/55 + qSOFA 3/3 = septischer Schock bei Urosepsis. Aggressive VEL, O₂, schneller Transport!"},
{id:"exam_sepsis_e",bpr:"sepsis",caseId:121,
meldung:"5J Kind, Fieber, Petechien, Nackensteifigkeit, somnolent",
ankunft:"Kind im Kinderbett, somnolent, Petechien am Rumpf sichtbar, Eltern panisch.",
findings:{
vitalzeichen:"HF: 160/min | RR: 70/40 mmHg | SpO₂: 93% | AF: 30/min | Temp: 40,1°C | BZ: 75 mg/dl",
anamnese:"S: Mutter: 'Heute morgen noch fit, dann Fieber, jetzt diese Flecken und schläft nur noch.' A: keine. M: Ibuprofen-Saft gegeben. P: gesund, Impfungen komplett. L: verweigert. E: rapide Verschlechterung in 6h!",
inspektion:"Somnolent, Petechien (nicht wegdrückbar!) Rumpf und Extremitäten, marmorierte Haut, kalte Extremitäten",
auskultation:"Herztöne tachykard, Lunge frei",
ekg:"Sinustachykardie 160/min",
neurologie:"GCS 10 (A2V3M5), somnolent, Nackensteifigkeit positiv, Pupillen isokor",
palpation:"Kalte Extremitäten, Rekapzeit >5s, Petechien nicht wegdrückbar"
},
xabcde:{c:"Keine Blutung",a:"Frei",b:"SpO₂ 93% → O₂-Gabe",c2:"RR 70/40 + HF 160 + Rekapzeit >5s → SEPTISCHER SCHOCK beim Kind!",d:"GCS 10 + Nackensteifigkeit + Petechien → MENINGOKOKKEN-SEPSIS!",e:"Petechien + Fieber + Nackensteifigkeit → SOFORT Klinik!"},
spezial:{name:"Meningokokken-Sepsis Kind",result:"Meningokokken-Sepsis – Notfall!\n→ Petechien + Fieber + Nackensteifigkeit = klassische Trias!\n→ VEL: 20 ml/kg NaCl 0,9% Bolus (= 100 ml bei 5J/20kg)\n→ Wiederholung bis 60 ml/kg in 1. Stunde!\n→ O₂ hochdosiert\n→ i.v./i.o.-Zugang SOFORT\n→ Ceftriaxon 50-100 mg/kg i.v. wenn Transport >30 min\n→ Sofort-Transport in Kinderklinik!\n Foudroyanter Verlauf möglich! Minuten zählen!\n Petechien = Glastest: nicht wegdrückbar!"},
diagnoseOptionen:["Meningokokken-Sepsis","Virusinfekt mit Exanthem","ITP (Immunthrombozytopenie)","Kawasaki-Syndrom"],
correctDiagnose:0,
diagnoseErklaerung:"Kind + Fieber + nicht-wegdrückbare Petechien + Nackensteifigkeit + Schock = Meningokokken-Sepsis bis zum Beweis des Gegenteils. Sofortige VEL + Transport!"},
{id:"exam_trauma_d",bpr:"polytrauma",caseId:122,
meldung:"28J Motorradfahrer, Frontalkollision, bewusstlos, instabiles Becken",
ankunft:"Motorradfahrer liegt auf der Straße, Helm noch auf, bewusstlos, sichtbare Oberschenkeldeformität.",
findings:{
vitalzeichen:"RR: 80/50 mmHg | HF: 130/min | SpO₂: 90% | AF: 28/min",
anamnese:"S: Zeuge: 'Frontal in PKW gefahren, ca. 60 km/h, 5m durch die Luft.' A: unbekannt. M: unbekannt. P: unbekannt. L: unbekannt. E: HGV Motorrad vs. PKW vor 8 min",
inspektion:"Bewusstlos, Helm intakt, Prellmarke Thorax, Oberschenkelfraktur links (Fehlstellung), Becken instabil bei vorsichtiger Kompression, Blut am Hosenboden",
auskultation:"Links abgeschwächtes Atemgeräusch (Pneumothorax?), Herztöne leise, tachykard",
ekg:"Sinustachykardie 130/min",
neurologie:"GCS 7 (A1V2M4), Pupillen: links weiter als rechts",
palpation:"Instabiles Becken! Oberschenkelfraktur links, Abdomen gespannt"
},
xabcde:{c:"Blut am Hosenboden → Beckenfraktur mit Blutung!",a:"GCS 7 → Atemwegssicherung! Helm ab mit HWS-Immobilisation!",b:"SpO₂ 90%, links abgeschwächt → V.a. Pneumothorax → Entlastung!",c2:"RR 80/50 → hämorrhagischer Schock! Beckenschlinge + VEL!",d:"GCS 7, Anisokorie → SHT! Neurochirurgie!",e:"Polytrauma! Oberschenkelfraktur + Becken + Thorax + SHT"},
spezial:{name:"Polytrauma-Management",result:"Polytrauma ABCDE:\n<C> Beckenschlinge anlegen! SOFORT!\nA: Helm ab (4-Hände-Griff), HWS-Immobilisation, Intubation\nB: V.a. Pneumothorax li → Entlastungspunktion!\nC: 2x großlumiger Zugang, VEL aggressiv (Ziel RR 80-90syst)\n   Tranexamsäure 1g i.v.! Beckenschlinge! Oberschenkelschiene!\nD: Anisokorie → SHT mit erhöhtem ICP\nE: Ganzkörperuntersuchung, Wärmeerhalt!\n Permissive Hypotension bis 80-90 syst! Letale Trias vermeiden!"},
diagnoseOptionen:["Polytrauma mit hämorrhagischem Schock","Isoliertes SHT mit akuter Kreislaufdekompensation","Isolierte Beckenfraktur","Spinaltrauma bei vorbestehender Grunderkrankung"],
correctDiagnose:0,
diagnoseErklaerung:"HGV + GCS 7 + Anisokorie + instabiles Becken + Oberschenkelfraktur + abgeschwächtes AG links + Schock = Polytrauma. Beckenschlinge, Thoraxentlastung, VEL, TXA!"},
{id:"exam_trauma_e",bpr:"polytrauma",caseId:123,
meldung:"65J Fußgängerin, von PKW mit 40 km/h erfasst, multiple Prellmarken",
ankunft:"Frau liegt auf Zebrastreifen, wach aber schmerzgeplagt, Prellmarken Thorax und Abdomen.",
findings:{
vitalzeichen:"RR: 100/70 mmHg | HF: 110/min | SpO₂: 94% | AF: 24/min",
anamnese:"S: Zeugen: 'PKW hat sie beim Abbiegen erfasst, ca. 40 km/h.' A: unbekannt. M: 'Nehme Blutverdünner.' P: unbekannt. L: unbekannt. E: Anprall vor 5 min",
inspektion:"Wach, schmerzverzerrt, Prellmarke Thorax rechts, Abdominalprellmarke, Unterschenkeldeformität rechts, Schürfwunden",
auskultation:"Herztöne tachykard, Lunge rechts abgeschwächt, links normal",
ekg:"Sinustachykardie 110/min",
neurologie:"GCS 14 (A4V4M6), orientiert, Schmerzen",
palpation:"Thorax rechts druckschmerzhaft (Rippenserienfraktur?), Abdomen diffus druckschmerzhaft (Abwehrspannung!), Unterschenkelfraktur rechts"
},
xabcde:{c:"Keine massive externe Blutung",a:"Frei, wach",b:"SpO₂ 94%, rechts abgeschwächt → Rippenserienfraktur ± Pneumothorax",c2:"RR 100/70 + HF 110 + Abwehrspannung → V.a. abdominelle Blutung! Antikoagulanzien!",d:"GCS 14",e:"Rippenfraktur + V.a. Milz-/Leberruptur + Unterschenkelfraktur → Polytrauma!"},
spezial:{name:"Polytrauma Fußgänger",result:"Fußgänger vs. PKW – typische Verletzungen:\n→ Bumper-Fraktur (Unterschenkel/Knie)\n→ Thorax-/Abdominaltrauma (Motorhaube)\n→ SHT (Windschutzscheibe)\nVersorgung:\n→ 2x großlumiger Zugang, VEL\n→ Tranexamsäure 1g i.v.\n→ Analgesie! Ketamin 0,25 mg/kg i.v.\n→ Schiene Unterschenkel\n→ Schockraumanmeldung!\n CAVE: Antikoagulanzien → erhöhtes Blutungsrisiko!\n Abdominelle Blutung kann auch bei stabilem RR vorliegen!"},
diagnoseOptionen:["Polytrauma (Thorax, Abdomen, Extremität)","Isolierte Unterschenkelfraktur","Nur Thoraxtrauma mit Rippenfraktur","Wirbelsäulenverletzung mit begleitender Bewusstseinstrübung"],
correctDiagnose:0,
diagnoseErklaerung:"PKW vs. Fußgänger + Prellmarken Thorax/Abdomen + Abwehrspannung + Rippenfraktur + Unterschenkelfraktur + Antikoagulation = Polytrauma. TXA, VEL, Schockraum!"},
{id:"exam_therm_d",bpr:"thermisch",caseId:124,
meldung:"Grillunfall mit Spiritus, 35J Mann, Verbrennungen Oberkörper und Arme",
ankunft:"Mann steht im Garten, Verbrennungen sichtbar, starke Schmerzen, schreit.",
findings:{
vitalzeichen:"RR: 130/85 mmHg | HF: 120/min | SpO₂: 97% | AF: 22/min",
anamnese:"S: 'Habe Spiritus auf den Grill geschüttet, Stichflamme!' A: keine. M: keine. P: gesund. L: unbekannt. E: Stichflamme vor 15 min",
inspektion:"Verbrennungen Oberkörper ventral, beide Arme (2a-2b), Gesicht frei, keine Rußspuren, Haare angesengt, NRS 9/10",
auskultation:"Herztöne tachykard, Lunge frei, kein Stridor",
ekg:"Sinustachykardie 120/min",
neurologie:"GCS 15, schreit vor Schmerzen",
palpation:"Verbrannte Areale teils weißlich (2b), teils gerötet mit Blasen (2a)"
},
xabcde:{c:"Keine Blutung",a:"Frei, Gesicht frei, kein Inhalationstrauma",b:"SpO₂ 97%, Lunge frei",c2:"Tachykardie → Schmerz + Volumenverlust. VEL starten!",d:"GCS 15, massive Schmerzen → Analgesie!",e:"KOF: Oberkörper ventral 18% + beide Arme 2×9% = ca. 36% KOF!"},
spezial:{name:"Verbrennung >20% KOF",result:"Schwere Verbrennung (>20% KOF 2°+):\n→ Analgesie! Morphin 5 mg i.v. oder Esketamin 0,25 mg/kg\n→ VEL: Parkland-Formel → 4 ml × kg × %KOF in 24h\n  → 35J, ~80kg: 4×80×36 = 11.520 ml/24h → 50% in 8h\n  → Präklinisch: 1000 ml NaCl 0,9% starten\n→ Wundabdeckung: Metalline-Tuch (NICHT kühlen bei >20%!)\n→ Kein Eiswasser! Hypothermie-Gefahr!\n→ Verbrennungszentrum anmelden!\n KEINE Kühlung bei >20% KOF → Hypothermie-Risiko!"},
diagnoseOptionen:["Verbrennung 2a-2b ca. 36% KOF","Verbrennung 1° oberflächlich","Verätzung und hämodynamischer Instabilität","Verbrennung 3° Oberkörper und laborchemisch zu sichernder Verdachtsdiagnose"],
correctDiagnose:0,
diagnoseErklaerung:"Stichflamme + Blasen (2a) + weißliche Areale (2b) + Oberkörper ventral + beide Arme ≈ 36% KOF = schwere Verbrennung. Analgesie, VEL nach Parkland, NICHT kühlen, Verbrennungszentrum!"},
{id:"exam_therm_e",bpr:"thermisch",caseId:125,
meldung:"Wohnungsbrand, 42J Frau, Rußspuren, heisere Stimme, Stridor",
ankunft:"Frau vor Wohnhaus, Rußspuren im Gesicht, hustet, Stimme heiser, Feuerwehr löscht noch.",
findings:{
vitalzeichen:"RR: 140/90 mmHg | HF: 115/min | SpO₂: 91% | AF: 24/min",
anamnese:"S: Feuerwehr: 'War im verrauchten Raum, 5-10 min Rauchexposition.' A: keine. M: keine bekannt. P: unbekannt. L: unbekannt. E: aus brennender Wohnung gerettet vor 10 min",
inspektion:"Rußspuren Gesicht, Rußpartikel in Nasenlöchern und Mund, versengte Augenbrauen und Nasenhaar, Stimme heiser, inspiratorischer Stridor",
auskultation:"Inspiratorischer Stridor, beidseits Giemen, vereinzelt Rasselgeräusche",
ekg:"Sinustachykardie 115/min",
neurologie:"GCS 15, ängstlich, Kopfschmerzen",
palpation:"Keine äußeren Verbrennungen am Körper"
},
xabcde:{c:"Keine Blutung",a:"Stridor + Heiserkeit → INHALATIONSTRAUMA! Atemweg bedroht!",b:"SpO₂ 91% → O₂ 100% mit Reservoir! CO-Intox möglich!",c2:"HF 115, RR 140/90 → Stressreaktion",d:"GCS 15, Kopfschmerzen → CO-Intoxikation?",e:"Rußpartikel Nase/Mund + versengte Haare = Inhalationstrauma!"},
spezial:{name:"Inhalationstrauma + CO-Intox",result:"Inhalationstrauma – DREIFACHE GEFAHR:\n1. Thermisch: Heißluft → Larynxödem! Intubation erwägen!\n2. Chemisch: Rauchgas → toxische Pneumonitis\n3. CO-Intoxikation: SpO₂ falsch hoch! CO-Hb messen!\n→ O₂ 100% über Reservoir (CO-HWZ: 60 min bei FiO₂ 1,0)\n→ Frühe Intubation BEVOR Schwellung zunimmt!\n→ Kopfschmerzen = CO-Symptom!\n→ Verbrennungszentrum/Klinik mit HBO!\n CAVE: SpO₂-Messung bei CO nicht verlässlich!\n Stridor kann sich rasch verschlechtern!"},
diagnoseOptionen:["Inhalationstrauma mit V.a. CO-Intoxikation","Asthmaanfall durch Rauch mit respiratorischer Insuffizienz","Rauchgasreizung ohne Inhalationstrauma","Angstreaktion mit Hyperventilation"],
correctDiagnose:0,
diagnoseErklaerung:"Rauchexposition + Rußpartikel in Atemwegen + versengte Haare + Stridor + Heiserkeit + Kopfschmerzen = Inhalationstrauma mit V.a. CO-Intoxikation. O₂ 100%, frühe Intubation erwägen!"},
{id:"exam_lungoed_d",bpr:"lungenoedem",caseId:126,
meldung:"68J Frau, akute Atemnot, schaumiges Sputum, nächtliche Orthopnoe",
ankunft:"Frau sitzt aufrecht im Bett, kämpft um Luft, rosé-schaumiges Sputum.",
findings:{
vitalzeichen:"RR: 200/110 mmHg | HF: 120/min | SpO₂: 82% | AF: 32/min",
anamnese:"S: 'Bin aufgewacht, konnte nicht mehr atmen!' A: keine. M: Ramipril, Torasemid, Bisoprolol (heute vergessen). P: Herzinsuffizienz NYHA III, Z.n. MI 2018. L: salzig gegessen. E: akut aus dem Schlaf heraus",
inspektion:"Aufrecht sitzend, massiv dyspnoisch, rosé-schaumiges Sputum, Halsvenenstauung, Unterschenkelödeme bds.",
auskultation:"Feuchte RG beidseits bis Lungenspitzen, 3. Herzton, Herztöne tachykard",
ekg:"Sinustachykardie 120/min, Zeichen der Linkshypertrophie",
neurologie:"GCS 14, agitiert",
palpation:"Unterschenkelödeme bds., Halsvenenstauung"
},
xabcde:{c:"Keine Blutung",a:"Frei, aber Sputum absaugen!",b:"SpO₂ 82% + feuchte RG → AKUTES LUNGENÖDEM! CPAP + O₂!",c2:"RR 200/110 → hypertensives Lungenödem! Nitro + Furosemid!",d:"GCS 14, agitiert",e:"Herzinsuffizienz + vergessene Medikamente + salziges Essen = Trigger"},
spezial:{name:"Akutes Lungenödem",result:"Akutes kardiogenes Lungenödem:\n→ Oberkörper hoch, Beine tief!\n→ CPAP/NIV 5-10 cmH₂O → SOFORT!\n→ O₂ hochdosiert über CPAP\n→ Nitroglycerin 0,4-0,8 mg s.l. (bei RRsyst >110!)\n→ Furosemid 40 mg i.v.\n→ Morphin 2-3 mg i.v. (Vorlastsenkung + Angst)\n→ Bei RR >180: Urapidil 10-25 mg i.v. titriert\n CPAP ist die wichtigste Maßnahme! Sofort starten!"},
diagnoseOptionen:["Akutes kardiogenes Lungenödem","Pneumonie bei unklarer Ätiologie","Lungenembolie mit neurologischem Defizit","COPD-Exazerbation bei Z.n. Trauma"],
correctDiagnose:0,
diagnoseErklaerung:"Herzinsuffizienz + akute Orthopnoe + rosé-schaumiges Sputum + feuchte RG bds. + Hypertonie = akutes kardiogenes Lungenödem. CPAP sofort, Nitro, Furosemid!"},
{id:"exam_lungoed_e",bpr:"lungenoedem",caseId:127,
meldung:"72J Dialysepatient, 2 Tage keine Dialyse, akute Luftnot",
ankunft:"Mann sitzt auf Stuhl, massive Dyspnoe, Beinödeme, brodelnde Atemgeräusche.",
findings:{
vitalzeichen:"RR: 220/120 mmHg | HF: 110/min | SpO₂: 78% | AF: 34/min",
anamnese:"S: 'Seit 2 Tagen keine Dialyse (Shunt-Problem), kann nicht mehr atmen.' A: Kontrastmittel. M: Amlodipin, Torasemid, Epo. P: terminale Niereninsuffizienz, Dialyse 3x/Woche, Hypertonie. L: viel getrunken. E: zunehmend seit 12h, jetzt akut",
inspektion:"Massive Beinödeme, Halsvenenstauung, sitzend, brodelnde Atmung, periphere Zyanose",
auskultation:"Feuchte RG beidseits großblasig, Herztöne leise, tachykard",
ekg:"Sinustachykardie 110/min, hohe T-Wellen (Hyperkaliämie?)",
neurologie:"GCS 14, erschöpft",
palpation:"Massive Ödeme, Anasarka, Shunt links Unterarm (kein Schwirren!)"
},
xabcde:{c:"Keine Blutung",a:"Frei, brodelndes Sputum",b:"SpO₂ 78% → CPAP + O₂ SOFORT!",c2:"RR 220/120 + Volumenüberladung → Nitro + vorsichtig Furosemid (wirkt kaum bei Anurie!)",d:"GCS 14",e:"Hohe T-Wellen → Hyperkaliämie? → Potentiell lebensbedrohlich! Shunt thrombosiert!"},
spezial:{name:"Flash-Lungenödem Dialysepatient",result:"Lungenödem bei Dialysepatient – Besonderheiten:\n→ CPAP/NIV sofort!\n→ Nitroglycerin 0,4-0,8 mg s.l. (Vorlastsenkung!)\n→ Furosemid oft UNWIRKSAM bei Anurie!\n→ Urapidil 10-25 mg i.v. bei RR >180\n→ CAVE: Hohe T-Wellen → Hyperkaliämie!\n  → Calciumgluconat 10% 10-20 ml i.v. (Kardioprotektiv!)\n  → Salbutamol vernebelt (senkt Kalium)\n→ Transport zur Notfall-Dialyse!\n Shunt prüfen: kein Schwirren = thrombosiert!"},
diagnoseOptionen:["Flash-Lungenödem bei Volumenüberladung (Dialyseausfall)","Pneumonie mit metabolischer Entgleisung","Myokardinfarkt und sekundärer Organbeteiligung","Perikarderguss bei infektiöser Genese"],
correctDiagnose:0,
diagnoseErklaerung:"Dialysepatient + 2 Tage keine Dialyse + massive Ödeme + Lungenödem + Hypertonie + V.a. Hyperkaliämie = Volumenüberladung mit Flash-Lungenödem. CPAP, Nitro, Notfall-Dialyse!"},
{id:"exam_hypert_d",bpr:"hypertensiv",caseId:128,
meldung:"58J Mann, starkes Nasenbluten, Kopfschmerzen, RR 240/130",
ankunft:"Mann sitzt im Bad, Handtuch voller Blut, Nasenbluten persistierend, klagt über Kopfschmerzen.",
findings:{
vitalzeichen:"RR: 240/130 mmHg | HF: 90/min | SpO₂: 97% | AF: 16/min",
anamnese:"S: 'Nase blutet seit 30 min, höllische Kopfschmerzen, sehe verschwommen.' A: keine. M: Amlodipin (unregelmäßig). P: Hypertonie seit 10 Jahren. L: viel Kaffee. E: plötzliches Nasenbluten, dann Kopfschmerzen und Sehstörung",
inspektion:"Nasenbluten anterior beidseits, Gesicht gerötet, angespannt",
auskultation:"Herztöne rhythmisch, Lunge frei",
ekg:"Sinusrhythmus 90/min, Linkshypertrophiezeichen",
neurologie:"GCS 15, Kopfschmerzen, Sehstörung (verschwommen), keine fokalen Defizite",
palpation:"Kräftiger Puls"
},
xabcde:{c:"Nasenbluten → Kompression + Kopf nach vorne!",a:"Frei (Blut schlucken vermeiden!)",b:"SpO₂ 97%",c2:"RR 240/130 + Kopfschmerzen + Sehstörung → HYPERTENSIVER NOTFALL!",d:"GCS 15, Kopfschmerzen, Sehstörung → Endorganschaden!",e:"Non-Compliance Medikation als Trigger"},
spezial:{name:"Hypertensiver Notfall",result:"Hypertensiver Notfall (RR >180/120 + Endorganschaden):\nEndorganschäden: Kopfschmerz, Sehstörung, Nasenbluten\n→ Urapidil 10-25 mg i.v. langsam\n→ Ziel: RR-Senkung max. 25% in 1. Stunde!\n→ NICHT zu schnell senken → Ischämie-Gefahr!\n→ Nasenbluten: Kompression, Kopf nach vorne\n→ Monitoring eng\n Sehstörung = mögliche hypertensive Retinopathie!\n Kopfschmerz + RR 240 = Hirnblutung ausschließen in Klinik!"},
diagnoseOptionen:["Hypertensiver Notfall mit Endorganschaden","Hypertensive Krise ohne Organschaden","Nasenbluten ohne Hypertonie","Schlaganfall mit Hypertonie"],
correctDiagnose:0,
diagnoseErklaerung:"RR 240/130 + Kopfschmerzen + Sehstörung + Nasenbluten = hypertensiver NOTFALL (nicht nur Krise!). Endorganschaden nachweisbar. Urapidil i.v., max. 25% RR-Senkung/Stunde."},
{id:"exam_hypert_e",bpr:"hypertensiv",caseId:129,
meldung:"62J Frau, RR 250/140, retrosternaler Druck, Dyspnoe, Medikamente abgesetzt",
ankunft:"Frau sitzt aufrecht, greift sich an die Brust, dyspnoisch, ängstlich.",
findings:{
vitalzeichen:"RR: 250/140 mmHg | HF: 105/min | SpO₂: 90% | AF: 24/min",
anamnese:"S: 'Habe meine Blutdrucktabletten seit 3 Tagen abgesetzt (nicht vertragen).' A: Husten bei ACE-Hemmern. M: Ramipril und Amlodipin abgesetzt. P: Hypertonie Grad III, KHK. L: unbekannt. E: Brustschmerz und Atemnot seit 1h, zunehmend",
inspektion:"Aufrecht sitzend, dyspnoisch, ängstlich, leichtes Schwitzen",
auskultation:"Feuchte RG basal beidseits, Herztöne tachykard",
ekg:"Sinustachykardie 105/min, ST-Senkungen V4-V6",
neurologie:"GCS 15, ängstlich",
palpation:"Pulse kräftig, tachykard"
},
xabcde:{c:"Keine Blutung",a:"Frei",b:"SpO₂ 90% + basale RG → beginnendes Lungenödem → CPAP!",c2:"RR 250/140 + Brustschmerz + ST-Senkung → hypertensive Krise + ACS? + Lungenödem!",d:"GCS 15",e:"Medikamente abgesetzt → Rebound-Hypertonie!"},
spezial:{name:"Hypertensiver Notfall multimodal",result:"Hypertensiver Notfall mit mehreren Endorganen:\n→ Herz: Brustschmerz + ST-Senkung → myokardiale Ischämie\n→ Lunge: basale RG → beginnendes Lungenödem\nTherapie:\n→ Urapidil 10-25 mg i.v. langsam titriert\n→ Nitroglycerin 0,4 mg s.l. (senkt Vorlast + RR)\n→ CPAP wenn Lungenödem zunimmt\n→ O₂-Gabe\n→ Morphin 3 mg i.v. bei Brustschmerz\n→ Ziel: RR um 25% senken in 1h\n Medikamenten-Absetzen ist häufiger Trigger!"},
diagnoseOptionen:["Hypertensiver Notfall mit kardiopulmonaler Dekompensation","Akuter Myokardinfarkt mit kardialer Beteiligung","Lungenembolie und drohender Dekompensation","Aortendissektion bei bestehender Medikation"],
correctDiagnose:0,
diagnoseErklaerung:"RR 250/140 + Medikamente abgesetzt + Brustschmerz + ST-Senkung + basale RG = hypertensiver Notfall mit kardialer und pulmonaler Dekompensation. Urapidil + Nitro + CPAP."},
{id:"exam_lae_d",bpr:"lae",caseId:130,
meldung:"42J Frau, plötzliche Atemnot nach Langstreckenflug, Brustschmerz",
ankunft:"Frau am Flughafen, sitzt auf Bank, hält sich die Brust, Tachykardie.",
findings:{
vitalzeichen:"RR: 105/70 mmHg | HF: 130/min | SpO₂: 88% | AF: 28/min",
anamnese:"S: 'Plötzlich keine Luft mehr bekommen, Stechen in der Brust rechts.' A: keine. M: Orale Kontrazeptiva. P: keine bekannt. L: im Flugzeug gegessen. E: nach 12h-Flug, plötzlich vor 30 min",
inspektion:"Ängstlich, tachypnoisch, greift sich an rechte Brust, rechtes Bein geschwollen",
auskultation:"Herztöne tachykard, betonter 2. HT, Lunge rechts abgeschwächt",
ekg:"Sinustachykardie 130/min, S1Q3T3-Typ, Rechtstyp, inkompletter Rechtsschenkelblock",
neurologie:"GCS 15, ängstlich",
palpation:"Rechter Unterschenkel umfangsvermehrt, überwärmt, druckschmerzhaft Wade"
},
xabcde:{c:"Keine Blutung",a:"Frei",b:"SpO₂ 88%, AF 28 → O₂ hochdosiert!",c2:"HF 130 → Rechtsherzbelastung. RR noch stabil. Wells-Score berechnen!",d:"GCS 15",e:"Langstreckenflug + Pille + Beinschwellung → KLASSISCHE LAE-Trias!"},
spezial:{name:"Lungenarterienembolie",result:"Wells-Score: Tachykardie ✓ (1,5), Immobilisation Flug ✓ (1,5),\nLAE wahrscheinlicher ✓ (3), Zeichen TVT ✓ (3) = 9 Punkte!\n→ LAE hochwahrscheinlich!\n→ O₂ hochdosiert\n→ Heparin 5.000 IE i.v. SOFORT!\n→ VEL 500 ml (Rechtsherzunterstützung)\n→ Analgesie bei Schmerzen\n→ Monitoring eng (kann rasch dekompensieren!)\n→ Transport Klinik mit CT-Angiographie\n Pille + Langstreckenflug = hohe Risikokombination!"},
diagnoseOptionen:["Lungenarterienembolie","Pneumothorax mit progredientem Verlauf","Pleuritis bei unklarer Bewusstseinslage","Akutes Koronarsyndrom"],
correctDiagnose:0,
diagnoseErklaerung:"Langstreckenflug + Pille + plötzliche Dyspnoe + Tachykardie + Beinschwellung + S1Q3T3 + Wells 9 = Lungenarterienembolie. Heparin 5.000 IE sofort!"},
{id:"exam_lae_e",bpr:"lae",caseId:131,
meldung:"55J Mann, Z.n. Knie-OP vor 10 Tagen, plötzlich kollabiert, PEA",
ankunft:"Mann liegt am Boden, leblos, Ehefrau hat CPR begonnen. Z.n. Knie-TEP.",
findings:{
vitalzeichen:"RR: nicht messbar | HF: PEA | SpO₂: nicht messbar | AF: 0/min",
anamnese:"S: Ehefrau: 'Stand auf, hat nach Luft geschnappt und ist zusammengebrochen.' A: keine. M: Rivaroxaban (seit OP), Ibuprofen. P: Z.n. Knie-TEP vor 10 Tagen, Adipositas. L: Frühstück. E: plötzlicher Kollaps vor 3 min",
inspektion:"Leblos, gestaute Halsvenen, zyanotisch, Kompressionsstrümpfe an, OP-Narbe Knie rechts",
auskultation:"Keine Herztöne, keine Atemgeräusche",
ekg:"PEA – organisierter Rhythmus ohne Puls, HF 40",
neurologie:"GCS 3, areaktiv",
palpation:"Kein Karotispuls, gestaute Halsvenen"
},
xabcde:{c:"Keine Blutung",a:"CPR fortsetzen, Atemwegsmanagement",b:"Beatmung 30:2",c2:"PEA + gestaute Halsvenen + Z.n. OP → V.a. MASSIVE LAE!",d:"GCS 3",e:"Knie-OP + Adipositas + PEA + Halsvenen → LAE bis Beweis!"},
spezial:{name:"LAE mit Kreislaufstillstand",result:"PEA + Risikofaktoren → V.a. fulminante LAE!\n→ CPR nach ALS-Algorithmus\n→ Adrenalin 1 mg i.v. alle 3-5 min\n→ Lyse unter CPR: Alteplase 50 mg i.v. als Bolus!\n→ Nach Lyse: CPR mindestens 60-90 min fortsetzen!\n→ Heparin 5.000 IE i.v. nach Lyse\n→ Kein Abbruch <90 min nach Lyse!\n Gestaute Halsvenen bei PEA → Obstruktive Ursache!\n (Spannungspneu oder LAE → beides ausschließen!)"},
diagnoseOptionen:["Fulminante LAE mit Kreislaufstillstand","Myokardinfarkt mit Kreislaufstillstand","Spannungspneumothorax und vegetativer Begleitsymptomatik","Aortendissektion mit akuter Kreislaufdekompensation"],
correctDiagnose:0,
diagnoseErklaerung:"Z.n. Knie-OP + Risikofaktoren + plötzlicher Kollaps + PEA + gestaute Halsvenen = fulminante LAE. Lyse mit Alteplase 50 mg unter CPR! Mindestens 60-90 min weiter reanimieren!"},
{id:"exam_krupp_d",bpr:"obstruktion_kind",caseId:132,
meldung:"2J Kind, bellender Husten, Stridor, 3 Uhr nachts",
ankunft:"Kleinkind auf dem Arm der Mutter, bellender Husten, inspiratorischer Stridor.",
findings:{
vitalzeichen:"HF: 130/min | SpO₂: 95% | AF: 32/min | Temp: 36,8°C",
anamnese:"S: Mutter: 'Plötzlich aufgewacht mit bellendem Husten, Stridor.' A: keine. M: keine. P: gesund. L: normal. E: akut aus dem Schlaf",
inspektion:"Bellender Husten, inspiratorischer Stridor, leichte Einziehungen jugulär, kein Speichelfluss",
auskultation:"Stridor inspiratorisch, Lunge: Vesikuläratmen bds.",
ekg:"Sinustachykardie",
neurologie:"Wach, weint, GCS 15",
palpation:"Kein Fieber"
},
xabcde:{c:"Keine Blutung",a:"Stridor → obere Atemwegsobstruktion → Krupp!",b:"SpO₂ 95%, leichte Einziehungen → Krupp Grad II",c2:"HF 130 (altersgerecht + Aufregung)",d:"Wach, weint",e:"Kein Fieber + bellender Husten + nachts = typischer Pseudokrupp"},
spezial:{name:"Pseudokrupp-Management",result:"Pseudokrupp Grad II (Stridor in Ruhe, leichte Einziehungen):\n→ Kind beruhigen! Mutter einbeziehen!\n→ Kühle feuchte Luft (Fenster öffnen)\n→ Rectodelt 100 mg rektal oder Dexamethason 0,15 mg/kg p.o.\n→ Bei Verschlechterung: Adrenalin vernebelt 3-5 mg\n→ O₂ nur bei SpO₂ <92%\n→ Oberkörper hoch\n CAVE: Epiglottitis ausschließen! (Fieber, Speichelfluss, Schluckbeschwerden)"},
diagnoseOptionen:["Pseudokrupp Grad II","Epiglottitis","Fremdkörperaspiration","Asthmaanfall"],
correctDiagnose:0,
diagnoseErklaerung:"2 Jahre + bellender Husten + Stridor + nachts + kein Fieber + kein Speichelfluss = Pseudokrupp Grad II. Rectodelt, beruhigen, kühle Luft!"},
{id:"exam_krupp_e",bpr:"obstruktion_kind",caseId:133,
meldung:"3J Kind, plötzlicher Hustenanfall beim Essen, zunehmender Stridor",
ankunft:"Kind hustet heftig, Eltern halten es, zunehmender Stridor, wird blass.",
findings:{
vitalzeichen:"HF: 150/min | SpO₂: 88% | AF: 35/min",
anamnese:"S: Eltern: 'Hat Nüsse gegessen, plötzlich angefangen zu husten, wird immer schlimmer.' A: keine. M: keine. P: gesund. L: gerade Nüsse gegessen. E: plötzlich vor 5 min",
inspektion:"Inspiratorischer und exspiratorischer Stridor, zunehmende Zyanose, hustet, würgt",
auskultation:"Stridor bds., rechts deutlich abgeschwächtes Atemgeräusch",
ekg:"Sinustachykardie",
neurologie:"Wach, panisch, GCS 15",
palpation:"Keine Auffälligkeiten"
},
xabcde:{c:"Keine Blutung",a:"Fremdkörper! Wenn effektiver Husten → zum Husten ermutigen!",b:"SpO₂ 88%, rechts abgeschwächt → FK rechter Hauptbronchus?",c2:"HF 150 bei 3J → Stress",d:"Wach, panisch",e:"Erdnüsse + plötzlich → FREMDKÖRPERASPIRATION!"},
spezial:{name:"FK-Aspiration Kind",result:"Fremdkörperaspiration 3J, bei Bewusstsein:\n→ Effektiver Husten? → Zum Husten ermutigen!\n→ Ineffektiver Husten (leiser, Zyanose):\n  → 5 Rückenschläge (zwischen Schulterblätter)\n  → 5 Thoraxkompressionen (>1J) / Oberbauchkompression (>1J)\n  → Wechsel bis FK raus oder bewusstlos\n→ Wenn bewusstlos: CPR beginnen!\n→ Laryngoskopie + Magill-Zange nur wenn FK sichtbar!\n KEINE blinde digitale Ausräumung beim Kind!"},
diagnoseOptionen:["Fremdkörperaspiration","Pseudokrupp bei vorbestehender Grunderkrankung","Asthmaanfall mit begleitender Bewusstseinstrübung","Epiglottitis und hämodynamischer Instabilität"],
correctDiagnose:0,
diagnoseErklaerung:"Plötzlich beim Essen + Nüsse + Stridor + einseitig abgeschwächtes AG = Fremdkörperaspiration. Bei effektivem Husten: husten lassen. Bei ineffektivem: Rückenschläge + Thoraxkompressionen!"},
{id:"exam_fk_d",bpr:"fk_aspiration",caseId:134,
meldung:"68J Mann, verschluckt sich beim Essen, greift an Hals, zyanotisch",
ankunft:"Mann steht am Tisch, greift sich an den Hals, kann nicht sprechen, wird blau.",
findings:{
vitalzeichen:"RR: nicht messbar | HF: >100 | SpO₂: 70% | AF: ineffektiv",
anamnese:"S: Ehefrau: 'Hat ein Steak gegessen, plötzlich konnte er nicht mehr atmen!' A: unbekannt. M: unbekannt. P: Z.n. Schlaganfall (Schluckstörung!). L: gerade Steak. E: plötzlich vor 2 min",
inspektion:"Universelles Erstickungszeichen (Hände am Hals), kann nicht sprechen, keine effektive Atmung, zunehmende Zyanose",
auskultation:"Kein Atemgeräusch",
ekg:"Nicht angelegt",
neurologie:"Wach, panisch, GCS 14",
palpation:"Nicht beurteilbar"
},
xabcde:{c:"Keine Blutung",a:"KOMPLETTE ATEMWEGSVERLEGUNG! SOFORT Heimlich!",b:"Keine effektive Atmung → Bolus entfernen!",c2:"Noch bei Bewusstsein → Heimlich-Manöver!",d:"Wach, panisch",e:"Z.n. Apoplex mit Schluckstörung → erhöhtes Aspirationsrisiko!"},
spezial:{name:"Bolusaspiration Erwachsener",result:"Komplette Atemwegsverlegung, bei Bewusstsein:\n→ 5 Rückenschläge\n→ 5 Oberbauchkompressionen (Heimlich-Manöver)\n→ Wechsel bis FK entfernt oder bewusstlos\n→ Wenn bewusstlos: CPR! Laryngoskopie + Magill-Zange!\n→ Nach Heimlich: immer Klinikvorstellung (innere Verletzungen!)\n Z.n. Schlaganfall = erhöhtes Aspirationsrisiko!\n Steak = häufigster tödlicher Fremdkörper beim Erwachsenen!"},
diagnoseOptionen:["Bolusaspiration mit kompletter Atemwegsverlegung","Anaphylaxie mit respiratorischer Insuffizienz","Herzinfarkt mit Atemnot bei unklarer Ätiologie","Panikattacke mit neurologischem Defizit"],
correctDiagnose:0,
diagnoseErklaerung:"Plötzlich beim Essen + Griff an den Hals + kann nicht sprechen + keine effektive Atmung = Bolusaspiration. Heimlich-Manöver sofort!"},
{id:"exam_fk_e",bpr:"fk_aspiration",caseId:135,
meldung:"5J Kind, V.a. Erdnuss aspiriert, intermittierender Stridor",
ankunft:"Kind hustet gelegentlich, sitzt bei den Eltern, intermittierender Stridor.",
findings:{
vitalzeichen:"HF: 110/min | SpO₂: 94% | AF: 24/min",
anamnese:"S: Eltern: 'Hat Erdnüsse gegessen, plötzlich gehustet, jetzt pfeift es manchmal.' A: keine. M: keine. P: gesund. L: Erdnüsse vor 20 min. E: initial heftiger Hustenanfall, jetzt intermittierend",
inspektion:"Sitzt aufrecht, hustet gelegentlich, intermittierender Stridor, rosig",
auskultation:"Rechts abgeschwächtes Atemgeräusch, links normal, intermittierender Stridor",
ekg:"Sinusrhythmus",
neurologie:"GCS 15, kooperativ",
palpation:"Unauffällig"
},
xabcde:{c:"Keine Blutung",a:"Intermittierender Stridor → partiell verlegte Atemwege",b:"SpO₂ 94%, rechts abgeschwächt → FK rechter Hauptbronchus",c2:"HF 110 → altersentsprechend",d:"GCS 15",e:"Erdnüsse = häufigster FK bei Kindern!"},
spezial:{name:"FK partiell – Kind",result:"Partielle Fremdkörperaspiration bei Kind:\n→ Effektiver Husten vorhanden → HUSTEN LASSEN!\n→ KEINE Rückenschläge bei effektivem Husten!\n→ Kind beruhigen, nicht aufreggen\n→ Sitzend transportieren\n→ O₂ bei SpO₂ <92%\n→ Transport in Kinderklinik zur Bronchoskopie\n→ Engmaschig überwachen (kann sich komplett verlegen!)\n Erdnüsse quellen auf → Entfernung dringend!\n KEINE blinde Extraktion!"},
diagnoseOptionen:["Partielle Fremdkörperaspiration","Asthmaanfall bei Z.n. Trauma","Pseudokrupp mit metabolischer Entgleisung","Bronchitis und sekundärer Organbeteiligung"],
correctDiagnose:0,
diagnoseErklaerung:"Erdnüsse gegessen + plötzlicher Husten + einseitig abgeschwächtes AG + intermittierender Stridor = partielle FK-Aspiration. Husten lassen, NICHT klopfen, Transport zur Bronchoskopie!"},
{id:"exam_aorta_d",bpr:"aortensyndrom",caseId:136,
meldung:"56J Mann, plötzlicher Vernichtungsschmerz zwischen Schulterblättern",
ankunft:"Mann am Boden, schreit vor Schmerzen, blass, schweißnass.",
findings:{
vitalzeichen:"RR li: 190/100 mmHg | RR re: 140/80 mmHg | HF: 100/min | SpO₂: 96% | AF: 22/min",
anamnese:"S: 'Wie ein Messer im Rücken, schlimmster Schmerz meines Lebens!' A: keine. M: Amlodipin (unregelmäßig). P: Hypertonie, Raucher. L: unbekannt. E: plötzlich vor 20 min",
inspektion:"Blass, schweißnass, Vernichtungsschmerz, unruhig",
auskultation:"Diastolikum über Aortenklappe, Lunge frei",
ekg:"Sinustachykardie 100/min, keine ST-Veränderungen",
neurologie:"GCS 15, massive Schmerzen",
palpation:"RR-Differenz >40 mmHg! Pulse Arm rechts schwächer"
},
xabcde:{c:"Keine Blutung extern",a:"Frei",b:"SpO₂ 96%",c2:"RR-Differenz >40 mmHg + Vernichtungsschmerz → V.A. AORTENDISSEKTION TYP A!",d:"GCS 15",e:"Hypertonie + Raucher → Risikofaktoren"},
spezial:{name:"Aortendissektion Typ A",result:"V.a. Aortendissektion Typ A (Aorta ascendens):\n→ CHIRURGISCHER NOTFALL! Sterblichkeit 1-2%/Stunde!\n→ RR-Senkung: Ziel RRsyst 100-120! Urapidil 10-25 mg i.v.\n→ HF-Senkung: Ziel HF <60! Esmolol oder Metoprolol i.v.\n→ Analgesie: Morphin 5-10 mg i.v.\n→ KEIN ASS, KEIN Heparin (Blutungsgefahr!)\n→ Diastolikum → Aortenklappeninsuffizienz\n→ Transport in Herzchirurgie!\n RR-Differenz >20 mmHg = RED FLAG für Dissektion!"},
diagnoseOptionen:["Aortendissektion Typ A","Akuter Myokardinfarkt","Lungenembolie bei infektiöser Genese","Pneumothorax mit kardialer Beteiligung"],
correctDiagnose:0,
diagnoseErklaerung:"Vernichtungsschmerz + RR-Differenz >40 mmHg + Diastolikum + Risikofaktoren = V.a. Aortendissektion Typ A. RR + HF senken, Morphin, sofort Herzchirurgie!"},
{id:"exam_aorta_e",bpr:"aortensyndrom",caseId:137,
meldung:"71J Raucher, plötzlicher Bauchschmerz mit Ausstrahlung Rücken, pulsierender Tumor",
ankunft:"Mann liegt auf Sofa, hält sich den Bauch, blass, kaltschweißig.",
findings:{
vitalzeichen:"RR: 90/60 mmHg | HF: 120/min | SpO₂: 96% | AF: 20/min",
anamnese:"S: 'Plötzlich Bauch- und Rückenschmerzen, mir ist schlecht.' A: keine. M: ASS, Atorvastatin. P: pAVK, Raucher 50 Pack-Years, bekanntes Bauchaortenaneurysma 4,5cm (letztes CT). L: Mittagessen. E: plötzlich vor 30 min",
inspektion:"Blass, kaltschweißig, liegt mit angezogenen Beinen, Schmerzgesicht",
auskultation:"Herztöne tachykard, Lunge frei, Darmgeräusche reduziert",
ekg:"Sinustachykardie 120/min",
neurologie:"GCS 15, massive Schmerzen",
palpation:"Pulsierender Tumor paraumbilikal, Abdomen druckschmerzhaft, Abwehrspannung, Pulse A. dorsalis pedis bds. abgeschwächt"
},
xabcde:{c:"Keine externe Blutung – ABER: retroperitoneale Blutung!",a:"Frei",b:"SpO₂ 96%",c2:"RR 90/60 + HF 120 → hämorrhagischer Schock! Rupturiertes BAA!",d:"GCS 15",e:"Bekanntes BAA + plötzlicher Schmerz + Schock = RUPTUR!"},
spezial:{name:"Rupturiertes Bauchaortenaneurysma",result:"V.a. rupturiertes BAA:\n→ CHIRURGISCHER NOTFALL! Höchste Priorität!\n→ Permissive Hypotension: Ziel RRsyst 70-80! NICHT normalisieren!\n→ VEL zurückhaltend (zu viel → mehr Blutung!)\n→ Analgesie: Morphin/Ketamin\n→ KEIN ASS stoppen\n→ 2x großlumiger Zugang\n→ Sofort-Transport in Gefäßchirurgie!\n Permissive Hypotension rettet Leben!\n Pulsierender Tumor + Schock = bis zum Beweis BAA-Ruptur!"},
diagnoseOptionen:["Rupturiertes Bauchaortenaneurysma","Akutes Abdomen (Perforation) mit unklarem zeitlichem Verlauf seit Symptombeginn","Niereninfarkt und drohender Dekompensation","Mesenterialinfarkt bei bestehender Medikation"],
correctDiagnose:0,
diagnoseErklaerung:"Bekanntes BAA + plötzlicher Bauch-/Rückenschmerz + pulsierender Tumor + Schock = rupturiertes Bauchaortenaneurysma. Permissive Hypotension, sofort Gefäßchirurgie!"},
{id:"exam_art_d",bpr:"art_verschluss",caseId:138,
meldung:"68J Frau, plötzlich blasses kaltes linkes Bein, starke Schmerzen",
ankunft:"Frau liegt auf Sofa, hält sich das linke Bein, das auffallend blass ist.",
findings:{
vitalzeichen:"RR: 140/80 mmHg | HF: 85/min (arrhythmisch) | SpO₂: 97% | AF: 16/min",
anamnese:"S: 'Plötzlich höllischer Schmerz im linken Bein, wird kalt und taub.' A: keine. M: keine Antikoagulation! P: VHF bekannt (bisher nicht behandelt). L: unbekannt. E: plötzlich vor 2h",
inspektion:"Linkes Bein blass, marmoriert ab Kniegelenk, rechts normal",
auskultation:"Herztöne arrhythmisch (VHF), Lunge frei",
ekg:"Vorhofflimmern 85/min",
neurologie:"GCS 15, Schmerzen NRS 8, Sensibilitätsstörung li Fuß",
palpation:"A. poplitea links nicht tastbar, A. dorsalis pedis + tibialis posterior links nicht tastbar, rechts alles tastbar, links kühler als rechts"
},
xabcde:{c:"Keine Blutung",a:"Frei",b:"SpO₂ 97%",c2:"VHF ohne Antikoagulation → Emboliequelle! 6P prüfen!",d:"GCS 15, Sensibilitätsstörung Fuß",e:"6P: Pain ✓, Pulslessness ✓, Pallor ✓, Paresthesia ✓, Paralysis?, Poikilothermie ✓"},
spezial:{name:"Akuter Arterienverschluss",result:"Akuter arterieller Verschluss – 6P:\n→ Pain, Pulselessness, Pallor, Paresthesia, Paralysis, Poikilothermie\n→ Heparin 5.000 IE i.v. SOFORT (Thrombuswachstum stoppen!)\n→ Analgesie: Morphin 3-5 mg i.v.\n→ Bein tief lagern (Schwerkraft nutzen!)\n→ NICHT kühlen, NICHT erwärmen\n→ Polstern, Druckstellen vermeiden\n→ Sofort-Transport in Gefäßchirurgie!\n VHF ohne Antikoagulation = häufigste Emboliequelle!\n Zeitfenster: 6h bis irreversibler Schaden!"},
diagnoseOptionen:["Akuter arterieller Verschluss links bei VHF-Embolie","Tiefe Venenthrombose mit progredientem Verlauf","Spinalkanalstenose bei unklarer Bewusstseinslage","Kompartmentsyndrom und vegetativer Begleitsymptomatik"],
correctDiagnose:0,
diagnoseErklaerung:"VHF ohne Antikoagulation + plötzlich blasses kaltes pulsoses Bein + 6P positiv = akuter arterieller Verschluss durch Embolie. Heparin sofort, Gefäßchirurgie!"},
{id:"exam_dehydr_d",bpr:"dehydratation",caseId:139,
meldung:"8 Monate Säugling, Durchfall seit 3 Tagen, eingefallene Fontanelle",
ankunft:"Säugling auf dem Arm der Mutter, schlapp, eingefallene Fontanelle, kaum Reaktion.",
findings:{
vitalzeichen:"HF: 170/min | SpO₂: 98% | AF: 30/min | Temp: 37,8°C | BZ: 60 mg/dl",
anamnese:"S: Mutter: 'Seit 3 Tagen Durchfall und Erbrechen, trinkt kaum noch.' A: keine. M: keine. P: gesund, 8 kg. L: seit 12h nichts behalten. E: zunehmend schlapper",
inspektion:"Schlapp, eingefallene Fontanelle, eingesunkene Augen, stehende Hautfalten, trockene Windel, kein Weinen mit Tränen",
auskultation:"Herztöne tachykard, Lunge frei",
ekg:"Sinustachykardie",
neurologie:"Reagiert nur auf Schmerz, schlaff",
palpation:"Stehende Hautfalten, Haut trocken, Rekapzeit 3s"
},
xabcde:{c:"Keine Blutung",a:"Frei",b:"SpO₂ 98%",c2:"HF 170 + stehende Hautfalten + eingefallene Fontanelle → SCHWERE DEHYDRATATION!",d:"Reagiert nur auf Schmerz → somnolent!",e:"BZ 60 → Hypoglykämie-Risiko beim Säugling!"},
spezial:{name:"Schwere Dehydratation Säugling",result:"Schwere Dehydratation Säugling (>10% KG-Verlust):\n→ VEL: NaCl 0,9% 20 ml/kg Bolus i.v./i.o. (= 160 ml bei 8kg)\n→ Re-Evaluation nach Bolus, ggf. wiederholen\n→ BZ 60 → Glucose 10% 2 ml/kg = 16 ml i.v.\n→ Max. 3 Boli à 20 ml/kg\n→ O₂ bei Bedarf\n→ Wärmeerhalt!\n→ Transport Kinderklinik!\n Eingefallene Fontanelle = ZUVERLÄSSIGSTES Zeichen beim Säugling!\n Keine Tränen beim Weinen = Dehydratation!"},
diagnoseOptionen:["Schwere Dehydratation bei Gastroenteritis","Meningitis mit akuter Kreislaufdekompensation","Sepsis bei vorbestehender Grunderkrankung","Invagination mit begleitender Bewusstseinstrübung"],
correctDiagnose:0,
diagnoseErklaerung:"Säugling + 3 Tage Durchfall/Erbrechen + eingefallene Fontanelle + stehende Hautfalten + Somnolenz = schwere Dehydratation. VEL 20 ml/kg sofort, BZ kontrollieren!"},
{id:"exam_dehydr_e",bpr:"dehydratation",caseId:140,
meldung:"82J Pflegeheim, 4 Tage Durchfall, somnolent, RR 70/40",
ankunft:"Frau im Pflegebett, kaum ansprechbar, blass, trocken.",
findings:{
vitalzeichen:"RR: 70/40 mmHg | HF: 130/min | SpO₂: 94% | AF: 22/min | Temp: 37,5°C | BZ: 180 mg/dl",
anamnese:"S: Pflege: '4 Tage Durchfall, trinkt kaum, heute kaum noch ansprechbar.' A: Penicillin. M: Ramipril, Metoprolol, Metformin, Torasemid. P: Herzinsuffizienz, DM2, Demenz. L: verweigert. E: zunehmende Verschlechterung",
inspektion:"Somnolent, stehende Hautfalten, trockene Schleimhäute, eingefallene Augen",
auskultation:"Herztöne tachykard, Lunge frei",
ekg:"Sinustachykardie 130/min",
neurologie:"GCS 10 (A2V3M5), desorientiert",
palpation:"Stehende Hautfalten, kühle Extremitäten, Rekapzeit >4s"
},
xabcde:{c:"Keine Blutung",a:"Frei, Aspirationsgefahr bei Somnolenz",b:"SpO₂ 94% → O₂-Gabe",c2:"RR 70/40 + HF 130 → HYPOVOLÄMISCHER SCHOCK!",d:"GCS 10, somnolent",e:"Dehydriert + Diuretikum + Durchfall = Teufelskreis"},
spezial:{name:"Dehydratationsschock Alter",result:"Hypovolämischer Schock bei Dehydratation:\n→ VEL: 500 ml NaCl 0,9% Bolus i.v.\n→ Vorsichtig bei Herzinsuffizienz! RG-Kontrolle!\n→ Max. 30 ml/kg in 1. Stunde\n→ BZ 180 → Stressreaktion, kein Insulin!\n→ Metformin + Dehydratation → Laktatazidose-Risiko!\n→ O₂-Gabe\n CAVE: Torasemid (Diuretikum) verschlimmert Dehydratation!\n Im Pflegeheim häufig zu spät erkannt!"},
diagnoseOptionen:["Hypovolämischer Schock bei Dehydratation","Septischer Schock und hämodynamischer Instabilität","Kardiogener Schock mit respiratorischer Insuffizienz","Medikamentenintoxikation"],
correctDiagnose:0,
diagnoseErklaerung:"4 Tage Durchfall + stehende Hautfalten + RR 70/40 + Somnolenz + Pflegeheim = hypovolämischer Schock bei Dehydratation. VEL (vorsichtig bei Herzinsuffizienz!). Diuretikum absetzen!"},
{id:"exam_strom_d",bpr:"stromunfall",caseId:141,
meldung:"Elektriker, 10.000V-Kontakt, bewusstlos, Verbrennungsmarken",
ankunft:"Mann liegt am Boden, bewusstlos. Strom abgeschaltet. Verbrennungsmarken an Hand und Fuß.",
findings:{
vitalzeichen:"RR: nicht messbar | HF: 40/min | SpO₂: 88% | AF: 8/min",
anamnese:"S: Kollege: 'Hat einen 10kV-Kasten berührt, wurde weggeschleudert.' A: unbekannt. M: unbekannt. P: unbekannt. L: unbekannt. E: Hochspannungsunfall vor 5 min",
inspektion:"Bewusstlos, Strommarke Eintritt rechte Hand (verkohlt), Austritt rechter Fuß, Sturzverletzung Hinterkopf",
auskultation:"Herztöne bradykard, Lunge: beidseits belüftet",
ekg:"Bradykardie 40/min, AV-Block II° Typ Mobitz",
neurologie:"GCS 6 (A1V2M3), Pupillen seitengleich",
palpation:"Strommarken, Haut dazwischen unauffällig"
},
xabcde:{c:"Keine massive Blutung extern",a:"GCS 6 → Atemwegssicherung! HWS-Immobilisation (Sturz!)",b:"AF 8 → assistierte Beatmung!",c2:"HF 40 + AV-Block → Atropin! Defibrillatonsbereitschaft!",d:"GCS 6 → SHT durch Sturz möglich!",e:"Strommarken: Eintritt Hand, Austritt Fuß → Strom durch Körper!"},
spezial:{name:"Hochspannungsunfall",result:"Hochspannungsunfall (>1000V):\n→ EIGENSCHUTZ! Strom abgeschaltet?\n→ Herzrhythmusstörungen häufig! → 24h Monitoring!\n→ Atropin bei Bradykardie\n→ Defibrillationsbereitschaft!\n→ VEL aggressiv (innere Verbrennungen → Myoglobin!)\n→ Strommarken ≠ Verbrennungsausmaß! → Innere Schäden!\n→ HWS-Immobilisation (Sturz/Weggeschleudert)\n→ Analgesie!\n CAVE: Innere Verbrennungen >>  äußere! Rhabdomyolyse!\n Immer Traumacheck (Sturz, Schleudertrauma)!"},
diagnoseOptionen:["Hochspannungsunfall mit Herzrhythmusstörung","Niederspannungsunfall bei unklarer Ätiologie","Blitzschlag mit neurologischem Defizit","Verbrennung ohne Stromunfall"],
correctDiagnose:0,
diagnoseErklaerung:"10.000V-Kontakt + Strommarken Eintritt/Austritt + Bradykardie + AV-Block + Bewusstlosigkeit = Hochspannungsunfall. Atropin, VEL aggressiv, HWS-Sicherung, 24h Monitoring!"},
{id:"exam_trach_d",bpr:"tracheostoma",caseId:142,
meldung:"65J mit Tracheostoma, akute Atemnot, Sekretverhalt, SpO₂ 75%",
ankunft:"Mann sitzt aufrecht, greift sich ans Tracheostoma, SpO₂ 75%, sichtbar Sekret in Kanüle.",
findings:{
vitalzeichen:"RR: 170/100 mmHg | HF: 125/min | SpO₂: 75% | AF: 32/min",
anamnese:"S: Ehefrau: 'Hatte erkältung, Sekret wurde immer zäher, kriegt keine Luft mehr.' A: keine. M: diverse. P: Z.n. Laryngektomie (Kehlkopfkrebs), permanentes Tracheostoma seit 2020. L: pürierte Kost. E: zunehmend seit 2h, jetzt akut",
inspektion:"Agitiert, greift an Tracheostoma, zähes gelbliches Sekret sichtbar in Kanüle, Einziehungen suprasternal, kann nicht sprechen",
auskultation:"Pfeifendes Geräusch über Tracheostoma, beidseits kaum Atemgeräusch",
ekg:"Sinustachykardie 125/min",
neurologie:"GCS 13, agitiert, kann nicht sprechen (Laryngektomie)",
palpation:"Pulse tachykard, Haut kaltschweißig"
},
xabcde:{c:"Keine Blutung",a:"TRACHEOSTOMA VERSTOPFT! Eskalationsstufen!",b:"SpO₂ 75% → KRITISCHE HYPOXIE!",c2:"Tachykardie + Hypertonie → Stressreaktion",d:"GCS 13, agitiert",e:"Erkältung mit Sekretbildung → Kanüle verstopft"},
spezial:{name:"Tracheostoma-Eskalation",result:"Tracheostoma-Notfall – Eskalationsstufen:\n1. Absaugen mit Katheter durch Kanüle\n2. Innere Kanüle entfernen (wenn zweiteilig!)\n3. Kanüle entblocken (Cuff-Luft ablassen)\n4. Gesamte Kanüle entfernen!\n5. NaCl 0,9% 2-5 ml instillieren (Sekretlösung)\n6. Über Stoma beatmen (Beutel-Maske auf Stoma)\n LARYNGEKTOMIE = Mund/Nase ist NICHT mit Trachea verbunden!\n EINZIGER Atemweg = Stoma!"},
diagnoseOptionen:["Tracheostoma-Obstruktion durch Sekretverhalt","Pneumothorax bei Z.n. Trauma","Pneumonie mit Atemversagen mit metabolischer Entgleisung","Trachealstenose und sekundärer Organbeteiligung"],
correctDiagnose:0,
diagnoseErklaerung:"Tracheostoma + zähes Sekret in Kanüle + SpO₂ 75% + Erkältung = Tracheostoma-Obstruktion durch Sekretverhalt. Eskalationsstufen: Absaugen → Innenkanüle raus → Entblocken → Kanüle raus → Stoma-Beatmung!"},
{id:"exam_intox_d",bpr:"intoxikation",caseId:143,
meldung:"28J Frau, V.a. Suizidversuch mit Tabletten, GCS 8, Atemdepression",
ankunft:"Frau liegt auf Sofa, bewusstlos, leere Bromazepam-Packung auf Tisch.",
findings:{
vitalzeichen:"RR: 95/60 mmHg | HF: 70/min | SpO₂: 85% | AF: 8/min | BZ: 90 mg/dl",
anamnese:"S: Mitbewohnerin: 'Hat einen Brief hinterlassen, leere Tablettenpackung.' A: keine. M: Bromazepam (verschrieben). P: Depression. L: Alkohol getrunken. E: vor 1-2h?",
inspektion:"Bewusstlos, flache Atmung, leere Bromazepam-Packung (6mg x 20 Stk), leere Weinflasche",
auskultation:"Herztöne leise, Lunge frei",
ekg:"Sinusbradykardie 70/min",
neurologie:"GCS 8 (A2V2M4), Pupillen eng (Miosis), keine fokalen Defizite",
palpation:"Pulse bradykard, Haut warm"
},
xabcde:{c:"Keine Blutung",a:"GCS 8 → Atemweg gefährdet! Seitenlage!",b:"AF 8 + SpO₂ 85% → ATEMDEPRESSION! Beatmung!",c2:"RR 95/60, HF 70 → Benzodiazepine + Alkohol",d:"GCS 8 → Benzodiazepin-Intoxikation",e:"Abschiedsbrief → Suizidversuch! Psychiatrische Begleitung!"},
spezial:{name:"Benzodiazepin-Intoxikation",result:"Benzodiazepin-Intoxikation:\n→ Atemwegssicherung! GCS 8 + AF 8 → Intubation erwägen!\n→ O₂-Gabe, ggf. Beutelbeatmung\n→ Flumazenil 0,2 mg i.v. titriert (Antidot!)\n  CAVE: Krampfanfälle bei chronischer Einnahme!\n  CAVE: Kurze HWZ → Reboundgefahr!\n→ Monitoring eng\n→ Aktivkohle NICHT bei Bewusstlosigkeit!\n→ Psychiatrische Begleitung!\n Mischintoxikation + Alkohol → verstärkte Wirkung!"},
diagnoseOptionen:["Benzodiazepin-Intoxikation bei Suizidversuch","Opioid-Intoxikation bei infektiöser Genese","Alkoholintoxikation allein mit kardialer Beteiligung","Hypoglykämie und drohender Dekompensation"],
correctDiagnose:0,
diagnoseErklaerung:"Leere Benzo-Packung + Bewusstlosigkeit + Miosis + Atemdepression + Alkohol + Abschiedsbrief = Benzodiazepin-Intoxikation bei Suizidversuch. Atemwegssicherung, Flumazenil titriert!"},
{id:"exam_intox_e",bpr:"intoxikation",caseId:144,
meldung:"35J Mann, bewusstlos auf Parkbank, enge Pupillen, AF 4/min",
ankunft:"Mann liegt auf Parkbank, bewusstlos, Spritzbesteck neben ihm.",
findings:{
vitalzeichen:"RR: 80/50 mmHg | HF: 55/min | SpO₂: 60% | AF: 4/min",
anamnese:"S: Passant hat ihn gefunden. Spritzbesteck sichtbar. A: unbekannt. M: unbekannt. P: unbekannt. L: unbekannt. E: Auffindungszeitpunkt unbekannt",
inspektion:"Bewusstlos, Zyanose, Speichelfluss, Spritzbesteck und Löffel neben ihm, Injektionsnarben Unterarme",
auskultation:"Herztöne bradykard, Lunge: vereinzelt feuchte RG (Aspiration?)",
ekg:"Sinusbradykardie 55/min",
neurologie:"GCS 3 (A1V1M1), Pupillen maximal eng (Stecknadelpupillen!), keine Reaktion",
palpation:"Pulse bradykard, kaum tastbar, Haut kühl, zyanotisch"
},
xabcde:{c:"Keine Blutung",a:"GCS 3 + Speichelfluss → Aspiration! Absaugen! Intubation!",b:"AF 4 + SpO₂ 60% → SOFORT Beutelbeatmung + Naloxon!",c2:"RR 80/50, HF 55 → Opioid-Wirkung + Hypoxie",d:"GCS 3, Stecknadelpupillen → OPIOID-INTOXIKATION!",e:"Spritzbesteck, Injektionsnarben = i.v.-Drogenkonsum"},
spezial:{name:"Opioid-Intoxikation",result:"Opioid-Intoxikation – Trias: Bewusstlosigkeit + Miosis + Atemdepression\n→ Beutelbeatmung SOFORT!\n→ Naloxon 0,4 mg i.v. (oder i.m./intranasal!)\n→ Wiederholung alle 2-3 min bis AF >10/min\n→ CAVE: Naloxon-HWZ kürzer als Opioid → Rebound!\n→ Vorsichtig titrieren (Entzugssymptome vermeiden)\n→ Absaugen bei Speichelfluss/Aspiration\n→ Intubation bei GCS 3 und fehlender Besserung\n→ Monitoring mind. 2h nach letzter Naloxon-Gabe!\n Naloxon intranasal auch ohne i.v.-Zugang möglich!"},
diagnoseOptionen:["Opioid-Intoxikation","Benzodiazepin-Intoxikation","Hypoglykämie","Schlaganfall"],
correctDiagnose:0,
diagnoseErklaerung:"Spritzbesteck + Stecknadelpupillen + AF 4/min + Bewusstlosigkeit = Opioid-Intoxikation. Sofort Beutelbeatmung + Naloxon 0,4 mg! Auf Rebound achten!"},
{id:"exam_hypotherm_d",bpr:"hypothermie",caseId:145,
meldung:"Obdachloser, Winter, bewusstlos, Temp 28°C, Bradykardie",
ankunft:"Mann liegt unter Kartons, bewusstlos, steif, kaum Lebenszeichen.",
findings:{
vitalzeichen:"RR: 60/30 mmHg | HF: 30/min | SpO₂: nicht messbar | AF: 6/min | Temp rektal: 28°C",
anamnese:"S: Passant hat ihn gefunden. Obdachlos. A: unbekannt. M: vermutl. Alkohol. P: unbekannt. L: leere Flasche neben ihm. E: Expositionsdauer unklar, Nacht -5°C",
inspektion:"Bewusstlos, steif, blass-grau, kaum sichtbare Atmung, Alkoholgeruch",
auskultation:"Herztöne kaum hörbar, sehr langsam",
ekg:"Bradykardie 30/min, Osborn-Wellen (J-Wellen)!",
neurologie:"GCS 3, areaktiv, Muskelrigidität",
palpation:"Kein peripherer Puls tastbar, zentral schwach"
},
xabcde:{c:"Keine Blutung",a:"Vorsichtig! Minimale Manipulation!",b:"AF 6 → vorsichtige Beatmung mit warmer Luft",c2:"HF 30, RR 60/30 → Hypothermie Stadium III! CAVE: VF-Risiko!",d:"GCS 3, Muskelrigidität",e:"Temp 28°C → SCHWERE HYPOTHERMIE!"},
spezial:{name:"Schwere Hypothermie",result:"Hypothermie Stadium III (28°C, bewusstlos):\n→ VORSICHTIGE Handhabung! Jede Erschütterung → VF!\n→ Horizontaler Transport!\n→ Nasse Kleidung entfernen, isolieren\n→ KEINE aktive externe Wärmung der Extremitäten!\n→ Warme Infusionen (38-40°C) wenn möglich\n→ Bei Kreislaufstillstand: CPR + Defibrillation 1x\n→ Wenn VF persistiert: keine weiteren Defis bis Temp >30°C\n→ Adrenalin-Intervall verdoppeln bei Temp <30°C\n NIEMAND IST TOT, BIS ER WARM UND TOT IST!\n Osborn-Wellen = pathognomonisch für Hypothermie!"},
diagnoseOptionen:["Schwere Hypothermie Stadium III","Opioid-Intoxikation","Alkoholkoma bei bestehender Medikation","Schlaganfall mit progredientem Verlauf"],
correctDiagnose:0,
diagnoseErklaerung:"Obdachloser + Winter + Temp 28°C + Bradykardie + Osborn-Wellen + Muskelrigidität = schwere Hypothermie Stadium III. Vorsichtige Handhabung, Klinik mit Wiedererwärmung!"},
{id:"exam_hypotherm_e",bpr:"hypothermie",caseId:146,
meldung:"Segler aus kaltem Wasser geborgen, verwirrt, starkes Zittern",
ankunft:"Mann am Ufer, triefend nass, zittert stark, verwirrt, Rettungsweste an.",
findings:{
vitalzeichen:"RR: 100/70 mmHg | HF: 55/min | SpO₂: 94% | AF: 14/min | Temp: 33°C",
anamnese:"S: Rettungsschwimmer: 'Boot gekentert, war ca. 20 min im 8°C kalten Wasser.' A: unbekannt. M: unbekannt. P: unbekannt. L: unbekannt. E: Wassertemperatur 8°C, Exposition ~20 min",
inspektion:"Nass, starkes Zittern, verwirrt, blass, spricht verwaschen",
auskultation:"Herztöne bradykard, Lunge frei (kein Ertrinken!)",
ekg:"Sinusbradykardie 55/min, keine Osborn-Wellen",
neurologie:"GCS 13 (A4V3M6), verwirrt, desorientiert, Zittern",
palpation:"Haut kalt, Pulse tastbar"
},
xabcde:{c:"Keine Blutung",a:"Frei",b:"SpO₂ 94% → O₂",c2:"HF 55, RR 100/70 → milde bis moderate Hypothermie",d:"GCS 13, verwirrt, Zittern = Wärmeproduktion!",e:"Temp 33°C → Hypothermie Stadium I-II. Zittern = GUTES Zeichen!"},
spezial:{name:"Hypothermie Stadium I-II",result:"Hypothermie Stadium I-II (32-35°C):\n→ Nasse Kleidung entfernen!\n→ Isolation + aktive Wärmung (Decken, warme Getränke wenn wach)\n→ Horizontaler Transport (Afterdrop vermeiden!)\n→ Warme Infusionen wenn möglich\n→ Monitoring (HF, EKG, Temp)\n→ Zittern = aktive Wärmeproduktion = Stadium I-II\n→ Kein Zittern bei <32°C = Stadium III!\n Afterdrop: beim Aufwärmen sinkt Kerntemperatur erst weiter!\n Horizontale Rettung + Transport essentiell!"},
diagnoseOptionen:["Hypothermie Stadium I-II nach Wasserrettung","Ertrinken mit Hypothermie bei unklarer Bewusstseinslage","Alkoholintoxikation und vegetativer Begleitsymptomatik","Sepsis mit Unterkühlung mit akuter Kreislaufdekompensation"],
correctDiagnose:0,
diagnoseErklaerung:"Kaltwasser-Exposition 20 min + Temp 33°C + Zittern + Verwirrtheit = Hypothermie Stadium I-II. Nasse Kleidung aus, Isolation, horizontaler Transport, warme Getränke!"},
{id:"exam_geburt_d",bpr:"geburt",caseId:147,
meldung:"32J Erstgebärende, 39. SSW, Pressdrang, Kindskopf sichtbar",
ankunft:"Frau im Schlafzimmer, Presswehen, Kindskopf am Introitus sichtbar.",
findings:{
vitalzeichen:"RR: 130/80 mmHg | HF: 100/min | SpO₂: 98% | AF: 20/min",
anamnese:"S: 'Kann nicht mehr halten, Kind kommt!' A: keine. M: Magnesium (SS). P: Erstgebärende, 39+2 SSW, unauffällige SS. L: Frühstück. E: Pressdrang seit 30 min, zunehmend",
inspektion:"Presswehen, Kindskopf sichtbar im Scheideneingang, klares Fruchtwasser",
auskultation:"Kindliche Herztöne per Stethoskop: ~140/min",
ekg:"Nicht angelegt (Mutter)",
neurologie:"GCS 15, kooperativ, Schmerzen",
palpation:"Kindskopf am Introitus, Nabelschnur nicht vorgelagert"
},
xabcde:{c:"Keine Blutung aktuell",a:"Frei",b:"SpO₂ 98%",c2:"Stabil",d:"GCS 15, kooperativ",e:"Geburt steht unmittelbar bevor! Nicht aufhalten!"},
spezial:{name:"Geburt im RTW",result:"Geburt bei sichtbarem Kopf:\n→ NICHT aufhalten! Transport kontraindiziert!\n→ Dammschutz mit Handtuch/Tuch\n→ Kopf langsam entwickeln lassen\n→ Nabelschnur prüfen (um Hals?)\n→ Nach Kopf: auf äußere Drehung warten\n→ Kind abnabeln (2 Klemmen, dazwischen durchtrennen)\n→ Kind abtrocknen, WÄRME!\n→ APGAR 1-5-10 min\n→ Oxytocin 3-5 IE i.v. nach Geburt (Nachblutung!)\n→ Plazenta abwarten (nicht ziehen!)\n Mutter ansprechen, beruhigen, führen!"},
diagnoseOptionen:["Physiologische Geburt im Notfall","Placenta praevia bei vorbestehender Grunderkrankung","Nabelschnurvorfall mit begleitender Bewusstseinstrübung","Uterusruptur und hämodynamischer Instabilität"],
correctDiagnose:0,
diagnoseErklaerung:"39. SSW + Presswehen + Kindskopf sichtbar + klares Fruchtwasser + fetale HT 140/min = physiologische Geburt, nicht mehr aufzuhalten. Dammschutz, Kind entwickeln, Wärme, Oxytocin!"},
{id:"exam_geburt_e",bpr:"geburt",caseId:148,
meldung:"28J, 38. SSW, Sturzgeburt, Schulter steckt fest, Kind wird blau",
ankunft:"Kind teilweise geboren, Schultern stecken fest, Kopf bereits blau.",
findings:{
vitalzeichen:"RR: 140/90 mmHg | HF: 110/min | SpO₂: 97% | AF: 22/min",
anamnese:"S: 'Kind kommt nicht weiter, Schulter steckt!' A: keine. M: keine. P: 2. Kind, 38+4 SSW, Gestationsdiabetes, Kind geschätzt 4200g. L: unbekannt. E: Kopf vor 2 min geboren, Schultern stecken",
inspektion:"Kindskopf geboren, blau-livide, Kopf zieht sich zurück ('Turtle Sign'), Schultern nicht entwickelbar",
auskultation:"Kindliche HT nicht beurteilbar (Kompression)",
ekg:"Nicht angelegt",
neurologie:"Mutter: GCS 15, panisch",
palpation:"Kindskopf geboren, Schulter impaktiert hinter Symphyse"
},
xabcde:{c:"Keine Blutung aktuell",a:"Kind: Atemweg nicht frei (Kompression im Geburtskanal!)",b:"Kind kann nicht atmen → ZEITKRITISCH!",c2:"Mutter stabil",d:"Mutter: GCS 15",e:"Turtle Sign + Kind >4000g + GDM → SCHULTERDYSTOKIE!"},
spezial:{name:"Schulterdystokie",result:"Schulterdystokie – Zeitkritisch!\n→ McRoberts-Manöver: Beine der Mutter maximal an Bauch!\n→ Suprapubischer Druck (NICHT Fundus!)\n→ Durch Helfer von oben auf Symphyse drücken\n→ Ruhe bewahren, klare Ansagen\n→ Bei Misserfolg: innere Rotation (Woodsche Schraube)\n→ NIEMALS am Kopf des Kindes ziehen!\n→ NIEMALS Kristellerhandgriff (Fundusdruck)!\n→ Kind sofort nach Entwicklung: Abnabeln, Reanimation!\n 4-7 min Zeit bis irreversible Schäden!"},
diagnoseOptionen:["Schulterdystokie","Nabelschnurvorfall","Beckenendlage","Normale verzögerte Schulterentwicklung"],
correctDiagnose:0,
diagnoseErklaerung:"Turtle Sign + Schulter steckt + Makrosomie (4200g) + GDM = Schulterdystokie. McRoberts-Manöver + suprapubischer Druck sofort! NICHT am Kopf ziehen!"},
{id:"exam_aproblem_d",bpr:"a_problem_erw",caseId:149,
meldung:"80J Pflegeheim-Bewohnerin, bewusstlos, lautes Gurgelgeräusch, SpO₂ 70%",
ankunft:"Frau liegt im Bett, bewusstlos, lautes Gurgelgeräusch bei jedem Atemzug.",
findings:{
vitalzeichen:"RR: 180/100 mmHg | HF: 50/min | SpO₂: 70% | AF: 8/min (gurgelnde Atemgeräusche)",
anamnese:"S: Pflege: 'Beim Füttern plötzlich bewusstlos geworden, gurgelt.' A: keine. M: diverse. P: Z.n. Schlaganfall mit Dysphagie, Demenz, bettlägerig. L: gerade gefüttert (Brei). E: vor 5 min",
inspektion:"Bewusstlos, gurgelnde Atmung, Speisereste im Mund sichtbar, Zyanose",
auskultation:"Gurgelnde Atemgeräusche, Lunge: beidseits feuchte RG",
ekg:"Sinusbradykardie 50/min",
neurologie:"GCS 3 (A1V1M1), keine Reaktion",
palpation:"Pulse bradykard"
},
xabcde:{c:"Keine Blutung",a:"BOLUS-ASPIRATION! SOFORT absaugen + Freimachen!",b:"SpO₂ 70%, AF 8 → nach Freimachen Beatmung!",c2:"Bradykardie durch Hypoxie",d:"GCS 3 → Atemweg nicht geschützt",e:"Dysphagie nach Schlaganfall → Aspirationsrisiko!"},
spezial:{name:"Bolusaspiration bei Dysphagie",result:"Bolusaspiration bei bewusstloser Patientin:\n→ Absaugen mit großlumigem Katheter!\n→ Laryngoskopie → Magill-Zange wenn FK sichtbar!\n→ Esmarch-Handgriff\n→ Guedel-/Wendl-Tubus\n→ O₂ hochdosiert nach Freimachen\n→ Intubation wenn Atemweg nicht zu sichern\n→ Bei Kreislaufstillstand → CPR!\n Z.n. Schlaganfall mit Dysphagie = Hochrisiko für Aspiration!\n Fütterung = häufigster Auslöser!"},
diagnoseOptionen:["Bolusaspiration bei Dysphagie","Erneuter Schlaganfall","Epileptischer Anfall","Herzinfarkt mit respiratorischer Insuffizienz"],
correctDiagnose:0,
diagnoseErklaerung:"Beim Füttern + bewusstlos + gurgelnde Atmung + Speisereste im Mund + Dysphagie bekannt = Bolusaspiration. Sofort absaugen, Atemweg freimachen!"},
{id:"exam_aproblem_e",bpr:"a_problem_erw",caseId:150,
meldung:"55J Mann, ACE-Hemmer, massive Zungenschwellung, Stridor, SpO₂ 82%",
ankunft:"Mann im Wohnzimmer, massive Schwellung der Zunge, Stridor, kann kaum schlucken.",
findings:{
vitalzeichen:"RR: 160/95 mmHg | HF: 110/min | SpO₂: 82% | AF: 28/min",
anamnese:"S: 'Zunge ist plötzlich angeschwollen, kann kaum atmen!' A: Kontrastmittel. M: Ramipril (seit 3 Monaten!). P: Hypertonie, keine Allergien. L: unbekannt. E: Schwellung seit 1h, zunehmend",
inspektion:"Massive Zungenschwellung, Lippen geschwollen, Stridor, Speichelfluss, KEINE Urtikaria, KEINE Rötung",
auskultation:"Inspiratorischer Stridor, Lunge frei (kein Giemen!)",
ekg:"Sinustachykardie 110/min",
neurologie:"GCS 14, kann kaum sprechen, ängstlich",
palpation:"Keine Hautveränderungen"
},
xabcde:{c:"Keine Blutung",a:"Massive Zungenschwellung + Stridor → ATEMWEG KRITISCH BEDROHT!",b:"SpO₂ 82% → O₂ hochdosiert",c2:"RR 160/95, HF 110",d:"GCS 14, kann kaum sprechen",e:"ACE-Hemmer + Angioödem OHNE Urtikaria → BRADYKININ-vermittelt!"},
spezial:{name:"ACE-Hemmer-Angioödem",result:"ACE-Hemmer-induziertes Angioödem – BESONDERHEIT:\n→ KEINE Anaphylaxie! Bradykinin-vermittelt!\n→ Adrenalin KANN helfen, ist aber weniger wirksam!\n→ Prednisolon + Dimetinden versuchen\n→ Icatibant 30 mg s.c. (Bradykinin-Antagonist – wenn verfügbar)\n→ Frühzeitige Intubation erwägen BEVOR Schwellung zunimmt!\n→ Koniotomie-Bereitschaft!\n→ ACE-Hemmer SOFORT und DAUERHAFT absetzen!\n CAVE: Kann auch nach Jahren unter ACE-Hemmer auftreten!\n Keine Urtikaria = NICHT allergisch = Adrenalin weniger wirksam!"},
diagnoseOptionen:["ACE-Hemmer-induziertes Angioödem","Allergisches Angioödem, differentialdiagnostisch abzugrenzen von funktioneller Störung","Anaphylaxie bei unklarer Ätiologie","Peritonsillarabszess"],
correctDiagnose:0,
diagnoseErklaerung:"ACE-Hemmer + Angioödem + KEINE Urtikaria + KEIN Giemen = Bradykinin-vermitteltes Angioödem. Adrenalin weniger wirksam! Frühzeitig Intubation erwägen, ACE-Hemmer absetzen!"}

]);
