// NotSanTrainer 2025 - Prüfungsfälle (Teil 2/3, Fälle 51-100)
EXAM_CASES = EXAM_CASES.concat([
{id:"exam_hypotherm_b",bpr:"hypothermie",caseId:38,
meldung:"Obdachloser reglos auf Parkbank, Winter, Minusgrade",
ankunft:"Mann liegt zusammengekauert auf Bank, Nachttemperatur -5°C. Kaum Reaktion.",
findings:{
vitalzeichen:"RR: 80/50 mmHg | HF: 38/min | SpO₂: 88% | AF: 8/min | BZ: 65 mg/dl | Temp (tympanal): 29°C",
anamnese:"S: Passant: 'Liegt seit Stunden hier.' A: unbekannt. M: unbekannt. P: bekannter Alkoholiker laut Passanten. L: unbekannt. E: Kälteexposition bei Minusgraden, vermutlich Alkoholisiert",
inspektion:"Zusammengekauert, steif, blass-livide, kaum Reaktion auf Ansprache, verlangsamte Atmung, leerer Alkoholgeruch",
auskultation:"Herztöne sehr leise, bradykard. Lunge: abgeschwächtes AG bds",
ekg:"Sinusbradykardie 38/min, Osborn-Wellen (J-Wellen) sichtbar!, verlängertes QT",
neurologie:"GCS 7 (A2V2M3), reagiert nur auf Schmerzreiz, Pupillen weit, träge",
palpation:"Karotispuls schwach, langsam, Haut eiskalt, steif, Muskelrigidität"
},
xabcde:{c:"Keine Blutung",a:"Atemweg gefährdet bei GCS 7 → Absaugbereitschaft, SL wenn nötig",b:"AF 8, SpO₂ 88% → O₂-Gabe, ggf. assistierte Beatmung. CAVE: Warme Luft!",c2:"HF 38, RR 80/50 → Bradykardie hypothermiebedingt! Atropin bei <30°C meist wirkungslos!",d:"GCS 7, Pupillen weit → Hypothermie, NICHT automatisch Hirntod!",e:"Temp 29°C → HYPOTHERMIE STADIUM III! BZ 65 → Glucose erwägen"},
spezial:{name:"Hypothermie-Stadien",result:"Stadium I (35-32°C): Zittern, wach\nStadium II (32-28°C): Bewusstseinsminderung, kein Zittern\nStadium III (28-24°C): Bewusstlos, Vitalzeichen vorhanden ← DIESER PAT!\nStadium IV (<24°C): Kein Kreislauf\n→ Temp 29°C = STADIUM III\n→ PASSIVE + AKTIVE Wiedererwärmung\n→ Vorsichtige Bewegung (VF-Gefahr!)\n→ Max. 1x Defi + 1x Epi bei <30°C\n 'Nobody is dead until warm and dead!'"},
diagnoseOptionen:["Schwere Hypothermie Stadium III","Alkoholintoxikation ohne Hypothermie","Schlaganfall bei obdachlosem Patienten","Opiat-Intoxikation"],
correctDiagnose:0,
diagnoseErklaerung:"Kälteexposition + Temp 29°C + Bradykardie + Osborn-Wellen + GCS 7 = Hypothermie Stadium III. Passive + aktive Wiedererwärmung, vorsichtiger Transport, Kreislaufstillstand-Bereitschaft."},
{id:"exam_hypert_b",bpr:"hypertensiv",caseId:32,
meldung:"Starke Kopfschmerzen und Nasenbluten, 62J Frau, RR sehr hoch",
ankunft:"Patientin sitzt im Wohnzimmer, Kopf nach vorne, Tuch vor der Nase, blutet.",
findings:{
vitalzeichen:"RR: 240/130 mmHg | HF: 95/min | SpO₂: 97% | AF: 18/min | BZ: 160 mg/dl",
anamnese:"S: 'Schlimmste Kopfschmerzen seit Stunden, dann Nasenbluten, Übelkeit, Sehstörungen.' A: keine. M: 'Habe meine Tabletten seit 1 Woche nicht genommen.' P: Hypertonie, Diabetes Typ 2. L: Mittagessen. E: Kopfschmerzen seit Morgen, zunehmend",
inspektion:"Schmerzgeplagt, Epistaxis rechts, hält Tuch vor Nase, kneift Augen zusammen (Lichtempfindlichkeit)",
auskultation:"Herztöne regelmäßig, Lunge frei",
ekg:"Sinusrhythmus 95/min, linksventrikuläre Hypertrophie, keine akuten ST-Veränderungen",
neurologie:"GCS 15, wach, Kopfschmerzen, Sehstörungen (verschwommenes Sehen), keine fokalen Defizite, keine Paresen",
palpation:"Pulse kräftig, beidseits symmetrisch"
},
xabcde:{c:"Epistaxis → Kompression!",a:"Frei",b:"Unauffällig",c2:"RR 240/130 → HYPERTENSIVER NOTFALL! Endorganschaden?",d:"GCS 15, aber Kopfschmerzen + Sehstörungen → V.a. hypertensive Enzephalopathie",e:"BZ 160, keine weiteren Befunde"},
spezial:{name:"Hypertensiver Notfall",result:"RR 240/130 + Kopfschmerz + Sehstörung + Epistaxis\n→ Hypertensiver NOTFALL (mit Endorganzeichen!)\n→ NICHT hypertensive Krise (die wäre ohne Endorganzeichen)\nTherapie: Urapidil 5 mg i.v., Repetition möglich (max. 25 mg)\nZiel: Moderate Senkung um 20-25% in 1h\n KEINE rasche Senkung → Gefahr zerebraler Minderperfusion!\n DD: Schlaganfall ausschließen! Keine fokalen Defizite → spricht für hypertensiven Notfall"},
diagnoseOptionen:["Hypertensiver Notfall mit V.a. Enzephalopathie","Subarachnoidalblutung mit kardialer Beteiligung","Schlaganfall und drohender Dekompensation","Migräne bei bestehender Medikation"],
correctDiagnose:0,
diagnoseErklaerung:"RR 240/130 + Kopfschmerz + Sehstörung + Epistaxis bei Non-Compliance = hypertensiver Notfall. Urapidil 5 mg i.v., moderate RR-Senkung. DD: SAB/Schlaganfall ausschließen."},
{id:"exam_krampf_b",bpr:"krampf_erw",caseId:53,
meldung:"Mann krampft seit 10 Minuten, 40J, auf Gehweg",
ankunft:"Mann liegt auf Gehweg, tonisch-klonische Krämpfe, Schaum vor dem Mund.",
findings:{
vitalzeichen:"RR: 170/100 mmHg | HF: 130/min | SpO₂: 78% | AF: unregelmäßig | BZ: 95 mg/dl",
anamnese:"S: Passant: 'Ist plötzlich hingefallen und krampft seitdem.' A: unbekannt. M: Medikamentenblister in Tasche: Levetiracetam, Lamotrigin. P: vermutlich Epilepsie. L: unbekannt. E: plötzliches Ereignis vor 10 min",
inspektion:"Generalisierte tonisch-klonische Krämpfe, Schaum vor dem Mund, seitlicher Zungenbiss, Urinabgang, zyanotisch",
auskultation:"Nicht durchführbar während Krampf",
ekg:"Artefakte durch Muskelaktivität, Sinustachykardie zwischen Krämpfen",
neurologie:"Nicht beurteilbar während aktivem Krampf",
palpation:"Generalisierter Muskeltonus erhöht, periphere Pulse tastbar"
},
xabcde:{c:"Keine Blutung, Zungenbiss",a:"Während Krampf gefährdet → Seitenlage nach Krampfende! KEIN Beißkeil!",b:"SpO₂ 78% → O₂-Gabe! Hypoxie durch Krampf!",c2:"Tachykardie, RR erhöht → sympathikoadrenerge Reaktion auf Krampf",d:"AKTIVER STATUS EPILEPTICUS (>5 min)! Sofort Midazolam!",e:"Zungenbiss, Urinabgang → typisch epileptisch, BZ 95 = normal"},
spezial:{name:"Status epilepticus – Therapie",result:"Krampfdauer >5 min = STATUS EPILEPTICUS\n→ Midazolam ADÄQUAT HOCH dosieren, NICHT titrieren!\nErwachsener: 0,1 mg/kgKG i.v. ODER 10 mg i.m./buccal/nasal\nMax. 20 mg, einmalige Repetition möglich\n CAVE: Kein primär hypoxisch bedingter Krampf? → SpO₂ 78% → O₂ vorher!\n→ BZ prüfen (hier 95 = normal)\n→ Antiepileptika in Tasche = bekannte Epilepsie"},
diagnoseOptionen:["Status epilepticus bei bekannter Epilepsie","Hypoglykämischer Krampf mit progredientem Verlauf","Synkope mit Myoklonien bei unklarer Bewusstseinslage","Psychogener nicht-epileptischer Anfall"],
correctDiagnose:0,
diagnoseErklaerung:"Tonisch-klonisch >5 min + Antiepileptika in Tasche + Zungenbiss + Urinabgang = Status epilepticus bei bekannter Epilepsie. Midazolam 0,1 mg/kgKG i.v. oder 10 mg buccal. O₂-Gabe!"},
{id:"exam_krampf_kind_b",bpr:"krampf_kind",caseId:56,
meldung:"Kleinkind krampft, 2J, hohes Fieber, erstmalig",
ankunft:"Kind auf Sofa, generalisierte Krämpfe, Mutter panisch. Stirn glühend heiß.",
findings:{
vitalzeichen:"HF: 175/min | SpO₂: 85% | AF: unregelmäßig | BZ: 100 mg/dl | Temp: 40,2°C",
anamnese:"S: Mutter: 'Hatte seit Morgen Fieber, plötzlich angefangen zu krampfen, seit 3 min.' A: keine. M: Paracetamol-Saft vor 2h. P: gesund, erste Episode. L: wenig getrunken. E: Fieber seit Morgen, plötzlicher Krampfbeginn",
inspektion:"Generalisierte tonisch-klonische Krämpfe, gerötet, heiß, Schaum vor dem Mund",
auskultation:"Nicht durchführbar während Krampf",
ekg:"Nicht angelegt",
neurologie:"Aktiver Krampfanfall",
palpation:"Heiße Haut, Temp 40,2°C"
},
xabcde:{c:"Keine Blutung",a:"Während Krampf überwachen, nach Krampfende Seitenlage",b:"SpO₂ 85% → O₂-Gabe!",c2:"HF 175, altersgemäß bei Fieber + Krampf",d:"Aktiver Krampfanfall! Wenn >5 min → Midazolam!",e:"Temp 40,2°C → FIEBERKRAMPF!"},
spezial:{name:"Fieberkrampf Kind – Vorgehen",result:"Erstmaliger Fieberkrampf, 2 Jahre, Dauer aktuell 3 min\n→ Wenn selbstlimitierend (<5 min): Abwarten, O₂, Sicherheit\n→ Wenn >5 min: Midazolam buccal!\n 1-4 Jahre: Buccolam 5 mg buccal\n ODER nasal: 10-20 kgKG → 5 mg\n→ KEINE Antipyrese im aktiven Krampf!\n→ Nach Krampfende: Fiebersenkung (Paracetamol/Ibuprofen)\n KEIN primär hypoxischer Krampf → Midazolam indiziert falls >5 min"},
diagnoseOptionen:["Fieberkrampf (erstmalig, unkompliziert)","Meningitis mit Krampf und vegetativer Begleitsymptomatik","Epileptischer Anfall mit akuter Kreislaufdekompensation","Intoxikation bei vorbestehender Grunderkrankung"],
correctDiagnose:0,
diagnoseErklaerung:"Alter 2J + Fieber 40,2°C + erstmaliger generalisierter Krampf = Fieberkrampf. Wenn >5 min: Midazolam buccal 5 mg (1-4J). O₂-Gabe, Sicherheit. Nach Krampfende Fiebersenkung."},
{id:"exam_apoplex_b",bpr:"schlaganfall",caseId:68,
meldung:"Plötzliche Sprachstörung und Armlähmung, 73J Frau, seit 45 Minuten",
ankunft:"Patientin sitzt im Stuhl, spricht unverständlich, rechter Arm hängt kraftlos.",
findings:{
vitalzeichen:"RR: 185/100 mmHg | HF: 80/min (arrhythmisch) | SpO₂: 95% | AF: 16/min | BZ: 130 mg/dl",
anamnese:"S: Ehemann: 'Wir saßen beim Kaffee, plötzlich hat sie Kaffee verschüttet, kann nicht mehr sprechen.' A: keine. M: Apixaban, Bisoprolol, Ramipril. P: Vorhofflimmern, Hypertonie. L: Kaffee. E: plötzlicher Beginn vor 45 min, Zeitpunkt genau bekannt!",
inspektion:"Im Stuhl sitzend, versucht zu sprechen (Wortfindungsstörung, unverständlich), rechter Arm kraftlos, Mundwinkel rechts hängend",
auskultation:"Herztöne arrhythmisch, Lunge frei",
ekg:"Vorhofflimmern 80/min, keine ST-Veränderungen",
neurologie:"GCS 13 (A4V3M6), motorische Aphasie, Fazialisparese rechts, Armparese rechts (Kraft 1/5), Bein rechts (Kraft 3/5), Blickdeviation nach links",
palpation:"Pulse arrhythmisch, beidseits symmetrisch"
},
xabcde:{c:"Keine Blutung",a:"Cave: Schluckstörung bei Aphasie → Aspirationsschutz!",b:"SpO₂ 95%, AF 16 → aktuell stabil, O₂ nur bei SpO₂ <92%",c2:"Arrhythmisch (VHF), RR 185 → NICHT unter 180 senken!",d:"FOKALNEUROLOGISCHES DEFIZIT! BE-FAST positiv!",e:"Keine Verletzungen"},
spezial:{name:"BE-FAST",result:"Balance: nicht getestet (sitzt)\nEyes: Blickdeviation nach links ✓\nFace: Fazialisparese rechts ✓\nArms: Armparese rechts ✓\nSpeech: Motorische Aphasie ✓\nTime: Symptombeginn vor 45 min → LYSE-ZEITFENSTER!\n→ RR: 185 → NICHT senken (erst ab >220)!\n→ BZ 130 → unauffällig\n→ NOAK (Apixaban) in Vormedikation → Klinik informieren!\n Stroke Unit mit Lysemöglichkeit anfahren!"},
diagnoseOptionen:["Akuter ischämischer Schlaganfall (MCA links)","Migräne mit Aura mit begleitender Bewusstseinstrübung","Postiktale Todd-Parese nach Krampf, bei persistierenden Symptomen trotz initialer Maßnahmen","Hypoglykämie und hämodynamischer Instabilität"],
correctDiagnose:0,
diagnoseErklaerung:"Plötzliche Aphasie + Fazialisparese + Armparese rechts + Blickdeviation bei VHF-Patientin = akuter ischämischer Schlaganfall (MCA links). Zeitfenster 45 min → Lyse möglich! RR NICHT senken. Stroke Unit!"},
{id:"exam_trauma_b",bpr:"polytrauma",caseId:65,
meldung:"Fahrradunfall, 35J Mann, vom LKW erfasst, bewusstlos",
ankunft:"Mann liegt auf Straße, Fahrradhelm zerbrochen, Oberschenkelfraktur rechts sichtbar.",
findings:{
vitalzeichen:"RR: 80/50 mmHg | HF: 135/min | SpO₂: 88% | AF: 28/min, flach | BZ: 120 mg/dl",
anamnese:"S: Zeuge: 'LKW hat ihn beim Abbiegen erfasst, 5 Meter weit geschleudert.' A: unbekannt. M: unbekannt. P: unbekannt. L: unbekannt. E: Hochrasanztrauma vor 8 min",
inspektion:"Bewusstlos, instabiler Thorax rechts (Prellmarke), offene Oberschenkelfraktur rechts mit starker Blutung, Prellmarke Abdomen, Helm zerbrochen",
auskultation:"Rechts abgeschwächtes AG (Pneumothorax?), links belüftet. Herztöne tachykard, leise",
ekg:"Sinustachykardie 135/min",
neurologie:"GCS 7 (A1V2M4), Pupillen: links 3mm, rechts 5mm (anisocor!) → V.a. epidurale Blutung!",
palpation:"Instabiler Thorax rechts, Abdomen gespannt, offene Fraktur OS rechts mit pulsierender Blutung, Becken instabil bei Kompression"
},
xabcde:{c:"KRITISCHE BLUTUNG OS rechts → Tourniquet! Becken instabil → Beckenschlinge!",a:"GCS 7 → Atemweg sichern! Cave: HWS-Immobilisation",b:"SpO₂ 88%, rechts abgeschwächt → V.a. Pneumothorax! Thoraxentlastung erwägen!",c2:"RR 80/50, HF 135 → HÄMORRHAGISCHER SCHOCK! VEL + TXA!",d:"GCS 7, Anisokorie → V.a. intrakranielle Blutung! LOAD-AND-GO!",e:"Hypothermieprophylaxe! Polytrauma = Gesamtversorgung"},
spezial:{name:"<c>ABCDE Polytrauma",result:"<c>: Tourniquet OS rechts + Beckenschlinge → SOFORT!\nA: GCS 7 → Atemwegssicherung, HWS-Immobilisation\nB: V.a. Pneumothorax rechts → Thoraxentlastungspunktion erwägen\nC: Hämorrhagischer Schock → 2x großlumige Zugänge, VEL, TXA 15 mg/kgKG\nD: Anisokorie → SHT mit Einklemmungsgefahr! → LOAD-AND-GO!\nE: Hypothermieprophylaxe\n Schwerstes Polytrauma → schnellster Transport ins Traumazentrum!"},
diagnoseOptionen:["Polytrauma mit hämorrhagischem Schock und SHT","Isoliertes SHT mit Bewusstlosigkeit","Isolierte Oberschenkelfraktur mit Volumenmangel","Spannungspneumothorax als Hauptproblem"],
correctDiagnose:0,
diagnoseErklaerung:"Hochrasanztrauma + GCS 7 + Anisokorie + offene Fraktur + instabiles Becken + Thoraxbefund = schwerstes Polytrauma. <c>ABCDE: Tourniquet, Beckenschlinge, Atemweg, Thorax, VEL + TXA, Load-and-Go!"},
{id:"exam_strom_b",bpr:"stromunfall",caseId:74,
meldung:"Kind hat in Steckdose gefasst, 3J, schreit, Verbrennungsmarke Hand",
ankunft:"Kind weint auf Arm der Mutter, Strommarke am rechten Zeigefinger.",
findings:{
vitalzeichen:"HF: 150/min | SpO₂: 99% | AF: 28/min | BZ: 130 mg/dl",
anamnese:"S: Mutter: 'Hat mit Gabel in Steckdose gefasst, Stecker ohne Kindersicherung.' A: keine. M: keine. P: gesund. L: Mittagessen. E: Niederspannungsunfall (230V) vor 10 min",
inspektion:"Weint, Strommarke rechter Zeigefinger (kleiner weißlicher Bezirk), sonst äußerlich unauffällig",
auskultation:"Herztöne regelmäßig, tachykard (Aufregung), Lunge frei",
ekg:"Sinustachykardie 150/min (altersgemäß bei Aufregung), keine Rhythmusstörungen aktuell",
neurologie:"GCS 15, weint, reagiert adäquat, bewegt alle Extremitäten",
palpation:"Pulse tastbar, peripher warm, Strommarke rechter Zeigefinger"
},
xabcde:{c:"Keine Blutung",a:"Frei",b:"Unauffällig",c2:"Tachykard (altersgemäß bei Weinen), aktuell stabil. ABER: Rhythmusstörungen können verzögert auftreten!",d:"GCS 15, wach, reagiert",e:"Strommarke rechter Zeigefinger, keine Austrittsmarke erkennbar"},
spezial:{name:"Stromunfall – Monitoring",result:"Niederspannung (230V Haushalt)\nAktuell: Kind stabil, keine Rhythmusstörungen\n→ TROTZDEM: Klinikeinweisung obligat!\n→ 12-Kanal-EKG + 24h Monitoring!\n→ Herzenzyme (Troponin) bestimmen lassen\n→ Strommarke versorgen (steriler Verband)\n Rhythmusstörungen können VERZÖGERT auftreten (bis 24h)!\n Cave: Auch bei scheinbar harmlosem Stromunfall → Klinik!"},
diagnoseOptionen:["Stromunfall (Niederspannung) – stabile Situation, Monitoring nötig","Harmlose Hautverbrennung ohne systemische Gefährdung","Krampfanfall ausgelöst durch Strom mit respiratorischer Insuffizienz","Verbrühung bei unklarer Ätiologie"],
correctDiagnose:0,
diagnoseErklaerung:"Steckdose (230V) + Strommarke + Kind = Stromunfall, aktuell stabil. Trotzdem zwingend Klinikeinweisung mit 24h-EKG-Monitoring wegen Gefahr verzögerter Rhythmusstörungen!"},
{id:"exam_therm_b",bpr:"thermisch",caseId:77,
meldung:"Verbrühung Kleinkind, 18 Monate, Topf mit heißem Wasser umgekippt",
ankunft:"Kind schreit, Mutter hat Kleidung teilweise ausgezogen, Rötung und Blasen Oberkörper.",
findings:{
vitalzeichen:"HF: 175/min | SpO₂: 98% | AF: 30/min | BZ: 110 mg/dl",
anamnese:"S: Mutter: 'Hat am Herd den Topf runtergezogen, kochendes Wasser über Brust und Arme.' A: keine. M: keine. P: gesund. L: Mittagessen. E: Verbrühung vor 15 min",
inspektion:"Schreit, Verbrühung Brust/Bauch und beide Arme: Rötung, Blasenbildung, z.T. offene Blasen. Geschätzt ca. 25% VKOF (Brust 2x9% + Arme partiell)",
auskultation:"Herztöne tachykard, Lunge frei, keine Inhalationsverletzung (kein Ruß, kein Stridor)",
ekg:"Nicht angelegt",
neurologie:"Wach, schreit (schmerzbedingt)",
palpation:"Haut im Bereich der Verbrühung: teils IIa (Blasen, Rötung, schmerzhaft), teils IIb (offene Blasen, weißlich)"
},
xabcde:{c:"Keine Blutung",a:"Frei, keine Inhalation",b:"Unauffällig",c2:"HF 175, stabil aber → Volumentherapie bei >10% VKOF beim Kind!",d:"Wach, schreit → Schmerztherapie!",e:"VKOF ca. 25%, Grad IIa-IIb → schwere thermische Verletzung beim Kleinkind!"},
spezial:{name:"Thermische Verletzung Kind",result:"VKOF ca. 25% (Brust + Arme) → SCHWER\nGrad IIa-IIb (Blasen, z.T. offen)\n→ KEINE Kühlung! (Hypothermiegefahr bei Kindern!)\n→ Steriler Verband / Metalline-Folie\n→ VEL: 10 ml/kgKG i.v.\n→ Schmerztherapie: z.B. Esketamin nasal/i.v.\n→ Wärmeerhalt! Hypothermieprophylaxe!\n >10% VKOF beim Kind → Verbrennungszentrum!\n Handinnenfläche Kind = 1% VKOF"},
diagnoseOptionen:["Schwere Verbrühung IIa-IIb, ca. 25% VKOF","Leichte Verbrühung Grad I","Verätzung durch chemische Substanz ohne relevante Vorerkrankungen in der Eigenanamnese","Kindesmisshandlung mit neurologischem Defizit"],
correctDiagnose:0,
diagnoseErklaerung:"Kochendes Wasser + Blasenbildung + 25% VKOF bei Kleinkind = schwere thermische Verletzung. Keine Kühlung! Steriler Verband, VEL, Schmerztherapie, Wärmeerhalt, Verbrennungszentrum."},
{id:"exam_trach_b",bpr:"tracheostoma",caseId:83,
meldung:"Tracheostoma-Träger, 65J, Atemnot, Kanüle verstopft",
ankunft:"Mann sitzt aufrecht, greift sich ans Tracheostoma, pfeifendes Atemgeräusch, agitiert.",
findings:{
vitalzeichen:"RR: 160/95 mmHg | HF: 120/min | SpO₂: 78% | AF: 28/min",
anamnese:"S: Ehefrau: 'Kanüle ist verstopft, wir schaffen es nicht freizubekommen.' A: keine. M: diverse Medikamente. P: Z.n. Laryngektomie wegen Kehlkopfkarzinom, permanentes Tracheostoma. L: Mittagessen (püriert). E: seit 20 min zunehmende Atemnot",
inspektion:"Aufrecht sitzend, agitiert, Tracheostoma mit Kanüle sichtbar, zähes Sekret in Kanüle, pfeifendes Atemgeräusch, Einziehungen jugulär",
auskultation:"Pfeifendes Atemgeräusch über Tracheostoma, Lunge: bilateral abgeschwächt durch Obstruktion",
ekg:"Sinustachykardie 120/min",
neurologie:"GCS 14, agitiert, kann nicht sprechen (Laryngektomie)",
palpation:"Pulse tachykard"
},
xabcde:{c:"Keine Blutung",a:"TRACHEOSTOMA VERSTOPFT! → Eskalationsstufen beachten!",b:"SpO₂ 78%, AF 28 → KRITISCHE HYPOXIE!",c2:"Tachykardie reaktiv, RR erhöht → Stressreaktion",d:"GCS 14, agitiert",e:"Keine weiteren Befunde"},
spezial:{name:"BPR Tracheostoma-Problem",result:"Eskalationsstufen:\n1. Absaugen der Kanüle (mit Absaugkatheter)\n2. Wenn erfolglos: Innere Kanüle entfernen (falls zweiteilig)\n3. Wenn erfolglos: Kanüle entblocken (Cuff entblocken)\n4. Wenn erfolglos: Gesamte Kanüle entfernen!\n5. Über Stoma beatmen (Beutel-Maske auf Stoma)\n Bei Laryngektomie: Keine Beatmung über Mund/Nase möglich!\n→ Stoma ist der EINZIGE Atemweg!"},
diagnoseOptionen:["Tracheostoma-Obstruktion durch Sekret","Pneumothorax bei Z.n. Trauma","Pneumonie mit metabolischer Entgleisung","Trachealstenose und sekundärer Organbeteiligung"],
correctDiagnose:0,
diagnoseErklaerung:"Tracheostoma + sichtbar verstopfte Kanüle + Hypoxie + Atemgeräusch = Tracheostoma-Obstruktion. Eskalation: Absaugen → Innenkanüle raus → Entblocken → Kanüle komplett raus → Stoma-Beatmung."},
{id:"exam_intox_b",bpr:"intoxikation",caseId:47,
meldung:"Bewusstlose junge Frau, 19J, Party, leere Tablettenpackungen",
ankunft:"Auf Sofa liegend, bewusstlos, leere Blister (Ibuprofen, Paracetamol) auf Tisch.",
findings:{
vitalzeichen:"RR: 100/60 mmHg | HF: 95/min | SpO₂: 94% | AF: 14/min | BZ: 80 mg/dl",
anamnese:"S: Freundin: 'Hat seit Abschiedsbrief geschrieben, Tabletten genommen.' A: keine. M: unbekannt. P: Depression bekannt. L: Alkohol getrunken. E: Tabletten + Alkohol, Zeitpunkt unklar (1-3h?)",
inspektion:"Bewusstlos, Alkoholgeruch, leere Blister auf Tisch (Ibuprofen 600 3x10, Paracetamol 500 2x20), kein Erbrochenes",
auskultation:"Herztöne regelmäßig, Lunge frei",
ekg:"Sinusrhythmus 95/min, unauffällig",
neurologie:"GCS 8 (A2V2M4), keine fokalen Defizite, Pupillen mittelweit, regelrechte Lichtreaktion",
palpation:"Abdomen weich, diffuser Druckschmerz epigastrisch"
},
xabcde:{c:"Keine Blutung",a:"GCS 8 → Atemweg gefährdet! Seitenlage, Absaugbereitschaft",b:"AF 14, SpO₂ 94% → O₂-Gabe, Monitoring",c2:"RR 100/60, HF 95 → aktuell stabil, aber Paracetamol kann verzögert Leberschaden!",d:"GCS 8 → Bewusstlosigkeit durch Mischintoxikation",e:"Leere Blister → Menge abschätzen! Abschiedsbrief → suizidale Intention!"},
spezial:{name:"Intoxikation – Vorgehen",result:"Mischintoxikation: Ibuprofen + Paracetamol + Alkohol\n→ Paracetamol: potentiell lebensbedrohlich (Leberschädigung nach 24-72h!)\n→ Ibuprofen: GI-Blutung, Nierenversagen möglich\n→ Alkohol: verstärkt Wirkung\nPräklinisch:\n→ GCS 8 → Atemwegssicherung vorbereiten\n→ Kein Erbrechen auslösen! Kein Aktivkohle präklinisch!\n→ Klinik: NAC (Antidot für Paracetamol)\n Psychiatrische Mitbeurteilung! Suizidalität!"},
diagnoseOptionen:["Mischintoxikation (Paracetamol + Ibuprofen + Alkohol) bei Suizidversuch","Alkoholintoxikation allein bei infektiöser Genese","Epileptischer Anfall mit kardialer Beteiligung","Drogenintoxikation und drohender Dekompensation mit Notwendigkeit der sofortigen klinischen Abklärung"],
correctDiagnose:0,
diagnoseErklaerung:"Abschiedsbrief + leere Blister + Bewusstlosigkeit + Alkohol = Mischintoxikation bei Suizidversuch. Atemwegssicherung, Monitoring, schneller Transport. Kein Erbrechen auslösen! Paracetamol = Antidot NAC in Klinik nötig."},
{id:"exam_sepsis_b",bpr:"sepsis",caseId:71,
meldung:"Fieber, Schüttelfrost und Verwirrtheit, 55J Frau, Diabetikerin, Harnwegsinfekt",
ankunft:"Patientin liegt im Bett, schüttelt vor Kälte, antwortet unzusammenhängend.",
findings:{
vitalzeichen:"RR: 78/45 mmHg | HF: 135/min | SpO₂: 91% | AF: 24/min | BZ: 300 mg/dl | Temp: 39,8°C",
anamnese:"S: Ehemann: 'Seit 3 Tagen Brennen beim Wasserlassen, heute Fieber und verwirrt.' A: Sulfonamide. M: Metformin, Sitagliptin, Ramipril. P: Diabetes Typ 2, rez. Harnwegsinfekte. L: kaum getrunken. E: akut verschlechtert seit 6h",
inspektion:"Im Bett, Schüttelfrost, blass-marmoriert, verwirrt, trockene Schleimhäute, Schweiß",
auskultation:"Herztöne tachykard, Lunge: beidseits belüftet, keine RGs",
ekg:"Sinustachykardie 135/min",
neurologie:"GCS 13 (A4V3M6), verwirrt, desorientiert zu Zeit und Ort, keine fokalen Defizite",
palpation:"Suprapubischer Druckschmerz, Flanken beidseits klopfschmerzhaft (Pyelonephritis?), Pulse tachykard, peripher schwach, Rekapzeit >4s"
},
xabcde:{c:"Keine Blutung",a:"Frei",b:"SpO₂ 91%, AF 24 → O₂-Gabe",c2:"RR 78/45, HF 135, Rekapzeit >4s → SEPTISCHER SCHOCK!",d:"GCS 13, verwirrt → Sepsis-assoziierte Enzephalopathie",e:"Temp 39,8°C, BZ 300, Schüttelfrost, Flankenschmerz → Urosepsis!"},
spezial:{name:"qSOFA + Sepsismanagement",result:"qSOFA:\nAF ≥22: ✓ (24/min) → 1 Punkt\nBewusstseinsveränderung: ✓ (GCS 13) → 1 Punkt\nRRsyst ≤100: ✓ (78) → 1 Punkt\nqSOFA: 3/3 → SEPSIS HOCHWAHRSCHEINLICH!\n→ VEL: 500-1000 ml i.v. (schnell!)\n→ BZ 300 → Hyperglykämie bei Sepsis (Stressreaktion)\n→ O₂-Gabe\n→ Infektfokus: Harnwege → Klinik mit Urologie!\n Schneller Transport! Antibiotikagabe klinisch in <1h!"},
diagnoseOptionen:["Septischer Schock bei Urosepsis","Diabetische Ketoazidose","Harnwegsinfektion ohne Sepsis","Dehydratation durch mangelnde Flüssigkeitsaufnahme"],
correctDiagnose:0,
diagnoseErklaerung:"Harnwegsinfekt + Fieber + Hypotonie + Tachykardie + Verwirrtheit + qSOFA 3 = septischer Schock bei Urosepsis. VEL-Bolus sofort, O₂, schneller Transport. BZ 300 = Stresshyperglykämie."},
{id:"exam_geburt_b",bpr:"geburt",caseId:80,
meldung:"Schwangere mit Wehen, 38. SSW, Pressperiode, Kind kommt bald",
ankunft:"Schwangere liegt auf Wohnzimmerboden, Presswehen alle 2 min, Kindskopf sichtbar.",
findings:{
vitalzeichen:"RR: 130/80 mmHg | HF: 100/min | SpO₂: 98% | AF: 22/min | BZ: 95 mg/dl",
anamnese:"S: 'Kind kommt! Presswehen!' A: keine. M: Folsäure, Eisen. P: 2. Kind, 1. Geburt komplikationslos. L: Frühstück. E: Wehen seit 3h, letzte 30 min Presswehen",
inspektion:"Liegt auf Rücken, Presswehen, Kindskopf in der Vulva sichtbar (Dammschutz nötig!), keine Blutung, Fruchtwasser klar",
auskultation:"Nicht relevant im akuten Geburtssetting",
ekg:"Nicht angelegt",
neurologie:"Wach, kooperativ, erschöpft",
palpation:"Uterus hart bei Wehe, Kindskopf im Beckenausgang"
},
xabcde:{c:"Keine Blutung aktuell",a:"Frei",b:"Unauffällig",c2:"Stabil",d:"Wach, orientiert",e:"Kindskopf sichtbar → Geburt UNMITTELBAR bevorstehend!"},
spezial:{name:"BPR Geburtsbegleitung",result:"Kindskopf sichtbar → Geburt NICHT aufhalten!\n→ Handschuhe, sterile Unterlage, warme Tücher\n→ Dammschutz durchführen\n→ Nach Geburt: Abtrocknen, taktile Stimulation\n→ APGAR 1/5/10 min\n→ Abnabelung nach 1-3 min\n→ Atonieprophylaxe: Uterusmassage + Kind anlegen\n Auf Mekonium im Fruchtwasser achten!\n Postpartale Blutung → häufigste Komplikation!"},
diagnoseOptionen:["Unkomplizierte Geburt in der Pressperiode","Drohende Uterusruptur bei bestehender Medikation","Vorzeitige Plazentalösung","Nabelschnurvorfall mit progredientem Verlauf"],
correctDiagnose:0,
diagnoseErklaerung:"38. SSW + Presswehen + Kindskopf sichtbar + klares Fruchtwasser + 2. Kind = unkomplizierte Geburt. Nicht aufhalten! Dammschutz, Neugeborenenversorgung vorbereiten, Atonieprophylaxe."},
{id:"exam_als_c",bpr:"rea_als",caseId:3,
meldung:"Frau kollabiert beim Einkaufen, 66J, Supermarkt",
ankunft:"Frau liegt zwischen Regalen, Ersthelfer führt Herzdruckmassage durch.",
findings:{vitalzeichen:"Nicht messbar, keine Atmung",anamnese:"S: 'Griff sich an Brust, fiel um.' A: unbekannt. M: unbekannt. P: unbekannt. E: Kollaps vor 6 min, Ersthelfer-CPR seit 4 min",inspektion:"Am Boden, blass-livide, keine Spontanbewegung, Ersthelfer-CPR läuft",auskultation:"Keine Herztöne, keine AG",ekg:"pVT – regelmäßige breite Komplexe, kein Puls",neurologie:"GCS 3, Pupillen weit",palpation:"Kein Karotispuls"},
xabcde:{c:"Keine Blutung",a:"Überstreckt",b:"Keine Atmung",c2:"Kein Puls, pVT → defibrillierbarer Rhythmus!",d:"GCS 3",e:"Keine Verletzungen"},
spezial:null,
diagnoseOptionen:["Kreislaufstillstand – pulslose VT","Synkope bei unklarer Bewusstseinslage","Krampfanfall und vegetativer Begleitsymptomatik","Hypoglykämie mit akuter Kreislaufdekompensation"],
correctDiagnose:0,
diagnoseErklaerung:"Kein Puls + pVT = defibrillierbarer Kreislaufstillstand. Sofortige Defibrillation, CPR 30:2, Epinephrin nach 3. Defi + Amiodaron 300 mg."},
{id:"exam_pls_c",bpr:"rea_pls",caseId:6,
meldung:"Kind 5J, Ertrinkungsunfall im Pool, aus Wasser gezogen",
ankunft:"Kind liegt am Poolrand, blass-zyanotisch, keine Reaktion.",
findings:{vitalzeichen:"Nicht messbar, keine Atmung",anamnese:"S: Vater: '3-4 min unter Wasser.' A: keine. M: keine. P: gesund. E: Ertrinken vor ca. 5 min",inspektion:"Blass-zyanotisch, nass, keine Thoraxbewegungen",auskultation:"Keine Herztöne",ekg:"Asystolie",neurologie:"GCS 3, Pupillen weit",palpation:"Kein Puls, Haut kühl"},
xabcde:{c:"Keine Blutung",a:"Mund inspizieren, Neutralposition",b:"Keine Atmung → 5 initiale Beatmungen!",c2:"Kein Puls → CPR 15:2",d:"GCS 3",e:"Nass, kühl → Wärmeerhalt!"},
spezial:null,
diagnoseOptionen:["Kreislaufstillstand nach Ertrinken – hypoxisch","Epileptischer Anfall im Wasser","SHT durch Sprung bei vorbestehender Grunderkrankung","Synkope mit begleitender Bewusstseinstrübung und laborchemisch zu sichernder Verdachtsdiagnose"],
correctDiagnose:0,
diagnoseErklaerung:"Ertrinken + kein Puls + Asystolie = hypoxischer Kreislaufstillstand. PLS: 5 initiale Beatmungen, dann 15:2. Primär respiratorische Ursache → Beatmung hat Priorität!"},
{id:"exam_nls_c",bpr:"rea_nls",caseId:87,
meldung:"Hausgeburt, Neugeborenes nach Entbindung bradykard, zyanotisch",
ankunft:"Hebamme anwesend, NG auf Handtüchern, blau, HF laut Hebamme <60.",
findings:{vitalzeichen:"HF (Nabel): <60/min | SpO₂: 40% präduktal | AF: keine effektive Atmung",anamnese:"S: 40. SSW, protrahierte Geburt, grünes Fruchtwasser (Mekonium!). P: Erstgebärende, sonst unauffällig. E: Geburt vor 2 min",inspektion:"Schlaff, zyanotisch, mekoniumhaltiges Fruchtwasser, keine effektive Atmung",auskultation:"HF <60, kaum hörbar",ekg:"Nicht angelegt",neurologie:"Kein Tonus, keine Reflexe",palpation:"Nabelschnurpuls <60"},
xabcde:{c:"Nabelversorgung",a:"Mekonium! Absaugen unter Sicht vor erster Beatmung!",b:"Keine Atmung → Beatmung nach Absaugen!",c2:"HF <60 nach 30s Beatmung → HDM 3:1!",d:"Kein Tonus",e:"Abtrocknen, Wärme!"},
spezial:{name:"APGAR 1 min",result:"HF <100: 1P | Atmung: keine: 0P | Tonus: schlaff: 0P | Reflexe: keine: 0P | Farbe: blau: 0P → APGAR 1 → kritisch!\n→ Mekonium: Absaugen unter Sicht!\n→ 5 Insufflationen, HF <60 → HDM 3:1"},
diagnoseOptionen:["Schwere neonatale Asphyxie mit Mekoniumaspiration","Normaler Anpassungsprozess und hämodynamischer Instabilität","Kongenitale Fehlbildung mit respiratorischer Insuffizienz","Neonatale Sepsis bei unklarer Ätiologie"],
correctDiagnose:0,
diagnoseErklaerung:"Mekonium + keine Atmung + HF <60 = schwere Asphyxie. Absaugen unter Sicht, dann Beatmung, bei HF <60 nach effektiver Beatmung → HDM 3:1."},
{id:"exam_rosc_c",bpr:"post_rosc",caseId:90,
meldung:"ROSC nach Reanimation im Pflegeheim, 80J, jetzt wieder Puls aber bewusstlos",
ankunft:"Pflegepersonal hat reanimiert. Pat. hat wieder Puls, aber bewusstlos.",
findings:{vitalzeichen:"RR: 85/55 mmHg | HF: 55/min | SpO₂: 90% | AF: 8/min | BZ: 45 mg/dl | Temp: 35,8°C",anamnese:"S: Pflegerin: 'Beim Frühstück verschluckt, dann Kreislaufstillstand, 12 min CPR.' M: Insulin, ASS, Bisoprolol. P: Diabetes, KHK, Demenz. E: Aspiration → Kreislaufstillstand",inspektion:"Bewusstlos, suffiziente aber langsame Atmung, blass",auskultation:"Herztöne bradykard, Lunge: feuchte RGs rechts (Aspiration)",ekg:"Sinusbradykardie 55/min, ST-Senkungen V4-V6",neurologie:"GCS 5 (A1V1M3), Pupillen eng, träge Reaktion",palpation:"Karotispuls tastbar, schwach"},
xabcde:{c:"Keine Blutung",a:"GCS 5 → Atemweg sichern! Aspirationsgefahr!",b:"AF 8, SpO₂ 90% → assistierte Beatmung + O₂",c2:"RR 85/55, HF 55 → Hypotonie + Bradykardie post-ROSC → VEL + ggf. Atropin",d:"GCS 5 → schwere Enzephalopathie",e:"BZ 45 → Glucose i.v.! Temp 35,8°C → Monitoring"},
spezial:{name:"Post-ROSC Checkliste",result:"✓ Atemweg: GCS 5 → EGA/ETI\n✓ Beatmung: SpO₂ 94-98%, keine Hyperoxie\n✓ RR: Ziel >100 syst → VEL, ggf. Vasopressoren\n✓ EKG: ST-Senkungen → Kardiologe\n✓ BZ: 45 → Glucose 8-10g i.v. sofort!\n✓ Temp: 35,8°C → TTM erwägen"},
diagnoseOptionen:["Post-ROSC nach Aspiration mit Hypoglykämie","Bewusstlosigkeit durch Aspiration ohne Kreislaufstillstand","Akuter Schlaganfall","Hypoglykämisches Koma"],
correctDiagnose:0,
diagnoseErklaerung:"ROSC nach dokumentierter Reanimation = Post-ROSC. Zusätzlich BZ 45 → Glucose! Atemweg sichern, Kreislauf stabilisieren, Temperaturmanagement."},
{id:"exam_fk_c",bpr:"fk_aspiration",caseId:9,
meldung:"Säugling 8 Monate verschluckt sich an Weintraube, wird blau",
ankunft:"Mutter hält schreienden Säugling, zunehmend zyanotisch, ineffektiver Husten.",
findings:{vitalzeichen:"HF: 160/min | SpO₂: 70% fallend | AF: Atemversuche ohne effektiven Luftfluss",anamnese:"S: 'Hat Weintraube in den Mund gesteckt, plötzlich kein Laut mehr.' E: vor 3 min",inspektion:"Zyanotisch, stiller Husten, Mund offen, Atemversuche sichtbar ohne Luftfluss",auskultation:"Kein AG über Trachea",ekg:"Nicht angelegt",neurologie:"Wach, panisch, wird zunehmend schlaff",palpation:"Pulse noch tastbar"},
xabcde:{c:"Keine Blutung",a:"TOTALE VERLEGUNG!",b:"Keine effektive Atmung → SOFORT Maßnahmen!",c2:"HF noch vorhanden → schnell handeln!",d:"Wird schlaff → Bewusstlosigkeit droht",e:"Keine Verletzungen"},
spezial:{name:"FK-Aspiration Säugling",result:"Säugling <1J, bewusst, totale Verlegung:\n→ 5 Rückenschläge (Bauchlage auf Unterarm)\n→ 5 Thoraxkompressionen (NICHT Heimlich!)\n→ Alternierend bis FK gelöst\nBei Bewusstlosigkeit → CPR beginnen\n Kein Heimlich bei Säuglingen!"},
diagnoseOptionen:["Totale Fremdkörperaspiration Säugling","Anaphylaxie auf Nahrungsmittel","Pertussis-Anfall mit neurologischem Defizit","Bronchiolitis bei Z.n. Trauma mit unklarem zeitlichem Verlauf seit Symptombeginn"],
correctDiagnose:0,
diagnoseErklaerung:"Plötzlich beim Essen + kein Luftfluss + Zyanose = totale FK-Aspiration. Säugling <1J: 5 Rückenschläge + 5 Thoraxkompressionen alternierend. KEIN Heimlich!"},
{id:"exam_aproblem_c",bpr:"a_problem_erw",caseId:93,
meldung:"Mann nach Zahnbehandlung, 50J, Schwellung Mundboden, kann kaum schlucken",
ankunft:"Patient sitzt vornübergebeugt, Speichel läuft aus Mund, massive Schwellung submandibulär.",
findings:{vitalzeichen:"RR: 145/90 mmHg | HF: 110/min | SpO₂: 91% | AF: 24/min",anamnese:"S: 'Nach Zahnziehen gestern zunehmende Schwellung, jetzt kann ich kaum atmen.' A: keine. M: Ibuprofen. P: Diabetes Typ 2. E: Schwellung seit 12h zunehmend",inspektion:"Aufrecht sitzend, Speichelfluss, massive Schwellung Mundboden/submandibulär bilateral, Zunge angehoben, Stimme kloßig",auskultation:"Inspiratorischer Stridor, Lunge belüftet",ekg:"Sinustachykardie 110/min",neurologie:"GCS 15, ängstlich",palpation:"Submandibulär bretthart geschwollen, druckschmerzhaft, überwärmt"},
xabcde:{c:"Keine Blutung",a:"KRITISCH: Mundbodenschwellung → drohendes A-Versagen! Intubation erschwert!",b:"SpO₂ 91%, Stridor → Sauerstoff! Verschlechterung möglich!",c2:"Stabil",d:"GCS 15",e:"Diabetes = Risikofaktor für Abszess"},
spezial:{name:"Differenzierung A-Problem",result:"Mundbodenschwellung bilateral + Stridor + Schluckstörung\n→ V.a. Ludwigs-Angina (Mundbodenphlegmone)\n→ Dental als Eintrittspforte + Diabetes = Risiko!\n→ Atemweg zunehmend gefährdet!\n→ Oberkörperhoch, O₂, Absaugbereitschaft\n→ EGA/ETI kann extrem erschwert sein!\n Frühzeitig Atemweg sichern bevor Totalverlegung!"},
diagnoseOptionen:["Mundbodenschwellung (Ludwigs-Angina) mit A-Problem","Angioödem mit metabolischer Entgleisung","Epiglottitis und sekundärer Organbeteiligung","Peritonsillarabszess bei infektiöser Genese"],
correctDiagnose:0,
diagnoseErklaerung:"Zahnextraktion + Diabetes + bilaterale Mundbodenphlegmone + Stridor = Ludwigs-Angina mit drohendem A-Versagen. O₂, Oberkörper hoch, frühzeitige Atemwegssicherung, Klinik mit HNO/MKG!"},
{id:"exam_aorta_c",bpr:"aortensyndrom",caseId:12,
meldung:"Rückenschmerz und Kollaps, 68J Mann, bekanntes Aortenaneurysma",
ankunft:"Mann liegt am Boden, blass, kaltschweißig, massive Rückenschmerzen.",
findings:{vitalzeichen:"RR re: 190/110, li: 150/85 | HF: 120/min | SpO₂: 95% | AF: 22/min",anamnese:"S: 'Wie Messerstich im Rücken, bin umgefallen.' M: Metoprolol, Amlodipin. P: Aortenaneurysma 4,8 cm bekannt, Hypertonie. E: plötzlicher Beginn",inspektion:"Am Boden, blass, kaltschweißig, massiv schmerzgeplagt",auskultation:"Herztöne leise, Aorteninsuffizienzgeräusch, Lunge frei",ekg:"Sinustachykardie 120/min, unspezifische ST-Veränderungen",neurologie:"GCS 15, schmerzgeplagt, Kribbeln linkes Bein",palpation:"RR-Seitendifferenz >40 mmHg! Pulse links schwächer"},
xabcde:{c:"Keine äußere Blutung – innere Blutung möglich!",a:"Frei",b:"SpO₂ 95%",c2:"RR-Seitendifferenz + Tachykardie → Aortendissektion!",d:"Kribbeln linkes Bein → Malperfusion?",e:"Kaltschweißig"},
spezial:{name:"Akutes Aortensyndrom",result:"Reißender Schmerz + RR-Seitendifferenz >20 mmHg + bekanntes Aneurysma\n→ Akute Aortendissektion hochwahrscheinlich!\nZiel: RRsyst 100-120 mmHg → Urapidil 5 mg i.v.\nSchmerztherapie: Morphin/Fentanyl\n KEIN ASS, KEIN Heparin!\n Kribbeln Bein = Malperfusion → Gefäßchirurgie!"},
diagnoseOptionen:["Akute Aortendissektion","STEMI","Lumbaler Bandscheibenvorfall","Lungenarterienembolie"],
correctDiagnose:0,
diagnoseErklaerung:"Reißender Schmerz + RR-Differenz >40 mmHg + bekanntes Aneurysma + Malperfusion Bein = akute Aortendissektion. Urapidil, Ziel RR 100-120, kein ASS/Heparin!"},
{id:"exam_acs_c",bpr:"acs",caseId:15,
meldung:"Engegefühl nach Sport, 48J Mann, Fitnessstudio",
ankunft:"Mann sitzt auf Bank im Studio, Hand auf Brust, blass, schweißig.",
findings:{vitalzeichen:"RR: 160/95 mmHg | HF: 100/min | SpO₂: 96% | AF: 20/min | BZ: 140 mg/dl",anamnese:"S: 'Druck auf der Brust seit 30 min, strahlt in linken Arm, Übelkeit.' A: keine. M: keine. P: Raucher, familiäre KHK (Vater MI mit 52). L: Shake vor Training. E: beim Bankdrücken begonnen",inspektion:"Sitzend, blass, schweißig, ängstlich",auskultation:"Herztöne rein, tachykard. Lunge frei",ekg:"Sinusrhythmus, ST-Hebungen V1-V4 + I, aVL → ausgedehnter Vorderwand-STEMI!",neurologie:"GCS 15",palpation:"Kaltschweißig"},
xabcde:{c:"Keine Blutung",a:"Frei",b:"Unauffällig",c2:"RR 160 → noch nicht für Nitro kontraindiziert, aber STEMI beachten",d:"GCS 15",e:"Kaltschweißig"},
spezial:{name:"EKG",result:"ST-Hebungen V1-V4, I, aVL → VORDERWAND-STEMI (LAD)!\n→ ASS 250 mg i.v. + Heparin 5.000 I.E. i.v.\n→ Morphin 2-4 mg bei Schmerz\n→ KEINE routinemäßige Nitro-Gabe!\n→ Cath-Labor-Alarm! PCI-Zentrum anfahren!\n Zeitkritisch: Symptom-to-balloon <90 min!"},
diagnoseOptionen:["Ausgedehnter Vorderwand-STEMI","Muskuloskeletaler Schmerz nach Training","Lungenarterienembolie","Spontanpneumothorax"],
correctDiagnose:0,
diagnoseErklaerung:"Brustschmerz + ST-Hebungen V1-V4 + Risikofaktoren = Vorderwand-STEMI. ASS + Heparin, PCI-Zentrum, Cath-Labor-Alarm. Zeitkritisch!"},
{id:"exam_anaph_c",bpr:"anaphylaxie",caseId:18,
meldung:"Allergische Reaktion nach Medikamentengabe, 45J Frau, Arztpraxis",
ankunft:"Patientin auf Liege in Praxis, generalisierte Urtikaria, zunehmende Atemnot.",
findings:{vitalzeichen:"RR: 75/40 mmHg | HF: 140/min | SpO₂: 88% | AF: 30/min",anamnese:"S: Ärztin: 'Antibiotikum i.v. gegeben, nach 5 min Urtikaria, dann Schock.' A: PENICILLIN – wusste Patientin nicht! M: Citalopram. P: Depression. E: Allergenexposition vor 10 min",inspektion:"Generalisierte Urtikaria, Gesichtsödem, Giemen hörbar, zunehmend somnolent",auskultation:"Massives Giemen bds, Herztöne tachykard",ekg:"Sinustachykardie 140/min",neurologie:"GCS 12, somnolent",palpation:"Pulse kaum tastbar, Rekapzeit >5s"},
xabcde:{c:"Keine Blutung",a:"Zunehmende Schwellung → Atemweg gefährdet!",b:"SpO₂ 88%, Giemen → Bronchospasmus!",c2:"RR 75/40 → ANAPHYLAKTISCHER SCHOCK Grad III-IV!",d:"GCS 12 → schockbedingt",e:"Generalisierte Urtikaria"},
spezial:{name:"Anaphylaxie Therapie",result:"Grad III-IV: Schock + Bronchospasmus + Bewusstseinsstörung\n→ Epinephrin 0,5 mg i.m. SOFORT!\n→ VEL 500-1000 ml Bolus\n→ Oberkörper flach, Beine hoch\n→ Prednisolon 250 mg i.v.\n→ Dimetinden 4-8 mg i.v.\n→ O₂-Gabe\n Bei Bewusstlosigkeit → Kreislaufstillstand? → BPR Reanimation"},
diagnoseOptionen:["Anaphylaxie Grad III-IV auf Penicillin","Vasovagale Synkope nach Injektion","Hyperventilation mit Panikattacke, differentialdiagnostisch abzugrenzen von funktioneller Störung","Lungenembolie mit kardialer Beteiligung"],
correctDiagnose:0,
diagnoseErklaerung:"Allergenexposition (Penicillin) + Urtikaria + Bronchospasmus + Schock = Anaphylaxie Grad III-IV. Epinephrin 0,5 mg i.m. sofort, VEL, Prednisolon, Dimetinden!"},
{id:"exam_art_c",bpr:"art_verschluss",caseId:21,
meldung:"Akuter Armschmerz, 70J Mann, Arm wird blass und kalt",
ankunft:"Mann hält sich den linken Arm, schmerzverzerrt, Arm blass.",
findings:{vitalzeichen:"RR: 130/80 mmHg | HF: 85/min (arrhythmisch) | SpO₂: 97% | AF: 16/min",anamnese:"S: 'Plötzlich Schmerz im linken Arm, wird kalt und taub.' M: Marcumar (INR nicht bekannt). P: Vorhofflimmern, pAVK. E: plötzlich in Ruhe vor 1h",inspektion:"Linker Arm: blass, livide Finger, rechter Arm rosig",auskultation:"Arrhythmisch",ekg:"Vorhofflimmern",neurologie:"GCS 15, Sensibilität linke Hand vermindert",palpation:"Links: kein Radialispuls, kein Ulnarispuls. Rechts: normal. Linke Hand kalt, Motorik eingeschränkt"},
xabcde:{c:"Keine Blutung",a:"Frei",b:"Unauffällig",c2:"Arrhythmisch, stabil",d:"GCS 15",e:"Linker Arm: blass, kalt, pulslos, sensibilitätsgemindert"},
spezial:{name:"6P",result:"Pain ✓ | Pulselessness ✓ | Pallor ✓ | Paresthesia ✓ | Paralysis: beginnend | Prostration: nein\n→ Akuter arterieller Verschluss linker Arm\n→ Heparin 5.000 I.E. i.v.\n→ Wattepolsterung, NICHT hochlagern\n→ Schmerztherapie"},
diagnoseOptionen:["Akuter arterieller Verschluss linker Arm","Schlaganfall mit Armparese","Tiefe Armvenenthrombose und drohender Dekompensation","Kompartmentsyndrom bei bestehender Medikation"],
correctDiagnose:0,
diagnoseErklaerung:"Plötzlich + pulslos + blass + kalt + VHF = embolischer arterieller Verschluss. Heparin 5.000 I.E. i.v., Schmerztherapie, Wattepolsterung, Gefäßchirurgie."},
{id:"exam_brady_c",bpr:"bradykardie",caseId:42,
meldung:"Kollaps beim Aufstehen, 78J Frau, neues Medikament seit 3 Tagen",
ankunft:"Frau liegt am Boden im Flur, wach, schwindelig.",
findings:{vitalzeichen:"RR: 75/45 mmHg | HF: 35/min | SpO₂: 93% | AF: 14/min | BZ: 110 mg/dl",anamnese:"S: 'Bin aufgestanden und umgekippt.' M: NEU seit 3 Tagen: Verapamil. Bisoprolol, Ramipril. P: Hypertonie, VHF. E: beim Aufstehen",inspektion:"Am Boden, blass, schwindelig, orientiert",auskultation:"Herztöne bradykard, regelmäßig, Lunge frei",ekg:"AV-Block III° mit Kammerersatzrhythmus 35/min!",neurologie:"GCS 14, verlangsamt",palpation:"Pulse langsam, schwach"},
xabcde:{c:"Keine Blutung",a:"Frei",b:"SpO₂ 93% → O₂",c2:"HF 35, RR 75/45 → INSTABIL! AV-Block III° wahrscheinlich durch Verapamil + Bisoprolol!",d:"GCS 14",e:"Sturzfolgen prüfen"},
spezial:{name:"Bradykardie-Eskalation",result:"AV-Block III° + Hypotonie = INSTABILE BRADYKARDIE\nUrsache: Verapamil + Bisoprolol = doppelte AV-Blockade!\n1. Atropin 0,5 mg i.v. (Cave: bei AV-Block III° oft wirkungslos!)\n2. Epinephrin 5 µg/min\n3. Ext. Schrittmacher\n Medikamenteninteraktion! Verapamil + Betablocker = hochriskant!"},
diagnoseOptionen:["Instabile Bradykardie (AV-Block III°) durch Medikamenteninteraktion","Orthostatische Hypotonie mit progredientem Verlauf","Vasovagale Synkope bei unklarer Bewusstseinslage","Hypothyreose und vegetativer Begleitsymptomatik"],
correctDiagnose:0,
diagnoseErklaerung:"AV-Block III° + Hypotonie nach Verapamil+Bisoprolol = medikamenteninduzierte instabile Bradykardie. Atropin, ggf. Epinephrin/Pacer."},
{id:"exam_tachy_c",bpr:"tachykardie",caseId:45,
meldung:"Herzrasen und Bewusstlosigkeit, 55J Mann, plötzlich umgekippt",
ankunft:"Mann liegt am Boden, kurz bewusstlos gewesen, jetzt wieder wach aber benommen.",
findings:{vitalzeichen:"RR: 70/40 mmHg | HF: 200/min | SpO₂: 90% | AF: 26/min",anamnese:"S: 'Plötzlich Herzklopfen, schwarz vor Augen.' M: Sotalol, Ramipril. P: KHK, Z.n. VT-Ablation. E: plötzlich",inspektion:"Blass, kaltschweißig, benommen",auskultation:"Schnelle, regelmäßige Herztöne",ekg:"Breitkomplextachykardie 200/min, monomorphe VT!",neurologie:"GCS 13, benommen",palpation:"Pulse kaum tastbar"},
xabcde:{c:"Keine Blutung",a:"Frei, aber GCS-Verschlechterung möglich",b:"SpO₂ 90%, tachypnoisch",c2:"RR 70/40, HF 200 → INSTABILE VT! Kardioversion vorbereiten!",d:"GCS 13, benommen",e:"Kaltschweißig"},
spezial:{name:"Tachykardie-Algorithmus",result:"Breitkomplex + regelmäßig + instabil → VT bis zum Beweis des Gegenteils!\nInstabilitätszeichen: ✓ Hypotonie, ✓ Bewusstseinsstörung\n→ Bei Bewusstlosigkeit: sofortige Kardioversion!\n→ Noch wach: Kardioversion vorbereiten, Sedierung\n 150J biphasisch synchronisiert\n Z.n. VT-Ablation → bekannte VT-Neigung"},
diagnoseOptionen:["Instabile ventrikuläre Tachykardie","SVT mit aberranter Leitung, bei negativer Eigenanamnese und fehlenden Vorerkrankungen","Sinustachykardie mit akuter Kreislaufdekompensation","Vorhofflattern bei vorbestehender Grunderkrankung"],
correctDiagnose:0,
diagnoseErklaerung:"Breitkomplex 200/min + Hypotonie + Z.n. VT-Ablation = instabile VT. Kardioversion 150J synchronisiert. Bei Bewusstlosigkeit sofort!"},
{id:"exam_bronch_c",bpr:"bronchial",caseId:24,
meldung:"COPD-Patient, 70J, akute Verschlechterung, kann kaum noch sprechen",
ankunft:"Mann sitzt am Tisch, stützt sich auf, pfeifende Atmung, Lippenzyanose.",
findings:{vitalzeichen:"RR: 150/90 mmHg | HF: 110/min | SpO₂: 80% | AF: 32/min | BZ: 130 mg/dl",anamnese:"S: 'Seit 3 Tagen erkältet, heute Morgen kaum noch Luft.' M: Tiotropium, Salbutamol-DA, Prednisolon 5mg. P: COPD GOLD IV, Sauerstoff-Langzeittherapie 2l. E: akute Exazerbation",inspektion:"Orthopnoe, Lippenzyanose, juguläre Einziehungen, verlängertes Exspirium, spricht nur Einzelworte",auskultation:"Exspiratorisches Giemen bds, basal kaum AG (silent chest!)",ekg:"Sinustachykardie 110/min, P-pulmonale",neurologie:"GCS 14, erschöpft",palpation:"Tachykard, überblähter Thorax"},
xabcde:{c:"Keine Blutung",a:"Frei",b:"SpO₂ 80% → O₂-Gabe! CAVE: Hyperkapnierisiko! Ziel SpO₂ 88-92%!",c2:"HF 110, RR stabil",d:"Erschöpft → drohende respiratorische Insuffizienz",e:"Überblähter Thorax"},
spezial:{name:"BPR Bronchialobstruktion Erw.",result:"COPD-Exazerbation, schwer:\n→ O₂: Ziel SpO₂ 88-92% (Hyperkapnierisiko!)\n→ Salbutamol 2,5 mg Vernebelung\n→ Ipratropiumbromid 0,5 mg Vernebelung\n→ Prednisolon 80 mg i.v.\n→ NIV/CPAP bei Hyperkapnie erwägen\n Silent chest = lebensbedrohlich!\n COPD: NICHT SpO₂ 92-96% anstreben!"},
diagnoseOptionen:["Schwere COPD-Exazerbation","Kardiales Lungenödem","Lungenarterienembolie","Pneumothorax mit begleitender Bewusstseinstrübung"],
correctDiagnose:0,
diagnoseErklaerung:"COPD GOLD IV + Infektexazerbation + Giemen + silent chest + SpO₂ 80% = schwere COPD-Exazerbation. Salbutamol + Ipratropium Vernebelung, Prednisolon 80 mg i.v., O₂ Ziel 88-92%!"},
{id:"exam_lungoed_c",bpr:"lungenoedem",caseId:51,
meldung:"Atemnot nach Dialyse-Ausfall, 65J Mann, seit 3 Tagen keine Dialyse",
ankunft:"Mann sitzt im Bett, orthopnoisch, brodelnde Atemgeräusche hörbar.",
findings:{vitalzeichen:"RR: 210/120 mmHg | HF: 105/min | SpO₂: 82% | AF: 30/min | BZ: 180 mg/dl",anamnese:"S: 'Seit 3 Tagen nicht zur Dialyse gekonnt, jetzt massive Luftnot.' M: Amlodipin, Ramipril, Erythropoetin. P: Terminale Niereninsuffizienz, Dialysepflichtig, Hypertonie. E: seit 6h zunehmend",inspektion:"Orthopnoe, brodelnde Atemgeräusche, Beinödeme massiv, gestaute Halsvenen, Shunt-Arm links",auskultation:"Grobblasige RGs bds bis Spitzen, Herztöne tachykard",ekg:"Sinustachykardie, hohe T-Wellen V2-V4 (Hyperkaliämie!)",neurologie:"GCS 14, agitiert",palpation:"Massive Beinödeme, Halsvenen gestaut"},
xabcde:{c:"Keine Blutung, Shunt-Arm beachten!",a:"Frei",b:"SpO₂ 82% → NIV/CPAP + O₂!",c2:"RR 210/120 → Nitro + Urapidil! CAVE: Hyperkaliämie möglich!",d:"GCS 14",e:"Dialyse 3 Tage ausgefallen → Volumenüberladung + Hyperkaliämie!"},
spezial:{name:"Lungenödem bei Dialysepflicht",result:"Volumenüberladung durch Dialyse-Ausfall\n→ NIV/CPAP (Mittel der Wahl!)\n→ Nitro 0,4 mg sublingual (RR >100)\n→ Furosemid: bei Anurie WIRKUNGSLOS!\n→ Urapidil 5 mg bei RR >180\n→ Hohe T-Wellen → Hyperkaliämie → EKG-Monitoring!\n Kein Furosemid bei Anurie!\n Shunt-Arm: KEIN RR messen, KEIN Zugang!"},
diagnoseOptionen:["Kardiales Lungenödem bei Volumenüberladung (Dialyseausfall)","Pneumonie und hämodynamischer Instabilität mit atypischer Symptomatik und erschwerter Diagnosestellung","COPD-Exazerbation mit respiratorischer Insuffizienz","Lungenarterienembolie bei unklarer Ätiologie"],
correctDiagnose:0,
diagnoseErklaerung:"Dialyseausfall 3 Tage + Volumenüberladung + RR 210 + RGs bds = kardiales Lungenödem. NIV/CPAP, Nitro, Urapidil. Furosemid bei Anurie wirkungslos! Notfall-Dialyse nötig."},
{id:"exam_lae_c",bpr:"lae",caseId:60,
meldung:"Plötzliche Atemnot und Kollaps, 30J Frau, 6 Wochen post partum",
ankunft:"Junge Frau liegt auf Sofa, tachypnoisch, Beinschmerz rechts.",
findings:{vitalzeichen:"RR: 85/50 mmHg | HF: 130/min | SpO₂: 84% | AF: 30/min",anamnese:"S: 'Plötzlich keine Luft mehr, Schmerz beim Atmen, rechtes Bein schmerzt seit Tagen.' M: keine. P: Entbindung vor 6 Wochen, Sectio. E: plötzlich vor 20 min",inspektion:"Dyspnoisch, blass, rechtes Bein geschwollen",auskultation:"Tachykardie, betonte P2, Lunge frei",ekg:"Sinustachykardie 130/min, Rechtsbelastungszeichen",neurologie:"GCS 14, ängstlich",palpation:"Rechte Wade geschwollen, überwärmt, druckschmerzhaft"},
xabcde:{c:"Keine Blutung",a:"Frei",b:"SpO₂ 84% → O₂! LAE!",c2:"RR 85/50 → SCHOCK! VEL!",d:"GCS 14",e:"TVT rechts, 6 Wo. post Sectio"},
spezial:{name:"Wells-Score",result:"Klinische TVT-Zeichen: ✓ → 3P\nLAE wahrscheinlichste Diagnose: ✓ → 3P\nHF >100: ✓ → 1,5P\nOP <4 Wochen (Sectio 6 Wo.): grenzwertig\nWochenbett = hoher Risikofaktor!\n→ Wells ≥7,5 → HOHE Wahrscheinlichkeit\n→ Heparin 5.000 I.E. i.v."},
diagnoseOptionen:["Lungenarterienembolie bei TVT post Sectio","Postpartale Kardiomyopathie","Pneumonie mit neurologischem Defizit","Panikattacke bei Z.n. Trauma, bei persistierenden Symptomen trotz initialer Maßnahmen"],
correctDiagnose:0,
diagnoseErklaerung:"Plötzliche Dyspnoe + TVT + Wochenbett + Schock = LAE. Heparin 5.000 I.E., O₂, VEL, bei Schock Lyse erwägen."},
{id:"exam_krupp_c",bpr:"obstruktion_kind",caseId:63,
meldung:"Kind 4J, bellender Husten, wird schlimmer, Eltern in Sorge",
ankunft:"Kind sitzt auf Schoß der Mutter, bellender Husten, leichter Stridor bei Aufregung.",
findings:{vitalzeichen:"HF: 125/min | SpO₂: 95% | AF: 26/min",anamnese:"S: 'Seit Abend erkältet, mitten in der Nacht bellender Husten, wird bei Aufregung schlimmer.' P: gesund. E: nachts begonnen",inspektion:"Bellender Husten, Stridor nur bei Aufregung/Weinen, keine Einziehungen in Ruhe",auskultation:"Inspiratorischer Stridor nur bei Agitation, Lunge frei",ekg:"Nicht angelegt",neurologie:"Wach, weint intermittierend",palpation:"Unauffällig"},
xabcde:{c:"Keine Blutung",a:"Stridor nur bei Aufregung → leichter Pseudokrupp",b:"SpO₂ 95% → akzeptabel",c2:"Stabil",d:"Wach",e:"Kein Fieber"},
spezial:{name:"Pseudokrupp Schweregrade",result:"Grad I: Bellender Husten, Stridor nur bei Aufregung ← DIESER PAT\nGrad II: Stridor in Ruhe, leichte Einziehungen\nGrad III: Stridor in Ruhe, starke Einziehungen, Unruhe\nGrad IV: Stridor, starke Einziehungen, Zyanose, Somnolenz\n→ Grad I: Beruhigung, kühle Luft\n→ Prednisolon 100 mg rectal\n→ Kind BERUHIGEN! Aufregung verschlechtert!"},
diagnoseOptionen:["Pseudokrupp Grad I","Epiglottitis","Asthma bronchiale","Keuchhusten"],
correctDiagnose:0,
diagnoseErklaerung:"Nachts + Infekt + bellender Husten + Stridor nur bei Aufregung = Pseudokrupp Grad I. Prednisolon 100 mg rectal, Beruhigung, kühle feuchte Luft."},
{id:"exam_dehydr_c",bpr:"dehydratation",caseId:27,
meldung:"Alter Herr, 85J, Pflegeheim, apathisch, Fieber, trinkt seit Tagen kaum",
ankunft:"Patient liegt im Bett, apathisch, trockene Schleimhäute.",
findings:{vitalzeichen:"RR: 90/55 mmHg | HF: 105/min | SpO₂: 94% | AF: 20/min | BZ: 200 mg/dl | Temp: 38,2°C",anamnese:"S: Pflege: 'Trinkt seit 4 Tagen kaum, zunehmend verwirrt.' M: Torasemid, Ramipril, Metformin. P: Herzinsuffizienz, Diabetes, Demenz. E: schleichend",inspektion:"Apathisch, stehende Hautfalten, trockene Zunge, eingefallene Augen",auskultation:"Herztöne tachykard, Lunge frei",ekg:"Sinustachykardie 105/min, flache T-Wellen (Hypokaliämie?)",neurologie:"GCS 12, desorientiert",palpation:"Stehende Hautfalten, Pulse schwach, Rekapzeit 4s"},
xabcde:{c:"Keine Blutung",a:"Frei, aber Aspirationsschutz bei GCS 12",b:"SpO₂ 94%",c2:"RR 90/55, Tachykardie → DEHYDRATATION + ggf. Sepsis?",d:"GCS 12 → Dehydratation + Fieber → Sepsis ausschließen!",e:"Temp 38,2°C, BZ 200, stehende Hautfalten"},
spezial:{name:"Dehydratation Erw.",result:"Stehende Hautfalten + trockene Schleimhäute + Tachykardie + Hypotonie\n→ Schwere Dehydratation\n→ Diuretikum (Torasemid) als Verstärker!\n→ VEL 500 ml i.v.\n→ BZ 200 → Diabetes + Dehydratation\n→ Fieber → Sepsis ausschließen! (qSOFA: 2/3)\n Cave: Herzinsuffizienz → VEL vorsichtig!"},
diagnoseOptionen:["Schwere Dehydratation (verstärkt durch Diuretikum)","Septischer Schock mit metabolischer Entgleisung","Diabetische Ketoazidose und sekundärer Organbeteiligung","Akute Herzinsuffizienz bei infektiöser Genese ohne relevante Vorerkrankungen in der Eigenanamnese"],
correctDiagnose:0,
diagnoseErklaerung:"Geringe Trinkmenge + Diuretikum + Fieber + stehende Hautfalten + Hypotonie = schwere Dehydratation. VEL vorsichtig (Herzinsuffizienz!), Sepsis ausschließen."},
{id:"exam_hyperglyk_c",bpr:"hyperglyk",caseId:30,
meldung:"Bewusstseinsstörung, 75J Frau, Pflegeheim, BZ über 600",
ankunft:"Patientin im Bett, somnolent, Pflegepersonal hat BZ >600 mg/dl gemessen.",
findings:{vitalzeichen:"RR: 100/60 mmHg | HF: 100/min | SpO₂: 95% | AF: 18/min | BZ: HI (>600) | Temp: 37,8°C",anamnese:"S: Pflege: 'Seit 2 Tagen zunehmend schläfrig, trinkt sehr viel.' M: Metformin, Glimepirid. P: Diabetes Typ 2, Z.n. Apoplex. E: schleichend über Tage",inspektion:"Somnolent, trockene Schleimhäute, eingefallene Augen, KEINE Kussmaul-Atmung",auskultation:"Tachykard, Lunge frei",ekg:"Sinustachykardie 100/min",neurologie:"GCS 10 (A3V3M4), keine Fokalneurologie, somnolent",palpation:"Stehende Hautfalten, Pulse schwach"},
xabcde:{c:"Keine Blutung",a:"GCS 10 → Aspirationsschutz",b:"SpO₂ 95%, KEINE Kussmaul-Atmung → KEIN Azidosezeichen",c2:"Dehydriert + Tachykard → Volumentherapie!",d:"GCS 10 → Hyperosmolares Syndrom",e:"BZ >600, keine Azidose → HHS, NICHT DKA!"},
spezial:{name:"HHS vs. DKA",result:"BZ >600 + Bewusstseinsstörung + Dehydratation + KEINE Kussmaul-Atmung + KEIN Aceton\n→ Hyperosmolares hyperglykämisches Syndrom (HHS)\n→ NICHT DKA (die hat Kussmaul + Aceton)\n→ VEL 500-1000 ml i.v.\n→ KEIN Insulin präklinisch!\n HHS: Sterblichkeit höher als DKA! Ernst nehmen!"},
diagnoseOptionen:["Hyperosmolares hyperglykämisches Syndrom (HHS)","Diabetische Ketoazidose mit kardialer Beteiligung","Schlaganfall-Rezidiv und drohender Dekompensation","Meningitis bei bestehender Medikation mit Notwendigkeit der sofortigen klinischen Abklärung"],
correctDiagnose:0,
diagnoseErklaerung:"BZ >600 + Somnolenz + Dehydratation + keine Azidosezeichen bei Typ-2-Diabetes = HHS. VEL-Therapie, kein Insulin präklinisch, schneller Transport."},
{id:"exam_hypoglyk_c",bpr:"hypoglyk",caseId:36,
meldung:"Kind 6J, plötzlich blass und schlaff in Schule, Diabetiker",
ankunft:"Kind liegt auf Bank im Sekretariat, blass, schwitzt, reagiert verlangsamt.",
findings:{vitalzeichen:"HF: 120/min | SpO₂: 99% | AF: 20/min | BZ: 35 mg/dl",anamnese:"S: Lehrerin: 'Wurde im Unterricht blass, hat gezittert, kann nicht mehr richtig sprechen.' M: Insulinpumpe! P: Diabetes Typ 1 seit 2 Jahren. L: Frühstück, aber Sport in 1. Stunde. E: schleichend in der 2. Stunde",inspektion:"Blass, schweißig, zittrig, Insulinpumpe am Bauch sichtbar",auskultation:"Herztöne tachykard, Lunge frei",ekg:"Nicht angelegt",neurologie:"GCS 13, verlangsamt, kann noch schlucken",palpation:"Feucht-kalt, Tremor"},
xabcde:{c:"Keine Blutung",a:"Frei",b:"Unauffällig",c2:"Tachykardie → adrenerge Gegenregulation",d:"GCS 13, verlangsamt → Neuroglykopenische Symptome!",e:"BZ 35! Insulinpumpe → Hypoglykämie!"},
spezial:{name:"Hypoglykämie Kind",result:"BZ 35 mg/dl + noch schluckfähig (GCS 13)\n→ ORALE GLUCOSEGABE möglich! Traubenzucker, Saft\n→ Wenn keine Besserung oder Verschlechterung:\n Glucose i.v. 0,2 g/kgKG\n ODER Glucagon: <25 kgKG: 0,5 mg i.m., >25 kgKG: 1 mg i.m.\n→ Insulinpumpe: STOPPEN / pausieren!\n Sport + Insulinpumpe = häufige Hypoglykämie-Ursache"},
diagnoseOptionen:["Schwere Hypoglykämie bei Typ-1-Diabetes","Epileptischer Anfall mit progredientem Verlauf","Vasovagale Synkope bei unklarer Bewusstseinslage","Vergiftung und vegetativer Begleitsymptomatik"],
correctDiagnose:0,
diagnoseErklaerung:"BZ 35 + Insulinpumpe + Sport = Hypoglykämie. Noch schluckfähig → orale Glucose zuerst. Insulinpumpe stoppen! Bei Verschlechterung: Glucose i.v. oder Glucagon."},
{id:"exam_hypotherm_c",bpr:"hypothermie",caseId:39,
meldung:"Bergsteiger in Notlage, 35J, erschöpft, zittert stark, Höhenrettung",
ankunft:"Mann sitzt in Biwak, durchnässt, zittert unkontrolliert, orientiert.",
findings:{vitalzeichen:"RR: 110/70 mmHg | HF: 90/min | SpO₂: 94% | AF: 20/min | BZ: 70 mg/dl | Temp: 33°C",anamnese:"S: 'Bin gestürzt, lag 3h in nassem Schnee, konnte nicht weiter.' M: keine. P: gesund, sportlich. E: Kälteexposition 3h",inspektion:"Zittert massiv, durchnässte Kleidung, Schürfwunden, orientiert, kann sprechen",auskultation:"Herztöne regelmäßig, Lunge frei",ekg:"Sinusrhythmus 90/min, leichte J-Wellen",neurologie:"GCS 15, wach, zittert, leicht verlangsamt",palpation:"Haut kalt, feucht, Pulse tastbar"},
xabcde:{c:"Schürfwunden, keine kritische Blutung",a:"Frei",b:"SpO₂ 94%",c2:"Stabil, aber Hypothermie!",d:"GCS 15, orientiert, zittert → STADIUM I-II",e:"Temp 33°C → HYPOTHERMIE STADIUM II. BZ 70 → grenzwertig"},
spezial:{name:"Hypothermie-Stadien",result:"Temp 33°C + Zittern + Bewusstsein erhalten\n→ STADIUM II (32-35°C = Stadium I-II Übergang)\n→ Nasse Kleidung entfernen!\n→ Passive Wiedererwärmung (Isolierung, Rettungsdecke)\n→ Warme Getränke wenn schluckfähig\n→ BZ 70 → Glucose oral\n→ VORSICHTIGER Transport (VF-Gefahr bei Manipulation!)\n Patienten NICHT aktiv bewegen wenn möglich!"},
diagnoseOptionen:["Akzidentielle Hypothermie Stadium II","Hypothermie Stadium I (milde Form)","Erschöpfung ohne relevante Hypothermie","Höhenkrankheit"],
correctDiagnose:0,
diagnoseErklaerung:"Kälteexposition 3h + Temp 33°C + Zittern + wach = Hypothermie Stadium II. Nasse Kleidung entfernen, passive Wiedererwärmung, vorsichtiger Transport!"},
{id:"exam_hypert_c",bpr:"hypertensiv",caseId:33,
meldung:"Schwangere SSW 36, starke Kopfschmerzen, Sehstörungen, hoher RR",
ankunft:"Schwangere liegt auf Sofa, klagt über Kopfschmerzen und Lichtblitze.",
findings:{vitalzeichen:"RR: 190/115 mmHg | HF: 95/min | SpO₂: 97% | AF: 18/min | BZ: 100 mg/dl",anamnese:"S: 'Seit Stunden Kopfschmerzen, jetzt Lichtblitze und Oberbauchschmerzen.' M: Methyldopa (wegen SIH). P: Schwangerschaftsinduzierte Hypertonie seit SSW 32. L: Mittagessen. E: zunehmend seit 4h",inspektion:"Ödeme Hände/Gesicht, schmerzgeplagt, lichtempfindlich",auskultation:"Herztöne regelmäßig, Lunge frei",ekg:"Sinusrhythmus 95/min",neurologie:"GCS 15, Kopfschmerzen, gesteigerte Reflexe, Blitzlichter",palpation:"Oberbauch rechts druckschmerzhaft (Leberkapselspannung!), Ödeme +++"},
xabcde:{c:"Keine Blutung",a:"Frei – aber Eklampsieanfall möglich!",b:"Unauffällig",c2:"RR 190/115 → Schwere Präeklampsie!",d:"Kopfschmerzen + Sehstörungen + gesteigerte Reflexe → EKLAMPSIE droht!",e:"Ödeme, Oberbauchschmerz rechts = HELLP möglich"},
spezial:{name:"Präeklampsie/Eklampsie",result:"RR >160/110 + Kopfschmerz + Sehstörung + gesteigerte Reflexe + Oberbauchschmerz\n→ SCHWERE PRÄEKLAMPSIE mit drohender Eklampsie!\n→ Urapidil: KONTRAINDIZIERT in Schwangerschaft!\n→ RR-Senkung klinisch mit Nifedipin/Dihydralazin\n→ Präklinisch: Ruhe, Seitenlage links, O₂\n→ MgSO₄ zur Eklampsie-Prophylaxe (klinisch)\n→ Schneller Transport in Perinatalzentrum!\n CAVE: Kramfpbereitschaft! Midazolam bereithalten!"},
diagnoseOptionen:["Schwere Präeklampsie mit drohender Eklampsie","Migräne in der Schwangerschaft","Hypertensive Krise ohne Schwangerschaftsbezug","HELLP-Syndrom"],
correctDiagnose:0,
diagnoseErklaerung:"SSW 36 + RR 190/115 + Kopfschmerz + Sehstörung + Oberbauchschmerz + Reflexsteigerung = schwere Präeklampsie. Kein Urapidil! Perinatalzentrum, Krampfbereitschaft!"},
{id:"exam_krampf_c",bpr:"krampf_erw",caseId:54,
meldung:"Frau krampft in Straßenbahn, 25J, beißt auf Zunge",
ankunft:"Straßenbahn angehalten, Frau liegt auf Boden, Krampf soeben beendet, postiktal.",
findings:{vitalzeichen:"RR: 140/85 mmHg | HF: 100/min | SpO₂: 93% | AF: 18/min | BZ: 90 mg/dl",anamnese:"S: Fahrgast: 'Hat plötzlich gezuckt und ist umgefallen, hat ca. 2 min gekrampft.' M: In Handtasche: Levetiracetam. P: vermutlich Epilepsie. E: 1 einzelner Anfall, selbstlimitiert",inspektion:"Postiktal, somnolent, seitlicher Zungenbiss blutet, Einnässung",auskultation:"Herztöne regelmäßig, Lunge frei",ekg:"Sinusrhythmus 100/min",neurologie:"GCS 11 (A3V3M5), postiktal, desorientiert, keine fokalen Defizite, Pupillen isokor",palpation:"Zungenbiss seitlich, keine Verletzungen durch Sturz"},
xabcde:{c:"Zungenbiss blutet leicht",a:"Frei, Seitenlage zur Aspirationsprophylaxe",b:"SpO₂ 93% → O₂, bessert sich im Verlauf",c2:"Stabil",d:"Postiktal, GCS 11 → erwartet! Überwachung!",e:"BZ 90 → normal"},
spezial:{name:"Postiktaler Zustand",result:"Einzelner Krampfanfall, selbstlimitiert (<5 min)\n→ KEIN Status epilepticus → KEIN Midazolam nötig!\n→ Seitenlage, Schutz, O₂\n→ Postiktale Phase: Minuten bis Stunden\n→ GCS-Monitoring: sollte sich bessern\n→ BZ prüfen (hier normal)\n→ Transport zur Abklärung\n Bei erneutem Krampf → Midazolam bereithalten"},
diagnoseOptionen:["Postiktaler Zustand nach einzelnem epileptischem Anfall","Status epilepticus mit akuter Kreislaufdekompensation","Synkope mit Myoklonien bei vorbestehender Grunderkrankung","Psychogener Anfall mit begleitender Bewusstseinstrübung und laborchemisch zu sichernder Verdachtsdiagnose"],
correctDiagnose:0,
diagnoseErklaerung:"Einzelner Krampf <5 min + Zungenbiss + Einnässung + Antiepileptika = epileptischer Anfall mit spontanem Ende. Postiktale Überwachung, KEIN Midazolam nötig. Bei erneutem Anfall → Midazolam."},
{id:"exam_krampf_kind_c",bpr:"krampf_kind",caseId:57,
meldung:"Kind 5J krampft seit 8 Minuten, Status epilepticus",
ankunft:"Kind liegt im Bett, generalisierte Krämpfe, zyanotisch.",
findings:{vitalzeichen:"HF: 160/min | SpO₂: 80% | AF: unregelmäßig | BZ: 85 mg/dl | Temp: 37,0°C",anamnese:"S: Mutter: 'Krampft seit 8 min, ist Epileptiker, hat Medikament vergessen.' M: Valproat (heute Morgen vergessen). P: Epilepsie seit 3 J. E: Krampfbeginn vor 8 min",inspektion:"Generalisierte tonisch-klonische Krämpfe, zyanotisch",auskultation:"Nicht beurteilbar",ekg:"Nicht angelegt",neurologie:"Aktiver Krampf, GCS nicht beurteilbar",palpation:"Generalisierter Tonus erhöht"},
xabcde:{c:"Keine Blutung",a:"Während Krampf überwachen",b:"SpO₂ 80% → O₂!",c2:"Tachykard",d:"STATUS EPILEPTICUS >5 min → Midazolam!",e:"Kein Fieber, BZ normal"},
spezial:{name:"Krampf Kind – Dosierung",result:"Kind 5 Jahre, >5 min = STATUS EPILEPTICUS\nBuccal: Buccolam 7,5 mg (5-9 J.)\nNasal (MAD): ca. 20 kgKG → 5-10 mg\ni.v.: 0,1 mg/kgKG\nEinmalige Repetition möglich\n NICHT titrieren, adäquat hoch dosieren!\n Kein Fieber → primär epileptisch, KEIN Fieberkrampf\n Ursache: vergessenes Valproat"},
diagnoseOptionen:["Status epilepticus bei bekannter Epilepsie (Med. vergessen)","Fieberkrampf und hämodynamischer Instabilität","Meningoenzephalitis mit respiratorischer Insuffizienz","Intoxikation bei unklarer Ätiologie"],
correctDiagnose:0,
diagnoseErklaerung:"Kind 5J + Epilepsie + vergessenes Medikament + Krampf >5 min = Status epilepticus. Midazolam buccal 7,5 mg (5-9J.), O₂, NICHT titrieren!"},
{id:"exam_apoplex_c",bpr:"schlaganfall",caseId:69,
meldung:"Plötzliche Sehstörung und Schwindel, 60J Mann, kann nicht mehr gehen",
ankunft:"Mann sitzt auf Stuhl, klagt über Doppelbilder, Übelkeit, unsicherer Gang.",
findings:{vitalzeichen:"RR: 175/95 mmHg | HF: 75/min | SpO₂: 96% | AF: 16/min | BZ: 120 mg/dl",anamnese:"S: 'Plötzlich alles doppelt, Schwindel, kann kaum stehen, Übelkeit.' M: Metformin, Atorvastatin, ASS. P: Diabetes, Hyperlipidämie, Hypertonie. E: plötzlich vor 30 min",inspektion:"Sitzt unsicher, Nystagmus sichtbar, Übelkeit, kein Erbrechen",auskultation:"Herztöne regelmäßig, Lunge frei",ekg:"Sinusrhythmus 75/min",neurologie:"GCS 15, aber: Doppelbilder, horizontaler Nystagmus, Dysarthrie (verwaschene Sprache), Rumpfataxie, Finger-Nase-Versuch unsicher",palpation:"Unauffällig"},
xabcde:{c:"Keine Blutung",a:"Cave: Aspirationsschutz bei Übelkeit + Schluckstörung",b:"Unauffällig",c2:"RR 175 → NICHT senken (unter 220 nicht indiziert)",d:"Nystagmus + Ataxie + Dysarthrie → VERTEBROBASILÄRER SCHLAGANFALL!",e:"Keine Verletzungen"},
spezial:{name:"BE-FAST + posteriorer Schlaganfall",result:"Balance: ✓ Rumpfataxie, kann nicht stehen\nEyes: ✓ Doppelbilder, Nystagmus!\nFace: Dysarthrie ✓\nArms: Ataxie ✓\nSpeech: Verwaschene Sprache ✓\nTime: 30 min → LYSE-ZEITFENSTER!\n→ POSTERIORER SCHLAGANFALL (Vertebrobasilär)!\n→ Oft übersehen! Kein klassischer Halbseitenausfall!\n→ RR NICHT senken! Stroke Unit!"},
diagnoseOptionen:["Vertebrobasilärer Schlaganfall","Benigner Lagerungsschwindel","Vestibularneuritis","Kleinhirntumor mit neurologischem Defizit"],
correctDiagnose:0,
diagnoseErklaerung:"Plötzlich + Doppelbilder + Ataxie + Nystagmus + Dysarthrie = vertebrobasilärer Schlaganfall. BE-FAST positiv! RR nicht senken. Stroke Unit mit Lysemöglichkeit!"},
{id:"exam_trauma_c",bpr:"polytrauma",caseId:66,
meldung:"Fußgänger von PKW erfasst, 45J Frau, liegt auf Straße",
ankunft:"Frau liegt auf Fahrbahn, stöhnt, offensichtliche Unterschenkelfraktur links.",
findings:{vitalzeichen:"RR: 95/60 mmHg | HF: 120/min | SpO₂: 92% | AF: 26/min | BZ: 110 mg/dl",anamnese:"S: Zeuge: 'PKW ca. 50 km/h, Frau wurde über Motorhaube geschleudert.' E: Unfall vor 5 min",inspektion:"Stöhnt, offene Unterschenkelfraktur links blutend, Prellmarke Thorax re, Schürfwunden Gesicht, Becken stabil",auskultation:"Lunge: rechts abgeschwächt (Kontusion?), links belüftet. Herztöne tachykard",ekg:"Sinustachykardie 120/min",neurologie:"GCS 12 (A3V4M5), desorientiert, bewegt alle Extremitäten",palpation:"Thorax rechts druckschmerzhaft, kein Hautemphysem, offene Fraktur US links, Abdomen weich"},
xabcde:{c:"Offene Fraktur blutet → Kompressionsverband! Kein Tourniquet nötig (kontrollierbare Blutung)",a:"Frei, aber GCS 12 → überwachen",b:"SpO₂ 92%, rechts abgeschwächt → Thoraxkontusion, Pneumothorax möglich → O₂, Monitoring",c2:"RR 95/60, Tachy → Hämorrhagie möglich → VEL",d:"GCS 12 → SHT? Monitoring",e:"Offene Fraktur US, Schürfwunden → Wundversorgung, Schiene, Wärmeerhalt"},
spezial:{name:"<c>ABCDE",result:"<c>: Offene Fraktur blutet → Kompressionsverband\nA: Frei, aber GCS 12 → Monitoring, HWS-Immobilisation\nB: Rechts abgeschwächt → V.a. Lungenkontusion/Pneumothorax → O₂, Monitoring\nC: Tachykardie + Hypotonie → VEL + TXA erwägen\nD: GCS 12 → SHT möglich (Schürfwunden Gesicht)\nE: Wärme, Schiene, Transport\n→ Traumazentrum!"},
diagnoseOptionen:["Polytrauma (SHT + Thoraxtrauma + offene Fraktur)","Isolierte Unterschenkelfraktur","Isoliertes SHT bei Z.n. Trauma","Beckenfraktur mit Blutung mit metabolischer Entgleisung"],
correctDiagnose:0,
diagnoseErklaerung:"PKW-Anprall 50 km/h + GCS 12 + Thoraxbefund + offene Fraktur = Polytrauma. <c>ABCDE: Blutung versorgen, Atemweg sichern, VEL, TXA, Traumazentrum."},
{id:"exam_strom_c",bpr:"stromunfall",caseId:75,
meldung:"Arbeiter nach Hochspannungsunfall, 30J, bewusstlos, Feuerwehr hat abgeschaltet",
ankunft:"Mann liegt am Boden neben Schaltanlage, bewusstlos, Verbrennungen sichtbar.",
findings:{vitalzeichen:"RR: 80/50 mmHg | HF: 145/min (arrhythmisch) | SpO₂: 90% | AF: 10/min",anamnese:"S: Kollege: 'Hat an Hochspannung (>1000V) gegriffen, wurde weggeschleudert.' E: Hochspannungsunfall vor 10 min, Strom abgeschaltet",inspektion:"Bewusstlos, schwere Verbrennungen rechte Hand und Unterarm (Eintritt), linker Fuß (Austritt), Tetanische Muskelkontraktionen residual",auskultation:"Arrhythmische Herztöne, Lunge bds belüftet",ekg:"Unregelmäßig, VES-Salven, drohende VT!",neurologie:"GCS 6 (A1V2M3), Pupillen mittelweit",palpation:"Pulse unregelmäßig, Verbrennungen III° Hand/Arm"},
xabcde:{c:"Keine äußere Blutung, Verbrennungen!",a:"GCS 6 → Atemwegssicherung!",b:"AF 10, SpO₂ 90% → assistierte Beatmung!",c2:"Arrhythmisch, VES-Salven → Defi-Bereitschaft! Hypotonie → VEL!",d:"GCS 6 → Bewusstlosigkeit durch Stromunfall",e:"Verbrennungen III° → steriler Verband, Hochspannung = innere Verletzungen möglich!"},
spezial:{name:"Hochspannungsunfall",result:"Hochspannung >1000V → SCHWERE innere Verletzungen möglich!\n→ Muskel-/Organschäden entlang des Strompfades\n→ Rhabdomyolyse → Nierenversagen!\n→ Herzrhythmusstörungen: VES, VT, VF möglich\n→ Defi-Bereitschaft!\n→ VEL-Therapie (Rhabdomyolyse → hoher Bedarf)\n→ Verbrennungen versorgen\n Innere Verletzungen >> äußere!"},
diagnoseOptionen:["Hochspannungsunfall mit Bewusstlosigkeit und HRST","Niederspannungsunfall und sekundärer Organbeteiligung","Bewusstlosigkeit durch Sturztrauma","Thermische Verbrennung ohne Stromkontakt"],
correctDiagnose:0,
diagnoseErklaerung:"Hochspannung + Bewusstlosigkeit + HRST + Verbrennungen = schwerer Stromunfall. Atemweg sichern, Defi-Bereitschaft, VEL großzügig, Verbrennungszentrum!"},
{id:"exam_therm_c",bpr:"thermisch",caseId:78,
meldung:"Hausbrand, 50J Mann, aus Feuer gerettet, Gesicht verbrannt, Ruß im Mund",
ankunft:"Feuerwehr hat Mann gerettet, sitzt vor Haus, heisere Stimme, Gesichtsverbrennungen.",
findings:{vitalzeichen:"RR: 130/80 mmHg | HF: 115/min | SpO₂: 91% | AF: 24/min",anamnese:"S: Feuerwehr: 'War ca. 5 min im Brandrauch, Flammen im Gesicht.' E: Hausbrand vor 15 min",inspektion:"Gesicht: Verbrennungen II°, versengtes Nasen-/Augenbrauen-Haar, Ruß in Nase und Mund, heisere Stimme, stridor angedeutet",auskultation:"Leichter inspiratorischer Stridor! Giemen bds, Herztöne tachykard",ekg:"Sinustachykardie 115/min",neurologie:"GCS 15, husted, heiser",palpation:"Gesicht ödematös, Ruß perioral"},
xabcde:{c:"Keine äußere Blutung",a:"INHALATIONSTRAUMA! Stridor + Heiserkeit + Ruß → A-Problem droht! Frühintubation erwägen!",b:"SpO₂ 91%, Giemen → O₂ 15 l/min! CO-Intoxikation möglich (SpO₂ falsch hoch!)!",c2:"Stabil aktuell",d:"GCS 15",e:"Gesichtsverbrennungen II°, Inhalationstrauma → KEINE Kühlung Gesicht!"},
spezial:{name:"Inhalationstrauma",result:"Anzeichen Inhalationstrauma:\n✓ Brandrauchexposition in geschlossenem Raum\n✓ Gesichtsverbrennungen\n✓ Versengtes Gesichtshaar\n✓ Ruß in Mund/Nase\n✓ Heiserkeit/Stridor → LARYNXÖDEM beginnt!\n→ O₂ 15 l/min (auch bei normaler SpO₂ → CO-Intox!)\n→ FRÜHINTUBATION erwägen bevor Larynxödem zunimmt!\n→ SpO₂ bei CO-Intox FALSCH HOCH! Nicht vertrauen!\n A-Problem kann sich in Minuten verschlechtern!"},
diagnoseOptionen:["Inhalationstrauma mit drohendem A-Problem + V.a. CO-Intoxikation","Reine Gesichtsverbrennung ohne Inhalation","Asthmaanfall ausgelöst durch Rauch bei infektiöser Genese","Rauchgasvergiftung ohne Verbrennung mit kardialer Beteiligung"],
correctDiagnose:0,
diagnoseErklaerung:"Brandrauch + Ruß + versengtes Haar + Stridor + Heiserkeit = Inhalationstrauma. A-Problem droht! O₂ 15 l/min (CO!), Frühintubation erwägen! SpO₂ nicht verlässlich bei CO."},
{id:"exam_trach_c",bpr:"tracheostoma",caseId:84,
meldung:"Kind 4J mit Tracheostoma, Atemnot, Kanüle disloziert",
ankunft:"Kind weint, Mutter hält Kind, Kanüle steht schief, Atemnot.",
findings:{vitalzeichen:"HF: 155/min | SpO₂: 80% | AF: 35/min",anamnese:"S: Mutter: 'Kanüle hat sich beim Spielen gelöst, bekomme sie nicht wieder rein.' M: keine. P: Tracheostoma seit Geburt (Trachealstenose). E: Dislokation vor 5 min",inspektion:"Kanüle teilweise herausgerutscht, Stoma sichtbar, Kind atmet teilweise über Stoma, zyanotisch",auskultation:"Verminderte AG bds, gurgelnde Geräusche über Stoma",ekg:"Nicht angelegt",neurologie:"Wach, weint, agitiert",palpation:"Tachykard"},
xabcde:{c:"Keine Blutung",a:"KANÜLE DISLOZIERT! → Kanüle entfernen und Stoma freihalten!",b:"SpO₂ 80% → O₂ über Stoma!",c2:"Tachykard → Stressreaktion",d:"Wach, agitiert",e:"Keine Verletzungen"},
spezial:{name:"Tracheostoma Kind – Kanülenwechsel",result:"Dislozierte Kanüle bei Kind:\n→ Kanüle komplett entfernen!\n→ Stoma offenhalten (mit Klemme/Spreizer wenn nötig)\n→ O₂ über Stoma geben\n→ Neue/gleiche Kanüle vorsichtig einführen\n→ Wenn nicht möglich: Beutel-Maske über Stoma beatmen\n→ Reserve: kleinere Kanüle oder Tubus als Platzhalter\n Kind hat keine anderen Atemwege als Stoma!\n Stoma kann sich schnell verengen!"},
diagnoseOptionen:["Tracheostoma-Kanüle disloziert – Atemnotfall","Fremdkörperaspiration über Stoma","Pneumothorax und drohender Dekompensation mit unklarem zeitlichem Verlauf seit Symptombeginn","Trachealstenose-Rezidiv bei bestehender Medikation"],
correctDiagnose:0,
diagnoseErklaerung:"Dislozierte Kanüle + Hypoxie = Atemnotfall. Kanüle raus, Stoma freihalten, O₂ über Stoma, neue Kanüle vorsichtig einsetzen. Stoma = einziger Atemweg!"},
{id:"exam_intox_c",bpr:"intoxikation",caseId:48,
meldung:"Bewusstloser in Garage, 50J, Auto lief, Garagentor zu – CO-Verdacht",
ankunft:"Feuerwehr hat belüftet. Mann liegt in Garage, bewusstlos, Auto aus.",
findings:{vitalzeichen:"RR: 130/85 mmHg | HF: 110/min | SpO₂: 99% (CAVE!) | AF: 22/min | BZ: 100 mg/dl",anamnese:"S: Nachbar: 'Motor lief in geschlossener Garage, Suizidverdacht.' M: Antidepressiva laut Nachbar. P: Depression bekannt. E: CO-Exposition, Dauer unklar (30-60 min?)",inspektion:"Bewusstlos, kirschrote Hautfarbe (CAVE: nicht immer vorhanden!), keine Verletzungen",auskultation:"Herztöne tachykard, Lunge frei",ekg:"Sinustachykardie 110/min, keine ST-Veränderungen",neurologie:"GCS 6 (A1V2M3), Pupillen mittelweit, keine Fokalneurologie",palpation:"Pulse tastbar, Haut warm"},
xabcde:{c:"Keine Blutung",a:"GCS 6 → Atemwegssicherung!",b:"SpO₂ 99% → BEI CO-INTOX NICHT VERLÄSSLICH! O₂ 15 l/min über Maske mit Reservoir!",c2:"Stabil aktuell",d:"GCS 6 → schwere CO-Intoxikation!",e:"Keine Verletzungen, V.a. Suizidversuch"},
spezial:{name:"CO-Intoxikation",result:"Geschlossene Garage + laufender Motor + Bewusstlosigkeit\n→ SCHWERE CO-INTOXIKATION!\n→ SpO₂ bei CO FALSCH NORMAL! (Pulsoximeter misst COHb mit!)\n→ O₂ 15 l/min mit Reservoir (FiO₂ 1,0!)\n→ Atemwegssicherung bei GCS 6\n→ Klinik mit hyperbare O₂-Therapie wenn verfügbar\n Eigenschutz! Nur mit Atemschutz/nach Belüftung!\n Suizidversuch → Psychiatrie"},
diagnoseOptionen:["Schwere CO-Intoxikation bei Suizidversuch","Alkoholintoxikation mit progredientem Verlauf","Schlaganfall bei unklarer Bewusstseinslage","Medikamentenintoxikation und vegetativer Begleitsymptomatik"],
correctDiagnose:0,
diagnoseErklaerung:"Geschlossene Garage + Motor + Bewusstlosigkeit + SpO₂ falsch normal = CO-Intoxikation. O₂ 15 l/min FiO₂ 1,0! Atemweg sichern! SpO₂ nicht verlässlich!"},
{id:"exam_sepsis_c",bpr:"sepsis",caseId:72,
meldung:"Fieber und Beinschmerz, 40J Mann, geschwollenes rotes Bein, Schüttelfrost",
ankunft:"Mann liegt im Bett, schüttelt, rechtes Bein massiv gerötet und geschwollen.",
findings:{vitalzeichen:"RR: 80/45 mmHg | HF: 130/min | SpO₂: 93% | AF: 25/min | BZ: 160 mg/dl | Temp: 40,5°C",anamnese:"S: 'Kleine Wunde am Bein, jetzt massiv geschwollen und rot, Fieber, Schüttelfrost.' M: keine. P: Adipositas, Diabetes Typ 2 (nicht eingestellt). E: Wunde seit 5 Tagen, heute akut verschlechtert",inspektion:"Rechter Unterschenkel: massiv gerötet, geschwollen, überwärmt, Hautnekrose zentral. Schüttelfrost, verwirrt",auskultation:"Herztöne tachykard, Lunge frei",ekg:"Sinustachykardie 130/min",neurologie:"GCS 13, verwirrt, desorientiert",palpation:"Rechtes Bein: massiv druckschmerzhaft, fluktuierend, Crepitatio? (Gasbrand möglich!)"},
xabcde:{c:"Keine aktive Blutung",a:"Frei",b:"SpO₂ 93% → O₂",c2:"RR 80/45, HF 130 → SEPTISCHER SCHOCK! VEL sofort!",d:"GCS 13, verwirrt",e:"Infektfokus: nekrotisierende Weichteilinfektion rechts! Temp 40,5°C"},
spezial:{name:"qSOFA + Fokus",result:"qSOFA: AF ≥22 ✓ | GCS <15 ✓ | RRsyst ≤100 ✓ → 3/3\n→ SEPTISCHER SCHOCK!\nFokus: Nekrotisierende Weichteilinfektion (→ Gasbrand/Fasziitis möglich!)\n→ VEL 500-1000 ml i.v. schnell\n→ O₂-Gabe\n→ Klinik mit Chirurgie! OP-Indikation!\n Crepitatio = V.a. Gasbrand → NOTFALL-OP!"},
diagnoseOptionen:["Septischer Schock bei nekrotisierender Weichteilinfektion","Tiefe Beinvenenthrombose mit akuter Kreislaufdekompensation","Erysipel ohne Sepsis bei vorbestehender Grunderkrankung","Kompartmentsyndrom mit begleitender Bewusstseinstrübung"],
correctDiagnose:0,
diagnoseErklaerung:"Infizierte Wunde + Nekrose + Schock + qSOFA 3 = septischer Schock bei Weichteilinfektion. VEL sofort, O₂, schneller Transport, chirurgische Intervention nötig!"},
{id:"exam_geburt_c",bpr:"geburt",caseId:81,
meldung:"Schwangere, Nabelschnurvorfall, Kindsteile tastbar, SSW 39",
ankunft:"Schwangere im Badezimmer, Blasensprung, Nabelschnur sichtbar in der Vulva!",
findings:{vitalzeichen:"RR: 125/80 mmHg | HF: 100/min | SpO₂: 98%",anamnese:"S: 'Fruchtwasser abgegangen, da hängt etwas raus!' M: Folsäure. P: 3. Kind, SSW 39, Steißlage bekannt. E: Blasensprung vor 10 min",inspektion:"Nabelschnur sichtbar zwischen Vulvalippen! Pulsierend! Kindsteile nicht im Beckenausgang",auskultation:"Nicht relevant",ekg:"Nicht angelegt",neurologie:"Wach, panisch",palpation:"Nabelschnur pulsierend tastbar (kindliche HF ca. 110/min → bradykard-grenzwertig!)"},
xabcde:{c:"Keine Blutung",a:"Frei",b:"Unauffällig",c2:"Mutter stabil",d:"Wach, ängstlich",e:"NABELSCHNURVORFALL! Lebensbedrohlich für Kind!"},
spezial:{name:"Nabelschnurvorfall – Notfall!",result:"Nabelschnurvorfall = ABSOLUTER NOTFALL für das Kind!\n→ NICHT an Nabelschnur ziehen!\n→ Nabelschnur NICHT reponieren!\n→ Mutter in Knie-Ellenbogen-Lage (oder Beckenhochlagerung)\n→ Mit Hand den vorangehenden Kindsteil hochdrücken (Druck von Nabelschnur nehmen!)\n→ Nabelschnur feucht halten (feuchtes Tuch)\n→ SOFORTIGER Transport, Klinik vorinformieren: Not-Sectio!\n Kindliche Bradykardie = Zeichen der Kompression!"},
diagnoseOptionen:["Nabelschnurvorfall – kindlicher Notfall","Normaler Blasensprung ohne Komplikation, differentialdiagnostisch abzugrenzen von funktioneller Störung","Vorzeitige Plazentalösung","Uterusruptur und hämodynamischer Instabilität"],
correctDiagnose:0,
diagnoseErklaerung:"Sichtbare Nabelschnur nach Blasensprung + Steißlage = Nabelschnurvorfall. Knie-Ellenbogen-Lage, Kindsteil hochdrücken, Nabelschnur feucht halten, Not-Sectio!"}
,
{id:"exam_als_d",bpr:"rea_als",caseId:94,
meldung:"Bewusstlose Person, 72J, Supermarkt, Laienhelfer vor Ort",
ankunft:"Frau liegt am Boden neben der Kasse. Laienhelfer haben AED angebracht – kein Schock empfohlen. Keine CPR aktuell.",
findings:{
vitalzeichen:"RR: nicht messbar | HF: 0/min | SpO₂: nicht messbar | AF: 0/min",
anamnese:"S: Laienhelfer: 'Ist einfach umgefallen an der Kasse.' A: unbekannt. M: unbekannt. P: unbekannt. L: unbekannt. E: Kollaps vor ca. 5 min, AED: kein Schock empfohlen",
inspektion:"Leblos, blass-grau, keine Thoraxexkursionen, Einkaufswagen umgekippt, AED-Pads kleben",
auskultation:"Keine Herztöne, keine Atemgeräusche",
ekg:"Asystolie",
neurologie:"GCS 3, Pupillen weit, keine Lichtreaktion",
palpation:"Kein Karotispuls tastbar"
},
xabcde:{c:"Keine Blutung",a:"Nicht gesichert → Überstrecken, Absaugen",b:"Keine Atmung → Beatmung!",c2:"Asystolie → CPR + Adrenalin 1 mg alle 3-5 min!",d:"GCS 3, weite Pupillen",e:"Keine äußeren Verletzungen"},
spezial:{name:"ALS-Algorithmus Asystolie/PEA",result:"Asystolie = nicht-schockbarer Rhythmus\n→ CPR 30:2 sofort!\n→ Adrenalin 1 mg i.v. SOFORT (bei nicht-schockbar!)\n→ Alle 3-5 min Adrenalin wiederholen\n→ Reversible Ursachen: 4H + HITS\n→ Rhythmuscheck alle 2 min\n→ KEIN Amiodaron bei Asystolie!\n AED: kein Schock empfohlen = nicht-schockbar!"},
diagnoseOptionen:["Kreislaufstillstand – Asystolie","Synkope mit spontaner Erholung","Krampfanfall mit Bewusstlosigkeit","Hypoglykämischer Schock"],
correctDiagnose:0,
diagnoseErklaerung:"Leblos + kein Puls + AED kein Schock empfohlen + Asystolie am Monitor = Kreislaufstillstand mit nicht-schockbarem Rhythmus. Sofort CPR + Adrenalin!"},
{id:"exam_als_e",bpr:"rea_als",caseId:95,
meldung:"Sportler, 28J, auf Fußballplatz zusammengebrochen, Ersthelfer mit CPR",
ankunft:"Junger Mann liegt auf dem Rasen. Mitspieler führen CPR durch. AED meldet: Schock empfohlen.",
findings:{
vitalzeichen:"RR: nicht messbar | HF: 0/min | SpO₂: nicht messbar | AF: 0/min",
anamnese:"S: Mitspieler: 'Ist beim Sprint einfach umgefallen, sofort CPR begonnen, 1 AED-Schock gegeben.' A: keine bekannt. M: keine. P: keine bekannt. L: 2h vor Sport gegessen. E: Kollaps vor 4 min, 1 AED-Schock",
inspektion:"Junger Mann in Sportkleidung, leblos, CPR durch Ersthelfer, AED-Pads kleben",
auskultation:"Keine Herztöne, keine Atemgeräusche",
ekg:"Kammerflimmern (VF)",
neurologie:"GCS 3, Pupillen mittelweit",
palpation:"Kein Karotispuls"
},
xabcde:{c:"Keine Blutung",a:"Nicht gesichert → Atemwegsmanagement parallel zu CPR",b:"Keine Atmung → Beatmung 30:2",c2:"VF → Defibrillation + CPR! Adrenalin nach 3. Schock!",d:"GCS 3",e:"Junger Sportler → an Commotio cordis, HOCM, Long-QT denken!"},
spezial:{name:"ALS-Algorithmus VF/pVT",result:"Kammerflimmern = schockbarer Rhythmus\n→ Defibrillation 360J (mono) / 150-200J (bi)\n→ Sofort weiter CPR 2 min\n→ Rhythmuscheck → erneut Schock wenn VF\n→ Nach 3. Schock: Adrenalin 1 mg + Amiodaron 300 mg i.v.\n→ Nach 5. Schock: Amiodaron 150 mg\n Bei jungem Sportler: Commotio cordis, HOCM, Brugada, Long-QT als Ursache!"},
diagnoseOptionen:["Kreislaufstillstand – Kammerflimmern","Vasovagale Synkope beim Sport","Hitzschlag mit Bewusstlosigkeit","Hypoglykämie bei Sportler"],
correctDiagnose:0,
diagnoseErklaerung:"Junger Sportler + plötzlicher Kollaps + AED Schock empfohlen + VF am Monitor = Kreislaufstillstand mit schockbarem Rhythmus. Bei jungen Sportlern: HOCM, Commotio cordis, Long-QT, Brugada als Ursache möglich."},
{id:"exam_pls_d",bpr:"rea_pls",caseId:96,
meldung:"4-jähriges Kind, aus Pool geborgen, bewusstlos",
ankunft:"Kind liegt am Beckenrand, nass, leblos. Mutter hysterisch. Bystander haben Kind aus dem Wasser geholt.",
findings:{
vitalzeichen:"RR: nicht messbar | HF: 40/min (schwach) | SpO₂: nicht messbar | AF: 0/min",
anamnese:"S: Mutter: 'War nur 2 Minuten weg, lag im Wasser!' A: keine. M: keine. P: gesund. L: unbekannt. E: Submersionsdauer unklar, geschätzt 2-5 min",
inspektion:"Kind nass, blass-zyanotisch, keine Atmung, schlaff",
auskultation:"Bradykarde Herztöne ~40/min, keine Atemgeräusche",
ekg:"Sinusbradykardie 40/min",
neurologie:"GCS 3, schlaffe Muskulatur, weite Pupillen",
palpation:"Schwacher Karotispuls tastbar, Haut kalt"
},
xabcde:{c:"Keine Blutung",a:"Freimachen, Absaugen (Wasser/Erbrochenes möglich)",b:"Keine Atmung → 5 initiale Beatmungen! Dann 15:2",c2:"HF 40 bei Kind → CPR starten bei HF <60 mit Kreislaufzeichen schlecht!",d:"GCS 3, schlaff",e:"Nass, kalt → Hypothermie möglich, Wärmeerhalt!"},
spezial:{name:"PLS-Algorithmus Ertrinken",result:"Ertrinken bei Kindern:\n→ 5 initiale Beatmungen (primär respiratorische Ursache!)\n→ Dann CPR 15:2\n→ HF <60/min mit schlechter Perfusion → CPR!\n→ Adrenalin 10 µg/kg i.v./i.o.\n→ Bei Hypothermie: Reanimation fortsetzen bis Wiedererwärmung!\n→ Kein Kind ist tot, solange es nicht warm und tot ist!\n Aspiriertes Wasser nicht absaugen (geht ins Gewebe)"},
diagnoseOptionen:["Ertrinken mit Bradykardie/Kreislaufversagen","Krampfanfall im Wasser mit respiratorischer Insuffizienz","Commotio nach Sprung ins Becken","Anaphylaktische Reaktion auf Chlor"],
correctDiagnose:0,
diagnoseErklaerung:"Kind aus Wasser geborgen + keine Atmung + Bradykardie 40/min = Ertrinken mit drohendem Kreislaufstillstand. 5 initiale Beatmungen, dann CPR 15:2. Adrenalin i.o. wenn i.v. nicht möglich."},
{id:"exam_pls_e",bpr:"rea_pls",caseId:97,
meldung:"Säugling, 3 Monate, plötzlich blau und schlaff, keine Reaktion",
ankunft:"Mutter hält leblosen Säugling im Arm. Kind zyanotisch, keine Bewegung, keine Reaktion auf Ansprache.",
findings:{
vitalzeichen:"RR: nicht messbar | HF: 0/min | SpO₂: nicht messbar | AF: 0/min",
anamnese:"S: Mutter: 'Lag im Bettchen, plötzlich blau, reagiert nicht mehr!' A: keine. M: keine. P: gesund, Frühgeborenes 36. SSW. L: vor 1h gestillt. E: vor ca. 5 min bemerkt",
inspektion:"Säugling zyanotisch, schlaff, keine Thoraxexkursionen, keine Reaktion",
auskultation:"Keine Herztöne, keine Atemgeräusche",
ekg:"Asystolie",
neurologie:"Keine Reaktion, areaktive Pupillen, Muskeltonus aufgehoben",
palpation:"Kein Brachialispuls tastbar"
},
xabcde:{c:"Keine Blutung",a:"Neutralposition! Kein Überstrecken beim Säugling!",b:"5 initiale Beatmungen! Mund-über-Mund-und-Nase oder Beutel-Maske Größe 0/1",c2:"Asystolie → CPR Säugling: 2 Daumen-Technik 15:2, Adrenalin 10 µg/kg i.v./i.o.",d:"Areaktiv",e:"V.a. SIDS, Wärmeerhalt!"},
spezial:{name:"PLS Säugling",result:"Reanimation Säugling:\n→ Neutralposition (nicht überstrecken!)\n→ 5 initiale Beatmungen\n→ CPR: Zwei-Daumen-Technik 15:2 (Drucktiefe 4 cm)\n→ Thoraxkompressionsfrequenz 100-120/min\n→ Adrenalin 10 µg/kg i.v./i.o. (= 0,1 ml/kg 1:10.000)\n→ Zugang: i.o. am proximalen Tibia bevorzugt!\n V.a. SIDS: Eltern begleiten, Krisenintervention!"},
diagnoseOptionen:["V.a. SIDS – Kreislaufstillstand Säugling","Verschlucken mit Erstickung, bei negativer Eigenanamnese und fehlenden Vorerkrankungen","Meningitis mit Kreislaufversagen","Krampfanfall beim Säugling"],
correctDiagnose:0,
diagnoseErklaerung:"Säugling 3 Monate + plötzlich leblos + Asystolie + keine erkennbare Ursache = V.a. SIDS (Sudden Infant Death Syndrome). Sofort CPR mit 5 initialen Beatmungen, dann 15:2 Zwei-Daumen-Technik."},
{id:"exam_nls_d",bpr:"rea_nls",caseId:98,
meldung:"Notgeburt, Neugeborenes schlaff, Schnappatmung",
ankunft:"Mutter hat gerade entbunden. Neugeborenes liegt auf Handtuch, schlaff, vereinzelt Schnappatmung.",
findings:{
vitalzeichen:"HF: 80/min (Nabelschnur) | SpO₂: nicht messbar | AF: Schnappatmung",
anamnese:"S: Hebamme nicht vor Ort. 38. SSW, Spontangeburt. Unauffällige SS. Fruchtwasser klar.",
inspektion:"Neugeborenes schlaff, blass-zyanotisch, vereinzelt Schnappatmung, kein kräftiges Schreien, Nabelschnur nicht abgeklemmt",
auskultation:"Herztöne auskultierbar ~80/min, keine Atemgeräusche beidseits",
ekg:"Nicht angelegt (Auskultation/Palpation)",
neurologie:"Schlaffer Tonus, keine Reflexe auf Stimulation",
palpation:"Nabelschnurpuls tastbar ~80/min"
},
xabcde:{c:"Nabelschnur: Abnabeln wenn versorgt",a:"Kopf in Neutralposition, Absaugen nur wenn Verlegung sichtbar!",b:"Schnappatmung = KEINE effektive Atmung → 5 Inflationsbeatmungen!",c2:"HF 80 → wenn nach Beatmung HF <60 → Thoraxkompressionen 3:1!",d:"Schlaff, keine Reflexe → unreife Adaptation",e:"WÄRME! Abtrocknen, einwickeln, Mütze!"},
spezial:{name:"NLS-Algorithmus",result:"Neugeborenenreanimation:\n1. Abnabeln, abtrocknen, Wärme!\n2. Kopf Neutralposition\n3. 5 Inflationsbeatmungen (je 2-3s, Druck 20-25 cmH₂O)\n4. Re-Evaluation: Thoraxhebung? HF?\n5. HF <60 nach effektiver Beatmung → Thoraxkompressionen 3:1\n6. Adrenalin 10-30 µg/kg i.v. (NVK!) wenn HF <60 trotz CPR\n Schnappatmung = keine effektive Atmung!"},
diagnoseOptionen:["Postpartale Anpassungsstörung/Asphyxie","Frühgeburtlichkeit bei unklarer Ätiologie","Mekoniumaspiration mit neurologischem Defizit","Nabelschnurvorfall bei Z.n. Trauma mit atypischer Symptomatik und erschwerter Diagnosestellung"],
correctDiagnose:0,
diagnoseErklaerung:"Neugeborenes + schlaff + Schnappatmung + HF 80 = postpartale Anpassungsstörung. Schnappatmung gilt als keine effektive Atmung → 5 Inflationsbeatmungen! Wärme ist kritisch!"},
{id:"exam_rosc_d",bpr:"post_rosc",caseId:99,
meldung:"ROSC nach 20 min Reanimation, Patient intubiert, instabiler Kreislauf",
ankunft:"68-jähriger, ROSC nach Kammerflimmern. Intubiert, komatös. Monitor: Sinustachykardie.",
findings:{
vitalzeichen:"RR: 85/60 mmHg | HF: 110/min | SpO₂: 99% bei FiO₂ 1,0 | AF: beatmet 12/min | etCO₂: 45 mmHg",
anamnese:"S: Ehefrau anwesend. Plötzlicher Kollaps zu Hause. Keine Vorankündigung. CPR durch Frau begonnen. REA 20 min, 4 Defi, ROSC. A: Penicillin. M: ASS, Bisoprolol, Ramipril, Atorvastatin. P: KHK, Z.n. MI 2019.",
inspektion:"Intubiert, komatös, blass, Schweiß, keine Spontanbewegungen",
auskultation:"Herztöne tachykard, Lunge beidseits belüftet",
ekg:"Sinustachykardie 110/min, ST-Hebungen V1-V4 (STEMI!)",
neurologie:"GCS 3 (intubiert), Pupillen mittelweit, träge Lichtreaktion beidseits",
palpation:"Pulse tachykard, peripher schwach, Haut kühl, Rekapzeit 4s"
},
xabcde:{c:"Keine Blutung",a:"Intubiert, Tubuslage prüfen, etCO₂ bestätigt",b:"SpO₂ 99% bei FiO₂ 1,0 → FiO₂ REDUZIEREN! Ziel SpO₂ 94-98%!",c2:"RR 85/60 → Hypotension → VEL + ggf. Noradrenalin. ST-Hebung → PCI!",d:"GCS 3 → Targeted Temperature Management in Klinik",e:"Temperatur messen, Wärmeerhalt zunächst"},
spezial:{name:"Post-ROSC-Management",result:"Post-ROSC Bündel:\n1. Oxygenierung: SpO₂ 94-98% (NICHT 100%! Hyperoxie schadet!)\n2. Ventilation: etCO₂ 35-45 mmHg (Normokapnie)\n3. Hämodynamik: RRsyst >100 mmHg → VEL, Vasopressoren\n4. 12-Kanal-EKG: ST-Hebung → sofort PCI/Herzkatheter!\n5. Temperaturmanagement: Ziel 32-36°C für 24h\n6. BZ-Kontrolle: Ziel 140-180 mg/dl\n Kein Fieber zulassen! Kein Adrenalinbolus!"},
diagnoseOptionen:["ROSC nach VF bei STEMI – Post-Reanimationsbehandlung","Kardiogener Schock ohne ROSC mit metabolischer Entgleisung","Lungenembolie als Ursache und sekundärer Organbeteiligung","Sepsis mit Kreislaufversagen bei infektiöser Genese"],
correctDiagnose:0,
diagnoseErklaerung:"ROSC nach VF + ST-Hebungen V1-V4 + Z.n. KHK = STEMI als Ursache des Kreislaufstillstands. FiO₂ reduzieren (Ziel 94-98%), Hämodynamik stabilisieren, sofort Herzkatheter!"},
{id:"exam_anaph_d",bpr:"anaphylaxie",caseId:100,
meldung:"Allergische Reaktion, 32J Frau, Restaurant, Atemnot und Hautausschlag",
ankunft:"Frau sitzt im Restaurant, generalisierte Urtikaria, geschwollene Lippen, Stridor hörbar.",
findings:{
vitalzeichen:"RR: 80/50 mmHg | HF: 130/min | SpO₂: 89% | AF: 26/min",
anamnese:"S: 'Habe Curry gegessen, wusste nicht dass Erdnüsse drin sind!' A: Erdnüsse (bekannt, EpiPen dabei aber nicht benutzt). M: keine. P: Z.n. anaphylaktischer Reaktion 2022. L: gerade gegessen (Curry). E: Symptome seit 10 min, rasch progredient",
inspektion:"Generalisierte Urtikaria, Lippenschwellung, Zungenschwellung beginnend, Stridor, aufrecht sitzend, ängstlich",
auskultation:"Stridor inspiratorisch, Giemen bds. exspiratorisch",
ekg:"Sinustachykardie 130/min",
neurologie:"GCS 15, ängstlich, Stimme heiser",
palpation:"Pulse tachykard, peripher kaum tastbar, Haut warm, gerötet"
},
xabcde:{c:"Keine Blutung",a:"Zungenschwellung + Stridor → Atemweg bedroht! Adrenalin sofort!",b:"SpO₂ 89%, Giemen → Bronchospasmus → O₂ + Adrenalin + Salbutamol",c2:"RR 80/50 → anaphylaktischer Schock Grad III-IV! VEL aggressiv!",d:"GCS 15, ängstlich",e:"Generalisierte Urtikaria, bekannte Erdnussallergie"},
spezial:{name:"Anaphylaxie-Management",result:"Anaphylaxie Grad III-IV:\n→ Adrenalin 0,5 mg i.m. (Oberschenkel!) – SOFORT!\n→ Wiederholung nach 5 min wenn keine Besserung\n→ O₂ hochdosiert\n→ VEL: 500-1000 ml kristalloid Bolus\n→ Prednisolon 250 mg i.v.\n→ Dimetinden 4 mg i.v.\n→ Bei Bronchospasmus: Salbutamol 4 Hübe\n→ Bei Schock: Adrenalin i.v. titriert (0,1 mg Boli)\n EpiPen der Patientin nutzen wenn verfügbar!"},
diagnoseOptionen:["Anaphylaxie Grad III bei Erdnussallergie","Asthmaanfall mit kardialer Beteiligung","Angioödem ohne Anaphylaxie","Panikattacke mit Hyperventilation"],
correctDiagnose:0,
diagnoseErklaerung:"Bekannte Erdnussallergie + Allergenexposition + Urtikaria + Angioödem + Stridor + Bronchospasmus + Schock = Anaphylaxie Grad III. Adrenalin 0,5 mg i.m. sofort!"},
]);
