// NotSanTrainer 2025 - Fallsimulationen (Teil 4/4, Fälle 115-150)
CASES = CASES.concat([
{id:115,title:"Subtiler Krampf beim Säugling",bpr:"krampf_kind",scenario:"6 Monate, subtile Zuckungen, Blickdeviation, Apnoe. Temp 38,2°C.",
steps:[
{q:"Warum schwer erkennbar?",opts:["Immer generalisiert gemäß SOP des Rettungsdienstes","Subtile Präsentation: Zuckungen, Blickdeviation, Apnoe","Säuglinge krampfen nie bei fehlenden Kontraindikationen","Nur Fieberkrämpfe unter Berücksichtigung des klinischen Bildes"],correct:1,explanation:"Säuglingskrämpfe oft subtil!"},
{q:"Midazolam-Dosis (8 kg) intranasal?",opts:["5 mg","0,5 mg","1,6 mg","10 mg"],correct:2,explanation:"0,2 mg/kgKG × 8 = 1,6 mg intranasal."},
{q:"Kritischer BZ beim Säugling?",opts:["< 45 mg/dl","< 60 mg/dl","< 100 mg/dl","< 80 mg/dl"],correct:0,explanation:"Säugling: BZ < 45 mg/dl behandlungspflichtig!"},
{q:"i.v.-Zugang nicht möglich?",opts:["Unbegrenzt versuchen","Nach 2 Versuchen/90 sek → i.o.!","i.o. zuerst mit Voranmeldung in der Zielklinik","Nur Handrücken nach Ausschluss reversibler Ursachen"],correct:1,explanation:"Max. 2 Versuche, dann i.o.!"},
{q:"Transport?",opts:["Kinderklinik mit Pädiatrie","Erwachsenen-NA bei hämodynamischer Instabilität","Hausarzt unter Zeitdruck im Einsatzgeschehen","Kinderarzt-Praxis"],correct:0,explanation:"Säugling mit Krampf → immer Kinderklinik."}
,
{q:"Übergabe (SINNHAFT): Fazit/Teamfragen (F/T) bei Krampfanfall Kind – wer wiederholt die Kernpunkte?",opts:["Nur der Oberarzt als initiale Maßnahme vor Transport","Der Übergeber fasst nochmal zusammen","Das ÜBERNEHMENDE Team wiederholt (Closed Loop)","Niemand – einmal reicht bei gesicherter Diagnose und Indikation"],correct:2,explanation:"Krampfanfall Kind: Beim Fazit wiederholt das ÜBERNEHMENDE Team: Identifikation, Notfallereignis, Priorität, Handlungen. Dann Raum für Teamfragen."}]},
{id:116,title:"Schwere Hypoglykämie mit Bewusstlosigkeit",bpr:"hypoglyk",scenario:"52-jähriger Diabetiker Typ 1, bewusstlos aufgefunden. Insulinpumpe sichtbar, Schwitzen, Tremor.",
steps:[
{q:"BZ 28 mg/dl. Sofortmaßnahme?",opts:["Insulin stoppen reicht, was jedoch in der aktuellen Situation kontraindiziert wäre","Glukosefreie Infusion","Glucose 40% i.v. (0,5 g/kgKG)","Abwarten mit begleitender Sauerstofftherapie"],correct:2,explanation:"Schwere Hypoglykämie: Glucose 40% i.v. sofort!"},
{q:"Kein i.v.-Zugang – Alternative?",opts:["Glucose oral (bewusstlos!)","Insulin erhöhen","Glucagon 1 mg i.m.","Abwarten"],correct:2,explanation:"Ohne Zugang: Glucagon 1 mg i.m. KEINE orale Gabe bei Bewusstlosigkeit!"},
{q:"BZ nach Glucose: 90 mg/dl, Patient wach. Was überprüfen?",opts:["Nur Transport nach differentialdiagnostischer Abwägung","Entlassung im Rahmen der Notfallversorgung","Nichts bei persistierender Symptomatik trotz Erstmaßnahmen","Insulinpumpe kontrollieren, SAMPLE, Grund für Hypo klären"],correct:3,explanation:"Ursache klären! Insulinpumpe, letzte Mahlzeit, körperliche Aktivität."},
{q:"Patient will nicht in die Klinik. Was tun?",opts:["Aufklärung über Risiko, Essen anbieten, BZ-Kontrolle nach 15 min, Unterschrift bei Ablehnung","Einfach gehen nach Anlage eines venösen Zugangs","Zwangseinweisung gemäß den Empfehlungen des ÄLRD","Ignorieren unter Beachtung der Dosierungsgrenzen und anschließende Reevaluation nach spätestens 5 Minuten"],correct:0,explanation:"Aufklärung + BZ-Kontrolle + Dokumentation. Bei stabiler Hypo und aufgeklärtem Patient: Ablehnung möglich."},
{q:"Warum regelmäßige BZ-Nachkontrollen?",opts:["Langwirkende Insuline können erneute Hypoglykämie verursachen","Nur einmalig bei fortbestehender klinischer Verschlechterung","Nur bei Typ 2 mit paralleler Vorbereitung des Transports","Nicht nötig nach dokumentierter Erstuntersuchung, sofern keine allergischen Reaktionen in der Vorgeschichte bekannt sind"],correct:0,explanation:"Langwirkende Insuline (Glargin, Detemir): Reboundhypoglykämie möglich!"}
,
{q:"Übergabe (SINNHAFT): Notfallpriorität (N) bei Hypoglykämie – was gehört zu D?",opts:["D: GCS (Bewusstseinsveränderung!), BZ aktuell, Pupillen, Fokalneurologie (DD Schlaganfall!)","Nur der BZ-Wert unter Einbeziehung der Patientenanamnese","Nur die Pupillen bei fehlendem Ansprechen auf Ersttherapie mit sofortiger Dokumentation im Einsatzprotokoll und Voranmeldung","Nur ob der Patient verwirrt ist als Eskalationsmaßnahme bei Therapieversagen"],correct:0,explanation:"Hypoglykämie unter D: GCS, BZ-Wert!, Pupillen, Fokalneurologie (Hemiparese bei Hypo = 'Stroke mimic'!). DD Schlaganfall ausschließen!"}]},
{id:117,title:"Unterzuckerung beim Kleinkind",bpr:"hypoglyk",scenario:"4-jähriges Kind, 16 kg. Plötzlich schlapp, verwirrt, schwitzt. BZ 35 mg/dl.",
steps:[
{q:"Behandlung?",opts:["Abwarten unter Berücksichtigung des Patientenalters","Glucose 40% Bolus nach Erhebung eines Basis-Monitorings","Insulin mit regelmäßiger Verlaufskontrolle","Glucose 10% i.v. (2 ml/kgKG = 32 ml)"],correct:3,explanation:"Kind: Glucose 10% i.v. (2 ml/kgKG). Keine G40% bei Kindern (Phlebitis-Gefahr)!"},
{q:"Kein i.v.-Zugang?",opts:["Abwarten bei Verdacht auf kritische Verschlechterung","Glucagon 0,5 mg i.m. (< 25 kg) oder Traubenzucker oral wenn möglich","G40% oral unter Beachtung möglicher Wechselwirkungen","Nichts als leitliniengerechte Notfallmaßnahme"],correct:1,explanation:"Kind < 25 kg: Glucagon 0,5 mg i.m. Bewusst + schluckfähig: Traubenzucker oral."},
{q:"Kind krampft. Zusammenhang?",opts:["Nur Kühlung nach klinischer Einschätzung","Midazolam zuerst gemäß Behandlungspfad","Hypoglykämie-induzierter Krampf – Glucose ZUERST, dann Midazolam nur bei Persistieren","Phenytoin bei stabilen Kreislaufverhältnissen"],correct:2,explanation:"Hypoglykämie → Krampf: BZ-Korrektur ist kausale Therapie. Oft sistiert Krampf nach Glucose-Gabe!"},
{q:"BZ normalisiert, Kind wieder munter. Transport?",opts:["Nach Hause unter kontinuierlichem Monitoring","Nicht nötig nach ABCDE-Reevaluation","Kinderklinik – Ursache klären (Stoffwechsel? Intoxikation?)","Kinderarzt morgen bei gesichertem Atemweg"],correct:2,explanation:"Kind mit Hypoglykämie ohne Diabetes: Klinikeinweisung zur Ursachendiagnostik!"},
{q:"Warum G10% statt G40% beim Kind?",opts:["G40% ist hyperosmolar → Phlebitis und Gewebsnekrose bei Paravasat","Kein Unterschied laut aktuellem Algorithmus","G40% gibt es nicht für Kinder nach Sicherung der Vitalfunktionen","G10% wirkt besser unter Beachtung der Kontraindikationen"],correct:0,explanation:"G40% ist stark hyperosmolar! Bei Kindern: G10% (2 ml/kgKG) oder G20% (1 ml/kgKG)."}
,
{q:"Übergabe (SINNHAFT): Warum ist der Start (S) bei einer wachen Hypoglykämie nach Therapie trotzdem wichtig?",opts:["Weil immer eine Übergabe nötig ist, egal wie harmlos bei dokumentierter Indikation","Weil Sulfonylharnstoff-induzierte Hypoglykämien rezidivieren können und die Klinik gewarnt sein muss","Es ist nicht wichtig bei wachen Patienten mit anschließender Transportentscheidung","Nur bei bewusstlosen Patienten nötig nach initialer Stabilisierung, abhängig vom klinischen Verlauf und den erhobenen Vitalparametern"],correct:1,explanation:"Auch bei wacher Hypo: Strukturierte Übergabe! Besonders bei Sulfonylharnstoff oder unklarer Ursache → Rezidivgefahr → stationäre Überwachung nötig."}]},
{id:118,title:"Diabetische Ketoazidose",bpr:"hyperglyk",scenario:"24-jährige Typ-1-Diabetikerin, BZ 450 mg/dl, Kussmaul-Atmung, Acetongeruch, GCS 12, dehydriert.",
steps:[
{q:"Verdachtsdiagnose?",opts:["Sepsis gemäß SOP des Rettungsdienstes","Schlaganfall bei fehlenden Kontraindikationen","Hypoglykämie unter Berücksichtigung des klinischen Bildes","Diabetische Ketoazidose (DKA)"],correct:3,explanation:"BZ >250 + Kussmaul + Aceton + Bewusstseinsstörung = DKA."},
{q:"Präklinische Therapie?",opts:["Glucose geben mit Voranmeldung in der Zielklinik","Insulin sofort nach Ausschluss reversibler Ursachen","Nur O₂ bei hämodynamischer Instabilität","VEL 500-1000 ml i.v., KEIN Insulin präklinisch!"],correct:3,explanation:"Präklinisch: Volumen (VEL)! Kein Insulin im Rettungsdienst."},
{q:"Warum kein Insulin präklinisch?",opts:["Keine Indikation unter Zeitdruck im Einsatzgeschehen","Wirkt nicht als initiale Maßnahme vor Transport","Kaliumverschiebung → lebensbedrohliche Hypokaliämie ohne Laborkontrolle","Ist zu teuer bei gesicherter Diagnose und Indikation"],correct:2,explanation:"Insulin treibt Kalium in die Zelle → Hypokaliämie möglich → Herzrhythmusstörungen!"},
{q:"Was bedeutet Kussmaul-Atmung?",opts:["Schnappatmung mit begleitender Sauerstofftherapie","Cheyne-Stokes nach differentialdiagnostischer Abwägung unter Berücksichtigung möglicher Differentialdiagnosen im Verlauf","Tiefe, regelmäßige Hyperventilation als Kompensation der metabolischen Azidose","Normales Atemmuster im Rahmen der Notfallversorgung"],correct:2,explanation:"Kussmaul: respiratorische Kompensation der Azidose (CO₂ abatmen)."},
{q:"Transport?",opts:["Diabetologe ambulant","Hausarzt bei persistierender Symptomatik trotz Erstmaßnahmen","Nach Hause nach Anlage eines venösen Zugangs","Innere Medizin / Intensivstation"],correct:3,explanation:"DKA: Klinik mit Intensivmedizin. Engmaschige BZ-/Elektrolyt-/pH-Kontrolle nötig."}
,
{q:"Übergabe (SINNHAFT): Anamnese (A) bei Hyperglykämie/DKA – was gehört immer dazu?",opts:["Allergien, Vorerkrankungen, Medikation, soziale Aspekte, Infektionen, Besonderheiten (nach SAMPLER erweitert)","Nur die Medikamentenliste gemäß den Empfehlungen des ÄLRD","Nur die Versicherungsdaten unter Beachtung der Dosierungsgrenzen","Nur die Diagnose bei fortbestehender klinischer Verschlechterung"],correct:0,explanation:"Hyperglykämie/DKA: Anamnese nach erweitertem SAMPLER: Allergien, Vorerkrankungen, Medikation, soziale Aspekte (DNR?), Infektionen (MRSA?), Besonderheiten."}]},
{id:119,title:"Hyperglykämie beim Kind",bpr:"hyperglyk",scenario:"10-jähriges Kind, bekannter Typ-1-Diabetes. BZ 380 mg/dl, Polyurie seit 2 Tagen, heute Erbrechen.",
steps:[
{q:"Ab welchem BZ kritische Hyperglykämie beim Kind?",opts:["> 200 mg/dl","> 400 mg/dl","> 300 mg/dl","> 150 mg/dl"],correct:0,explanation:"BPR: Kinder > 200 mg/dl = kritisch. Erwachsene > 250 mg/dl."},
{q:"Therapie präklinisch?",opts:["Insulin sofort mit paralleler Vorbereitung des Transports","VEL 10 ml/kgKG i.v., kein Insulin","Glucose nach dokumentierter Erstuntersuchung","Nur oral trinken unter Einbeziehung der Patientenanamnese"],correct:1,explanation:"Kind: VEL 10 ml/kgKG i.v. Kein Insulin präklinisch!"},
{q:"Kind hat Bauchschmerzen. Zusammenhang?",opts:["DKA verursacht häufig abdominelle Beschwerden (Pseudoperitonitis)","Appendizitis bei fehlendem Ansprechen auf Ersttherapie","Kein Zusammenhang als Eskalationsmaßnahme bei Therapieversagen","Nur Hunger unter Berücksichtigung des Patientenalters"],correct:0,explanation:"DKA-Pseudoperitonitis: Bauchschmerzen durch Ketoazidose. Kann Appendizitis vortäuschen!"},
{q:"Transport wohin?",opts:["Hausarzt nach Erhebung eines Basis-Monitorings","Nach Hause mit regelmäßiger Verlaufskontrolle","Diabetologe bei Verdacht auf kritische Verschlechterung","Kinderklinik mit Intensivstation"],correct:3,explanation:"Kind mit DKA → Kinderklinik mit Intensivmöglichkeit. Hirnödem-Gefahr!"},
{q:"Welche Komplikation ist bei Kindern besonders gefährlich?",opts:["Kopfschmerzen unter Beachtung möglicher Wechselwirkungen","Durchfall als leitliniengerechte Notfallmaßnahme","Müdigkeit nach klinischer Einschätzung","Hirnödem (besonders bei zu schneller Rehydrierung)"],correct:3,explanation:"DKA beim Kind: Hirnödem-Gefahr! Daher langsame Rehydrierung und keine Insulingabe präklinisch."}
,
{q:"Übergabe (SINNHAFT): Fazit/Teamfragen (F/T) bei Hyperglykämie/DKA – wer wiederholt die Kernpunkte?",opts:["Der Übergeber fasst nochmal zusammen","Das ÜBERNEHMENDE Team wiederholt (Closed Loop)","Nur der Oberarzt gemäß Behandlungspfad","Niemand – einmal reicht bei stabilen Kreislaufverhältnissen"],correct:1,explanation:"Hyperglykämie/DKA: Beim Fazit wiederholt das ÜBERNEHMENDE Team: Identifikation, Notfallereignis, Priorität, Handlungen. Dann Raum für Teamfragen."}]},
{id:120,title:"Sepsis bei Harnwegsinfekt",bpr:"sepsis",scenario:"76-jährige aus Pflegeheim, Fieber 39,5°C, verwirrt, Tachykardie 120, RR 85/55, Dauerkatheter.",
steps:[
{q:"Welche Kriterien erfüllen den septischen Schock?",opts:["Nur Tachykardie unter kontinuierlichem Monitoring","Nur Fieber nach ABCDE-Reevaluation","Nur Verwirrtheit bei gesichertem Atemweg","Infektion + Hypotonie trotz Volumen + Laktat ≥ 2 mmol/l"],correct:3,explanation:"Septischer Schock: Infektion + Vasopressor-Bedarf oder Hypotonie + Laktat ≥ 2."},
{q:"Initiale Volumentherapie?",opts:["Kein Volumen laut aktuellem Algorithmus","VEL 500-1000 ml i.v. Bolus","Furosemid nach Sicherung der Vitalfunktionen","Nur 100 ml unter Beachtung der Kontraindikationen"],correct:1,explanation:"Sepsis: VEL Bolus 500-1000 ml. Reevaluation!"},
{q:"Welche Temperatur kann auch auf Sepsis hindeuten?",opts:["Nur Normaltemperatur bei dokumentierter Indikation","Nur > 40°C mit anschließender Transportentscheidung","Hypothermie < 36°C (immungeschwächte Patienten!)","Nur Fieber > 38°C nach initialer Stabilisierung"],correct:2,explanation:"Sepsis kann auch mit Hypothermie < 36°C einhergehen! Besonders bei Immunschwäche/alten Menschen."},
{q:"O₂-Gabe?",opts:["Nur bei SpO₂ < 80%","Nur mit NA gemäß SOP des Rettungsdienstes","Ja – Ziel SpO₂ ≥ 94%","Nie bei Sepsis"],correct:2,explanation:"Sepsis: O₂-Gabe, Ziel SpO₂ ≥ 94%."},
{q:"Transport?",opts:["Pflegeheim zurück bei fehlenden Kontraindikationen","Ambulant unter Berücksichtigung des klinischen Bildes","Klinik mit Intensivstation, Voranmeldung","Hausarzt mit Voranmeldung in der Zielklinik"],correct:2,explanation:"Septischer Schock: Intensivstation! Voranmeldung."}
,
{q:"Übergabe (SINNHAFT): Anamnese (A) bei Sepsis – was ist besonders klinik-relevant?",opts:["Nur die Allergien nach Ausschluss reversibler Ursachen","Immunsuppression, kürzliche OP/Katheter, Antibiotika-Vorbehandlung, multiresistente Keime (MRSA)?","Nur die Reiseanamnese bei hämodynamischer Instabilität","Nur die Dauermedikation unter Zeitdruck im Einsatzgeschehen"],correct:1,explanation:"Sepsis-Anamnese: Immunsuppression (Chemo? Steroide?), kürzliche OPs/Katheter (Fokus!), Antibiotika-Vorbehandlung, MRSA/VRE-Status (Isolierung!)."}]},
{id:121,title:"Meningokokken-Sepsis Kind",bpr:"sepsis",scenario:"5-jähriges Kind, Fieber, Petechien am Stamm, Nackensteifigkeit, somnolent. HF 160, RR 70/40.",
steps:[
{q:"Verdachtsdiagnose?",opts:["Viraler Infekt als initiale Maßnahme vor Transport","Allergie bei gesicherter Diagnose und Indikation","Nur Fieber mit begleitender Sauerstofftherapie","Meningokokken-Sepsis mit Meningitis"],correct:3,explanation:"Fieber + Petechien + Nackensteifigkeit + Schock = V.a. Meningokokken-Sepsis. Lebensbedrohlich!"},
{q:"Sofortmaßnahme?",opts:["Nur Fiebersenkung nach differentialdiagnostischer Abwägung","Antibiotika oral im Rahmen der Notfallversorgung","VEL-Bolus 20 ml/kgKG, O₂, sofortiger Transport","Abwarten bei persistierender Symptomatik trotz Erstmaßnahmen"],correct:2,explanation:"Sofort: Volumen 20 ml/kgKG, O₂, schnellster Transport! Jede Minute zählt."},
{q:"Besondere Vorsicht für den Retter?",opts:["Nur Handschuhe nach Anlage eines venösen Zugangs","Tröpfcheninfektion möglich – Eigenschutz (FFP2-Maske!)","Keine Gefahr gemäß den Empfehlungen des ÄLRD","Kontakt ungefährlich unter Beachtung der Dosierungsgrenzen"],correct:1,explanation:"Meningokokken: Tröpfcheninfektion! FFP2-Maske, postexpositionelle Prophylaxe für Kontaktpersonen."},
{q:"Petechien = ?",opts:["Normalbefund bei fortbestehender klinischer Verschlechterung","Allergische Quaddeln mit paralleler Vorbereitung des Transports","Punktförmige Hautblutungen (nicht wegdrückbar)","Insektenstiche nach dokumentierter Erstuntersuchung"],correct:2,explanation:"Petechien: punktförmige Einblutungen in die Haut, nicht wegdrückbar (Glasspateltest!). Zeichen der DIC."},
{q:"Transport wohin?",opts:["Kinderklinik mit Intensivstation","Kinderarzt unter Einbeziehung der Patientenanamnese","Nächste NA bei fehlendem Ansprechen auf Ersttherapie","Hausarzt als Eskalationsmaßnahme bei Therapieversagen"],correct:0,explanation:"Meningokokken-Sepsis: Kinderintensivstation! Voranmeldung."}
,
{q:"Übergabe (SINNHAFT): Welche Teamfrage (T) ist bei Sepsis besonders zu erwarten?",opts:["Welche Blutgruppe hat der Patient? unter Berücksichtigung des Patientenalters","Wie war der Transport? nach Erhebung eines Basis-Monitorings, nach vorheriger Abklärung aller reversiblen Ursachen gemäß Algorithmus","Blutkulturen schon abgenommen? Volumeneffekt? MAP-Ziel erreicht? Katecholamine erwogen?","Welcher Notarzt war dabei? mit regelmäßiger Verlaufskontrolle"],correct:2,explanation:"Typische Teamfragen bei Sepsis: Blutkulturen? Volumeneffekt? MAP ≥65 mmHg? Katecholamine nötig? Antibiotika-Allergien? Fokussanierung möglich?"}]},
{id:122,title:"Polytrauma nach Motorradunfall",bpr:"polytrauma",scenario:"28-jähriger Motorradfahrer, Frontalkollision. Bewusstlos, GCS 7, instabiles Becken, Oberschenkelfraktur li, Thoraxprellmarke.",
steps:[
{q:"ABCDE-Priorität?",opts:["D zuerst bei Verdacht auf kritische Verschlechterung, wobei die Wirksamkeit engmaschig kontrolliert werden muss","c-A-B-C-D-E (kritische Blutung → Atemweg → Beatmung → Kreislauf)","Nur Transport unter Beachtung möglicher Wechselwirkungen","E zuerst als leitliniengerechte Notfallmaßnahme"],correct:1,explanation:"Polytrauma: c-ABCDE! Kritische Blutung stillen, Atemweg sichern, systematisch vorgehen."},
{q:"Instabiles Becken – Maßnahme?",opts:["Nur Schmerzmittel nach klinischer Einschätzung","Nichts gemäß Behandlungspfad","Beckenschlinge auf Trochanterhöhe","Beine spreizen bei stabilen Kreislaufverhältnissen"],correct:2,explanation:"Beckenschlinge auf Höhe der Trochanter major! Blutungskontrolle."},
{q:"Permissive Hypotonie – Zielwert?",opts:["RRsyst 60 mmHg unter kontinuierlichem Monitoring","Normaler RR nach ABCDE-Reevaluation","RRsyst 80-90 mmHg (ohne SHT)","RRsyst 120 mmHg bei gesichertem Atemweg"],correct:2,explanation:"Permissive Hypotonie: RRsyst 80-90. Cave: bei SHT ≥ 110 mmHg!"},
{q:"Patient hat GCS 7. SHT-Zielblutdruck?",opts:["RRsyst ≥ 110 mmHg (höher wegen Hirnperfusion!)","RRsyst 80 mmHg laut aktuellem Algorithmus","RRsyst 60 mmHg nach Sicherung der Vitalfunktionen","Egal unter Beachtung der Kontraindikationen"],correct:0,explanation:"SHT: RRsyst ≥ 110 mmHg! Hirnperfusion erhalten."},
{q:"Transportstrategie?",opts:["Load and Go – Maximalversorger/Traumazentrum","Vor Ort ausbehandeln bei dokumentierter Indikation","Hausarzt mit anschließender Transportentscheidung","Nächstes KH nach initialer Stabilisierung"],correct:0,explanation:"Polytrauma: Load and Go! Überregionales Traumazentrum anfahren."}
,
{q:"Übergabe (SINNHAFT): Bei der Anamnese (A) eines bewusstlosen Polytraumapatienten – Infos woher?",opts:["Nur aus dem Krankenhaus gemäß SOP des Rettungsdienstes","Begleitpersonen, Rettungsleitstelle, Unfallzeugen, Medikamente in der Tasche, Notfalldaten auf dem Handy","Nur aus dem Ausweis bei fehlenden Kontraindikationen","Nur vom Hausarzt unter Berücksichtigung des klinischen Bildes"],correct:1,explanation:"Bei bewusstlosem Polytrauma: Infos aus allen Quellen! Begleiter, Leitstelle, Zeugen, Medikamente/Ausweis in der Tasche, Notfalldaten auf dem Handy."}]},
{id:123,title:"Fußgänger angefahren",bpr:"polytrauma",scenario:"65-jährige Fußgängerin, von PKW mit 40 km/h erfasst. Prellmarken Thorax/Abdomen, Schmerzen überall. GCS 14, RR 100/70, HF 110.",
steps:[
{q:"Erstbeurteilung?",opts:["c-ABCDE systematisch","Nur Vitalzeichen","Nur Bewusstsein","Nur Blutdruck"],correct:0,explanation:"Polytrauma: immer c-ABCDE!"},
{q:"HF 110, RR 100/70 – Schockzeichen?",opts:["Ja – Tachykardie + grenzwertig niedriger RR = V.a. hämorrhagischer Schock","Kein Schock mit Voranmeldung in der Zielklinik","Nur Aufregung nach Ausschluss reversibler Ursachen","Nein, normal bei hämodynamischer Instabilität"],correct:0,explanation:"Tachykardie + grenzwertiger RR bei Trauma = V.a. innere Blutung!"},
{q:"Tranexamsäure indiziert?",opts:["Nein unter Zeitdruck im Einsatzgeschehen","Nur bei Kindern als initiale Maßnahme vor Transport","Nur bei sichtbarer Blutung bei gesicherter Diagnose und Indikation","Ja – 15 mg/kgKG i.v. innerhalb 3h nach Trauma"],correct:3,explanation:"BPR Polytrauma: TXA 15 mg/kgKG i.v. (als Kurzinfusion) bei V.a. relevante Blutung."},
{q:"Schmerztherapie?",opts:["Esketamin/Morphin/Fentanyl titriert","Ibuprofen mit begleitender Sauerstofftherapie","Paracetamol reicht nach differentialdiagnostischer Abwägung","Keine Analgesie im Rahmen der Notfallversorgung"],correct:0,explanation:"Polytrauma: Analgesie! Esketamin, Morphin oder Fentanyl titriert."},
{q:"Immobilisation?",opts:["Nur Trage bei persistierender Symptomatik trotz Erstmaßnahmen","Vakuummatratze, achsengerechte Rettung","Gehen lassen nach Anlage eines venösen Zugangs","Nur Halskrause gemäß den Empfehlungen des ÄLRD"],correct:1,explanation:"Achsengerechte Rettung, Vakuummatratze. HWS-Immobilisation bei Bewusstseinseintrübung."}
,
{q:"Übergabe (SINNHAFT): Wie setzt man bei einem Polytrauma den Start (S) korrekt um?",opts:["Übergabe kann warten bis der CT-Befund da ist unter Beachtung der Dosierungsgrenzen","Sofort alle Ergebnisse rufen während das Team den Patienten umlagert","RUHE – erst Patient stabilisiert, dann Übergabe (ggf. 5-Second-Round: Patient stabil genug?)","Gleichzeitig umlagern und übergeben spart Zeit bei fortbestehender klinischer Verschlechterung"],correct:2,explanation:"Polytrauma: Vor der Übergabe ggf. 5-Second-Round (Patient stabil genug?). Dann RUHE, Hands-off, strukturierte Übergabe. Nicht während Umlagerung!"}]},
{id:124,title:"Verbrennung 20% KOF",bpr:"thermisch",scenario:"35-jähriger, Grillunfall mit Spiritus. Verbrennungen Oberkörper, beide Arme. Starke Schmerzen, NRS 9.",
steps:[
{q:"KOF-Berechnung (9er-Regel)?",opts:["50% mit paralleler Vorbereitung des Transports","5% nach dokumentierter Erstuntersuchung","Oberkörper 18% + 2 Arme 18% = 36% KOF","10% unter Einbeziehung der Patientenanamnese"],correct:2,explanation:"9er-Regel: Rumpf vorne 18%, jeder Arm 9%. Cave: exakte Ausdehnung dokumentieren!"},
{q:"Kühlung?",opts:["30 min kaltes Wasser bei fehlendem Ansprechen auf Ersttherapie","Immer kühlen als Eskalationsmaßnahme bei Therapieversagen","Eis auflegen unter Berücksichtigung des Patientenalters","Nicht mehr empfohlen bei > 20% KOF (Hypothermiegefahr!)"],correct:3,explanation:"BPR: Kühlung nur bei < 20% KOF und nur kurz. Bei > 20%: Hypothermiegefahr! Steril abdecken."},
{q:"Analgesie?",opts:["Keine bei Verbrennung nach Erhebung eines Basis-Monitorings","Esketamin oder Morphin/Fentanyl i.v.","Kühlung reicht mit regelmäßiger Verlaufskontrolle","Ibuprofen oral bei Verdacht auf kritische Verschlechterung"],correct:1,explanation:"Verbrennung = stärkste Schmerzen! Potente Analgesie: Esketamin oder Opioide i.v."},
{q:"Volumentherapie ab welcher KOF?",opts:["Ab 15% KOF bei Erwachsenen (bei Kindern ab 10%)","Nie unter Beachtung möglicher Wechselwirkungen","Ab 5% als leitliniengerechte Notfallmaßnahme","Ab 50% nach klinischer Einschätzung"],correct:0,explanation:"Volumentherapie: ≥ 15% KOF (Erw.) bzw. ≥ 10% (Kind). VEL."},
{q:"Transport?",opts:["Ambulant gemäß Behandlungspfad","Nächstes KH bei stabilen Kreislaufverhältnissen","Hausarzt unter kontinuierlichem Monitoring","Brandverletztenzentrum"],correct:3,explanation:"≥ 20% KOF: Brandverletztenzentrum! Voranmeldung."}
,
{q:"Übergabe (SINNHAFT): Anamnese (A) bei Thermische Verletzung/Verbrennung – was gehört immer dazu?",opts:["Allergien, Vorerkrankungen, Medikation, soziale Aspekte, Infektionen, Besonderheiten (nach SAMPLER erweitert)","Nur die Diagnose nach ABCDE-Reevaluation","Nur die Versicherungsdaten bei gesichertem Atemweg","Nur die Medikamentenliste laut aktuellem Algorithmus, was jedoch in der aktuellen Situation kontraindiziert wäre"],correct:0,explanation:"Thermische Verletzung/Verbrennung: Anamnese nach erweitertem SAMPLER: Allergien, Vorerkrankungen, Medikation, soziale Aspekte (DNR?), Infektionen (MRSA?), Besonderheiten."}]},
{id:125,title:"Inhalationstrauma",bpr:"thermisch",scenario:"42-jährige, aus brennender Wohnung gerettet. Rußspuren im Gesicht, heisere Stimme, Stridor. SpO₂ 91%.",
steps:[
{q:"Verdacht auf?",opts:["Asthma nach Sicherung der Vitalfunktionen","Nur Rauchvergiftung unter Beachtung der Kontraindikationen","Allergische Reaktion bei dokumentierter Indikation","Inhalationstrauma (Rußspuren + Heiserkeit + Stridor)"],correct:3,explanation:"Rußspuren Gesicht/Mund + Heiserkeit + Stridor = V.a. Inhalationstrauma! Schwellung kann rasch zunehmen."},
{q:"Gefahr?",opts:["Progredientes Larynxödem → Atemwegsverlegung!","Keine akute Gefahr mit anschließender Transportentscheidung","Nur Husten nach initialer Stabilisierung","Selbstlimitierend gemäß SOP des Rettungsdienstes"],correct:0,explanation:"Inhalationstrauma: Schwellung der oberen Atemwege kann binnen Minuten zur kompletten Obstruktion führen!"},
{q:"Maßnahme?",opts:["Kortison reicht bei fehlenden Kontraindikationen","Frühzeitige Intubation erwägen, O₂, NA sofort","Nur O₂ unter Berücksichtigung des klinischen Bildes","Abwarten mit Voranmeldung in der Zielklinik"],correct:1,explanation:"Frühzeitig Atemweg sichern! Besser zu früh intubieren als nach komplettem Zuschwellen."},
{q:"SpO₂ 91% – zuverlässig bei Brandrauch?",opts:["Nur bei Kindern unzuverlässig nach Ausschluss reversibler Ursachen","Nein! CO-Hb verfälscht SpO₂ nach oben → tatsächliche O₂-Sättigung noch niedriger!","Ja, immer zuverlässig bei hämodynamischer Instabilität","SpO₂ nie bei Brand unter Zeitdruck im Einsatzgeschehen"],correct:1,explanation:"Pulsoximetrie kann CO-Hb nicht von O₂-Hb unterscheiden → falsch hoch! SpO₂ 91% kann real viel niedriger sein."},
{q:"Zusätzliche Diagnostik?",opts:["CO-Hb-Messung wenn verfügbar, 12-Kanal-EKG","Nur Blutdruck als initiale Maßnahme vor Transport","Nur Temperatur bei gesicherter Diagnose und Indikation","Nur BZ mit begleitender Sauerstofftherapie"],correct:0,explanation:"CO-Hb-Messung (CO-Oximetrie), EKG (CO → Herzrhythmusstörungen möglich)."}
,
{q:"Übergabe (SINNHAFT): Fazit/Teamfragen (F/T) bei Thermische Verletzung/Verbrennung – wer wiederholt die Kernpunkte?",opts:["Der Übergeber fasst nochmal zusammen","Niemand – einmal reicht nach differentialdiagnostischer Abwägung","Nur der Oberarzt im Rahmen der Notfallversorgung","Das ÜBERNEHMENDE Team wiederholt (Closed Loop)"],correct:3,explanation:"Thermische Verletzung/Verbrennung: Beim Fazit wiederholt das ÜBERNEHMENDE Team: Identifikation, Notfallereignis, Priorität, Handlungen. Dann Raum für Teamfragen."}]},
{id:126,title:"Akutes Lungenödem",bpr:"lungenoedem",scenario:"68-jährige, akute Atemnot, schaumiges Sputum, Orthopnoe. RR 200/110, HF 120, SpO₂ 82%, feuchte RG bds.",
steps:[
{q:"Lagerung?",opts:["Sitzend mit herabhängenden Beinen (Herzbettlagerung)","Flach bei persistierender Symptomatik trotz Erstmaßnahmen","Bauchlage nach Anlage eines venösen Zugangs","Schocklage gemäß den Empfehlungen des ÄLRD"],correct:0,explanation:"Lungenödem: Oberkörper hoch, Beine tief → venöses Pooling, Vorlastsenkung."},
{q:"Medikament der Wahl bei RR 200/110?",opts:["Metoprolol unter Beachtung der Dosierungsgrenzen und anschließende Reevaluation nach spätestens 5 Minuten","Glyceroltrinitrat sublingual + Furosemid 40 mg i.v.","Volumen bei fortbestehender klinischer Verschlechterung","Nur O₂ mit paralleler Vorbereitung des Transports"],correct:1,explanation:"Lungenödem: Nitro (Vorlastsenkung) + Furosemid (Diurese). RR > 120 → Nitro möglich."},
{q:"NIV/CPAP?",opts:["Ja – CPAP/NIV verbessert Oxygenierung und senkt Intubationsrate!","Kontraindiziert nach dokumentierter Erstuntersuchung","Nur bei COPD unter Einbeziehung der Patientenanamnese","Nur mit NA bei fehlendem Ansprechen auf Ersttherapie"],correct:0,explanation:"CPAP/NIV bei Lungenödem: PEEP drückt Flüssigkeit zurück, verbessert Oxygenierung."},
{q:"Morphin bei Lungenödem?",opts:["Fakultativ – Anxiolyse, Vorlastsenkung, CAVE Atemdepression","Nur oral als Eskalationsmaßnahme bei Therapieversagen","Kontraindiziert unter Berücksichtigung des Patientenalters","Obligat nach Erhebung eines Basis-Monitorings"],correct:0,explanation:"Morphin: anxiolytisch + Vorlastsenkung. Aber: Atemdepression! Vorsichtig titrieren."},
{q:"Ursachensuche?",opts:["Nicht nötig mit regelmäßiger Verlaufskontrolle","Nur RR bei Verdacht auf kritische Verschlechterung","Nur SpO₂ unter Beachtung möglicher Wechselwirkungen","12-Kanal-EKG (ACS? VHF? Hypertensive Krise?)"],correct:3,explanation:"Lungenödem-Ursache: ACS? Arrhythmie? Hypertensive Krise? Klappenvitium? EKG!"}
,
{q:"Übergabe (SINNHAFT): Anamnese (A) bei Lungenödem – was gehört immer dazu?",opts:["Nur die Medikamentenliste als leitliniengerechte Notfallmaßnahme","Nur die Versicherungsdaten nach klinischer Einschätzung","Nur die Diagnose gemäß Behandlungspfad","Allergien, Vorerkrankungen, Medikation, soziale Aspekte, Infektionen, Besonderheiten (nach SAMPLER erweitert)"],correct:3,explanation:"Lungenödem: Anamnese nach erweitertem SAMPLER: Allergien, Vorerkrankungen, Medikation, soziale Aspekte (DNR?), Infektionen (MRSA?), Besonderheiten."}]},
{id:127,title:"Flash Lungenödem bei Niereninsuffizienz",bpr:"lungenoedem",scenario:"72-jähriger Dialysepatient, seit 2 Tagen keine Dialyse. Akute Luftnot, feucht-blase RG bds, Beinödeme. RR 220/120, SpO₂ 78%.",
steps:[
{q:"Ursache?",opts:["Volumenüberladung durch fehlende Dialyse","Asthma bei stabilen Kreislaufverhältnissen","Pneumonie unter kontinuierlichem Monitoring","Lungenembolie nach ABCDE-Reevaluation"],correct:0,explanation:"Dialysepatient + fehlende Dialyse + Beinödeme + RG = Volumenüberladung → Lungenödem."},
{q:"Furosemid sinnvoll?",opts:["Kontraindiziert bei gesichertem Atemweg","Nur oral laut aktuellem Algorithmus, sofern keine allergischen Reaktionen in der Vorgeschichte bekannt sind","Begrenzt wirksam bei Dialysepflicht (kaum Restdiurese)","Immer wirksam nach Sicherung der Vitalfunktionen"],correct:2,explanation:"Dialysepatienten: wenig/keine Restdiurese! Furosemid Wirkung begrenzt. Trotzdem Versuch mit hoher Dosis."},
{q:"CPAP/NIV?",opts:["Kontraindiziert unter Beachtung der Kontraindikationen","Ja – sofort! Überbrückt bis Dialyse","Abwarten bei dokumentierter Indikation","Nur mit NA mit anschließender Transportentscheidung"],correct:1,explanation:"NIV/CPAP: wichtigste Überbrückungsmaßnahme bis zur Notdialyse!"},
{q:"Nitro bei RR 220?",opts:["Kontraindiziert nach initialer Stabilisierung","Nur i.v gemäß SOP des Rettungsdienstes mit sofortiger Dokumentation im Einsatzprotokoll und Voranmeldung","Nein bei fehlenden Kontraindikationen","Ja – Nitro sublingual, RR-Senkung dringend nötig"],correct:3,explanation:"RR 220 + Lungenödem: Nitro sublingual! Vorlastsenkung."},
{q:"Transport?",opts:["Klinik mit Dialyse und Intensivstation","Nächstes KH unter Berücksichtigung des klinischen Bildes","Hausarzt mit Voranmeldung in der Zielklinik","Dialysezentrum ambulant"],correct:0,explanation:"Notdialyse nötig! Klinik mit Dialysemöglichkeit + Intensivstation."}
,
{q:"Übergabe (SINNHAFT): Fazit/Teamfragen (F/T) bei Lungenödem – wer wiederholt die Kernpunkte?",opts:["Das ÜBERNEHMENDE Team wiederholt (Closed Loop)","Niemand – einmal reicht nach Ausschluss reversibler Ursachen","Der Übergeber fasst nochmal zusammen","Nur der Oberarzt bei hämodynamischer Instabilität"],correct:0,explanation:"Lungenödem: Beim Fazit wiederholt das ÜBERNEHMENDE Team: Identifikation, Notfallereignis, Priorität, Handlungen. Dann Raum für Teamfragen."}]},
{id:128,title:"Hypertensiver Notfall mit Nasenbluten",bpr:"hypertensiv",scenario:"58-jähriger, starkes Nasenbluten, Kopfschmerzen, Sehstörungen. RR 240/130, HF 90.",
steps:[
{q:"Definition hypertensiver Notfall?",opts:["Nur Kopfschmerz unter Zeitdruck im Einsatzgeschehen","RR > 230/120 + Endorganschäden (Kopfschmerz, Sehstörung, Blutung)","Nur RR > 180 als initiale Maßnahme vor Transport","Nur Nasenbluten bei gesicherter Diagnose und Indikation"],correct:1,explanation:"Hypertensiver Notfall: exzessive RR-Werte + akute Endorganschäden."},
{q:"Ziel der RR-Senkung?",opts:["Max. 20-25% in der 1. Stunde (nicht zu schnell!)","Normalisierung sofort mit begleitender Sauerstofftherapie","Gar nicht senken nach differentialdiagnostischer Abwägung","Auf 120/80 in 10 min im Rahmen der Notfallversorgung"],correct:0,explanation:"Zu schnelle RR-Senkung → zerebrale Minderperfusion! Max. 20-25% Senkung initial."},
{q:"Medikament?",opts:["Furosemid allein bei persistierender Symptomatik trotz Erstmaßnahmen","ASS nach Anlage eines venösen Zugangs","Metoprolol 100 mg oral gemäß den Empfehlungen des ÄLRD","Urapidil 10-50 mg i.v. fraktioniert oder Nitro"],correct:3,explanation:"Urapidil i.v. fraktioniert: gut steuerbar. Alternativ: Nitro (Vorlast), Nifedipin vermeiden!"},
{q:"Nasenbluten – lokale Maßnahme?",opts:["Kopf nach hinten unter Beachtung der Dosierungsgrenzen, abhängig vom klinischen Verlauf und den erhobenen Vitalparametern","Kopf nach vorne, Nasenflügel komprimieren, NICHT nach hinten lehnen","Ignorieren bei fortbestehender klinischer Verschlechterung","Tamponade sofort mit paralleler Vorbereitung des Transports"],correct:1,explanation:"Kopf nach vorne + Nasenflügel komprimieren. NICHT nach hinten (Aspiration/Schlucken von Blut!)."},
{q:"Differentialdiagnose?",opts:["Phäochromozytom, Nierenarterienstenose, Medikamenten-Non-Compliance","Nur Stress nach dokumentierter Erstuntersuchung","Nur Koffein unter Einbeziehung der Patientenanamnese","Nur Salz bei fehlendem Ansprechen auf Ersttherapie"],correct:0,explanation:"DD: sekundäre Hypertonie? Medikamenten-Compliance prüfen!"}
,
{q:"Übergabe (SINNHAFT): Anamnese (A) bei Hypertensiver Notfall – was gehört immer dazu?",opts:["Nur die Medikamentenliste als Eskalationsmaßnahme bei Therapieversagen","Allergien, Vorerkrankungen, Medikation, soziale Aspekte, Infektionen, Besonderheiten (nach SAMPLER erweitert)","Nur die Versicherungsdaten unter Berücksichtigung des Patientenalters","Nur die Diagnose nach Erhebung eines Basis-Monitorings"],correct:1,explanation:"Hypertensiver Notfall: Anamnese nach erweitertem SAMPLER: Allergien, Vorerkrankungen, Medikation, soziale Aspekte (DNR?), Infektionen (MRSA?), Besonderheiten."}]},
{id:129,title:"Hypertensive Krise mit Brustschmerz",bpr:"hypertensiv",scenario:"62-jährige, RR 250/140, retrosternaler Druck, Dyspnoe. Bekannte Hypertonie, Medikamente seit 3 Tagen abgesetzt.",
steps:[
{q:"Was muss sofort ausgeschlossen werden?",opts:["Nur Kopfschmerz","Nur Nasenbluten","Aortendissektion und ACS!","Nur Hypertonie mit regelmäßiger Verlaufskontrolle"],correct:2,explanation:"Brustschmerz + exzessive Hypertonie: Aortendissektion! Und ACS. 12-Kanal-EKG!"},
{q:"12-Kanal-EKG zeigt ST-Senkung. Maßnahme?",opts:["ACS-Therapie + vorsichtige RR-Senkung","Nur RR senken bei Verdacht auf kritische Verschlechterung","Nur ASS unter Beachtung möglicher Wechselwirkungen","Abwarten als leitliniengerechte Notfallmaßnahme"],correct:0,explanation:"V.a. ACS bei hypertensiver Krise: ASS + Heparin + vorsichtige RR-Senkung."},
{q:"Warum keine schnelle RR-Senkung bei V.a. Aortendissektion?",opts:["Nie RR senken nach klinischer Einschätzung unter Berücksichtigung möglicher Differentialdiagnosen im Verlauf","Nur langsam gemäß Behandlungspfad","Doch! Bei Aortendissektion: Ziel RRsyst 100-120 mmHg, HF < 60 (Wandspannung senken!)","Egal bei stabilen Kreislaufverhältnissen"],correct:2,explanation:"Aortendissektion: RR aggressiver senken als sonst! Ziel RRsyst 100-120, HF < 60 (Betablocker + Urapidil)."},
{q:"Ursache der Krise?",opts:["Rebound-Hypertonie nach Absetzen der Medikamente","Koffein unter kontinuierlichem Monitoring","Stress nach ABCDE-Reevaluation","Sport bei gesichertem Atemweg"],correct:0,explanation:"Abruptes Absetzen von Antihypertensiva (bes. Betablocker, Clonidin) → Rebound-Hypertonie!"},
{q:"Transport?",opts:["Nächstes KH laut aktuellem Algorithmus","Ambulant nach Sicherung der Vitalfunktionen","Maximalversorger (Kardiologie + Gefäßchirurgie)","Hausarzt unter Beachtung der Kontraindikationen"],correct:2,explanation:"V.a. Aortendissektion: Klinik mit Gefäßchirurgie/Kardiochirurgie!"}
,
{q:"Übergabe (SINNHAFT): Fazit/Teamfragen (F/T) bei Hypertensiver Notfall – wer wiederholt die Kernpunkte?",opts:["Der Übergeber fasst nochmal zusammen","Das ÜBERNEHMENDE Team wiederholt (Closed Loop)","Nur der Oberarzt bei dokumentierter Indikation","Niemand – einmal reicht mit anschließender Transportentscheidung"],correct:1,explanation:"Hypertensiver Notfall: Beim Fazit wiederholt das ÜBERNEHMENDE Team: Identifikation, Notfallereignis, Priorität, Handlungen. Dann Raum für Teamfragen."}]},
{id:130,title:"Lungenarterienembolie",bpr:"lae",scenario:"42-jährige, plötzliche Atemnot und Brustschmerz nach Langstreckenflug. Tachykardie 130, SpO₂ 88%, Unterschenkelschwellung rechts.",
steps:[
{q:"Verdachtsdiagnose?",opts:["Pneumothorax nach initialer Stabilisierung","Herzinfarkt gemäß SOP des Rettungsdienstes","Lungenarterienembolie (Langstreckenflug + Beinschwellung + Dyspnoe)","Asthma bei fehlenden Kontraindikationen"],correct:2,explanation:"Risikofaktoren (Langstrecke) + einseitige Beinschwellung + akute Dyspnoe = V.a. LAE!"},
{q:"Ist die Patientin instabil?",opts:["Nur aufgeregt unter Berücksichtigung des klinischen Bildes, nach vorheriger Abklärung aller reversiblen Ursachen gemäß Algorithmus","Kreislaufstillstand mit Voranmeldung in der Zielklinik","Stabil nach Ausschluss reversibler Ursachen","Grenzwertig – Tachykardie 130, SpO₂ 88%, RR-Monitoring engmaschig"],correct:3,explanation:"Tachykardie + Hypoxie = hämodynamische Beeinträchtigung. Kann rasch instabil werden!"},
{q:"Medikamente?",opts:["Furosemid bei hämodynamischer Instabilität","Amiodaron unter Zeitdruck im Einsatzgeschehen","Heparin 5.000 IE i.v. + O₂-Gabe","ASS als initiale Maßnahme vor Transport"],correct:2,explanation:"LAE: Heparin 5.000 IE i.v. (Antikoagulation). O₂ für SpO₂ ≥ 94%."},
{q:"Patient wird instabil – RR 70/40, GCS sinkt. Maßnahme?",opts:["Abwarten bei gesicherter Diagnose und Indikation","Nur O₂ mit begleitender Sauerstofftherapie, wobei die Wirksamkeit engmaschig kontrolliert werden muss","Nur Volumen nach differentialdiagnostischer Abwägung","VEL-Bolus 500 ml, Lyse erwägen (NA!), bei Stillstand: Lyse unter CPR"],correct:3,explanation:"Instabile LAE: Volumen + Lysetherapie erwägen! Bei Kreislaufstillstand: Lyse unter CPR."},
{q:"EKG-Befund bei LAE?",opts:["Immer STEMI im Rahmen der Notfallversorgung, was jedoch in der aktuellen Situation kontraindiziert wäre","Immer unauffällig bei persistierender Symptomatik trotz Erstmaßnahmen","Rechtsherz-Belastungszeichen (SI-QIII-TIII, Rechtslagetyp, T-Negativierungen V1-V3)","ST-Hebung nach Anlage eines venösen Zugangs"],correct:2,explanation:"EKG bei LAE oft: SI-QIII-TIII, Rechtslagetyp, T-Inversion V1-V3. Kann aber auch normal sein!"}
,
{q:"Übergabe (SINNHAFT): Notfallereignis (N) bei LAE – was beschreibt das WAS?",opts:["WAS: V.a. Lungenarterienembolie, WIE: akut einsetzende Dyspnoe + Thoraxschmerz, WANN: Symptombeginn","Nur: Patient hat Luftnot gemäß den Empfehlungen des ÄLRD","Nur die Sauerstoffsättigung unter Beachtung der Dosierungsgrenzen","Nur den EKG-Befund bei fortbestehender klinischer Verschlechterung"],correct:0,explanation:"LAE-Ereignis: Verdachtsdiagnose LAE, akutes Einsetzen der Dyspnoe + atemabhängiger Thoraxschmerz, exakter Symptombeginn (relevant für Lyse)."}]},
{id:131,title:"LAE mit Kreislaufstillstand",bpr:"lae",scenario:"55-jähriger, Z.n. Knie-TEP vor 10 Tagen. Plötzlich kollabiert. PEA am Monitor, weite Halsvenen.",
steps:[
{q:"V.a. massive LAE als Ursache. CPR-Besonderheit?",opts:["Perikardpunktion mit paralleler Vorbereitung des Transports","Lysetherapie unter CPR erwägen!","Nur Standard-CPR nach dokumentierter Erstuntersuchung","Thoraxdrainage unter Einbeziehung der Patientenanamnese"],correct:1,explanation:"LAE als Ursache des Kreislaufstillstands: Lyse unter CPR! Danach CPR 60-90 min fortsetzen."},
{q:"Wie lange CPR nach Lyse?",opts:["Mindestens 60-90 min","Nur 20 min bei fehlendem Ansprechen auf Ersttherapie","Sofort beenden","Standard 30 min und anschließende Reevaluation nach spätestens 5 Minuten"],correct:0,explanation:"Nach Lyse: CPR mindestens 60-90 min fortsetzen (Wirkungseintritt abwarten!)."},
{q:"Welcher Hinweis spricht für LAE?",opts:["Fieber als Eskalationsmaßnahme bei Therapieversagen","Post-OP + immobilisiert + PEA + gestaute Halsvenen","Nur Dyspnoe unter Berücksichtigung des Patientenalters","Brustschmerz allein nach Erhebung eines Basis-Monitorings"],correct:1,explanation:"Risikoprofil (OP, Immobilisation) + PEA + Rechtsherzbelastung = V.a. LAE!"},
{q:"Heparin bei Stillstand?",opts:["Nur nach ROSC mit regelmäßiger Verlaufskontrolle","5.000 IE i.v. in der CPR","Kontraindiziert bei CPR","Nur oral bei Verdacht auf kritische Verschlechterung"],correct:1,explanation:"Heparin i.v. auch unter CPR bei V.a. LAE!"},
{q:"ROSC nach Lyse. Besonderheit?",opts:["Blutungsrisiko erhöht – keine invasiven Maßnahmen wenn vermeidbar","Normal behandeln unter Beachtung möglicher Wechselwirkungen","Lyse wiederholen als leitliniengerechte Notfallmaßnahme","Kein Risiko nach klinischer Einschätzung"],correct:0,explanation:"Post-Lyse: erhöhtes Blutungsrisiko! Invasive Eingriffe minimieren."}
,
{q:"Übergabe (SINNHAFT): Welche Teamfrage (T) ist bei instabiler LAE besonders zu erwarten?",opts:["CT-Angio möglich? Patient stabil genug? Lyse in Erwägung? Heparin schon gegeben?","Welcher Notarzt war dabei? gemäß Behandlungspfad","Wie war das Wetter? bei stabilen Kreislaufverhältnissen","Welcher RTW war im Einsatz? unter kontinuierlichem Monitoring"],correct:0,explanation:"Teamfragen LAE: CT-Angio möglich (Patient stabil genug)? Lyse erwogen? Heparin-Gabe? Wells-Score? Echokardiographie geplant?"}]},
{id:132,title:"Pseudokrupp nachts",bpr:"obstruktion_kind",scenario:"2-jähriges Kind, bellender Husten, inspiratorischer Stridor, leichte Einziehungen. Kein Fieber. 3 Uhr nachts.",
steps:[
{q:"Verdachtsdiagnose?",opts:["Pseudokrupp (bellender Husten, Stridor, nachts, Alter 6 Mo-5 J)","Fremdkörper nach ABCDE-Reevaluation","Epiglottitis bei gesichertem Atemweg","Asthma laut aktuellem Algorithmus"],correct:0,explanation:"Bellender Husten + inspiratorischer Stridor + nachts + Kleinkind = typisch Pseudokrupp."},
{q:"Erstmaßnahme?",opts:["Antibiotika nach Sicherung der Vitalfunktionen","Kind beruhigen, Eltern beruhigen, kühle Luft, Prednisolon 100 mg Supp.","Intubation sofort unter Beachtung der Kontraindikationen","Laryngoskopie bei dokumentierter Indikation"],correct:1,explanation:"Pseudokrupp: Beruhigung + kühle Luft + Prednisolon Supp. 100 mg rektal."},
{q:"Verschlechterung: Stridor in Ruhe, stärkere Einziehungen. Nächste Stufe?",opts:["Intubation sofort mit anschließender Transportentscheidung","Atropin nach initialer Stabilisierung","Salbutamol gemäß SOP des Rettungsdienstes","Epinephrin vernebelt (4-5 mg)"],correct:3,explanation:"Schwerer Pseudokrupp: Epinephrin vernebelt! Schnelle Schleimhautabschwellung."},
{q:"Wie unterscheiden Sie von Epiglottitis?",opts:["Epiglottitis: hohes Fieber, kloßige Sprache, Speichelfluss, kein bellender Husten","Nur Jahreszeit bei fehlenden Kontraindikationen","Nur Alter unter Berücksichtigung des klinischen Bildes","Gleiche Symptome mit Voranmeldung in der Zielklinik"],correct:0,explanation:"Epiglottitis: hohes Fieber, kloßige Sprache, Speichelfluss, Schluckschmerz. Pseudokrupp: bellend, kein hohes Fieber."},
{q:"Was dürfen Sie bei Epiglottitis NICHT tun?",opts:["Transport nach Ausschluss reversibler Ursachen","Sauerstoff geben bei hämodynamischer Instabilität","Kind beruhigen unter Zeitdruck im Einsatzgeschehen","Mundinspektion mit Spatel (kann Totalobstruktion auslösen!)"],correct:3,explanation:"Epiglottitis: KEIN Spatel! Keine Manipulation am Rachen. Kind nicht hinlegen. Sitzend lassen!"}
,
{q:"Übergabe (SINNHAFT): Anamnese (A) bei Obstruktion Kind (Krupp/Epiglottitis) – was gehört immer dazu?",opts:["Allergien, Vorerkrankungen, Medikation, soziale Aspekte, Infektionen, Besonderheiten (nach SAMPLER erweitert)","Nur die Medikamentenliste als initiale Maßnahme vor Transport","Nur die Versicherungsdaten bei gesicherter Diagnose und Indikation","Nur die Diagnose mit begleitender Sauerstofftherapie, sofern keine allergischen Reaktionen in der Vorgeschichte bekannt sind"],correct:0,explanation:"Obstruktion Kind (Krupp/Epiglottitis): Anamnese nach erweitertem SAMPLER: Allergien, Vorerkrankungen, Medikation, soziale Aspekte (DNR?), Infektionen (MRSA?), Besonderheiten."}]},
{id:133,title:"Fremdkörperaspiration Kleinkind",bpr:"obstruktion_kind",scenario:"3-jähriges Kind, plötzlicher Hustenanfall beim Essen. Zunehmender Stridor, wird zyanotisch.",
steps:[
{q:"Effektiver Husten vorhanden?",opts:["Intubation nach differentialdiagnostischer Abwägung","Laryngoskopie im Rahmen der Notfallversorgung mit sofortiger Dokumentation im Einsatzprotokoll und Voranmeldung","Prüfen! Wenn ja: Husten ermutigen. Wenn nein: Rückenschläge!","Sofort Heimlich bei persistierender Symptomatik trotz Erstmaßnahmen"],correct:2,explanation:"Erst prüfen: Husten effektiv? JA → Husten lassen. NEIN → 5 Rückenschläge."},
{q:"Kind kann nicht mehr husten, wird schlaff. Maßnahmen?",opts:["Heimlich sofort nach Anlage eines venösen Zugangs","Nur O₂ gemäß den Empfehlungen des ÄLRD","Finger in den Mund unter Beachtung der Dosierungsgrenzen","5 Rückenschläge, dann 5 Thoraxkompressionen (Säugling) / Oberbauchkompressionen (> 1 J)"],correct:3,explanation:"Kind > 1 J: 5 Rückenschläge + 5 Oberbauchkompressionen (Heimlich) im Wechsel."},
{q:"Kind wird bewusstlos. Was jetzt?",opts:["Nur O₂ bei fortbestehender klinischer Verschlechterung","Nur Rückenschläge weiter mit paralleler Vorbereitung des Transports","CPR beginnen! 15:2, nach jeder Atemspende Mund inspizieren","Abwarten nach dokumentierter Erstuntersuchung"],correct:2,explanation:"Bewusstloses Kind mit Fremdkörper: CPR-Algorithmus! Thoraxkompressionen können FK lösen."},
{q:"Bei Säugling < 1 Jahr: Heimlich-Manöver erlaubt?",opts:["Immer Heimlich unter Einbeziehung der Patientenanamnese","Nur bei Erwachsenen bei fehlendem Ansprechen auf Ersttherapie","Ja als Eskalationsmaßnahme bei Therapieversagen, abhängig vom klinischen Verlauf und den erhobenen Vitalparametern","NEIN – bei Säuglingen Thoraxkompressionen statt Oberbauchkompressionen!"],correct:3,explanation:"Säugling: KEIN Heimlich! Rückenschläge + Thoraxkompressionen (Verletzungsgefahr Abdomen)."},
{q:"FK-Aspiration bei sichtbarem Fremdkörper im Mund?",opts:["Vorsichtig entfernen – NICHT blind digital ausräumen!","Immer blind ausräumen unter Berücksichtigung des Patientenalters","Ignorieren nach Erhebung eines Basis-Monitorings","Tiefer schieben mit regelmäßiger Verlaufskontrolle unter Berücksichtigung möglicher Differentialdiagnosen im Verlauf"],correct:0,explanation:"Nur sichtbare Fremdkörper entfernen! Blindes Ausräumen kann FK tiefer schieben."}
,
{q:"Übergabe (SINNHAFT): Fazit/Teamfragen (F/T) bei Obstruktion Kind (Krupp/Epiglottitis) – wer wiederholt die Kernpunkte?",opts:["Das ÜBERNEHMENDE Team wiederholt (Closed Loop)","Der Übergeber fasst nochmal zusammen","Nur der Oberarzt bei Verdacht auf kritische Verschlechterung","Niemand – einmal reicht unter Beachtung möglicher Wechselwirkungen"],correct:0,explanation:"Obstruktion Kind (Krupp/Epiglottitis): Beim Fazit wiederholt das ÜBERNEHMENDE Team: Identifikation, Notfallereignis, Priorität, Handlungen. Dann Raum für Teamfragen."}]},
{id:134,title:"Fremdkörperaspiration Erwachsener",bpr:"fk_aspiration",scenario:"68-jähriger verschluckt sich beim Essen. Greift sich an den Hals, kann nicht sprechen, wird zyanotisch.",
steps:[
{q:"Universelles Erstickungszeichen?",opts:["Husten als leitliniengerechte Notfallmaßnahme","Kopfschütteln","Griff an den Hals","Schreien nach klinischer Einschätzung"],correct:2,explanation:"Griff an den Hals = universelles Zeichen der Atemwegsverlegung."},
{q:"Patient kann nicht husten. Maßnahme?",opts:["Nur O₂ gemäß Behandlungspfad","Finger in den Mund bei stabilen Kreislaufverhältnissen","Intubation unter kontinuierlichem Monitoring","5 Rückenschläge, dann 5 Oberbauchkompressionen (Heimlich)"],correct:3,explanation:"Ineffektiver Husten: 5 Rückenschläge + 5 Heimlich-Handgriffe im Wechsel."},
{q:"Patient wird bewusstlos?",opts:["Abwarten nach ABCDE-Reevaluation","CPR beginnen (30:2), Mund inspizieren vor jeder Beatmung","Nur Beatmung bei gesichertem Atemweg","Nur Rückenschläge laut aktuellem Algorithmus"],correct:1,explanation:"Bewusstlos → CPR! Thoraxkompressionen können FK lösen."},
{q:"Beatmung nicht möglich trotz korrekter Kopfposition?",opts:["Nur HDM weiter nach Sicherung der Vitalfunktionen","Laryngoskopie + FK-Extraktion mit Magill-Zange","Aufgeben unter Beachtung der Kontraindikationen","Mehr Kraft bei dokumentierter Indikation"],correct:1,explanation:"Laryngoskopie unter CPR: FK visualisieren und mit Magill-Zange entfernen!"},
{q:"Nach Heimlich-Manöver: Klinikvorstellung nötig?",opts:["Ja – Abdominalverletzungen (Leber, Milz) möglich!","Nur bei Schmerzen mit anschließender Transportentscheidung","Nein nach initialer Stabilisierung","Nur bei Kindern gemäß SOP des Rettungsdienstes"],correct:0,explanation:"Nach Oberbauchkompressionen: immer Klinikvorstellung (innere Verletzungen möglich)."}
,
{q:"Übergabe (SINNHAFT): Anamnese (A) bei FK-Aspiration beim Kind – was ist besonders relevant?",opts:["Nur das Gewicht bei fehlenden Kontraindikationen","Nur die Allergien unter Berücksichtigung des klinischen Bildes","Nur der Kindergarten mit Voranmeldung in der Zielklinik","Art des FK, Impfstatus, Vorerkrankungen (Trachealkanüle?), Zeugenaussagen zum Hergang"],correct:3,explanation:"Kind + FK: Art des verschluckten Objekts (Batterie? Magnet? = Notfall!), Größe, Zeugenaussagen, Impfstatus, Vorerkrankungen der Atemwege."}]},
{id:135,title:"Fremdkörper in Trachea",bpr:"fk_aspiration",scenario:"5-jähriges Kind, V.a. aspirierte Erdnuss. Intermittierender Stridor, SpO₂ 94%, noch bei Bewusstsein.",
steps:[
{q:"Effektiver Husten?",opts:["Rückenschläge sofort nach Ausschluss reversibler Ursachen","Ja – Kind husten lassen! Nicht klopfen!","Sofort Heimlich bei hämodynamischer Instabilität","Intubation unter Zeitdruck im Einsatzgeschehen"],correct:1,explanation:"Effektiver Husten = beste FK-Clearance! Husten ermutigen, NICHT stören."},
{q:"SpO₂ fällt auf 86%. Husten wird schwächer. Nächste Maßnahme?",opts:["5 Rückenschläge + 5 Oberbauchkompressionen (> 1 J)","Nur O₂ als initiale Maßnahme vor Transport, nach vorheriger Abklärung aller reversiblen Ursachen gemäß Algorithmus","Laryngoskopie bei gesicherter Diagnose und Indikation","Abwarten mit begleitender Sauerstofftherapie"],correct:0,explanation:"Ineffektiver Husten: Rückenschläge + Oberbauchkompressionen bei Kind > 1 Jahr."},
{q:"Warum ist die Erdnuss besonders problematisch?",opts:["Kein Problem nach differentialdiagnostischer Abwägung","Nur Geschmack im Rahmen der Notfallversorgung","Nur Allergie bei persistierender Symptomatik trotz Erstmaßnahmen","Erdnüsse quellen auf und verursachen Schleimhautschwellung"],correct:3,explanation:"Erdnüsse: quellen durch Feuchtigkeit auf, enthalten Öle die Schleimhautschwellung verursachen!"},
{q:"Kind stabilisiert sich, atmet mit Stridor. Transport?",opts:["Flach lagern nach Anlage eines venösen Zugangs","Sitzend/aufrecht, O₂, Kinderchirurgie (Bronchoskopie!)","Hausarzt gemäß den Empfehlungen des ÄLRD","Abwarten unter Beachtung der Dosierungsgrenzen, wobei die Wirksamkeit engmaschig kontrolliert werden muss"],correct:1,explanation:"V.a. FK: Klinik mit Bronchoskopie-Möglichkeit! Transport sitzend."},
{q:"Was sollten Sie bei V.a. FK NICHT tun?",opts:["Blind mit dem Finger im Rachen ausräumen","O₂ geben bei fortbestehender klinischer Verschlechterung","Monitoring mit paralleler Vorbereitung des Transports","Kind beruhigen nach dokumentierter Erstuntersuchung"],correct:0,explanation:"NICHT blind ausräumen! FK kann tiefer geschoben werden."}
,
{q:"Übergabe (SINNHAFT): Teamfragen (T) bei FK-Aspiration – was fragt die Klinik?",opts:["Wie war der Transport? unter Einbeziehung der Patientenanamnese","Welcher RTW war im Einsatz? bei fehlendem Ansprechen auf Ersttherapie","Welcher Notarzt war dabei? als Eskalationsmaßnahme bei Therapieversagen","FK noch in situ? Bronchoskopie-Bereitschaft nötig? HNO/Pädiatrie informiert? Röntgen nötig?"],correct:3,explanation:"Teamfragen FK: FK entfernt oder noch in situ? Bronchoskopie-Team alarmiert? Lokalisation (einseitig?), Röntgen-Thorax geplant?"}]},
{id:136,title:"Aortendissektion Typ A",bpr:"aortensyndrom",scenario:"56-jähriger, plötzlicher Vernichtungsschmerz zwischen den Schulterblättern, reißender Charakter. RR li 190/100, re 140/80. Blass.",
steps:[
{q:"RR-Differenz zwischen den Armen – Bedeutung?",opts:["Normal unter Berücksichtigung des Patientenalters, was jedoch in der aktuellen Situation kontraindiziert wäre","Nur Messfehler nach Erhebung eines Basis-Monitorings","Irrelevant mit regelmäßiger Verlaufskontrolle","Typisch für Aortendissektion! Unterschied > 20 mmHg verdächtig"],correct:3,explanation:"RR-Seitendifferenz > 20 mmHg bei Vernichtungsschmerz = V.a. Aortendissektion!"},
{q:"Zielblutdruck?",opts:["Normal bei Verdacht auf kritische Verschlechterung","RRsyst 100-120 mmHg, HF < 60/min","Nicht senken unter Beachtung möglicher Wechselwirkungen","180/100 als leitliniengerechte Notfallmaßnahme"],correct:1,explanation:"Aortendissektion: aggressiv RR + HF senken! RRsyst 100-120, HF < 60."},
{q:"Medikamente?",opts:["ASS + Heparin nach klinischer Einschätzung","Urapidil + Metoprolol i.v. (HF senken!) + potente Analgesie","Nur Analgesie gemäß Behandlungspfad","Nur Volumen bei stabilen Kreislaufverhältnissen"],correct:1,explanation:"RR-Senkung (Urapidil) + HF-Senkung (Betablocker) + Analgesie. KEIN ASS/Heparin (Blutungsrisiko)!"},
{q:"Warum kein ASS/Heparin?",opts:["Immer geben unter kontinuierlichem Monitoring und anschließende Reevaluation nach spätestens 5 Minuten","Blutungsgefahr bei Dissektion! (DD ACS beachten)","Nur bei Typ B nach ABCDE-Reevaluation","Kein Grund bei gesichertem Atemweg"],correct:1,explanation:"Aortendissektion: KEIN ASS/Heparin → verstärkt Blutung! Cave: DD ACS."},
{q:"Transport?",opts:["Kardiologie reicht laut aktuellem Algorithmus","Nächstes KH nach Sicherung der Vitalfunktionen","Hausarzt unter Beachtung der Kontraindikationen","Maximalversorger mit Herz-/Gefäßchirurgie"],correct:3,explanation:"Typ A Dissektion: Not-OP! Klinik mit Herzchirurgie/Gefäßchirurgie."}
,
{q:"Übergabe (SINNHAFT): Anamnese (A) bei V.a. Aortendissektion?",opts:["Nur die Allergien bei dokumentierter Indikation","Nur die Familienanamnese mit anschließender Transportentscheidung","Nur die Medikation nach initialer Stabilisierung","Hypertonie-Anamnese, Marfan-Syndrom?, Schwangerschaft?, Antikoagulation, vorangegangene Aorten-OP"],correct:3,explanation:"Aortensyndrom-Anamnese: Hypertonie (häufigste Ursache!), Bindegewebserkrankung (Marfan, Ehlers-Danlos), Schwangerschaft, vorherige Aorten-OP, Kokain-Konsum."}]},
{id:137,title:"Akutes Aortensyndrom – Bauchaorta",bpr:"aortensyndrom",scenario:"71-jähriger Raucher, plötzlicher Bauchschmerz mit Ausstrahlung in den Rücken. Pulsierender Tumor im Abdomen. RR 90/60, HF 120.",
steps:[
{q:"Verdachtsdiagnose?",opts:["Appendizitis gemäß SOP des Rettungsdienstes","Ileus bei fehlenden Kontraindikationen","Rupturiertes Bauchaortenaneurysma (BAA)","Nierenkolik unter Berücksichtigung des klinischen Bildes"],correct:2,explanation:"Pulsierender abdomineller Tumor + Schock + Rückenschmerz = V.a. BAA-Ruptur!"},
{q:"Sofortmaßnahme?",opts:["Abwarten mit Voranmeldung in der Zielklinik, sofern keine allergischen Reaktionen in der Vorgeschichte bekannt sind","CT vor Ort nach Ausschluss reversibler Ursachen","2 großlumige Zugänge, VEL, permissive Hypotonie, sofortiger Transport","Nur Analgesie bei hämodynamischer Instabilität"],correct:2,explanation:"Lebensbedrohlicher Notfall! Großlumige Zugänge, Volumen, sofortiger Transport. Permissive Hypotonie."},
{q:"Permissive Hypotonie hier?",opts:["RR 140 anstreben unter Zeitdruck im Einsatzgeschehen","Nein, RR normalisieren als initiale Maßnahme vor Transport","Ja – RRsyst 80-90 mmHg tolerieren (weniger Blutung)","Irrelevant bei gesicherter Diagnose und Indikation"],correct:2,explanation:"Permissive Hypotonie: Syst. 80-90 mmHg. Zu hoher RR → mehr Blutung aus Ruptur."},
{q:"Transport?",opts:["Ambulant mit begleitender Sauerstofftherapie","Hausarzt nach differentialdiagnostischer Abwägung","Nächstes KH im Rahmen der Notfallversorgung","Gefäßchirurgie / Maximalversorger, Voranmeldung!"],correct:3,explanation:"BAA-Ruptur: sofort Gefäßchirurgie! Jede Minute zählt."},
{q:"Analgesie?",opts:["Esketamin oder Fentanyl titriert","Ibuprofen bei persistierender Symptomatik trotz Erstmaßnahmen","Paracetamol nach Anlage eines venösen Zugangs","Keine gemäß den Empfehlungen des ÄLRD"],correct:0,explanation:"Starke Schmerzen → potente Analgesie. Esketamin oder Opioide titriert."}
,
{q:"Übergabe (SINNHAFT): Warum ist das Fazit (F) bei V.a. Aortendissektion besonders kritisch?",opts:["Weil die RR-Differenz und fehlende Pulse in der Hektik untergehen können – Closed Loop sichert diese Info","Es ist nicht besonders kritisch unter Beachtung der Dosierungsgrenzen","Weil es gesetzlich vorgeschrieben ist bei fortbestehender klinischer Verschlechterung mit sofortiger Dokumentation im Einsatzprotokoll und Voranmeldung","Weil die Klinik den Patienten meist nicht kennt mit paralleler Vorbereitung des Transports"],correct:0,explanation:"Fazit sichert ab: RR-Differenz, fehlende Pulse und Ziel-RR sind lebenswichtige Infos die in der Hektik verloren gehen. Closed Loop schützt davor."}]},
{id:138,title:"Akuter Arterienverschluss Bein",bpr:"art_verschluss",scenario:"68-jährige, plötzlich blasses, kaltes linkes Bein, starke Schmerzen, kein Fußpuls tastbar.",
steps:[
{q:"6 P der akuten Ischämie?",opts:["Nur Schmerz nach dokumentierter Erstuntersuchung","3 P reichen unter Einbeziehung der Patientenanamnese","Pain, Paleness, Pulselessness, Paresthesia, Paralysis, Prostration","Nur Blässe bei fehlendem Ansprechen auf Ersttherapie, abhängig vom klinischen Verlauf und den erhobenen Vitalparametern"],correct:2,explanation:"6P: Schmerz, Blässe, Pulslosigkeit, Parästhesien, Paralyse, Erschöpfung."},
{q:"Lagerung?",opts:["Betroffenes Bein tief lagern (Schwerkraft-unterstützte Perfusion)","Flach als Eskalationsmaßnahme bei Therapieversagen","Bein hochlagern unter Berücksichtigung des Patientenalters","Schocklage nach Erhebung eines Basis-Monitorings"],correct:0,explanation:"Bein tief lagern: Schwerkraft unterstützt die restliche Perfusion."},
{q:"Medikamente?",opts:["ASS mit regelmäßiger Verlaufskontrolle","Kühlung bei Verdacht auf kritische Verschlechterung","Kompression unter Beachtung möglicher Wechselwirkungen","Heparin 5.000 IE i.v. + Analgesie"],correct:3,explanation:"Heparin i.v. (Thrombuswachstum verhindern) + potente Analgesie."},
{q:"Zeitfenster für Revaskularisation?",opts:["6 Stunden (Golden Hour der Gefäßchirurgie)","Unbegrenzt als leitliniengerechte Notfallmaßnahme","24 Stunden nach klinischer Einschätzung","1 Woche gemäß Behandlungspfad"],correct:0,explanation:"6-Stunden-Regel: danach irreversible Muskelschäden. Zeitkritisch!"},
{q:"Transport?",opts:["Klinik mit Gefäßchirurgie","Phlebologie bei stabilen Kreislaufverhältnissen","Hausarzt unter kontinuierlichem Monitoring","Nächstes KH nach ABCDE-Reevaluation"],correct:0,explanation:"Akuter arterieller Verschluss: Gefäßchirurgie! Embolektomie/Lyse."}
,
{q:"Übergabe (SINNHAFT): Anamnese (A) bei Arterieller Verschluss – was gehört immer dazu?",opts:["Nur die Versicherungsdaten bei gesichertem Atemweg","Nur die Diagnose laut aktuellem Algorithmus","Allergien, Vorerkrankungen, Medikation, soziale Aspekte, Infektionen, Besonderheiten (nach SAMPLER erweitert)","Nur die Medikamentenliste nach Sicherung der Vitalfunktionen"],correct:2,explanation:"Arterieller Verschluss: Anamnese nach erweitertem SAMPLER: Allergien, Vorerkrankungen, Medikation, soziale Aspekte (DNR?), Infektionen (MRSA?), Besonderheiten."}]},
{id:139,title:"Dehydratation Säugling",bpr:"dehydratation",scenario:"8 Monate, 8 kg. Seit 3 Tagen Durchfall und Erbrechen. Eingefallene Fontanelle, stehende Hautfalten, trockene Schleimhäute. HF 170.",
steps:[
{q:"Schweregrad der Dehydratation?",opts:["Schwer (eingefallene Fontanelle + stehende Hautfalten + Tachykardie)","Mittelschwer unter Beachtung der Kontraindikationen","Keine bei dokumentierter Indikation","Leicht mit anschließender Transportentscheidung unter Berücksichtigung möglicher Differentialdiagnosen im Verlauf"],correct:0,explanation:"Eingefallene Fontanelle + stehende Hautfalten + Tachykardie = schwere Dehydratation!"},
{q:"Volumengabe?",opts:["Nur oral nach initialer Stabilisierung","10 ml gesamt gemäß SOP des Rettungsdienstes","500 ml Bolus bei fehlenden Kontraindikationen, nach vorheriger Abklärung aller reversiblen Ursachen gemäß Algorithmus","VEL 20 ml/kgKG Bolus i.v. (= 160 ml), Reevaluation"],correct:3,explanation:"Kind: VEL 20 ml/kgKG Bolus. Bei 8 kg = 160 ml. Reevaluation nach jedem Bolus!"},
{q:"Kein i.v.-Zugang möglich?",opts:["Abwarten","Nur oral","Rektal unter Berücksichtigung des klinischen Bildes","i.o.-Zugang!"],correct:3,explanation:"Kein i.v. bei schwerem Schock → i.o.-Zugang! Keine Zeitverluste."},
{q:"BZ messen – warum?",opts:["Nicht nötig mit Voranmeldung in der Zielklinik","Säuglinge haben geringe Glykogenreserven → Hypoglykämiegefahr!","Irrelevant nach Ausschluss reversibler Ursachen","Nur bei Diabetes bei hämodynamischer Instabilität"],correct:1,explanation:"Säugling + Erbrechen + Dehydratation → Hypoglykämie möglich! BZ messen."},
{q:"Transport?",opts:["Nach Hause","Kinderarzt","Hausarzt","Kinderklinik"],correct:3,explanation:"Schwere Dehydratation beim Säugling: immer Klinik!"}
,
{q:"Übergabe (SINNHAFT): Anamnese (A) bei Dehydratation – was gehört immer dazu?",opts:["Allergien, Vorerkrankungen, Medikation, soziale Aspekte, Infektionen, Besonderheiten (nach SAMPLER erweitert)","Nur die Diagnose unter Zeitdruck im Einsatzgeschehen","Nur die Versicherungsdaten als initiale Maßnahme vor Transport","Nur die Medikamentenliste bei gesicherter Diagnose und Indikation"],correct:0,explanation:"Dehydratation: Anamnese nach erweitertem SAMPLER: Allergien, Vorerkrankungen, Medikation, soziale Aspekte (DNR?), Infektionen (MRSA?), Besonderheiten."}]},
{id:140,title:"Gastroenteritis mit Schock",bpr:"dehydratation",scenario:"82-jährige aus Pflegeheim, 4 Tage Durchfall. Somnolent, stehende Hautfalten, RR 70/40, HF 130.",
steps:[
{q:"Schockform?",opts:["Hypovolämischer Schock durch Flüssigkeitsverlust","Kardiogener Schock mit begleitender Sauerstofftherapie","Septischer Schock nach differentialdiagnostischer Abwägung","Anaphylaxie im Rahmen der Notfallversorgung"],correct:0,explanation:"Durchfall + Dehydratation → hypovolämischer Schock."},
{q:"Therapie?",opts:["Nur oral bei persistierender Symptomatik trotz Erstmaßnahmen","VEL 500-1000 ml Bolus, Schocklage","Furosemid nach Anlage eines venösen Zugangs","Noradrenalin zuerst gemäß den Empfehlungen des ÄLRD"],correct:1,explanation:"Hypovolämischer Schock: Volumen, Volumen, Volumen! VEL i.v."},
{q:"Was muss ausgeschlossen werden?",opts:["Sepsis (Gastroenteritis kann septisch werden!)","Nur BZ unter Beachtung der Dosierungsgrenzen","Nur Elektrolyte bei fortbestehender klinischer Verschlechterung","Nur Dehydratation mit paralleler Vorbereitung des Transports"],correct:0,explanation:"Alte Menschen: Gastroenteritis → Sepsis möglich! Temperatur, Infektzeichen prüfen."},
{q:"BZ 280 mg/dl. Bedeutung?",opts:["Stressreaktion ODER entgleister Diabetes → Ursache klären","Hypoglykämie nach dokumentierter Erstuntersuchung","Irrelevant unter Einbeziehung der Patientenanamnese","Normal bei fehlendem Ansprechen auf Ersttherapie"],correct:0,explanation:"Hyperglykämie bei Schock: Stressreaktion oder DKA/HHS. Anamnese: Diabetes bekannt?"},
{q:"Transport?",opts:["Ambulant als Eskalationsmaßnahme bei Therapieversagen","Hausarzt unter Berücksichtigung des Patientenalters","Pflegeheim zurück, wobei die Wirksamkeit engmaschig kontrolliert werden muss","Klinik mit Intensivstation"],correct:3,explanation:"Schock: immer Klinik mit Intensivmöglichkeit!"}
,
{q:"Übergabe (SINNHAFT): Fazit/Teamfragen (F/T) bei Dehydratation – wer wiederholt die Kernpunkte?",opts:["Nur der Oberarzt nach Erhebung eines Basis-Monitorings","Der Übergeber fasst nochmal zusammen","Das ÜBERNEHMENDE Team wiederholt (Closed Loop)","Niemand – einmal reicht mit regelmäßiger Verlaufskontrolle"],correct:2,explanation:"Dehydratation: Beim Fazit wiederholt das ÜBERNEHMENDE Team: Identifikation, Notfallereignis, Priorität, Handlungen. Dann Raum für Teamfragen."}]},
{id:141,title:"Stromunfall Hochspannung",bpr:"stromunfall",scenario:"Elektriker, Kontakt mit 10.000V-Leitung. Bewusstlos, Verbrennungsmarken an Hand und Fuß. GCS 6, HF 40.",
steps:[
{q:"Erstmaßnahme?",opts:["CPR sofort bei Verdacht auf kritische Verschlechterung, was jedoch in der aktuellen Situation kontraindiziert wäre","Nur rufen unter Beachtung möglicher Wechselwirkungen","Sofort anfassen als leitliniengerechte Notfallmaßnahme","Eigenschutz! Spannungsfreiheit sicherstellen! Dann erst Zugang"],correct:3,explanation:"Hochspannung: IMMER Spannungsfreiheit durch Fachpersonal sicherstellen! Lebensgefahr für Retter!"},
{q:"EKG?",opts:["Später nach klinischer Einschätzung und anschließende Reevaluation nach spätestens 5 Minuten","Nicht nötig gemäß Behandlungspfad","Nur bei Beschwerden bei stabilen Kreislaufverhältnissen","12-Kanal-EKG obligat! Rhythmusstörungen häufig"],correct:3,explanation:"BPR: EKG bei jedem Stromunfall obligat! Arrhythmien (VF, VT, AV-Block) häufig."},
{q:"Bradykardie HF 40. Maßnahme?",opts:["Atropin 0,5 mg i.v., Schrittmacher bereithalten","Nur beobachten unter kontinuierlichem Monitoring","Amiodaron nach ABCDE-Reevaluation, sofern keine allergischen Reaktionen in der Vorgeschichte bekannt sind","Metoprolol bei gesichertem Atemweg"],correct:0,explanation:"Strominduzierte Bradykardie: Atropin, ggf. Schrittmacher."},
{q:"Verbrennungsmarken Ein-/Austritt – Bedeutung?",opts:["Strom ist durch den Körper geflossen → innere Organschäden möglich!","Nur Hautschaden laut aktuellem Algorithmus","Nur kosmetisch nach Sicherung der Vitalfunktionen","Irrelevant unter Beachtung der Kontraindikationen"],correct:0,explanation:"Ein-/Austrittsstellen: Strom durchfloss den Körper! Myokardschaden, Rhabdomyolyse, innere Verbrennungen möglich."},
{q:"Monitoring-Dauer?",opts:["Nicht nötig bei dokumentierter Indikation","24h EKG-Monitoring in Klinik (Spätarrhythmien!)","Nur 1 Stunde mit anschließender Transportentscheidung","Ambulant nach initialer Stabilisierung"],correct:1,explanation:"Stromunfall: 24h Monitoring! Spätarrhythmien möglich, auch nach Stunden."}
,
{q:"Übergabe (SINNHAFT): Anamnese (A) bei Stromunfall – was gehört immer dazu?",opts:["Nur die Diagnose gemäß SOP des Rettungsdienstes","Nur die Medikamentenliste bei fehlenden Kontraindikationen","Allergien, Vorerkrankungen, Medikation, soziale Aspekte, Infektionen, Besonderheiten (nach SAMPLER erweitert)","Nur die Versicherungsdaten unter Berücksichtigung des klinischen Bildes"],correct:2,explanation:"Stromunfall: Anamnese nach erweitertem SAMPLER: Allergien, Vorerkrankungen, Medikation, soziale Aspekte (DNR?), Infektionen (MRSA?), Besonderheiten."}]},
{id:142,title:"Tracheostoma-Notfall",bpr:"tracheostoma",scenario:"65-jähriger mit Tracheostoma nach Laryngektomie. Akute Atemnot, Sekretverhalt, SpO₂ 75%.",
steps:[
{q:"Erstmaßnahme?",opts:["Sauerstoff über Gesichtsmaske","Mund-zu-Mund beatmen","Absaugen des Tracheostomas!","Intubation oral"],correct:2,explanation:"Tracheostoma verstopft: Absaugen! Sekret/Borken entfernen."},
{q:"Absaugen nicht erfolgreich. Nächster Schritt?",opts:["Abwarten mit Voranmeldung in der Zielklinik","Mund-zu-Mund nach Ausschluss reversibler Ursachen","Orale Intubation bei hämodynamischer Instabilität mit sofortiger Dokumentation im Einsatzprotokoll und Voranmeldung","Kanüle entfernen, Stoma freihalten, Beatmung über Stoma"],correct:3,explanation:"Kanüle entfernen! Bei Laryngektomie: keine Verbindung Mund-Trachea → Beatmung NUR über Stoma."},
{q:"Warum keine Mund-zu-Mund-Beatmung bei Laryngektomie?",opts:["Kehlkopf fehlt – keine Verbindung zwischen Mund und Trachea","Nur bei Kindern unter Zeitdruck im Einsatzgeschehen","Hygiene als initiale Maßnahme vor Transport","Geht auch bei gesicherter Diagnose und Indikation"],correct:0,explanation:"Laryngektomie = Kehlkopf komplett entfernt. Mundhöhle und Trachea sind getrennt."},
{q:"Notfall-Oxygenierung über Stoma?",opts:["Larynxmaske oral mit begleitender Sauerstofftherapie","Beutel-Maske über Stoma, ggf. kleinerer Tubus durch Stoma","Nur O₂-Brille nach differentialdiagnostischer Abwägung","CPAP Gesicht im Rahmen der Notfallversorgung"],correct:1,explanation:"Beatmung über Stoma: Beutel direkt aufsetzen oder Tubus (kleiner als Stoma-Durchmesser) einführen."},
{q:"Transport?",opts:["HNO-Klinik","Ambulant","Hausarzt","Pflegeheim zurück"],correct:0,explanation:"Tracheostoma-Notfall: HNO-Klinik!"}
,
{q:"Übergabe (SINNHAFT): Anamnese (A) bei Tracheostoma-Notfall – was gehört immer dazu?",opts:["Allergien, Vorerkrankungen, Medikation, soziale Aspekte, Infektionen, Besonderheiten (nach SAMPLER erweitert)","Nur die Medikamentenliste bei persistierender Symptomatik trotz Erstmaßnahmen","Nur die Versicherungsdaten nach Anlage eines venösen Zugangs","Nur die Diagnose gemäß den Empfehlungen des ÄLRD"],correct:0,explanation:"Tracheostoma-Notfall: Anamnese nach erweitertem SAMPLER: Allergien, Vorerkrankungen, Medikation, soziale Aspekte (DNR?), Infektionen (MRSA?), Besonderheiten."}]},
{id:143,title:"Intoxikation Benzodiazepine",bpr:"intoxikation",scenario:"28-jährige, V.a. Suizidversuch mit Tabletten (leere Bromazepam-Packung). GCS 8, AF 8/min, SpO₂ 85%.",
steps:[
{q:"Welches Symptommuster?",opts:["Erbrechen + Durchfall unter Beachtung der Dosierungsgrenzen","Krampfanfälle bei fortbestehender klinischer Verschlechterung","Mydriasis + Tachykardie mit paralleler Vorbereitung des Transports","Atemdepression + Bewusstseinsminderung + Miosis = Sedativa/Benzo"],correct:3,explanation:"Benzodiazepine: Atemdepression, Somnolenz/Koma, Miosis. Kreislauf oft stabil."},
{q:"Antidot?",opts:["Atropin nach dokumentierter Erstuntersuchung","Glucose unter Einbeziehung der Patientenanamnese","Flumazenil – CAVE: Krampfanfälle möglich! Nur auf NA-Anordnung","Naloxon bei fehlendem Ansprechen auf Ersttherapie, abhängig vom klinischen Verlauf und den erhobenen Vitalparametern"],correct:2,explanation:"Flumazenil: BZ-Antidot. CAVE: Krampfauslösung bei chronischer Einnahme/Mischintoxikation! Nur nach NA-Rücksprache."},
{q:"Erstmaßnahme?",opts:["Antidot sofort als Eskalationsmaßnahme bei Therapieversagen","Atemwegssicherung + assistierte Beatmung + O₂","Magenspülung unter Berücksichtigung des Patientenalters","Kohle oral nach Erhebung eines Basis-Monitorings"],correct:1,explanation:"A-B-C! Atemdepression behandeln: Atemweg sichern, beatmen, O₂."},
{q:"Aktivkohle?",opts:["Nur wenn wach genug und < 1h nach Einnahme (Aspirationsrisiko bei GCS 8!)","Auch bei Koma mit regelmäßiger Verlaufskontrolle","Nie bei Verdacht auf kritische Verschlechterung","Immer unter Beachtung möglicher Wechselwirkungen"],correct:0,explanation:"Kohle NUR bei ausreichend wachem Patient und zeitnah. GCS 8 → Aspirationsgefahr!"},
{q:"Psychiatrische Abklärung?",opts:["Ja – nach medizinischer Stabilisierung obligat bei Suizidversuch","Nicht nötig als leitliniengerechte Notfallmaßnahme","Ambulant nach klinischer Einschätzung","Nur bei Wiederholung gemäß Behandlungspfad"],correct:0,explanation:"Suizidversuch: nach medizinischer Stabilisierung → psychiatrische Evaluation. Meldepflicht prüfen."}
,
{q:"Übergabe (SINNHAFT): Anamnese (A) bei Intoxikation – was gehört immer dazu?",opts:["Allergien, Vorerkrankungen, Medikation, soziale Aspekte, Infektionen, Besonderheiten (nach SAMPLER erweitert)","Nur die Versicherungsdaten bei stabilen Kreislaufverhältnissen","Nur die Diagnose unter kontinuierlichem Monitoring unter Berücksichtigung möglicher Differentialdiagnosen im Verlauf","Nur die Medikamentenliste nach ABCDE-Reevaluation"],correct:0,explanation:"Intoxikation: Anamnese nach erweitertem SAMPLER: Allergien, Vorerkrankungen, Medikation, soziale Aspekte (DNR?), Infektionen (MRSA?), Besonderheiten."}]},
{id:144,title:"Opiatintoxikation",bpr:"intoxikation",scenario:"35-jähriger, bewusstlos auf Parkbank. Enge Pupillen (Miosis), AF 4/min, SpO₂ 60%. Injektionsnarben Unterarm.",
steps:[
{q:"Klassische Trias?",opts:["Mydriasis + Tachykardie + Hypertonie","Krampf + Fieber + Exanthem","Koma + Atemdepression + Miosis","Erbrechen + Durchfall + Schmerz"],correct:2,explanation:"Opiat-Trias: Bewusstlosigkeit + Atemdepression + stecknadelkopfgroße Pupillen."},
{q:"Antidot?",opts:["Atropin bei gesichertem Atemweg","Kohle laut aktuellem Algorithmus","Flumazenil nach Sicherung der Vitalfunktionen","Naloxon 0,4 mg i.v. titriert (oder i.m./intranasal)"],correct:3,explanation:"Naloxon: Opiatantagonist. 0,4 mg i.v. titriert. Wirkdauer kürzer als Opiate → Überwachung!"},
{q:"Warum titriert und nicht als Bolus?",opts:["Zu schnelle Antagonisierung → akuter Entzug, Erbrechen, Aggression","Immer Bolus unter Beachtung der Kontraindikationen","Kein Grund bei dokumentierter Indikation","Nur bei Kindern titrieren mit anschließender Transportentscheidung"],correct:0,explanation:"Vollantagonisierung → Entzugssymptome, Erbrechen (Aspiration!), Aggression. Titrieren bis AF > 10/min!"},
{q:"Erstmaßnahme VOR Antidot?",opts:["Magenspülung nach initialer Stabilisierung","Atemwegssicherung + Beatmung + O₂","Naloxon sofort gemäß SOP des Rettungsdienstes","Nichts bei fehlenden Kontraindikationen"],correct:1,explanation:"A-B-C zuerst! Beatmung sicherstellen, dann Naloxon."},
{q:"Patient wacht auf und will gehen. Risiko?",opts:["Kein Risiko unter Berücksichtigung des klinischen Bildes","Nur bei Heroin mit Voranmeldung in der Zielklinik","Naloxon wirkt kürzer als Opiate → Renarkotisierung!","Kann gehen nach Ausschluss reversibler Ursachen, nach vorheriger Abklärung aller reversiblen Ursachen gemäß Algorithmus"],correct:2,explanation:"Naloxon: HWZ 30-90 min. Opiate oft länger! → Renarkotisierung. Monitoring mindestens 2h."}
,
{q:"Übergabe (SINNHAFT): Fazit/Teamfragen (F/T) bei Intoxikation – wer wiederholt die Kernpunkte?",opts:["Nur der Oberarzt bei hämodynamischer Instabilität","Der Übergeber fasst nochmal zusammen, wobei die Wirksamkeit engmaschig kontrolliert werden muss","Niemand – einmal reicht unter Zeitdruck im Einsatzgeschehen","Das ÜBERNEHMENDE Team wiederholt (Closed Loop)"],correct:3,explanation:"Intoxikation: Beim Fazit wiederholt das ÜBERNEHMENDE Team: Identifikation, Notfallereignis, Priorität, Handlungen. Dann Raum für Teamfragen."}]},
{id:145,title:"Schwere Hypothermie im Freien",bpr:"hypothermie",scenario:"Obdachloser, im Winter bewusstlos aufgefunden. Rektaltemperatur 28°C. Bradykardie 30/min, RR 60/30.",
steps:[
{q:"Hypothermie-Stadium?",opts:["Stadium III (28°C, bewusstlos, Bradykardie)","Stadium IV als initiale Maßnahme vor Transport","Stadium II bei gesicherter Diagnose und Indikation","Stadium I mit begleitender Sauerstofftherapie"],correct:0,explanation:"Swiss Staging: Stadium III: 24-28°C, bewusstlos, Vitalzeichen vorhanden."},
{q:"Was dürfen Sie NICHT tun?",opts:["O₂ geben nach differentialdiagnostischer Abwägung, was jedoch in der aktuellen Situation kontraindiziert wäre","Passiv wärmen im Rahmen der Notfallversorgung","Monitoring bei persistierender Symptomatik trotz Erstmaßnahmen","Aktiv bewegen/reiben (VF-Auslösung durch Afterdrop!)"],correct:3,explanation:"Hypothermie: NICHT aktiv bewegen! Kaltes Blut aus Peripherie → Kerntemperatur fällt weiter (Afterdrop) → VF!"},
{q:"Maßnahme?",opts:["Passiver Wärmeerhalt, horizontaler Transport, Monitoring, warme Infusionen","In Schnee reiben nach Anlage eines venösen Zugangs","Sofort aufsetzen gemäß den Empfehlungen des ÄLRD","Heiße Dusche unter Beachtung der Dosierungsgrenzen"],correct:0,explanation:"Passiver Wärmeerhalt (Isolierung), warme Infusionen i.v., horizontal transportieren."},
{q:"VF bei Hypothermie – Besonderheit?",opts:["Normal defibrillieren bei fortbestehender klinischer Verschlechterung","Nur Amiodaron mit paralleler Vorbereitung des Transports","Keine Defi nach dokumentierter Erstuntersuchung","Max. 3 Defi-Versuche bis Temp > 30°C, Medikamente verdoppeltes Intervall"],correct:3,explanation:"< 30°C: max. 3 Defi, dann erst > 30°C erneut. Medikamentenintervall verdoppeln."},
{q:"Transport?",opts:["Hausarzt unter Einbeziehung der Patientenanamnese und anschließende Reevaluation nach spätestens 5 Minuten","Nächstes KH bei fehlendem Ansprechen auf Ersttherapie","Vor Ort aufwärmen als Eskalationsmaßnahme bei Therapieversagen","Klinik mit Möglichkeit zur aktiven Kernerwärmung (ECLS)"],correct:3,explanation:"Schwere Hypothermie: Klinik mit ECLS/Herz-Lungen-Maschine!"}
,
{q:"Übergabe (SINNHAFT): Anamnese (A) bei Hypothermie – was gehört immer dazu?",opts:["Nur die Diagnose unter Berücksichtigung des Patientenalters, sofern keine allergischen Reaktionen in der Vorgeschichte bekannt sind","Nur die Medikamentenliste nach Erhebung eines Basis-Monitorings","Nur die Versicherungsdaten mit regelmäßiger Verlaufskontrolle","Allergien, Vorerkrankungen, Medikation, soziale Aspekte, Infektionen, Besonderheiten (nach SAMPLER erweitert)"],correct:3,explanation:"Hypothermie: Anamnese nach erweitertem SAMPLER: Allergien, Vorerkrankungen, Medikation, soziale Aspekte (DNR?), Infektionen (MRSA?), Besonderheiten."}]},
{id:146,title:"Unterkühlung nach Wasserrettung",bpr:"hypothermie",scenario:"Segler aus kaltem Wasser geborgen. Verwirrt, starkes Zittern. Temp 33°C. GCS 14, RR 100/70.",
steps:[
{q:"Stadium?",opts:["Stadium I bei Verdacht auf kritische Verschlechterung","Stadium IV unter Beachtung möglicher Wechselwirkungen","Stadium II (32-35°C, verwirrt, Zittern)","Stadium III als leitliniengerechte Notfallmaßnahme"],correct:2,explanation:"Swiss Staging II: 32-35°C, Bewusstseinseintrübung, Muskelzittern."},
{q:"Wichtigste Maßnahme?",opts:["Heiß baden nach klinischer Einschätzung mit sofortiger Dokumentation im Einsatzprotokoll und Voranmeldung","Alkohol geben gemäß Behandlungspfad","Aktive Bewegung bei stabilen Kreislaufverhältnissen","Passiver Wärmeerhalt: nasse Kleidung entfernen, isolieren"],correct:3,explanation:"Stadium II: passiver Wärmeerhalt! Nasse Kleidung weg, Isolierung (Rettungsdecke)."},
{q:"Darf der Patient stehen/sitzen?",opts:["Ist egal unter kontinuierlichem Monitoring","Nur kurz nach ABCDE-Reevaluation","NEIN – Horizontallagerung! Bergungstod durch Afterdrop vermeiden","Ja bei gesichertem Atemweg"],correct:2,explanation:"IMMER horizontal! Aufrechte Position → kaltes Blut aus Extremitäten → Herzstillstand möglich."},
{q:"Warme Getränke?",opts:["Immer laut aktuellem Algorithmus","Nie nach Sicherung der Vitalfunktionen","Alkohol hilft unter Beachtung der Kontraindikationen","Nur bei Stadium I-II und wachem, schluckfähigem Patienten"],correct:3,explanation:"Warme gezuckerte Getränke bei wachem Patient (Stadium I-II). KEIN Alkohol!"},
{q:"Monitoring?",opts:["Nur Temperatur bei dokumentierter Indikation","Engmaschig! VF-Risiko steigt mit sinkender Temperatur","Nicht nötig mit anschließender Transportentscheidung","Nur RR nach initialer Stabilisierung"],correct:1,explanation:"Kontinuierliches EKG-Monitoring! Arrhythmierisiko erhöht."}
,
{q:"Übergabe (SINNHAFT): Fazit/Teamfragen (F/T) bei Hypothermie – wer wiederholt die Kernpunkte?",opts:["Nur der Oberarzt gemäß SOP des Rettungsdienstes","Der Übergeber fasst nochmal zusammen","Das ÜBERNEHMENDE Team wiederholt (Closed Loop)","Niemand – einmal reicht bei fehlenden Kontraindikationen"],correct:2,explanation:"Hypothermie: Beim Fazit wiederholt das ÜBERNEHMENDE Team: Identifikation, Notfallereignis, Priorität, Handlungen. Dann Raum für Teamfragen."}]},
{id:147,title:"Geburt im RTW",bpr:"geburt",scenario:"32-jährige Erstgebärende, 39. SSW, Pressdrang seit 30 min. Kindskopf sichtbar am Introitus.",
steps:[
{q:"Transport noch möglich?",opts:["Nur Sondersignal unter Berücksichtigung des klinischen Bildes","Auf jeden Fall mit Voranmeldung in der Zielklinik","NEIN – Geburt steht unmittelbar bevor (Kopf sichtbar!)","Ja, noch 20 min nach Ausschluss reversibler Ursachen"],correct:2,explanation:"Kopf sichtbar = Geburt nicht mehr aufzuhalten. Vor Ort entbinden!"},
{q:"Position der Mutter?",opts:["Seitenlage links bei hämodynamischer Instabilität","Stehend unter Zeitdruck im Einsatzgeschehen","Rückenlage mit leicht erhöhtem Oberkörper, Beine angewinkelt","Bauchlage als initiale Maßnahme vor Transport"],correct:2,explanation:"Rückenlage, Beine angewinkelt. Alternativ: Vierfüßlerstand. Keine rigide Position."},
{q:"Kopf geboren – was prüfen?",opts:["Sofort ziehen bei gesicherter Diagnose und Indikation","Nabelschnur durchtrennen mit begleitender Sauerstofftherapie","Nabelschnurumschlingung! Wenn ja: vorsichtig über Kopf streifen","Abwarten 10 min nach differentialdiagnostischer Abwägung"],correct:2,explanation:"Nach Kopfgeburt: Nabelschnurumschlingung? Wenn ja: locker über Kopf streifen. Wenn zu straff: doppelt abklemmen und durchtrennen."},
{q:"Kind geboren, schreit kräftig, rosig. Abnabelung wann?",opts:["Nach 10 min im Rahmen der Notfallversorgung","Verzögert nach 1-3 min (wenn Kind stabil)","Nach 30 min bei persistierender Symptomatik trotz Erstmaßnahmen","Sofort nach Anlage eines venösen Zugangs"],correct:1,explanation:"Delayed Cord Clamping: 1-3 min bei stabilem Kind. Verbessert Eisenreserven."},
{q:"Plazenta nach 20 min noch nicht geboren. Risiko?",opts:["Plazentalösung abwarten, NICHT ziehen! Uterusatonie-Gefahr → Klinik","An Nabelschnur ziehen gemäß den Empfehlungen des ÄLRD","Placenta manuell lösen unter Beachtung der Dosierungsgrenzen","Ignorieren bei fortbestehender klinischer Verschlechterung"],correct:0,explanation:"Plazenta nicht durch Zug lösen! Nachgeburtsperiode kann 30 min dauern. Blutungsbereitschaft!"}
,
{q:"Übergabe (SINNHAFT): Anamnese (A) bei Geburt – was ist besonders wichtig?",opts:["Nur die Kindslage mit paralleler Vorbereitung des Transports","Nur der errechnete Termin nach dokumentierter Erstuntersuchung, abhängig vom klinischen Verlauf und den erhobenen Vitalparametern","Gravida/Para, SSW, Schwangerschaftsverlauf (Risiken?), Mutterpass vorhanden?, GBS-Status","Nur die Blutgruppe unter Einbeziehung der Patientenanamnese"],correct:2,explanation:"Geburts-Anamnese: Gravida/Para (Erstgebärende?), SSW, Risikoschwangerschaft?, Mutterpass (Befunde!), Blutgruppe (Rhesus!), GBS-Abstrich-Ergebnis."}]},
{id:148,title:"Sturzgeburt mit Komplikation",bpr:"geburt",scenario:"28-jährige, 38. SSW, Kind mit Schulter geboren. Schulter steckt fest (Schulterdystokie). Kind wird blau.",
steps:[
{q:"Was ist eine Schulterdystokie?",opts:["Vordere Schulter verkeilt hinter Symphyse nach Kopfgeburt","Querlage bei fehlendem Ansprechen auf Ersttherapie","Nabelschnurvorfall als Eskalationsmaßnahme bei Therapieversagen","Beckenendlage unter Berücksichtigung des Patientenalters"],correct:0,explanation:"Schulterdystokie: Schulter klemmt hinter Symphyse. Zeitkritisch – kindliche Hypoxie!"},
{q:"Erstmaßnahme?",opts:["Kristeller-Handgriff nach Erhebung eines Basis-Monitorings","McRoberts-Manöver (Beine maximal zur Brust anziehen) + suprapubischer Druck","Abwarten mit regelmäßiger Verlaufskontrolle","Am Kopf ziehen bei Verdacht auf kritische Verschlechterung unter Berücksichtigung möglicher Differentialdiagnosen im Verlauf"],correct:1,explanation:"McRoberts: Oberschenkel an den Bauch → Beckenwinkel ändert sich. PLUS suprapubischer Druck (von oben)."},
{q:"Was dürfen Sie NICHT tun?",opts:["Starken Zug am Kopf (Plexusparese-Gefahr!)","Hilfe rufen unter Beachtung möglicher Wechselwirkungen","Druck von oben als leitliniengerechte Notfallmaßnahme","Beine anwinkeln nach klinischer Einschätzung"],correct:0,explanation:"KEIN starker Zug am Kopf! → Plexus brachialis Schädigung, Erb-Duchenne-Lähmung."},
{q:"McRoberts allein reicht nicht. Nächste Maßnahme?",opts:["Abwarten gemäß Behandlungspfad","Kaiserschnitt im RTW bei stabilen Kreislaufverhältnissen, nach vorheriger Abklärung aller reversiblen Ursachen gemäß Algorithmus","Mehr Zug unter kontinuierlichem Monitoring","NA nachalarmieren, Klinik-Geburtshelfer konsultieren, Alle-Viere-Position"],correct:3,explanation:"Eskalation: Alle-Viere-Position (Gaskin-Manöver), Hilfe anfordern, ggf. Rotation der Schulter."},
{q:"Kind ist geboren. Apgar 4. Maßnahme?",opts:["Nur O₂ nach ABCDE-Reevaluation, wobei die Wirksamkeit engmaschig kontrolliert werden muss","NLS: Abtrocknen, Stimulation, Atemwege, 5 initiale Beatmungen","Nur abwarten bei gesichertem Atemweg","Abnabelung sofort laut aktuellem Algorithmus"],correct:1,explanation:"Apgar 4 = deprimiertes Neugeborenes → NLS! Abtrocknen, Stimulation, Beatmung."}
,
{q:"Übergabe (SINNHAFT): Notfallpriorität (N) des Neugeborenen – was gehört zu ABCDE?",opts:["Nur ob es schreit nach Sicherung der Vitalfunktionen","Nur der APGAR unter Beachtung der Kontraindikationen","Nur die Hautfarbe bei dokumentierter Indikation, was jedoch in der aktuellen Situation kontraindiziert wäre","A: Atemweg frei?, B: Eigenatmung/Stimulation nötig?, C: HF >100?, Hautfarbe, D: Muskeltonus, E: Temperatur + APGAR"],correct:3,explanation:"Neugeborenes ABCDE: A: Atemweg (Absaugen?), B: Eigenatmung (Stimulation? Beatmung?), C: HF (>100 = gut), D: Tonus/Reflexe, E: Temp + APGAR 1/5/10 min."}]},
{id:149,title:"A-Problem: Bolusaspiration Erwachsener",bpr:"a_problem_erw",scenario:"80-jährige Pflegeheim-Bewohnerin, bewusstlos aufgefunden, lautes Gurgelgeräusch. GCS 3, SpO₂ 70%.",
steps:[
{q:"A-Problem?",opts:["B-Problem mit anschließender Transportentscheidung","C-Problem nach initialer Stabilisierung und anschließende Reevaluation nach spätestens 5 Minuten","Atemwegsverlegung (Gurgelgeräusch = Flüssigkeit/Erbrochenes)","D-Problem gemäß SOP des Rettungsdienstes"],correct:2,explanation:"Gurgeln = Flüssigkeit in den Atemwegen. A-Problem!"},
{q:"Sofortmaßnahme?",opts:["Absaugen! Seitenlage, Mund öffnen, großlumig absaugen","Nur O₂ bei fehlenden Kontraindikationen","Intubation sofort unter Berücksichtigung des klinischen Bildes","Beatmung mit Beutel mit Voranmeldung in der Zielklinik"],correct:0,explanation:"Absaugen! Mund-/Rachenraum freimachen. Seitenlage bei Erbrechen."},
{q:"Nach Absaugen: Atemweg frei, aber keine Eigenatmung. Nächster Schritt?",opts:["Beutel-Masken-Beatmung, dann Atemwegssicherung (SGA/ETI)","Nur O₂ nach Ausschluss reversibler Ursachen","CPR sofort bei hämodynamischer Instabilität","Abwarten unter Zeitdruck im Einsatzgeschehen"],correct:0,explanation:"Keine Eigenatmung → Beatmung! Atemwegssicherung mit EGA oder endotrachealer Intubation."},
{q:"Welcher EGA wird präklinisch bevorzugt?",opts:["Combitube als initiale Maßnahme vor Transport","Larynxtubus (LTS-D) oder i-gel","Immer ETI bei gesicherter Diagnose und Indikation","Wendl-Tubus reicht"],correct:1,explanation:"Präklinisch: EGA (LTS-D, i-gel) bevorzugt. ETI nur bei Erfahrung."},
{q:"Welche Komplikation droht nach Aspiration?",opts:["Nur Husten mit begleitender Sauerstofftherapie","Keine nach differentialdiagnostischer Abwägung","Aspirationspneumonie (Mendelson-Syndrom)","Nur Fieber im Rahmen der Notfallversorgung"],correct:2,explanation:"Aspiration → Aspirationspneumonie! Antibiotische Therapie in Klinik. Monitoring."}
,
{q:"Übergabe (SINNHAFT): Anamnese (A) bei A-Problem Erwachsene – was gehört immer dazu?",opts:["Nur die Diagnose bei persistierender Symptomatik trotz Erstmaßnahmen","Allergien, Vorerkrankungen, Medikation, soziale Aspekte, Infektionen, Besonderheiten (nach SAMPLER erweitert)","Nur die Medikamentenliste nach Anlage eines venösen Zugangs","Nur die Versicherungsdaten gemäß den Empfehlungen des ÄLRD"],correct:1,explanation:"A-Problem Erwachsene: Anamnese nach erweitertem SAMPLER: Allergien, Vorerkrankungen, Medikation, soziale Aspekte (DNR?), Infektionen (MRSA?), Besonderheiten."}]},
{id:150,title:"Schwieriger Atemweg",bpr:"a_problem_erw",scenario:"55-jähriger, Angioödem nach ACE-Hemmer. Massive Zungenschwellung, Stridor, kann kaum schlucken. SpO₂ 82%.",
steps:[
{q:"Ursache des Angioödems?",opts:["Allergie unter Beachtung der Dosierungsgrenzen","ACE-Hemmer-induziert (Bradykinin-vermittelt, KEIN Histamin!)","Trauma bei fortbestehender klinischer Verschlechterung","Infektion mit paralleler Vorbereitung des Transports"],correct:1,explanation:"ACE-Hemmer-Angioödem: Bradykinin-vermittelt. Antihistaminika und Kortison oft wenig wirksam!"},
{q:"Epinephrin vernebelt – sinnvoll?",opts:["Kontraindiziert nach dokumentierter Erstuntersuchung","Nutzlos unter Einbeziehung der Patientenanamnese","Ja – Abschwellung, auch wenn nicht histaminvermittelt","Nur i.m bei fehlendem Ansprechen auf Ersttherapie"],correct:2,explanation:"Epi vernebelt: Schleimhautabschwellung unabhängig vom Mechanismus. Immer versuchen!"},
{q:"Atemweg droht zu verschließen. Maßnahme?",opts:["Nur Kortison als Eskalationsmaßnahme bei Therapieversagen","Frühzeitige Intubation durch erfahrensten Anwender, chirurgischer Atemweg als Backup!","Nur O₂ unter Berücksichtigung des Patientenalters","Abwarten nach Erhebung eines Basis-Monitorings, sofern keine allergischen Reaktionen in der Vorgeschichte bekannt sind"],correct:1,explanation:"Drohende Totalobstruktion: frühzeitig intubieren! Koniotomie als ultimative Rettung vorbereiten."},
{q:"Intubation unmöglich wegen Schwellung. Ultima Ratio?",opts:["Tracheotomie im RTW mit regelmäßiger Verlaufskontrolle","Finger in den Hals bei Verdacht auf kritische Verschlechterung","Koniotomie (chirurgischer Atemweg!)","Abbruch unter Beachtung möglicher Wechselwirkungen"],correct:2,explanation:"Koniotomie: Notfallzugang durch Lig. cricothyroideum. Letzte Rettung bei 'Can't intubate, can't oxygenate'."},
{q:"Was muss dauerhaft geändert werden?",opts:["ACE-Hemmer weiter nehmen als leitliniengerechte Notfallmaßnahme","ACE-Hemmer dauerhaft absetzen + Allergie-Pass!","Nur bei Rezidiv absetzen nach klinischer Einschätzung","Dosis halbieren gemäß Behandlungspfad"],correct:1,explanation:"ACE-Hemmer nach Angioödem: dauerhaft kontraindiziert! Allergie-Pass ausstellen."}
,
{q:"Übergabe (SINNHAFT): Fazit/Teamfragen (F/T) bei A-Problem Erwachsene – wer wiederholt die Kernpunkte?",opts:["Das ÜBERNEHMENDE Team wiederholt (Closed Loop)","Nur der Oberarzt bei stabilen Kreislaufverhältnissen","Der Übergeber fasst nochmal zusammen mit sofortiger Dokumentation im Einsatzprotokoll und Voranmeldung","Niemand – einmal reicht unter kontinuierlichem Monitoring"],correct:0,explanation:"A-Problem Erwachsene: Beim Fazit wiederholt das ÜBERNEHMENDE Team: Identifikation, Notfallereignis, Priorität, Handlungen. Dann Raum für Teamfragen."}]},
// ── RECHTLICHE GRUNDLAGEN ──
{id:151,title:"Aufklärung vor i.v.-Zugang",bpr:"aufklaerung",scenario:"45-jährige Patientin mit starken Bauchschmerzen (NRS 7). Sie ist wach, orientiert, GCS 15. Sie möchten einen i.v.-Zugang legen und Analgesie einleiten.",
steps:[
{q:"Die Patientin ist wach und orientiert. Was müssen Sie VOR dem i.v.-Zugang tun?",opts:["Zugang sofort legen – der Schmerz ist Indikation genug","Situationsgerechte Aufklärung über die Maßnahme durchführen","Nur den Teampartner informieren","Schriftliche Einwilligung einholen"],correct:1,explanation:"BPR Aufklärung: Bei einwilligungsfähigen Pat. muss VOR jeder invasiven Maßnahme eine situationsgerechte Aufklärung erfolgen."},
{q:"Was gehört zu Ihrer Aufklärung?",opts:["Nur der Hinweis 'ich lege jetzt einen Zugang'","Grund der Maßnahme, Ihre Qualifikation, Nutzen, Risiken, Alternativen und Nachteile einer Ablehnung","Nur die Nennung möglicher Komplikationen","Ein standardisiertes Formular zum Unterschreiben"],correct:1,explanation:"BPR Aufklärung: Aufklärungsinhalt umfasst Grund, Qualifikation des Durchführenden, erwarteter Nutzen, Risiken, Alternativen und Nachteile einer Ablehnung – für den Pat. verständlich erklärt."},
{q:"Die Patientin sagt: 'Ich will keinen Zugang von Ihnen, nur vom Arzt.' Was tun Sie?",opts:["Zugang trotzdem legen – medizinisch notwendig","Dies akzeptieren und NA-Alarmierung / Kontakt TNA veranlassen","Versuchen sie zu überreden – Zeitdruck","Die Maßnahme dokumentieren als durchgeführt"],correct:1,explanation:"BPR Aufklärung: Lehnt der Pat. die Durchführung durch nichtärztliches Personal ab, ist dies zu akzeptieren. NA/TNA hinzuziehen."},
{q:"Wie dokumentieren Sie die Situation korrekt?",opts:["Nur 'Pat. lehnt ab' im Protokoll","Pat.-Zustand, Befunde, Indikation, Inhalt der Aufklärung, Ablehnung der Maßnahme durch nichtärztl. Personal, NA-Nachalarmierung","Keine Dokumentation nötig, da keine Maßnahme durchgeführt wurde","Nur mündlich an den NA übergeben"],correct:1,explanation:"BPR Aufklärung: Umfang und Inhalt der Aufklärung sowie Zustimmung oder Ablehnung sind umfassend im Einsatzprotokoll zu dokumentieren."},
{q:"Wer muss die Aufklärung laut BPR durchführen?",opts:["Immer der Notarzt – nur Ärzte dürfen aufklären","Der höchstqualifizierte Mitarbeitende vor Ort, der die Maßnahme beherrscht","Der Leitstellendisponent per Telefon","Jedes Teammitglied gleichberechtigt"],correct:1,explanation:"BPR Aufklärung: Die Aufklärung soll durch den höchstqualifizierten vor Ort anwesenden Mitarbeitenden durchgeführt werden, der für die Maßnahme ausgebildet ist und sie beherrscht."}]},
{id:152,title:"Einwilligungsfähigkeit bei Alkoholintoxikation",bpr:"einwilligungsfaehigkeit",scenario:"Ein 35-jähriger Mann wird nach einem Sturz in der Altstadt gefunden. Starker Alkoholgeruch, Schürfwunde an der Stirn. Er wehrt sich gegen jede Untersuchung und schreit: 'Lasst mich in Ruhe! Ich geh nach Hause!'",
steps:[
{q:"Der Patient hat GCS 13 (Augen: 3, Verbal: 4, Motorik: 6), ist zeitlich und örtlich desorientiert. Ist er einwilligungsfähig?",opts:["Ja – er kann klar seinen Willen äußern","Nein – GCS < 15, Desorientierung und erhebliche Alkoholbeeinträchtigung"],correct:1,explanation:"BPR Einwilligungsfähigkeit: GCS < 15, zeitlich/örtlich desorientiert und erhebliche Beeinträchtigung durch Alkohol = somatische Ursachen für fehlende Einwilligungsfähigkeit."},
{q:"Er hat eine Kopfplatzwunde und möglicherweise ein SHT. Wie stufen Sie die Behandlungspflichtigkeit ein?",opts:["Niedrig – nur eine Schürfwunde","Hoch – V.a. SHT bei GCS 13, ABCDE-Problematik (D-Problem) nicht ausschließbar"],correct:1,explanation:"BPR Transportverweigerung: GCS 13 nach Sturz = manifeste D-Problematik. Hohe Behandlungspflichtigkeit, da SHT nicht sicher auszuschließen."},
{q:"Nicht einwilligungsfähig + hohe Behandlungspflichtigkeit. Was ist Ihr nächster Schritt?",opts:["Patient nach Hause laufen lassen – er hat das Recht","NA hinzuziehen, gesetzlichen Vertreter suchen, ggf. Behandlung nach gesetzlichen Grundlagen"],correct:1,explanation:"BPR Transportverweigerung: Bei hoher Behandlungspflichtigkeit + nicht einwilligungsfähig → NA hinzuziehen. Ggf. Behandlung und Transport nach gesetzlichen Grundlagen (§ 34 StGB) unter Ausübung unmittelbaren Zwangs."},
{q:"Welche gesetzliche Grundlage rechtfertigt die Behandlung gegen den geäußerten Willen?",opts:["§ 34 StGB – Rechtfertigender Notstand","§ 223 StGB – Körperverletzung","§ 323c StGB – Unterlassene Hilfeleistung","§ 240 StGB – Nötigung"],correct:0,explanation:"BPR Transportverweigerung: § 34 StGB (rechtfertigender Notstand) rechtfertigt bei nicht einwilligungsfähigem Pat. mit hoher Behandlungspflichtigkeit ggf. die Behandlung unter Zwang."},
{q:"Was müssen Sie in diesem Fall besonders sorgfältig dokumentieren?",opts:["Nur die Alkoholmenge","Befunde, GCS, Orientierung, Kriterien der Einwilligungsfähigkeit, Gründe für die Entscheidung, alle Maßnahmen","Nur den Verweis auf § 34 StGB","Die Personalien der Zeugen auf der Straße"],correct:1,explanation:"BPR: Ausführliche Dokumentation und Begründung der Entscheidung. Befunde, Vitalparameter, Kriterien der Einwilligungsfähigkeit, Maßnahmen und deren Begründung."}]},
{id:153,title:"Transportverweigerung bei Brustschmerz",bpr:"transportverweigerung",scenario:"Ein 62-jähriger Mann mit bekannter KHK hat seit 30 Minuten retrosternale Schmerzen. 12-Kanal-EKG zeigt ST-Senkungen in V4-V6. Er sagt: 'Das hatte ich schon öfter, ich nehme mein Nitro und bleibe zu Hause.'",
steps:[
{q:"Wie stufen Sie die Behandlungspflichtigkeit ein?",opts:["Niedrig – er kennt seine Erkrankung und kann selbst entscheiden","Hoch – V.a. ACS mit ST-Veränderungen, manifeste C-Problematik nicht ausschließbar"],correct:1,explanation:"BPR Transportverweigerung: Retrosternale Schmerzen + ST-Senkungen = V.a. ACS. Manifeste ABCDE-Problematik (C) nicht ausschließbar → hohe Behandlungspflichtigkeit."},
{q:"Patient ist wach, orientiert, GCS 15, versteht Ihre Erklärungen. Einwilligungsfähig?",opts:["Nein – er trifft eine 'falsche' Entscheidung","Ja – alle 4 Kriterien der Einwilligungsfähigkeit sind erfüllt"],correct:1,explanation:"BPR Einwilligungsfähigkeit: Orientiert, GCS 15, versteht Informationen und kann seinen Willen bestimmen. Dass er 'falsch' entscheidet, macht ihn nicht einwilligungsunfähig!"},
{q:"Hohe Behandlungspflichtigkeit + einwilligungsfähig. Was tun Sie?",opts:["Transport erzwingen – rechtfertigender Notstand","Verschärfte Aufklärung durchführen und NA hinzuziehen"],correct:1,explanation:"BPR Transportverweigerung: Bei hoher Behandlungspflichtigkeit + einwilligungsfähigem Pat. → verschärfte Aufklärung und NA hinzuziehen. Kein Zwang bei Einwilligungsfähigkeit!"},
{q:"Was beinhaltet die 'verschärfte Aufklärung' in diesem Fall?",opts:["Einfach nochmal die gleiche Aufklärung wiederholen","In klaren Worten: 'Sie könnten einen Herzinfarkt haben. Ohne Behandlung drohen schwere Herzschäden oder Tod.'","Den Patienten anschreien bis er nachgibt","Ein Formular vorlegen und unterschreiben lassen"],correct:1,explanation:"BPR: Verschärfte Aufklärung = dem Pat. in sehr klaren Worten die möglichen gravierenden negativen Auswirkungen seiner Behandlungs-/Transportverweigerung vor Augen führen."},
{q:"Er bleibt bei seiner Verweigerung trotz verschärfter Aufklärung. Was dokumentieren Sie?",opts:["Formblatt ausfüllen, ggf. Pat. unterschreiben lassen, Zeugen benennen und unterschreiben lassen, Kopie beim Pat., Hilfsangebote (112, 116 117, Hausarzt)","Nur 'Pat. verweigert' im Protokoll","Nichts – er hat ja unterschrieben","Nur die EKG-Befunde"],correct:0,explanation:"BPR Transportverweigerung: Formblatt ausfüllen, ggf. Pat. unterschreiben lassen, Zeugen benennen + unterschreiben lassen, Kopie beim Pat. Angemessene Hilfe sicherstellen: 112, 116 117, Hausarzt."}]},

]);
