// NotSanTrainer 2025 - Fallsimulationen (Teil 3/4, Fälle 77-114)
CASES = CASES.concat([
{id:77,title:"Großflächige Verbrennung Erwachsener",bpr:"thermisch",scenario:"40-Jähriger, Grillunfall mit Spiritus. Flammenverbrennung Oberkörper, Arme, Gesicht. VKOF ca. 30%. Rußpartikel im Gesicht, heisere Stimme.",
steps:[
{q:"Worauf weist die heisere Stimme hin?",opts:["V.a. Inhalationstrauma!","Erkältung gemäß den Empfehlungen des ÄLRD","Raucherproblem","Normal bei Schmerz"],correct:0,explanation:"Rußspuren + heisere Stimme + Exposition = V.a. Inhalationstrauma. Atemwegschwellung droht!"},
{q:"Volumentherapie beim Erwachsenen?",opts:["Kein Volumen unter Beachtung der Dosierungsgrenzen","Unbegrenzt bei fortbestehender klinischer Verschlechterung","Max. 1 l/h VEL (gewärmt)","Nur 250 ml mit paralleler Vorbereitung des Transports"],correct:2,explanation:"Erwachsene mit schweren Verbrennungen: Max. 1 l/h VEL (angewärmt). Überinfusion vermeiden!"},
{q:"Intubation bei V.a. Inhalationstrauma?",opts:["Nie präklinisch nach dokumentierter Erstuntersuchung","Nur bei SpO₂ < 70% unter Einbeziehung der Patientenanamnese","Sofort immer bei fehlendem Ansprechen auf Ersttherapie","Kritisch prüfen – nur bei klarer Indikation (Hypothermiegefahr durch Beatmung!)"],correct:3,explanation:"Indikation zur invasiven Atemwegssicherung kritisch bewerten – auch wegen Hypothermiegefahr. Stabiler Patient: nicht prophylaktisch intubieren."},
{q:"Wie schätzen Sie die VKOF beim Erwachsenen?",opts:["Nur Augenmaß als Eskalationsmaßnahme bei Therapieversagen","Wiegen unter Berücksichtigung des Patientenalters","9er-Regel nach Wallace","Handflächenregel"],correct:2,explanation:"9er-Regel: Kopf 9%, Arm je 9%, Bein je 18%, Rumpf vorne 18%, Rumpf hinten 18%, Genital 1%."},
{q:"Ab welcher VKOF sollte der Erwachsene ins Verbrennungszentrum?",opts:["Ab 5% nach Erhebung eines Basis-Monitorings","Ab 50% mit regelmäßiger Verlaufskontrolle","Alle bei Verdacht auf kritische Verschlechterung","Ab ca. 20% VKOF oder Gesicht/Hände/Füße/Genital oder Inhalation"],correct:3,explanation:"Verbrennungszentrum: ≥20% VKOF, Gesicht/Hände/Füße/Genital, Inhalationstrauma, zirkuläre Verbrennungen, Strom."}
,
{q:"Übergabe (SINNHAFT): Notfallpriorität (N) bei Thermische Verletzung/Verbrennung – nach welcher Struktur?",opts:["Nach persönlichem Ermessen unter Beachtung möglicher Wechselwirkungen","Alphabetisch nach Befunden als leitliniengerechte Notfallmaßnahme","Nach Dringlichkeit der Diagnostik nach klinischer Einschätzung","Nach dem (x)ABCDE-Schema mit pathologischen Befunden und Vitalparametern"],correct:3,explanation:"Thermische Verletzung/Verbrennung: Notfallpriorität IMMER nach ABCDE strukturiert. Pathologische Befunde + Vitalparameter pro Buchstabe, auffällige Befunde hervorheben."}]},
{id:78,title:"Verätzung mit Säure",bpr:"thermisch",scenario:"Chemiearbeiter, Salzsäure auf linken Arm und Hand gespritzt. Starke Schmerzen, Hautrötung und Blasenbildung.",
steps:[
{q:"Erste Maßnahme bei Verätzung?",opts:["Spülung mit viel Wasser (Eigenschutz beachten!)","Kühlpack gemäß Behandlungspfad, abhängig vom klinischen Verlauf und den erhobenen Vitalparametern","Neutralisation bei stabilen Kreislaufverhältnissen","Verband anlegen unter kontinuierlichem Monitoring"],correct:0,explanation:"Verätzung: Spülung mit viel Wasser. KEINE Neutralisation! Eigenschutz beachten."},
{q:"Wie behandeln Sie die Verbrennung/Verätzung im Rettungsdienst?",opts:["Nur Beobachtung nach ABCDE-Reevaluation","Aktive Kühlung bei gesichertem Atemweg","Steriles trockenes Abdecken + Schmerztherapie + VEL + Wärmeerhalt","Salbenverband laut aktuellem Algorithmus"],correct:2,explanation:"Sterile trockene Abdeckung, Schmerztherapie, Volumentherapie bei Bedarf, Wärmeerhalt."},
{q:"Transport?",opts:["Nächste Apotheke nach Sicherung der Vitalfunktionen","Ambulant unter Beachtung der Kontraindikationen","Hausarzt bei dokumentierter Indikation unter Berücksichtigung möglicher Differentialdiagnosen im Verlauf","Klinik nach regionalem Zuweisungskonzept (ggf. Verbrennungszentrum)"],correct:3,explanation:"Transport nach regionalem Zuweisungskonzept. Bei schweren Verätzungen: Verbrennungszentrum."},
{q:"Wie lange spülen Sie die Verätzung?",opts:["Gar nicht mit anschließender Transportentscheidung","Mindestens 20 Minuten mit viel Wasser","1 Minute nach initialer Stabilisierung","5 Minuten gemäß SOP des Rettungsdienstes"],correct:1,explanation:"Verätzung spülen: Mindestens 20 Minuten mit viel fließendem Wasser. Kontaminierte Kleidung sofort entfernen."},
{q:"Was ist bei Flusssäure (HF) anders?",opts:["Nichts bei fehlenden Kontraindikationen","Nur Wasserspülung unter Berücksichtigung des klinischen Bildes","Nur oberflächlich mit Voranmeldung in der Zielklinik","Flusssäure penetriert tief, systemische Toxizität (Hypokaliämie, HRST) → Calciumgluconat!"],correct:3,explanation:"Flusssäure: Penetriert tief ins Gewebe, bindet Calcium → Hypokalzämie → HRST. Spezifisch: Calciumgluconat-Gel/i.v.!"}
,
{q:"Übergabe (SINNHAFT): Handlungen (H) bei Thermische Verletzung/Verbrennung – was wird oft vergessen?",opts:["Die Transportzeit nach Ausschluss reversibler Ursachen","Der Name des Fahrers bei hämodynamischer Instabilität","Bewusst unterlassene Maßnahmen und deren Begründung","Die Einsatznummer unter Zeitdruck im Einsatzgeschehen"],correct:2,explanation:"Thermische Verletzung/Verbrennung: Bei Handlungen nicht nur WAS getan wurde, sondern auch was bewusst NICHT getan wurde + Begründung. Ermöglicht dem Team die Entscheidung zu prüfen."}]},
{id:79,title:"Ungeplante Geburt im RTW",bpr:"geburt",scenario:"28-jährige Erstgebärende, 39. SSW. Presswehen, Kindskopf sichtbar. Transport in Klinik nicht mehr möglich.",
steps:[
{q:"Was ist die wichtigste Handlung bei sichtbarem Kopf?",opts:["Dammschutz = Kopfbremse, kontrollierte Geburt unterstützen","Versuchen den Kopf zurückzudrücken als initiale Maßnahme vor Transport","Sofort abnabeln bei gesicherter Diagnose und Indikation","Notruf absetzen mit begleitender Sauerstofftherapie"],correct:0,explanation:"Dammschutz = Kopfbremse. Kontrollierte Geburt: Kopf lateral fassen, dorsal senken → vordere Schulter, ventral heben → hintere Schulter."},
{q:"Wann abnabeln?",opts:["Erst in Klinik nach differentialdiagnostischer Abwägung","Sofort im Rahmen der Notfallversorgung","Nach 10 Minuten bei persistierender Symptomatik trotz Erstmaßnahmen","Nach 1 Minute, 15-20 cm vom Nabel entfernt"],correct:3,explanation:"Abnabeln nach 1 Minute Wartezeit, 15-20 cm vom Nabel entfernt."},
{q:"Was tun Sie NICHT?",opts:["Sauerstoff bereithalten","Zug an Kindsteilen oder Dammschnitt","Material bereitlegen nach Anlage eines venösen Zugangs","Dammschutz gemäß den Empfehlungen des ÄLRD"],correct:1,explanation:"KEIN Zug an Kindsteilen, KEIN Dammschnitt durch Rettungsdienstpersonal!"},
{q:"Wie versorgen Sie das Neugeborene nach der Geburt?",opts:["Sofort abnabeln unter Beachtung der Dosierungsgrenzen","Nur zudecken bei fortbestehender klinischer Verschlechterung","Abtrocknen, Wärmeerhalt, Atemwege freimachen, Beurteilung (APGAR nach 1 min)","Sofort waschen mit paralleler Vorbereitung des Transports"],correct:2,explanation:"Neugeborenenversorgung: Abtrocknen, Wärmeerhalt (Haut-auf-Haut/Handtuch), Atemwege freimachen, APGAR nach 1 + 5 min."},
{q:"Was sind Zeichen einer normalen Adaptation?",opts:["Blass, schlaff nach dokumentierter Erstuntersuchung","Nur Puls unter Einbeziehung der Patientenanamnese","Nur Schreien bei fehlendem Ansprechen auf Ersttherapie","Schreien, rosige Haut, guter Tonus, HF > 100"],correct:3,explanation:"Normale Adaptation: Kräftiges Schreien, rosige Haut, guter Muskeltonus, HF > 100/min, regelmäßige Atmung."}
,
{q:"Übergabe (SINNHAFT): Identifikation (I) bei Geburt – was kommt zusätzlich?",opts:["Nur das Geschlecht des Kindes als Eskalationsmaßnahme bei Therapieversagen","Mutter: Name, Alter + Kind: Geschlecht, APGAR, geschätztes Gewicht + SSW","Nur Name der Mutter unter Berücksichtigung des Patientenalters","Nur die SSW nach Erhebung eines Basis-Monitorings"],correct:1,explanation:"Bei Geburt: ZWEI Patienten übergeben! Mutter (Name, Alter) UND Kind (Geschlecht, APGAR, geschätztes Gewicht, SSW). Evtl. getrennte Übergaben."}]},
{id:80,title:"Postpartale Blutung",bpr:"geburt",scenario:"Außerklinische Geburt vor 15 min. Plazenta nicht geboren, zunehmende vaginale Blutung. Mutter: RR 90/55, HF 125, blass.",
steps:[
{q:"Was ist die Ursache der Blutung?",opts:["Dammriss mit regelmäßiger Verlaufskontrolle","Plazentaablösung normal bei Verdacht auf kritische Verschlechterung","V.a. Uterusatonie (häufigste Ursache postpartaler Blutung)","Nur normal unter Beachtung möglicher Wechselwirkungen, nach vorheriger Abklärung aller reversiblen Ursachen gemäß Algorithmus"],correct:2,explanation:"Uterusatonie = häufigste Ursache der postpartalen Blutung. Plazenta soll nicht vor Ort abgewartet werden."},
{q:"Sofortmaßnahme bei uteriner Atonie?",opts:["Tourniquet am Bein als leitliniengerechte Notfallmaßnahme","Transabdominales Halten und Anreiben der Gebärmutter + Harnblase entleeren","Furosemid nach klinischer Einschätzung","Abwarten auf Plazenta gemäß Behandlungspfad"],correct:1,explanation:"Uterusatonie: Uterus transabdominal halten und kräftig reiben (Kontraktionsreiz). Harnblase entleeren."},
{q:"Transport – wie dringlich?",opts:["Ambulant bei stabilen Kreislaufverhältnissen","Nachbetreuung Hebamme genügt","Kann warten unter kontinuierlichem Monitoring","Zeitkritisch – Klinik mit Geburtshilfe!"],correct:3,explanation:"Postpartale Blutung ist ein Notfall. Sofortiger Transport mit i.v.-Zugang und VEL-Gabe."},
{q:"Wie viel Blutverlust ist lebensbedrohlich?",opts:["Ab 500 ml → Klasse I Blutung. Ab 1000-1500 ml → Schock","2 Liter nach ABCDE-Reevaluation, wobei die Wirksamkeit engmaschig kontrolliert werden muss","100 ml bei gesichertem Atemweg","5 Liter laut aktuellem Algorithmus"],correct:0,explanation:"Postpartale Blutung: >500 ml kritisch, >1000 ml potenziell lebensbedrohlich. Schwangere kompensieren lange → dann plötzliche Dekompensation."},
{q:"Dürfen Sie Uterotonica geben?",opts:["Oxytocin i.v nach Sicherung der Vitalfunktionen","Ja, immer unter Beachtung der Kontraindikationen","Nur oral bei dokumentierter Indikation","Keine uteruswirksamen Medikamente durch NotSan – mechanische Maßnahmen!"],correct:3,explanation:"Uterotonica (Oxytocin) durch NotSan nicht vorgesehen. Mechanisch: Uterusmassage + Harnblasenentleerung. NA/Klinik: Oxytocin."}
,
{q:"Übergabe (SINNHAFT): Notfallereignis (N) bei außerklinischer Geburt – Kernfragen?",opts:["Nur die Wehenhäufigkeit mit anschließender Transportentscheidung","Nur ob es ein Junge oder Mädchen ist nach initialer Stabilisierung","Nur: Kind geboren gemäß SOP des Rettungsdienstes, was jedoch in der aktuellen Situation kontraindiziert wäre","WAS: Spontangeburt, WIE: Komplikationen? (Schulterdystokie, Nabelschnur-Umschlingung), WANN: Uhrzeit der Geburt"],correct:3,explanation:"Notfallereignis Geburt: Spontangeburt (komplikationslos?), etwaige Komplikationen, exakte Geburtszeit, Plazenta geboren?"}]},
{id:81,title:"Nabelschnurvorfall",bpr:"geburt",scenario:"Schwangere, 37. SSW, Blasensprung. RTW-Team sieht Nabelschnur in der Vagina. Kindliche Herztöne: bradykard.",
steps:[
{q:"Was ist die sofortige Maßnahme?",opts:["Nabelschnur abbinden bei fehlenden Kontraindikationen","Abwarten unter Berücksichtigung des klinischen Bildes","Geburt forcieren mit Voranmeldung in der Zielklinik","Nabelschnur hochschieben, Becken der Mutter erhöhen, sofortiger Transport"],correct:3,explanation:"Nabelschnurvorfall = absoluter Notfall. Nabelschnur manuell entlasten, Becken hoch (Knie-Ellenbogen-Lage), SOFORT Transport."},
{q:"Warum ist das ein Notfall?",opts:["Gefahr für Mutter nach Ausschluss reversibler Ursachen","Infektion bei hämodynamischer Instabilität","Blutungsgefahr unter Zeitdruck im Einsatzgeschehen","Nabelschnurkompression → fetale Hypoxie → Kindstod"],correct:3,explanation:"Die vorgefallene Nabelschnur wird durch den kindlichen Kopf komprimiert → fetale Hypoxie."},
{q:"Welches ist das richtige Transportziel?",opts:["Nächster Gynäkologe als initiale Maßnahme vor Transport","Geburtshaus bei gesicherter Diagnose und Indikation","Zu Hause entbinden mit begleitender Sauerstofftherapie","Nächste Klinik mit Möglichkeit zur Notfall-Sectio"],correct:3,explanation:"Sofort in Klinik mit Möglichkeit zur Notfall-Sectio (Kaiserschnitt). JEDE Minute zählt!"},
{q:"Welche Lagerung bei Nabelschnurvorfall?",opts:["Flach auf dem Rücken nach differentialdiagnostischer Abwägung","Oberkörper hoch im Rahmen der Notfallversorgung","Knie-Ellenbogen-Lage oder Becken hoch (Trendelenburg)","Seitenlage links bei persistierender Symptomatik trotz Erstmaßnahmen"],correct:2,explanation:"Knie-Ellenbogen-Lage: Entlastet den vorliegenden Kindsteil von der Nabelschnur. Alternativ: Becken mit Kissen erhöhen."},
{q:"Dürfen Sie die Nabelschnur zurückschieben?",opts:["Abbinden nach Anlage eines venösen Zugangs","Durchschneiden gemäß den Empfehlungen des ÄLRD und anschließende Reevaluation nach spätestens 5 Minuten","Manuell entlasten: vorliegenden Kindsteil hochdrücken, Nabelschnur feucht halten","Nein unter Beachtung der Dosierungsgrenzen"],correct:2,explanation:"Vorliegenden Kindsteil manuell hochschieben → Nabelschnurkompression reduzieren. Nabelschnur feucht halten (NaCl-getränkte Kompressen)."}
,
{q:"Übergabe (SINNHAFT): Handlungen (H) bei postpartaler Blutung – was ist entscheidend?",opts:["Nur ob die Plazenta geboren wurde bei fortbestehender klinischer Verschlechterung, sofern keine allergischen Reaktionen in der Vorgeschichte bekannt sind","Nur die Volumentherapie mit paralleler Vorbereitung des Transports","Geschätzter Blutverlust, Uterusmassage, Oxytocin (Dosis/Uhrzeit/Wirkung), Volumenmenge, Kind angelegt?","Nur der Transport nach dokumentierter Erstuntersuchung"],correct:2,explanation:"Postpartale Blutung: Blutverlust (geschätzt!), Uterusmassage (Wirkung?), Oxytocin (Dosis+Uhrzeit), Volumen, Plazenta geboren?, Kindanlegen (Atonieprophylaxe)."}]},
{id:82,title:"Verlegtes Tracheostoma mit Atemnot",bpr:"tracheostoma",scenario:"62-jähriger Patient mit Laryngektomie (kein Kehlkopf). Schwere Atemnot, zyanotisch. Tracheostoma verlegt.",
steps:[
{q:"Kann dieser Patient über Mund und Nase beatmet werden?",opts:["Ja, normal unter Einbeziehung der Patientenanamnese","NEIN – bei Laryngektomie führt der Weg über Mund/Nase NICHT zur Lunge","Nur mit Hilfsmittel bei fehlendem Ansprechen auf Ersttherapie","Manchmal als Eskalationsmaßnahme bei Therapieversagen"],correct:1,explanation:"Verschlossener Kehlkopf (Laryngektomie): Mund/Nase-Weg ist Sackgasse! Nur über Tracheostoma beatmbar."},
{q:"Algorithmus: Was prüfen Sie zuerst?",opts:["Beutel-Maske über Mund unter Berücksichtigung des Patientenalters mit sofortiger Dokumentation im Einsatzprotokoll und Voranmeldung","Aufsätze entfernen, Innenkanüle entfernen, Absaugkatheter einführen","Intubation nach Erhebung eines Basis-Monitorings","Seitenlage mit regelmäßiger Verlaufskontrolle"],correct:1,explanation:"Aufsätze/Filter entfernen → Innenkanüle entfernen → Absaugkatheter einführen → endobronchiales Absaugen."},
{q:"Absaugen nicht möglich, keine Besserung. Was nun?",opts:["Mund-zu-Mund bei Verdacht auf kritische Verschlechterung","Thoraxentlastungspunktion unter Beachtung möglicher Wechselwirkungen","Aufgeben als leitliniengerechte Notfallmaßnahme","Trachealkanüle komplett entfernen → Beutel-Tracheostoma-Beatmung"],correct:3,explanation:"Trachealkanüle entfernen. Dann: Beutel-Tracheostoma-Beatmung (Mund/Nase mit Hand verschließen)."},
{q:"Was ist der Unterschied zwischen Laryngektomie und Tracheostoma mit Kehlkopf?",opts:["Nur die Stimme nach klinischer Einschätzung","Nur Kanülengröße gemäß Behandlungspfad","Kein Unterschied bei stabilen Kreislaufverhältnissen","Laryngektomie: KEIN Weg über Mund/Nase zur Lunge. Mit Kehlkopf: Weg existiert noch"],correct:3,explanation:"Entscheidender Unterschied: Laryngektomie = Sackgasse über Mund/Nase. Durchgängiger Kehlkopf = Mund/Nase-Weg noch intakt."},
{q:"Was gehört zur Übergabe?",opts:["Art des Tracheostomas (Laryngektomie ja/nein), Kanülengröße, Grunderkrankung","Nur Medikamente unter kontinuierlichem Monitoring","Nur Allergien nach ABCDE-Reevaluation","Nur Name bei gesichertem Atemweg"],correct:0,explanation:"Entscheidende Übergabe: Laryngektomie ja/nein, Kanülenart/-größe, Grunderkrankung, was bereits versucht wurde."}
,
{q:"Übergabe (SINNHAFT): Notfallereignis (N) bei Tracheostoma-Notfall – welche Kerninfo?",opts:["WAS: Verdachtsdiagnose, WIE: Ursache/Auslöser, WANN: Symptombeginn mit exakter Uhrzeit","Nur die Diagnose nennen laut aktuellem Algorithmus","Nur den Transportweg nach Sicherung der Vitalfunktionen, abhängig vom klinischen Verlauf und den erhobenen Vitalparametern","Nur ob der Patient Schmerzen hat unter Beachtung der Kontraindikationen"],correct:0,explanation:"Tracheostoma-Notfall: Beim Notfallereignis immer WAS (Verdachtsdiagnose), WIE (Ursache/Auslöser), WANN (exakter Zeitpunkt) strukturiert übergeben."}]},
{id:83,title:"Tracheostoma-Notfall bei durchgängigem Kehlkopf",bpr:"tracheostoma",scenario:"45-jährige Frau mit Tracheostoma (durchgängiger Kehlkopf, Trachealkanüle). Akute Atemnot, Kanüle scheint verlegt.",
steps:[
{q:"Unterschied zum Laryngektomie-Patienten?",opts:["Kein Unterschied bei dokumentierter Indikation unter Berücksichtigung möglicher Differentialdiagnosen im Verlauf","Durchgängiger Kehlkopf → Mund/Nase-Weg zur Lunge existiert noch!","Patient spricht immer mit anschließender Transportentscheidung","Kanüle nie verstopft nach initialer Stabilisierung"],correct:1,explanation:"Bei durchgängigem Kehlkopf: Der Weg über Mund und Nase zur Lunge besteht noch (anders als bei Laryngektomie)."},
{q:"Absaugen und Kanülenentfernung ohne Erfolg. Was als Fallback?",opts:["Beutel-Masken-Beatmung über Mund/Nase (Tracheostoma mit Hand verschließen)","Nichts gemäß SOP des Rettungsdienstes","Thoraxentlastung bei fehlenden Kontraindikationen","Aufgeben unter Berücksichtigung des klinischen Bildes"],correct:0,explanation:"Bei durchgängigem Kehlkopf: Beutel-Masken-Beatmung über Mund/Nase möglich – Tracheostoma mit Hand verschließen."},
{q:"Sauerstoff – wo geben Sie ihn?",opts:["Nur über Tracheostoma mit Voranmeldung in der Zielklinik","Über Tracheostoma UND wenn möglich zusätzlich über Mund/Nase","Nur über Mund/Nase nach Ausschluss reversibler Ursachen","Nur über Maske bei hämodynamischer Instabilität"],correct:1,explanation:"Bei durchgängigem Kehlkopf: O₂ über Tracheostoma + wenn möglich zusätzlich über Mund/Nase."},
{q:"Wie beatmen Sie über ein Tracheostoma?",opts:["Beutel direkt auf Tracheostoma-Öffnung aufsetzen","Nur Sauerstoff daneben halten","Beutel auf Mund unter Zeitdruck im Einsatzgeschehen","Mund-zu-Tracheostoma als initiale Maßnahme vor Transport"],correct:0,explanation:"Beutel-Tracheostoma-Beatmung: Beutel direkt auf die Stoma-Öffnung aufsetzen. Bei Laryngektomie: Mund/Nase verschließen nicht nötig. Bei durchgängigem Kehlkopf: Mund/Nase verschließen."},
{q:"Welche Absaugkatheter-Größe verwenden Sie?",opts:["Egal bei gesicherter Diagnose und Indikation, nach vorheriger Abklärung aller reversiblen Ursachen gemäß Algorithmus","Katheter muss durch Kanüle/Stoma passen, halber Innendurchmesser der Kanüle","Nur dünne mit begleitender Sauerstofftherapie","Größte verfügbare nach differentialdiagnostischer Abwägung"],correct:1,explanation:"Absaugkatheter: Maximal halber Innendurchmesser der Trachealkanüle. Zu groß → kein Luftfluss neben Katheter."}
,
{q:"Übergabe (SINNHAFT): Notfallpriorität (N) bei Tracheostoma-Notfall – nach welcher Struktur?",opts:["Nach dem (x)ABCDE-Schema mit pathologischen Befunden und Vitalparametern","Nach Dringlichkeit der Diagnostik im Rahmen der Notfallversorgung","Alphabetisch nach Befunden bei persistierender Symptomatik trotz Erstmaßnahmen","Nach persönlichem Ermessen nach Anlage eines venösen Zugangs"],correct:0,explanation:"Tracheostoma-Notfall: Notfallpriorität IMMER nach ABCDE strukturiert. Pathologische Befunde + Vitalparameter pro Buchstabe, auffällige Befunde hervorheben."}]},
{id:84,title:"Tracheostoma-Blutung",bpr:"tracheostoma",scenario:"58-jähriger Patient mit Tracheostoma nach Tumor-OP. Blutung aus dem Tracheostoma, zunehmende Atemnot. SpO₂ fällt.",
steps:[
{q:"Was hat Priorität?",opts:["Atemweg sichern – endobronchiales Absaugen der Blutkoagel","Tourniquet am Hals gemäß den Empfehlungen des ÄLRD, wobei die Wirksamkeit engmaschig kontrolliert werden muss","Furosemid unter Beachtung der Dosierungsgrenzen","Blutungsquelle suchen bei fortbestehender klinischer Verschlechterung"],correct:0,explanation:"A-Problem hat Priorität! Absaugen von Blut und Koageln aus dem Tracheostoma → Atemweg freimachen."},
{q:"Wenn massive Blutung nicht kontrollierbar?",opts:["Sofortiger Transport mit Absaugbereitschaft – chirurgische Intervention nötig","Abwarten mit paralleler Vorbereitung des Transports","Tournqiuet nach dokumentierter Erstuntersuchung","Heparin unter Einbeziehung der Patientenanamnese"],correct:0,explanation:"Tracheostoma-Blutung nach Tumor-OP kann lebensbedrohlich sein – sofortiger Transport zur chirurgischen Versorgung."},
{q:"Was gehört in die Übergabe an die Klinik?",opts:["Art des Tracheostomas (Laryngektomie ja/nein), Kanülengröße, Grunderkrankung, Blutungsbeginn","Nur Name bei fehlendem Ansprechen auf Ersttherapie","Nur Medikamente als Eskalationsmaßnahme bei Therapieversagen","Nur Allergie unter Berücksichtigung des Patientenalters, was jedoch in der aktuellen Situation kontraindiziert wäre"],correct:0,explanation:"Klinik braucht: Art des Tracheostomas, Laryngektomie ja/nein, Kanülengröße, Grunderkrankung, Verlauf."},
{q:"Was könnte die Blutung verursachen?",opts:["Nur Medikamente nach Erhebung eines Basis-Monitorings","Nur Kanüle mit regelmäßiger Verlaufskontrolle","Arrosionsblutung bei Tumor, Granulationsgewebe, Tracheo-innominate-Fistel","Nur Erkältung bei Verdacht auf kritische Verschlechterung"],correct:2,explanation:"Ursachen: Arrosionsblutung (Tumor wächst in Gefäß), Granulationsgewebe, Tracheo-innominate-Fistel (lebensbedrohlich!)."},
{q:"Welche Lagerung bei Tracheostoma-Blutung?",opts:["Flach unter Beachtung möglicher Wechselwirkungen","Oberkörper hoch + stabile Seitenlage bei Bewusstseinseinschränkung","Kopftieflage als leitliniengerechte Notfallmaßnahme","Bauchlage nach klinischer Einschätzung und anschließende Reevaluation nach spätestens 5 Minuten"],correct:1,explanation:"Oberkörper hoch (weniger Blutfluss zum Hals). Bei Bewusstseinstrübung: Seitenlage für Aspirationsschutz."}
,
{q:"Übergabe (SINNHAFT): Handlungen (H) bei Tracheostoma-Notfall – was wird oft vergessen?",opts:["Der Name des Fahrers gemäß Behandlungspfad","Bewusst unterlassene Maßnahmen und deren Begründung","Die Transportzeit bei stabilen Kreislaufverhältnissen","Die Einsatznummer unter kontinuierlichem Monitoring"],correct:1,explanation:"Tracheostoma-Notfall: Bei Handlungen nicht nur WAS getan wurde, sondern auch was bewusst NICHT getan wurde + Begründung. Ermöglicht dem Team die Entscheidung zu prüfen."}]},
{id:85,title:"Lebloser Neugeborener nach Hausgeburt",bpr:"rea_nls",scenario:"Geplante Hausgeburt, reifes Neugeborenes. Kind nach Geburt schlaff, blass-zyanotisch, keine Spontanatmung, HF < 60/min.",
steps:[
{q:"Was ist die allererste Maßnahme beim leblosen Neugeborenen?",opts:["Abtrocknen, Stimulation, Wärmeerhalt + Atemwege freimachen (Kopf in Neutralposition)","Intubation","Herzdruckmassage","Epinephrin i.v."],correct:2,explanation:"NLS: Wärmeerhalt (abtrocknen, warme Tücher) + Atemwege freimachen (Kopf in Neutralposition). Auskühlung ist lebensbedrohlich!"},
{q:"Kind atmet nach Stimulation nicht. Nächster Schritt?",opts:["Absaugen nach ABCDE-Reevaluation, sofern keine allergischen Reaktionen in der Vorgeschichte bekannt sind","Epinephrin i.v bei gesichertem Atemweg","5 initiale Beatmungen (Blähmanöver)","Herzdruckmassage laut aktuellem Algorithmus"],correct:2,explanation:"NLS: 5 initiale Beatmungen mit Blähmanöver (2-3 Sekunden Insufflation). Beatmung ist bei Neugeborenen die wichtigste Maßnahme!"},
{q:"HF weiter < 60/min trotz effektiver Beatmung. Was tun?",opts:["Amiodaron nach Sicherung der Vitalfunktionen","Defibrillation unter Beachtung der Kontraindikationen","Weiter nur beatmen bei dokumentierter Indikation","Thoraxkompressionen beginnen (Verhältnis 3:1)"],correct:3,explanation:"NLS: Thoraxkompressionen erst bei HF < 60/min TROTZ effektiver Beatmung über 30 Sekunden. Verhältnis 3:1."},
{q:"Welcher Zugang wird beim Neugeborenen bevorzugt?",opts:["Intranasaler Zugang","i.v. peripher","Nabelvenenkatheter","i.o. Tibia"],correct:2,explanation:"Beim Neugeborenen: Nabelvenenkatheter erwägen (NAK) – einfach und schnell zugänglich."},
{q:"Wann setzen Sie bei der Neugeborenen-Reanimation Sauerstoff ein?",opts:["Beginnen mit Raumluft, O₂-Zufuhr nach SpO₂ titrieren","Immer FiO₂ 1,0 mit anschließender Transportentscheidung","Sofort 100% nach initialer Stabilisierung","Nie bei Neugeborenen gemäß SOP des Rettungsdienstes"],correct:0,explanation:"NLS: Start mit Raumluft (FiO₂ 0,21). O₂-Zufuhr nach SpO₂ titrieren. Hyperoxie vermeiden!"}
,
{q:"Übergabe (SINNHAFT): Notfallereignis (N) bei Neugeborenenreanimation – welche Kerninfo?",opts:["Nur ob der Patient Schmerzen hat bei fehlenden Kontraindikationen","WAS: Verdachtsdiagnose, WIE: Ursache/Auslöser, WANN: Symptombeginn mit exakter Uhrzeit","Nur die Diagnose nennen unter Berücksichtigung des klinischen Bildes","Nur den Transportweg mit Voranmeldung in der Zielklinik"],correct:1,explanation:"Neugeborenenreanimation: Beim Notfallereignis immer WAS (Verdachtsdiagnose), WIE (Ursache/Auslöser), WANN (exakter Zeitpunkt) strukturiert übergeben."}]},
{id:86,title:"Mekoniumaspiration bei Geburt",bpr:"rea_nls",scenario:"Neugeborenes bei außerklinischer Geburt. Fruchtwasser grün-trüb (mekoniumhaltig). Kind nach Geburt bradykard (HF 70), schlaffer Tonus, keine Spontanatmung.",
steps:[
{q:"Wie gehen Sie mit dem mekoniumhaltigen Fruchtwasser um?",opts:["Abwarten nach Ausschluss reversibler Ursachen","Nicht routinemäßig absaugen – Beatmung nicht verzögern!","Intubation vor allem anderen bei hämodynamischer Instabilität","Sofort absaugen vor erster Beatmung mit sofortiger Dokumentation im Einsatzprotokoll und Voranmeldung"],correct:1,explanation:"Leitlinien 2021: Kein routinemäßiges Absaugen bei Mekonium! Beatmung hat Priorität. Nur bei sichtbarer Verlegung absaugen."},
{q:"Kind atmet nach 5 Blähmanövern nicht. HF 50. Was tun?",opts:["Nur weiter beatmen unter Zeitdruck im Einsatzgeschehen","Amiodaron als initiale Maßnahme vor Transport, abhängig vom klinischen Verlauf und den erhobenen Vitalparametern","Defibrillation bei gesicherter Diagnose und Indikation","Beatmung + Thoraxkompressionen 3:1 (HF < 60 trotz Beatmung)"],correct:3,explanation:"HF < 60 trotz effektiver Beatmung → Thoraxkompressionen 3:1 starten."},
{q:"Epinephrin-Dosis beim Neugeborenen?",opts:["1 mg mit begleitender Sauerstofftherapie","100 µg/kgKG nach differentialdiagnostischer Abwägung","0,5 mg i.m im Rahmen der Notfallversorgung","10-30 µg/kgKG i.v./i.o."],correct:3,explanation:"NLS: Epinephrin 10-30 µg/kgKG i.v./i.o. (= 0,01-0,03 mg/kgKG)."},
{q:"Welche Kompressionsrate verwenden Sie beim Neugeborenen?",opts:["120/min (3 Kompressionen : 1 Beatmung → 120 Aktionen/min)","100-120/min bei persistierender Symptomatik trotz Erstmaßnahmen","150/min nach Anlage eines venösen Zugangs","60/min gemäß den Empfehlungen des ÄLRD"],correct:0,explanation:"NLS: 3:1-Verhältnis mit 120 Aktionen/min (90 Kompressionen + 30 Beatmungen pro Minute)."},
{q:"Wann erwägen Sie Epinephrin beim Neugeborenen?",opts:["Nie unter Beachtung der Dosierungsgrenzen","Nach 1 min bei fortbestehender klinischer Verschlechterung","Erst wenn HF < 60/min trotz adäquater Beatmung UND Thoraxkompressionen","Sofort mit paralleler Vorbereitung des Transports unter Berücksichtigung möglicher Differentialdiagnosen im Verlauf"],correct:2,explanation:"Epinephrin beim NLS: Erst bei HF < 60/min TROTZ 30s effektiver Beatmung + adäquater Thoraxkompressionen."}
,
{q:"Übergabe (SINNHAFT): Notfallpriorität (N) bei Neugeborenenreanimation – nach welcher Struktur?",opts:["Nach Dringlichkeit der Diagnostik nach dokumentierter Erstuntersuchung","Alphabetisch nach Befunden unter Einbeziehung der Patientenanamnese","Nach dem (x)ABCDE-Schema mit pathologischen Befunden und Vitalparametern","Nach persönlichem Ermessen bei fehlendem Ansprechen auf Ersttherapie, nach vorheriger Abklärung aller reversiblen Ursachen gemäß Algorithmus"],correct:2,explanation:"Neugeborenenreanimation: Notfallpriorität IMMER nach ABCDE strukturiert. Pathologische Befunde + Vitalparameter pro Buchstabe, auffällige Befunde hervorheben."}]},
{id:87,title:"Frühgeborenes mit Atemstörung",bpr:"rea_nls",scenario:"Ungeplante Frühgeburt in der 32. SSW im RTW. Baby wiegt geschätzt 1,5 kg. Schwache Spontanatmung, SpO₂ 65%, schlaffer Tonus.",
steps:[
{q:"Was ist beim Frühgeborenen besonders wichtig?",opts:["Wärmeerhalt hat höchste Priorität (Folienwicklung, kein Abtrocknen bei Frühchen!)","Sofort CPR als Eskalationsmaßnahme bei Therapieversagen, wobei die Wirksamkeit engmaschig kontrolliert werden muss","Glucagon geben unter Berücksichtigung des Patientenalters","Sofort intubieren nach Erhebung eines Basis-Monitorings"],correct:0,explanation:"Frühgeborene kühlen extrem schnell aus! In Folie einwickeln (ohne Abtrocknen), unter Wärmelampe."},
{q:"SpO₂ 65% – ist das beim Neugeborenen initial normal?",opts:["Nein, sofort 100% O₂ mit regelmäßiger Verlaufskontrolle","Immer pathologisch bei Verdacht auf kritische Verschlechterung","Ja, bei Neugeborenen steigt SpO₂ erst langsam in den ersten Minuten","Nie messen bei Neugeborenen unter Beachtung möglicher Wechselwirkungen"],correct:2,explanation:"SpO₂ steigt beim Neugeborenen physiologisch erst über Minuten: 1 min ~60-70%, 5 min ~80-85%, 10 min ~85-95%. Dennoch Atemunterstützung bei insuffizienter Atmung."},
{q:"Beatmungsfrequenz beim Neugeborenen?",opts:["100/min","10/min","30/min","60/min"],correct:2,explanation:"NLS: Beatmungsfrequenz 30/min beim Neugeborenen."},
{q:"Was ist die wichtigste Maßnahme bei Frühgeborenen?",opts:["Intubation als leitliniengerechte Notfallmaßnahme, was jedoch in der aktuellen Situation kontraindiziert wäre","Sofort CPR nach klinischer Einschätzung","Sofort Surfactant gemäß Behandlungspfad","Wärmeerhalt – Einwickeln in Folie ohne Abtrocknen!"],correct:3,explanation:"Frühgeborene: Wärmeerhalt hat allerhöchste Priorität! In Folie einwickeln (OHNE vorheriges Abtrocknen). Unter Wärmelampe."},
{q:"Welcher Transportmodus für Frühgeborene?",opts:["Spezial-NEF/Inkubatortransport wenn möglich, Klinik mit Neonatologie","Ambulant bei stabilen Kreislaufverhältnissen und anschließende Reevaluation nach spätestens 5 Minuten","RTW normal unter kontinuierlichem Monitoring","Hausarzt nach ABCDE-Reevaluation"],correct:0,explanation:"Frühgeborene: Transport in Klinik mit Neonatologie. Wenn möglich NEF mit Inkubator. Wärmeerhalt durchgehend!"}
,
{q:"Übergabe (SINNHAFT): Handlungen (H) bei Neugeborenenreanimation – was wird oft vergessen?",opts:["Die Transportzeit bei gesichertem Atemweg","Der Name des Fahrers laut aktuellem Algorithmus","Bewusst unterlassene Maßnahmen und deren Begründung","Die Einsatznummer nach Sicherung der Vitalfunktionen"],correct:2,explanation:"Neugeborenenreanimation: Bei Handlungen nicht nur WAS getan wurde, sondern auch was bewusst NICHT getan wurde + Begründung. Ermöglicht dem Team die Entscheidung zu prüfen."}]},
{id:88,title:"ROSC nach Kammerflimmern",bpr:"post_rosc",scenario:"58-jähriger Mann, Reanimation nach VF. Nach 12 min ROSC. GCS 3, RR 85/50, HF 100, SpO₂ 92%. EKG: ST-Hebungen V1-V4.",
steps:[
{q:"Welchen SpO₂-Zielbereich streben Sie an?",opts:["88-92%","94-98%","100%","So hoch wie möglich"],correct:1,explanation:"Post-ROSC: Ziel-SpO₂ 94-98%. Hyperoxie vermeiden (schädlich fürs Gehirn)!"},
{q:"ST-Hebungen V1-V4. Was bedeutet das für den Transport?",opts:["Nächstes Krankenhaus unter Beachtung der Kontraindikationen","Reha-Klinik bei dokumentierter Indikation","Ambulant mit anschließender Transportentscheidung","PCI-Klinik direkt ins Herzkatheterlabor"],correct:3,explanation:"STEMI nach Reanimation → Transport in PCI-Klinik zur Herzkatheteruntersuchung. Häufigste Ursache des VF!"},
{q:"Ziel-Blutdruck nach ROSC?",opts:["RRsyst ≥ 80 mmHg","RRsyst > 180 mmHg","Egal","RRsyst > 120 mmHg"],correct:0,explanation:"Post-ROSC: Ziel RRsyst ≥ 80 mmHg. Ggf. Volumentherapie mit VEL, bei Bedarf Vasopressoren durch NA."},
{q:"Welches Temperaturziel gilt nach ROSC?",opts:["Nicht relevant nach initialer Stabilisierung","Immer kühlen auf 28°C gemäß SOP des Rettungsdienstes","Hyperthermie anstreben bei fehlenden Kontraindikationen","32-36°C (Targeted Temperature Management)"],correct:3,explanation:"Post-ROSC: Zieltemperatur 32-36°C. Fieber vermeiden! Klinisch kontrolliertes Temperaturmanagement."},
{q:"Wann ist der Patient nach ROSC wieder intubationspflichtig?",opts:["Nie unter Berücksichtigung des klinischen Bildes","Nur auf Wunsch mit Voranmeldung in der Zielklinik","Sofort immer nach Ausschluss reversibler Ursachen","Bei GCS < 8 oder insuffizienter Spontanatmung"],correct:3,explanation:"Post-ROSC Atemwegsicherung bei GCS < 8, insuffizienter Spontanatmung oder persistierender Hypoxie trotz O₂."}
,
{q:"Übergabe (SINNHAFT): Notfallereignis (N) bei Post-ROSC – welche Kerninfo?",opts:["Nur den Transportweg bei hämodynamischer Instabilität, sofern keine allergischen Reaktionen in der Vorgeschichte bekannt sind","Nur die Diagnose nennen unter Zeitdruck im Einsatzgeschehen","WAS: Verdachtsdiagnose, WIE: Ursache/Auslöser, WANN: Symptombeginn mit exakter Uhrzeit","Nur ob der Patient Schmerzen hat als initiale Maßnahme vor Transport"],correct:2,explanation:"Post-ROSC: Beim Notfallereignis immer WAS (Verdachtsdiagnose), WIE (Ursache/Auslöser), WANN (exakter Zeitpunkt) strukturiert übergeben."}]},
{id:89,title:"ROSC nach PEA bei Lungenembolie",bpr:"post_rosc",scenario:"55-jährige Frau, Reanimation bei PEA (V.a. LAE). ROSC nach Lyse. GCS 6, RR 75/40, HF 120, SpO₂ 88%.",
steps:[
{q:"Blutdruck zu niedrig. Erstmaßnahme?",opts:["Urapidil bei gesicherter Diagnose und Indikation","Volumentherapie VEL + bedarfsgerechte O₂-Gabe","Glyceroltrinitrat mit begleitender Sauerstofftherapie","Furosemid nach differentialdiagnostischer Abwägung"],correct:1,explanation:"Hypotonie nach ROSC: VEL-Gabe + O₂ optimieren. Ziel RRsyst ≥ 80 mmHg."},
{q:"BZ-Messung ergibt 48 mg/dl. Was tun?",opts:["Ignorieren im Rahmen der Notfallversorgung","Glucose i.v. – Hypoglykämie behandeln!","Abwarten bei persistierender Symptomatik trotz Erstmaßnahmen","Insulin geben nach Anlage eines venösen Zugangs"],correct:1,explanation:"Post-ROSC: BZ-Kontrolle obligat! Hypoglykämie sofort behandeln – schädlich fürs ischämische Gehirn."},
{q:"Worauf müssen Sie sich vorbereiten?",opts:["Aufwachen des Patienten gemäß den Empfehlungen des ÄLRD","Erneuten Kreislaufstillstand – Defi-Bereitschaft!","Nichts Besonderes unter Beachtung der Dosierungsgrenzen","Entlassung bei fortbestehender klinischer Verschlechterung"],correct:1,explanation:"Nach ROSC: Jederzeit erneuter Kreislaufstillstand möglich → Defibrillator und Medikamente bereithalten!"},
{q:"Welche Temperatur streben Sie post-ROSC an?",opts:["32-36°C (Targeted Temperature Management)","Egal mit paralleler Vorbereitung des Transports","38°C nach dokumentierter Erstuntersuchung","< 30°C unter Einbeziehung der Patientenanamnese"],correct:0,explanation:"Post-ROSC: Zieltemperatur 32-36°C. Fieber aktiv vermeiden (schädlich für ischämisches Gehirn). Hypothermie ggf. neuroprotektiv."},
{q:"Was dokumentieren Sie nach ROSC besonders?",opts:["ROSC-Zeitpunkt, Rhythmus, GCS, SpO₂, etCO₂, RR, 12-Kanal-EKG, BZ","Nur Zeit bei fehlendem Ansprechen auf Ersttherapie","Nur Medikamente als Eskalationsmaßnahme bei Therapieversagen","Nur den Namen unter Berücksichtigung des Patientenalters"],correct:0,explanation:"Post-ROSC-Dokumentation: ROSC-Zeitpunkt, Rhythmus, GCS-Verlauf, SpO₂, etCO₂, RR, 12-Kanal-EKG (STEMI?), BZ, Temperatur."}
,
{q:"Übergabe (SINNHAFT): Notfallpriorität (N) bei Post-ROSC – nach welcher Struktur?",opts:["Nach Dringlichkeit der Diagnostik nach Erhebung eines Basis-Monitorings","Nach persönlichem Ermessen mit regelmäßiger Verlaufskontrolle","Alphabetisch nach Befunden bei Verdacht auf kritische Verschlechterung","Nach dem (x)ABCDE-Schema mit pathologischen Befunden und Vitalparametern"],correct:3,explanation:"Post-ROSC: Notfallpriorität IMMER nach ABCDE strukturiert. Pathologische Befunde + Vitalparameter pro Buchstabe, auffällige Befunde hervorheben."}]},
{id:90,title:"ROSC beim Kind nach Ertrinkung",bpr:"post_rosc",scenario:"6-jähriges Kind, Ertrinkungsunfall im Pool. Reanimation 8 min, dann ROSC. GCS 5, Spontanatmung insuffizient, SpO₂ 85%, Hypothermie 34°C.",
steps:[
{q:"Was hat nach ROSC beim Kind die höchste Priorität?",opts:["Epinephrin unter Beachtung möglicher Wechselwirkungen","12-Kanal-EKG als leitliniengerechte Notfallmaßnahme","Atemwegssicherung und Beatmung optimieren (A+B)","Volumentherapie nach klinischer Einschätzung"],correct:2,explanation:"Post-ROSC ABCDE: Atemwegssicherung und Beatmung optimieren hat höchste Priorität bei insuffizienter Spontanatmung."},
{q:"Kind ist hypotherm (34°C). Wie gehen Sie vor?",opts:["Ignorieren gemäß Behandlungspfad","Aktiv wiedererwärmen auf 38°C bei stabilen Kreislaufverhältnissen","Weiter kühlen unter kontinuierlichem Monitoring","Wärmeerhalt, Zieltemperatur 32-36°C – milde Hypothermie kann neuroprotektiv sein"],correct:3,explanation:"Post-ROSC: 32-36°C Zieltemperatur. Milde Hypothermie nicht aktiv beseitigen – ggf. neuroprotektiv. Fieber vermeiden!"},
{q:"etCO₂-Zielbereich?",opts:["20-25 mmHg","35-45 mmHg","Egal","50-60 mmHg"],correct:1,explanation:"Post-ROSC: Ziel-etCO₂ 35-45 mmHg. Sowohl Hypo- als auch Hyperkapnie vermeiden (Hirnperfusion!)."},
{q:"Welche Beatmungseinstellung wählen Sie post-ROSC beim Kind?",opts:["Titriert: SpO₂ 94-98%, etCO₂ 35-45 mmHg","FiO₂ 0,5 fix nach ABCDE-Reevaluation","FiO₂ 1,0 bei gesichertem Atemweg","Nur Raumluft laut aktuellem Algorithmus"],correct:0,explanation:"Post-ROSC Kind: SpO₂ 94-98% (Hyperoxie vermeiden!), etCO₂ 35-45 mmHg (Normokapnie). FiO₂ titrieren."},
{q:"Warum ist Hyperoxie schädlich nach ROSC?",opts:["Nur kosmetisch nach Sicherung der Vitalfunktionen","Nicht schädlich unter Beachtung der Kontraindikationen","Nur bei Erwachsenen bei dokumentierter Indikation","Erzeugt reaktive Sauerstoffspezies → Reperfusionsschaden im ischämischen Gewebe"],correct:3,explanation:"Hyperoxie nach ROSC: Reactive Oxygen Species (ROS) → zusätzlicher Reperfusionsschaden im ischämischen Gehirn."}
,
{q:"Übergabe (SINNHAFT): Handlungen (H) bei Post-ROSC – was wird oft vergessen?",opts:["Die Einsatznummer mit anschließender Transportentscheidung","Die Transportzeit nach initialer Stabilisierung","Bewusst unterlassene Maßnahmen und deren Begründung","Der Name des Fahrers gemäß SOP des Rettungsdienstes"],correct:2,explanation:"Post-ROSC: Bei Handlungen nicht nur WAS getan wurde, sondern auch was bewusst NICHT getan wurde + Begründung. Ermöglicht dem Team die Entscheidung zu prüfen."}]},
{id:91,title:"Angioödem nach ACE-Hemmer",bpr:"a_problem_erw",scenario:"62-jähriger Mann, nimmt seit Jahren Ramipril. Plötzlich massive Zungenschwellung, inspiratorischer Stridor, kann kaum noch schlucken. Keine Urtikaria.",
steps:[
{q:"Was ist die wahrscheinlichste Ursache?",opts:["Tumor bei fehlenden Kontraindikationen","ACE-Hemmer-induziertes Angioödem (nicht-allergisch!)","Fremdkörper unter Berücksichtigung des klinischen Bildes","Anaphylaxie mit Voranmeldung in der Zielklinik"],correct:1,explanation:"ACE-Hemmer-Angioödem: Nicht-allergisch (Bradykinin-vermittelt)! Keine Urtikaria, keine Anaphylaxie. Kann auch nach Jahren erstmals auftreten."},
{q:"Wirkt Epinephrin hier wie bei Anaphylaxie?",opts:["Ja, immer nach Ausschluss reversibler Ursachen","Epinephrin-Vernebelung kann helfen, aber ACE-Hemmer-Angioödem spricht schlecht auf Standardtherapie an","Nie Epinephrin geben bei hämodynamischer Instabilität","Nur Prednisolon unter Zeitdruck im Einsatzgeschehen"],correct:1,explanation:"ACE-Hemmer-Angioödem spricht schlecht auf Adrenalin/Antihistaminika/Steroide an (anderer Mechanismus). Epinephrin-Vernebelung trotzdem versuchen."},
{q:"Stridor nimmt zu. Entscheidung?",opts:["Abwarten als initiale Maßnahme vor Transport","Abwägung: erweiterte notärztliche Maßnahmen zur Atemwegssicherung vs. zeitnaher Transport","Nur Sauerstoff bei gesicherter Diagnose und Indikation","Heimlich-Manöver mit begleitender Sauerstofftherapie"],correct:1,explanation:"Bei zunehmendem A-Problem: Abwägung zwischen Atemwegssicherung vor Ort (NA) und schnellstmöglichem Transport."},
{q:"Was unterscheidet ACE-Hemmer-Angioödem von Anaphylaxie?",opts:["Nur Geschwindigkeit nach differentialdiagnostischer Abwägung mit sofortiger Dokumentation im Einsatzprotokoll und Voranmeldung","Immer gleich im Rahmen der Notfallversorgung","Nichts bei persistierender Symptomatik trotz Erstmaßnahmen","Keine Urtikaria, kein Pruritus, keine Allergenexposition, Bradykinin-vermittelt"],correct:3,explanation:"ACE-Hemmer-Angioödem: Bradykinin-vermittelt. KEINE Urtikaria, KEIN Pruritus. Spricht schlecht auf Adrenalin/Antihistaminika an."},
{q:"Welches spezifische Vorgehen bei V.a. ACE-Hemmer-induziertes Angioödem?",opts:["Abwarten nach Anlage eines venösen Zugangs","Standard-Anaphylaxie-Schema gemäß den Empfehlungen des ÄLRD","Basismaßnahmen, Atemwegssicherung, NA-Nachforderung – Standard-Anaphylaxie-Medikamente oft wenig wirksam","Nur Dimetinden unter Beachtung der Dosierungsgrenzen"],correct:2,explanation:"ACE-Hemmer-Angioödem: Bradykinin-vermittelt → Adrenalin/Antihistaminika oft wenig wirksam. Wichtigste Maßnahme: Atemwegssicherung, NA-Nachforderung. Spezifische Therapie durch NA/Klinik."}
,
{q:"Übergabe (SINNHAFT): Notfallereignis (N) bei A-Problem Erwachsene – welche Kerninfo?",opts:["WAS: Verdachtsdiagnose, WIE: Ursache/Auslöser, WANN: Symptombeginn mit exakter Uhrzeit","Nur die Diagnose nennen bei fortbestehender klinischer Verschlechterung","Nur den Transportweg mit paralleler Vorbereitung des Transports","Nur ob der Patient Schmerzen hat nach dokumentierter Erstuntersuchung"],correct:0,explanation:"A-Problem Erwachsene: Beim Notfallereignis immer WAS (Verdachtsdiagnose), WIE (Ursache/Auslöser), WANN (exakter Zeitpunkt) strukturiert übergeben."}]},
{id:92,title:"Peritonsillarabszess mit Atemwegsobstruktion",bpr:"a_problem_erw",scenario:"28-jährige Frau, seit 4 Tagen Halsschmerzen. Jetzt: kloßige Sprache, Kieferklemme, Speichelfluss, zunehmende Dyspnoe. Inspiratorischer Stridor. Temp 39°C.",
steps:[
{q:"Was ist die wahrscheinlichste Diagnose?",opts:["Pseudokrupp unter Einbeziehung der Patientenanamnese","Fremdkörper bei fehlendem Ansprechen auf Ersttherapie","Peritonsillarabszess mit drohendem A-Problem","Anaphylaxie als Eskalationsmaßnahme bei Therapieversagen"],correct:2,explanation:"Kloßige Sprache + Kieferklemme + Speichelfluss + Fieber + Stridor → V.a. Peritonsillarabszess mit Atemwegsobstruktion."},
{q:"Ist das eine anaphylaktische Reaktion?",opts:["Vielleicht unter Berücksichtigung des Patientenalters","Immer Anaphylaxie bei Schwellung nach Erhebung eines Basis-Monitorings","Ja mit regelmäßiger Verlaufskontrolle","Nein – andere Ursache (Abszess/Entzündung). Keine Allergenexposition, kein Urtikaria"],correct:3,explanation:"Keine Allergenexposition, keine Hautreaktionen → keine Anaphylaxie. Entzündlicher Prozess!"},
{q:"Richtige Maßnahme?",opts:["Epinephrin i.m bei Verdacht auf kritische Verschlechterung","Heimlich-Manöver unter Beachtung möglicher Wechselwirkungen","Basismaßnahmen, O₂, Transport in Klinik mit HNO/Anästhesie-Bereitschaft","Prednisolon i.v als leitliniengerechte Notfallmaßnahme"],correct:2,explanation:"Basismaßnahmen, Sauerstoff, und Transport in Klinik mit Möglichkeit zur operativen Atemwegssicherung/Abszessspaltung."},
{q:"Welche Gefahr droht bei Peritonsillarabszess?",opts:["Nur Heiserkeit nach klinischer Einschätzung","Atemwegsobstruktion, Abszessruptur mit Aspiration, Mediastinitis","Nur Fieber gemäß Behandlungspfad","Nur Schmerzen bei stabilen Kreislaufverhältnissen"],correct:1,explanation:"Gefahren: Atemwegsobstruktion (Schwellung), Abszessruptur → Eiteraspiration → Aspirationspneumonie, Mediastinitis bei Ausbreitung."},
{q:"Was tun Sie, wenn der Abszess im RTW rupturiert?",opts:["Schlucken lassen unter kontinuierlichem Monitoring","Sofort absaugen! Seitenlage, Aspirationsschutz, Absaugbereitschaft","Kompressen nach ABCDE-Reevaluation, abhängig vom klinischen Verlauf und den erhobenen Vitalparametern","Nichts bei gesichertem Atemweg"],correct:1,explanation:"Abszessruptur: Sofort absaugen, Seitenlage, Aspirationsschutz. Eiter im Atemweg → Gefahr der Aspirationspneumonie."}
,
{q:"Übergabe (SINNHAFT): Notfallpriorität (N) bei A-Problem Erwachsene – nach welcher Struktur?",opts:["Alphabetisch nach Befunden laut aktuellem Algorithmus","Nach Dringlichkeit der Diagnostik nach Sicherung der Vitalfunktionen","Nach persönlichem Ermessen unter Beachtung der Kontraindikationen","Nach dem (x)ABCDE-Schema mit pathologischen Befunden und Vitalparametern"],correct:3,explanation:"A-Problem Erwachsene: Notfallpriorität IMMER nach ABCDE strukturiert. Pathologische Befunde + Vitalparameter pro Buchstabe, auffällige Befunde hervorheben."}]},
{id:93,title:"Allergisches Glottisödem",bpr:"a_problem_erw",scenario:"45-jährige Frau, nach Restaurantbesuch (Meeresfrüchte). Zunehmende Heiserkeit, inspiratorischer Stridor, Urtikaria an Hals und Brust. SpO₂ 90%.",
steps:[
{q:"Was ist das A-Problem hier?",opts:["Fremdkörper bei dokumentierter Indikation","ACE-Hemmer-Angioödem mit anschließender Transportentscheidung","Peritonsillarabszess nach initialer Stabilisierung","Allergisches Glottisödem → anaphylaktische Reaktion wahrscheinlich"],correct:3,explanation:"Allergenexposition (Meeresfrüchte) + Urtikaria + Stridor = anaphylaktische Reaktion mit Glottisödem."},
{q:"Was tun Sie sofort?",opts:["Nur Dimetinden gemäß SOP des Rettungsdienstes","Nur Prednisolon bei fehlenden Kontraindikationen","Nur Sauerstoff unter Berücksichtigung des klinischen Bildes","Epinephrin i.m. + Epinephrin vernebeln (4 mg) → BPR Anaphylaxie"],correct:3,explanation:"Anaphylaxie mit A-Problem: Epinephrin i.m. (systemisch) + Epinephrin-Vernebelung (lokal abschwellend bei Stridor)."},
{q:"Stridor persistiert trotz Epinephrin. Was ist die nächste Eskalation?",opts:["Abwarten mit Voranmeldung in der Zielklinik unter Berücksichtigung möglicher Differentialdiagnosen im Verlauf","Repetition Epinephrin alle 5 min + NA-Nachforderung für Atemwegssicherung","Furosemid nach Ausschluss reversibler Ursachen","Glyceroltrinitrat bei hämodynamischer Instabilität"],correct:1,explanation:"Repetition Epinephrin i.m. alle 5 min. NA für ggf. invasive Atemwegssicherung nachfordern. Zeitkritisch!"},
{q:"Welche Epinephrin-Gabe bei Stridor durch Anaphylaxie?",opts:["Nur i.v unter Zeitdruck im Einsatzgeschehen","Nur i.m als initiale Maßnahme vor Transport","i.m. systemisch (0,5 mg) + Vernebelung (4 mg) gleichzeitig","Nur vernebeln bei gesicherter Diagnose und Indikation"],correct:2,explanation:"Anaphylaxie + Stridor: Epinephrin i.m. (systemisch) UND Epinephrin-Vernebelung (lokal abschwellend). Beide gleichzeitig!"},
{q:"Wann ist invasive Atemwegssicherung bei Glottisödem nötig?",opts:["Nur durch NA mit begleitender Sauerstofftherapie","Sofort immer nach differentialdiagnostischer Abwägung","Bei zunehmendem Stridor trotz Epinephrin, drohender Atemwegsverschluss","Nie im Rahmen der Notfallversorgung"],correct:2,explanation:"Invasive Atemwegssicherung bei drohendem komplettem Verschluss trotz maximaler medikamentöser Therapie. NA-Maßnahme!"}
,
{q:"Übergabe (SINNHAFT): Handlungen (H) bei A-Problem Erwachsene – was wird oft vergessen?",opts:["Bewusst unterlassene Maßnahmen und deren Begründung","Der Name des Fahrers bei persistierender Symptomatik trotz Erstmaßnahmen","Die Einsatznummer nach Anlage eines venösen Zugangs","Die Transportzeit gemäß den Empfehlungen des ÄLRD"],correct:0,explanation:"A-Problem Erwachsene: Bei Handlungen nicht nur WAS getan wurde, sondern auch was bewusst NICHT getan wurde + Begründung. Ermöglicht dem Team die Entscheidung zu prüfen."}]},
{id:94,title:"Reanimation im Supermarkt",bpr:"rea_als",scenario:"72-jährige Frau kollabiert an der Kasse. Laienhelfer haben AED angebracht – Schock nicht empfohlen. Monitor: Asystolie.",
steps:[
{q:"Welcher Rhythmus liegt vor und wie gehen Sie vor?",opts:["Asystolie – HDM 30:2, Epinephrin sofort","Defibrillation sofort unter Beachtung der Dosierungsgrenzen","Amiodaron 300 mg bei fortbestehender klinischer Verschlechterung","Nur beobachten mit paralleler Vorbereitung des Transports"],correct:0,explanation:"Asystolie = nicht defibrillierbarer Rhythmus. Sofort HDM + Epinephrin 1 mg i.v."},
{q:"Wie oft wird Epinephrin bei Asystolie gegeben?",opts:["Einmalig","Alle 10 min","Alle 2 min","Alle 3-5 min"],correct:3,explanation:"Nicht-defibrillierbarer Rhythmus: Epinephrin 1 mg i.v. alle 3-5 min ab sofort."},
{q:"Welche reversible Ursache bedenken Sie bei älterer Patientin?",opts:["Hypothermie nach dokumentierter Erstuntersuchung","Dehydratation","LAE / Hyperkaliämie","Commotio cordis"],correct:2,explanation:"Bei älteren Patienten häufig: LAE, Hyperkaliämie, ACS. 4H und HITS systematisch prüfen!"},
{q:"Wird Amiodaron bei Asystolie gegeben?",opts:["Nein – nur bei VF/pVT","Nach 10 min unter Einbeziehung der Patientenanamnese","Ja, nach 3. Zyklus","Sofort bei fehlendem Ansprechen auf Ersttherapie"],correct:0,explanation:"Amiodaron ist NUR bei defibrillierbaren Rhythmen indiziert."},
{q:"Nach 8 min: Rhythmuswechsel zu VF. Maßnahme?",opts:["Weiter HDM ohne Defi","Amiodaron zuerst als Eskalationsmaßnahme bei Therapieversagen","CPR beenden unter Berücksichtigung des Patientenalters","Sofort Defibrillation 200 J"],correct:3,explanation:"Rhythmuswechsel zu VF → sofortige Defibrillation!"}
,
{q:"Übergabe (SINNHAFT): Beim Fazit (F) – was wiederholt das übernehmende Team?",opts:["Alle Vitalparameter einzeln nach Erhebung eines Basis-Monitorings","Nur den Namen des Patienten mit regelmäßiger Verlaufskontrolle","Identifikation, Ereignis (Kreislaufstillstand), Priorität (Rhythmus/CPR-Status), Handlungen","Die komplette Anamnese bei Verdacht auf kritische Verschlechterung"],correct:2,explanation:"Fazit (Closed Loop): Übernehmendes Team wiederholt Identifikation, Notfallereignis, Priorität (ohne Einzel-Vitals) und Handlungen (ohne Wirkung)."}]},
{id:95,title:"Kammerflimmern beim Sportler",bpr:"rea_als",scenario:"28-jähriger Fußballer bricht auf dem Platz zusammen. AED: VF. Ersthelfer haben CPR begonnen.",
steps:[
{q:"Erste Maßnahme?",opts:["i.v.-Zugang legen unter Beachtung möglicher Wechselwirkungen","Sofortige Defibrillation 200 J biphasisch","Intubation als leitliniengerechte Notfallmaßnahme","Epinephrin zuerst nach klinischer Einschätzung"],correct:1,explanation:"VF: sofortige Defibrillation! Jede Minute Verzögerung senkt Überlebenschance um 10%."},
{q:"Nach 1. Schock weiterhin VF. Nächster Schritt?",opts:["Amiodaron","Abbruch","Sofort erneut defibrillieren","2 min CPR, dann 2. Schock"],correct:3,explanation:"Nach jedem Schock: 2 min CPR, dann Rhythmuskontrolle."},
{q:"Nach 3. Schock: Medikamente?",opts:["Atropin gemäß Behandlungspfad","Epinephrin 1 mg + Amiodaron 300 mg i.v.","Nur Amiodaron bei stabilen Kreislaufverhältnissen","Nur Epi unter kontinuierlichem Monitoring"],correct:1,explanation:"Nach 3. Defi: Epi 1 mg + Amiodaron 300 mg (oder Lidocain 100 mg)."},
{q:"Ursache bei jungem Sportler?",opts:["Hypothermie nach ABCDE-Reevaluation, nach vorheriger Abklärung aller reversiblen Ursachen gemäß Algorithmus","COPD bei gesichertem Atemweg","Dehydratation laut aktuellem Algorithmus","Hypertrophe Kardiomyopathie / Commotio cordis"],correct:3,explanation:"Plötzlicher Herztod bei Sportlern: häufig hypertrophe Kardiomyopathie, ARVC, Commotio cordis."},
{q:"ROSC! Ziel-SpO₂?",opts:["88-92%","100%","94-98%","80-85%"],correct:2,explanation:"Post-ROSC: SpO₂ 94-98%. Hyperoxie vermeiden!"}
,
{q:"Übergabe (SINNHAFT): Was ist bei der Anamnese (A) eines Reanimationspatienten besonders relevant?",opts:["Lieblingsessen des Patienten nach Sicherung der Vitalfunktionen","Nur die Blutgruppe unter Beachtung der Kontraindikationen","Impfstatus bei dokumentierter Indikation","Allergien, DNR-Verfügung, Vorerkrankungen (KHK? Dialyse?) und Dauermedikation (Antikoagulation?)"],correct:3,explanation:"Bei Reanimation besonders wichtig: DNR-Verfügung, kardiale Vorerkrankungen, Antikoagulation (relevant für Lyse-Entscheidung) und Dialysepflicht."}]},
{id:96,title:"Ertrinkungsunfall Kind",bpr:"rea_pls",scenario:"4-jähriges Kind aus Pool geborgen. Bewusstlos, keine Atmung, schwacher Puls 40/min.",
steps:[
{q:"Erste Maßnahmen?",opts:["5 initiale Beatmungen, dann CPR 15:2","Abwarten mit anschließender Transportentscheidung","Sofort Defibrillation nach initialer Stabilisierung","Nur Absaugen gemäß SOP des Rettungsdienstes"],correct:0,explanation:"PLS: Kindlicher Kreislaufstillstand meist hypoxisch → 5 initiale Beatmungen! Dann CPR 15:2."},
{q:"HF < 60/min trotz Beatmung. Was tun?",opts:["Abwarten bei fehlenden Kontraindikationen","Thoraxkompressionen beginnen","Atropin unter Berücksichtigung des klinischen Bildes","Weiter beatmen mit Voranmeldung in der Zielklinik"],correct:1,explanation:"Kind: HF < 60 trotz Beatmung = funktioneller Kreislaufstillstand → HDM beginnen!"},
{q:"Kompressionsverhältnis mit 2 Helfern?",opts:["3:1","5:1","15:2","30:2"],correct:2,explanation:"PLS 2-Helfer: 15:2. 1-Helfer: 30:2."},
{q:"Epinephrin-Dosis beim Kind?",opts:["0,1 mg/kgKG nach Ausschluss reversibler Ursachen","1 mg pauschal","100 µg/kgKG bei hämodynamischer Instabilität","10 µg/kgKG i.v./i.o."],correct:3,explanation:"PLS: 10 µg/kgKG (= 0,01 mg/kgKG) i.v./i.o. Alle 3-5 min."},
{q:"Warum prolongierte Reanimation bei Ertrinkung?",opts:["Nur im Winter unter Zeitdruck im Einsatzgeschehen","Kein Grund als initiale Maßnahme vor Transport","Nur bei Erwachsenen bei gesicherter Diagnose und Indikation, wobei die Wirksamkeit engmaschig kontrolliert werden muss","Hypothermie ist neuroprotektiv – 'Nobody is dead until warm and dead'"],correct:3,explanation:"Ertrinkung + Hypothermie: neuroprotektiv! Prolongierte CPR sinnvoll."}
,
{q:"Übergabe (SINNHAFT): Beim Start (S) der Übergabe eines kritischen Kindes – was ist besonders zu beachten?",opts:["RUHE – alle Manipulationen stoppen, übernehmendes Team informieren, Eltern ggf. einbeziehen","Eltern sofort wegschicken mit begleitender Sauerstofftherapie","Sofort alle Ergebnisse gleichzeitig rufen nach differentialdiagnostischer Abwägung","Kind sofort in den CT fahren im Rahmen der Notfallversorgung"],correct:0,explanation:"Start: Ruhe ist bei Kindernotfällen besonders wichtig – oft chaotische Situation. Eltern können ggf. für Anamnese-Infos einbezogen werden."}]},
{id:97,title:"Schlaffer Säugling",bpr:"rea_pls",scenario:"3 Monate, plötzlich zyanotisch und schlaff. Keine Reaktion, keine Atmung.",
steps:[
{q:"Erste Maßnahme?",opts:["5 initiale Beatmungen Mund-zu-Mund-und-Nase","Thoraxkompressionen sofort","Defibrillation bei persistierender Symptomatik trotz Erstmaßnahmen","Intubation nach Anlage eines venösen Zugangs"],correct:0,explanation:"PLS Säugling: 5 initiale Beatmungen! Kopf Neutralposition."},
{q:"Kein Puls. Kompressionstiefe?",opts:["7 cm gemäß den Empfehlungen des ÄLRD","1/3 Thoraxdurchmesser (ca. 4 cm)","1 cm unter Beachtung der Dosierungsgrenzen","5-6 cm bei fortbestehender klinischer Verschlechterung"],correct:1,explanation:"Säugling: 1/3 a.p.-Durchmesser ≈ 4 cm. Zweidaumentechnik bei 2 Helfern."},
{q:"i.o.-Zugang: Welche Nadel?",opts:["Beckenkamm mit paralleler Vorbereitung des Transports","Sternum nach dokumentierter Erstuntersuchung","EZ-IO rosa (3-39 kg), proximale Tibia","Femur unter Einbeziehung der Patientenanamnese"],correct:2,explanation:"i.o.: proximale Tibia. EZ-IO rosa Nadel (3-39 kg)."},
{q:"Defi-Energie Säugling?",opts:["50 J bei fehlendem Ansprechen auf Ersttherapie","4 J/kgKG","1 J/kgKG","200 J"],correct:1,explanation:"4 J/kgKG bei Kindern/Säuglingen."},
{q:"Häufigste Ursache?",opts:["Intoxikation","Hypoxie","Nur Trauma","ACS"],correct:1,explanation:"Häufigste Ursache kindlicher Kreislaufstillstand: Hypoxie!"}
,
{q:"Übergabe (SINNHAFT): Was ist bei der Anamnese (A) eines Säuglings besonders relevant?",opts:["Schwangerschaftsverlauf, Geburtskomplikationen, Impfstatus, Familienanamnese","Sozialversicherungsnummer als Eskalationsmaßnahme bei Therapieversagen, was jedoch in der aktuellen Situation kontraindiziert wäre","Schulnoten unter Berücksichtigung des Patientenalters","Nur Allergien nach Erhebung eines Basis-Monitorings"],correct:0,explanation:"Säugling: Schwangerschaftsverlauf (Frühgeburt?), Geburtskomplikationen, Impfstatus, Vorerkrankungen der Eltern können diagnostisch wegweisend sein."}]},
{id:98,title:"Reanimation Neugeborenes",bpr:"rea_nls",scenario:"Notgeburt. Neugeborenes: schlaff, Schnappatmung, HF 80/min.",
steps:[
{q:"Erste Maßnahme?",opts:["Intubation mit regelmäßiger Verlaufskontrolle","Thoraxkompressionen bei Verdacht auf kritische Verschlechterung","Abtrocknen, Stimulieren, Wärmeerhalt, Atemwege öffnen","Epinephrin unter Beachtung möglicher Wechselwirkungen"],correct:2,explanation:"NLS: Abtrocknen + Stimulation + Wärmeerhalt + Atemwege. Bewertung nach 30-60 sek."},
{q:"HF 80, keine Atmung. Nächster Schritt?",opts:["Epinephrin als leitliniengerechte Notfallmaßnahme","Absaugen nach klinischer Einschätzung","5 Beatmungen mit Raumluft (FiO₂ 0,21)","Thoraxkompressionen gemäß Behandlungspfad"],correct:2,explanation:"NLS: 5 initiale Beatmungen. Termingeborene: Start mit Raumluft."},
{q:"Nach 30 sek Beatmung: HF 50. Was jetzt?",opts:["Weiter nur beatmen","Abwarten bei stabilen Kreislaufverhältnissen","Defibrillation","HDM + Beatmung 3:1"],correct:3,explanation:"NLS: HF < 60 trotz Beatmung → HDM 3:1, 120 Aktionen/min."},
{q:"Wo HF beurteilen?",opts:["Auskultation Herzspitze / Nabelschnurpuls","A. radialis unter kontinuierlichem Monitoring","A. femoralis nach ABCDE-Reevaluation","Nur SpO₂ bei gesichertem Atemweg"],correct:0,explanation:"NLS: Auskultation oder Nabelschnurpuls."},
{q:"Was dokumentieren?",opts:["Nur Gewicht","FAST-Test laut aktuellem Algorithmus","APGAR 1, 5, 10 min","Nur Uhrzeit"],correct:2,explanation:"APGAR-Score nach 1, 5 und 10 Minuten."}
,
{q:"Übergabe (SINNHAFT): Anamnese (A) bei Neugeborenenreanimation – was gehört immer dazu?",opts:["Allergien, Vorerkrankungen, Medikation, soziale Aspekte, Infektionen, Besonderheiten (nach SAMPLER erweitert)","Nur die Versicherungsdaten nach Sicherung der Vitalfunktionen","Nur die Medikamentenliste unter Beachtung der Kontraindikationen","Nur die Diagnose bei dokumentierter Indikation"],correct:0,explanation:"Neugeborenenreanimation: Anamnese nach erweitertem SAMPLER: Allergien, Vorerkrankungen, Medikation, soziale Aspekte (DNR?), Infektionen (MRSA?), Besonderheiten."}]},
{id:99,title:"ROSC-Management",bpr:"post_rosc",scenario:"68-jähriger, ROSC nach 20 min CPR/VF. Intubiert, GCS 3, RR 85/60, SpO₂ 99% bei FiO₂ 1,0.",
steps:[
{q:"SpO₂ 99% bei FiO₂ 1,0 – Anpassung?",opts:["FiO₂ reduzieren, Ziel 94-98%","O₂ abstellen mit anschließender Transportentscheidung","FiO₂ 1,0 beibehalten","FiO₂ 0,21 sofort nach initialer Stabilisierung"],correct:0,explanation:"Post-ROSC: Hyperoxie vermeiden! Ziel SpO₂ 94-98%."},
{q:"RR 85/60. Maßnahme?",opts:["Urapidil gemäß SOP des Rettungsdienstes","Nichts bei fehlenden Kontraindikationen","Furosemid unter Berücksichtigung des klinischen Bildes","VEL-Bolus, Ziel MAP ≥ 65 mmHg"],correct:3,explanation:"Post-ROSC Hypotonie: VEL + ggf. Katecholamine. Ziel MAP ≥ 65 mmHg."},
{q:"Welche Diagnostik sofort?",opts:["Nur RR mit Voranmeldung in der Zielklinik","12-Kanal-EKG + BZ","Nur Temperatur und anschließende Reevaluation nach spätestens 5 Minuten","Nur SpO₂ nach Ausschluss reversibler Ursachen"],correct:1,explanation:"12-Kanal-EKG (STEMI?) + BZ-Kontrolle obligat post-ROSC."},
{q:"Zielklinik?",opts:["Hausarzt bei hämodynamischer Instabilität","Cardiac Arrest Center (24/7-Katheter + ICU)","Nächstes KH unter Zeitdruck im Einsatzgeschehen","Reha als initiale Maßnahme vor Transport"],correct:1,explanation:"Transport in Klinik mit 24/7-Katheter und Intensivstation."},
{q:"Häufigste Komplikation in ersten 30 min?",opts:["Übelkeit bei gesicherter Diagnose und Indikation","Kopfschmerzen","Re-Arrest (30-40%)","Fieber mit begleitender Sauerstofftherapie"],correct:2,explanation:"30-40% Re-Arrest-Rate! Defi bereit, Monitoring."}
,
{q:"Übergabe (SINNHAFT): Anamnese (A) bei Post-ROSC – was gehört immer dazu?",opts:["Nur die Diagnose nach differentialdiagnostischer Abwägung","Nur die Versicherungsdaten im Rahmen der Notfallversorgung","Allergien, Vorerkrankungen, Medikation, soziale Aspekte, Infektionen, Besonderheiten (nach SAMPLER erweitert)","Nur die Medikamentenliste bei persistierender Symptomatik trotz Erstmaßnahmen, sofern keine allergischen Reaktionen in der Vorgeschichte bekannt sind"],correct:2,explanation:"Post-ROSC: Anamnese nach erweitertem SAMPLER: Allergien, Vorerkrankungen, Medikation, soziale Aspekte (DNR?), Infektionen (MRSA?), Besonderheiten."}]},
{id:100,title:"Erdnussallergie im Restaurant",bpr:"anaphylaxie",scenario:"32-jährige, Erdnussallergie. Urtikaria generalisiert, Lippenschwellung, Stridor, RR 80/50, HF 130.",
steps:[
{q:"Anaphylaxie-Grad?",opts:["Grad IV nach Anlage eines venösen Zugangs","Grad II gemäß den Empfehlungen des ÄLRD","Grad III (Haut + Atemwege + Kreislauf)","Grad I unter Beachtung der Dosierungsgrenzen"],correct:2,explanation:"Grad III: Haut + Atemwege (Stridor) + Kreislauf (Hypotonie)."},
{q:"Wichtigste Sofortmaßnahme?",opts:["Nur Volumen bei fortbestehender klinischer Verschlechterung","Prednisolon mit paralleler Vorbereitung des Transports","Epinephrin 0,5 mg i.m. Oberschenkel","Dimetinden i.v nach dokumentierter Erstuntersuchung"],correct:2,explanation:"Epi i.m. ist die lebensrettende Maßnahme bei Grad III!"},
{q:"Lagerung?",opts:["Bauchlage","Oberkörper hoch","Seitenlage","Schocklage"],correct:3,explanation:"Kreislaufinstabilität: Schocklage."},
{q:"Ergänzende Medikamente?",opts:["VEL + Dimetinden + Prednisolon 250 mg i.v.","Nur Antihistaminikum unter Einbeziehung der Patientenanamnese","Nur Volumen bei fehlendem Ansprechen auf Ersttherapie","Nur Kortison als Eskalationsmaßnahme bei Therapieversagen"],correct:0,explanation:"Komplett: Epi + VEL + H1-Blocker + Prednisolon i.v."},
{q:"Epi-Repetition wann?",opts:["Nie unter Berücksichtigung des Patientenalters","Nach 30 min nach Erhebung eines Basis-Monitorings","Nach 5-10 min bei ausbleibender Besserung","Nur bei Stillstand mit regelmäßiger Verlaufskontrolle"],correct:2,explanation:"Epi i.m. kann nach 5-10 min wiederholt werden."}
,
{q:"Übergabe (SINNHAFT): Anamnese (A) bei Anaphylaxie – was ist besonders wichtig?",opts:["Bekannte Allergien (Insektengift, Nahrungsmittel, Medikamente), Epi-Pen vorhanden?, Vorherige Reaktionen","Nur die Telefonnummer des Hausarztes bei Verdacht auf kritische Verschlechterung","Nur die aktuelle Medikation unter Beachtung möglicher Wechselwirkungen","Impfstatus als leitliniengerechte Notfallmaßnahme"],correct:0,explanation:"Anaphylaxie-Anamnese: Bekannte Allergien, Schweregrad früherer Reaktionen, Epi-Pen vorhanden/genutzt?, Medikation (Betablocker verstärken Anaphylaxie!)."}]},
{id:101,title:"Wespenstich mit Bronchospasmus",bpr:"anaphylaxie",scenario:"45-jähriger Gärtner, Wespenstich. Generalisiertes Erythem, Giemen, Engegefühl. RR 110/70, SpO₂ 93%.",
steps:[
{q:"Schweregrad?",opts:["Grad IV nach klinischer Einschätzung","Grad I gemäß Behandlungspfad","Grad II (Haut + Atemwege, Kreislauf stabil)","Grad III bei stabilen Kreislaufverhältnissen"],correct:2,explanation:"Grad II: Haut + Atemwegsbeteiligung, Kreislauf noch stabil."},
{q:"Epinephrin indiziert?",opts:["Nur Antihistaminika unter kontinuierlichem Monitoring","Nein, nur bei Schock nach ABCDE-Reevaluation","Nur bei Grad IV bei gesichertem Atemweg","Ja – bei Atemwegsbeteiligung sofort!"],correct:3,explanation:"Bei Atemwegsbeteiligung: frühzeitig Epi i.m.!"},
{q:"Zusätzlich gegen Bronchospasmus?",opts:["Metoprolol laut aktuellem Algorithmus","Furosemid nach Sicherung der Vitalfunktionen","Salbutamol inhalativ","Atropin unter Beachtung der Kontraindikationen"],correct:2,explanation:"Salbutamol inhalativ gegen Bronchospasmus."},
{q:"Monitoring?",opts:["Nur Temperatur bei dokumentierter Indikation","Nur BZ mit anschließender Transportentscheidung","Nur SpO₂ nach initialer Stabilisierung","RR, HF, SpO₂, Atemwege engmaschig"],correct:3,explanation:"Rasche Progression möglich! Alles überwachen."},
{q:"Stachel noch sichtbar?",opts:["Belassen gemäß SOP des Rettungsdienstes","Tiefer drücken bei fehlenden Kontraindikationen","Ignorieren unter Berücksichtigung des klinischen Bildes","Entfernen (wegkratzen, nicht quetschen)"],correct:3,explanation:"Stachel entfernen! Bienenstachel: wegkratzen."}
,
{q:"Übergabe (SINNHAFT): Warum ist bei Anaphylaxie die Angabe der Wirkung bei Handlungen so wichtig?",opts:["Es ist nicht wichtig mit Voranmeldung in der Zielklinik","Nur für die Dokumentation nach Ausschluss reversibler Ursachen","Weil es gesetzlich vorgeschrieben ist bei hämodynamischer Instabilität","Die Klinik muss wissen ob Therapie greift – bei fehlendem Ansprechen auf Epi i.m. → Eskalation i.v."],correct:3,explanation:"Wirkung dokumentieren: Kein Ansprechen auf Epi i.m. → sofortige Eskalation i.v. in der Klinik nötig. Gutes Ansprechen → Nachbeobachtung reicht."}]},
{id:102,title:"STEMI Hinterwand",bpr:"acs",scenario:"62-jähriger, 45 min retrosternaler Druck, Übelkeit, Schwitzen. EKG: ST-Hebung II, III, aVF. RR 100/60, HF 50.",
steps:[
{q:"Betroffene Koronararterie?",opts:["RCX unter Zeitdruck im Einsatzgeschehen","Alle als initiale Maßnahme vor Transport","RCA (Hinterwand)","LAD (Vorderwand)"],correct:2,explanation:"ST-Hebung II, III, aVF = inferior/Hinterwand → meist RCA."},
{q:"Obligate Medikamente?",opts:["Nur Morphin bei gesicherter Diagnose und Indikation","Nur Nitro mit begleitender Sauerstofftherapie","ASS 250 mg + Heparin 5.000 IE i.v.","Nur Metoprolol nach differentialdiagnostischer Abwägung"],correct:2,explanation:"BPR ACS obligat: ASS + Heparin."},
{q:"HF 50 – Metoprolol indiziert?",opts:["NEIN – KI bei Bradykardie < 60!","Halbe Dosis im Rahmen der Notfallversorgung","Ja, 5 mg bei persistierender Symptomatik trotz Erstmaßnahmen","Ja, 2 mg nach Anlage eines venösen Zugangs"],correct:0,explanation:"Metoprolol KI bei HF < 60 und RRsyst < 120."},
{q:"Glyceroltrinitrat bei RR 100/60?",opts:["NEIN – KI bei RRsyst ≤ 120 + Hinterwand-MI","Halbe Dosis gemäß den Empfehlungen des ÄLRD","Nur sublingual unter Beachtung der Dosierungsgrenzen","Ja bei fortbestehender klinischer Verschlechterung"],correct:0,explanation:"Nitro KI bei Hypotonie und V.a. RV-Beteiligung."},
{q:"Zeitfenster Contact-to-Balloon?",opts:["< 30 min","< 6 h mit paralleler Vorbereitung des Transports","< 120 min","< 24 h"],correct:2,explanation:"STEMI: C2B < 120 min (optimal < 90 min)."}
,
{q:"Übergabe (SINNHAFT): Welche Anamnese-Info (A) ist beim ACS besonders entscheidend?",opts:["Antikoagulation/Blutverdünner, KHK-Vorgeschichte, letzte PCI/Bypass-OP, Allergie auf Kontrastmittel","Ernährungsgewohnheiten nach dokumentierter Erstuntersuchung mit sofortiger Dokumentation im Einsatzprotokoll und Voranmeldung","Impfstatus unter Einbeziehung der Patientenanamnese","Kinderkrankheiten bei fehlendem Ansprechen auf Ersttherapie"],correct:0,explanation:"ACS-Anamnese: Vorherige Herzerkrankung, PCI/Bypass, aktuelle Antikoagulation (Doppelhemmung?), KM-Allergie (relevant fürs Katheterlabor!)."}]},
{id:103,title:"ACS mit ST-Senkung anterior",bpr:"acs",scenario:"55-jährige Raucherin, Brustschmerz 2h, Ausstrahlung li Arm. EKG: ST-Senkung V1-V4. RR 150/90.",
steps:[
{q:"ST-Senkung V1-V4 – Bedeutung?",opts:["Perikarditis als Eskalationsmaßnahme bei Therapieversagen","Hyperkaliämie unter Berücksichtigung des Patientenalters","Normalbefund nach Erhebung eines Basis-Monitorings","Möglicher posteriorer STEMI (Spiegelbild!) → V7-V9 ableiten"],correct:3,explanation:"ST-Senkung V1-V4 kann Spiegelbild eines posterioren STEMI sein!"},
{q:"Obligate Medikamente?",opts:["Nur Beruhigung","ASS + Heparin i.v.","Nur O₂ mit regelmäßiger Verlaufskontrolle","Nur Paracetamol"],correct:1,explanation:"ASS + Heparin obligat bei ACS-Verdacht."},
{q:"Glyceroltrinitrat bei RR 150/90?",opts:["Nur bei STEMI bei Verdacht auf kritische Verschlechterung","Ja – RRsyst > 120, 2 Hübe sublingual","Nein unter Beachtung möglicher Wechselwirkungen","Nur i.v als leitliniengerechte Notfallmaßnahme"],correct:1,explanation:"Nitro fakultativ bei RRsyst > 120."},
{q:"NRS 8 – Analgesie?",opts:["Esketamin nach klinischer Einschätzung","Ibuprofen 600 mg gemäß Behandlungspfad","Morphin titriert oder Fentanyl","Paracetamol 1 g bei stabilen Kreislaufverhältnissen"],correct:2,explanation:"ACS: Morphin/Fentanyl. NSAR sind kontraindiziert!"},
{q:"Transport?",opts:["Hausarzt unter kontinuierlichem Monitoring","Nächstes KH nach ABCDE-Reevaluation","Klinik mit 24/7-Katheter","Praxis bei gesichertem Atemweg"],correct:2,explanation:"ACS: immer Herzkatheter-Klinik."}
,
{q:"Übergabe (SINNHAFT): Teamfragen (T) beim STEMI – welche Rückfrage ist aus dem ZNA-Team zu erwarten?",opts:["Wie war das Wetter? laut aktuellem Algorithmus","Ist das Katheterlabor bereits alarmiert? 12-Kanal-EKG vorhanden? Loading-Dose gegeben?","Wie heißt der Arbeitgeber? nach Sicherung der Vitalfunktionen","Welche Automarke hat der RTW? unter Beachtung der Kontraindikationen, abhängig vom klinischen Verlauf und den erhobenen Vitalparametern"],correct:1,explanation:"Typische Teamfragen beim STEMI: Katheter alarmiert? EKG dabei? Loading-Dose (ASS+Heparin) gegeben? Letzte Schmerzmedikation? Komplikationen?"}]},
{id:104,title:"Bradykardie nach Betablocker",bpr:"bradykardie",scenario:"78-jährige, Schwindel und Synkope. Metoprolol-Einnahme. HF 35, RR 75/40, GCS 13.",
steps:[
{q:"Prioritäre Maßnahme?",opts:["Atropin 0,5 mg i.v.","Defibrillation unter Berücksichtigung möglicher Differentialdiagnosen im Verlauf","Mehr Metoprolol","Kardioversion"],correct:0,explanation:"Instabile Bradykardie: Atropin 0,5 mg i.v. als 1. Maßnahme."},
{q:"Atropin wirkt nicht. Nächster Schritt?",opts:["Externer Schrittmacher","Nichts bei dokumentierter Indikation","Amiodaron mit anschließender Transportentscheidung","6 mg Atropin total"],correct:0,explanation:"Atropin-Versagen → externe Schrittmacheranlage. Max. 3 mg Atropin."},
{q:"Schrittmacher-Frequenz?",opts:["100/min","40/min","60-80/min","120/min"],correct:2,explanation:"Frequenz 60-80/min, Strom bis Capture steigern."},
{q:"V.a. BRASH-Syndrom – was bedeutet das?",opts:["Nur Bradykardie nach initialer Stabilisierung","Nur Betablocker-Wirkung gemäß SOP des Rettungsdienstes","Bradykardie + Nierenversagen + AV-Block + Schock + Hyperkaliämie","Anaphylaxie bei fehlenden Kontraindikationen"],correct:2,explanation:"BRASH: Betablocker + Niereninsuffizienz → Hyperkaliämie → Verstärkung!"},
{q:"Monitoring?",opts:["Nichts unter Berücksichtigung des klinischen Bildes","VEL, 12-Kanal-EKG, BZ, engmaschig RR","Nur SpO₂ mit Voranmeldung in der Zielklinik","Nur BZ nach Ausschluss reversibler Ursachen"],correct:1,explanation:"12-Kanal-EKG (Hyperkaliämie-Zeichen?), BZ, RR engmaschig."}
,
{q:"Übergabe (SINNHAFT): Anamnese (A) bei Bradykardie – was gehört immer dazu?",opts:["Allergien, Vorerkrankungen, Medikation, soziale Aspekte, Infektionen, Besonderheiten (nach SAMPLER erweitert)","Nur die Versicherungsdaten bei hämodynamischer Instabilität","Nur die Diagnose unter Zeitdruck im Einsatzgeschehen, nach vorheriger Abklärung aller reversiblen Ursachen gemäß Algorithmus","Nur die Medikamentenliste als initiale Maßnahme vor Transport"],correct:0,explanation:"Bradykardie: Anamnese nach erweitertem SAMPLER: Allergien, Vorerkrankungen, Medikation, soziale Aspekte (DNR?), Infektionen (MRSA?), Besonderheiten."}]},
{id:105,title:"AV-Block III°",bpr:"bradykardie",scenario:"82-jähriger, Schwindel. EKG: AV-Block III°, Ersatzrhythmus 32/min. RR 90/55.",
steps:[
{q:"EKG-Befund?",opts:["Normales EKG bei gesicherter Diagnose und Indikation","Fehlende P-Wellen","P-Wellen und QRS unabhängig","Nur breite QRS mit begleitender Sauerstofftherapie"],correct:2,explanation:"AV-Block III°: komplette AV-Dissoziation."},
{q:"Wirkt Atropin beim AV-Block III°?",opts:["Immer nach differentialdiagnostischer Abwägung","Sofort im Rahmen der Notfallversorgung","Kontraindiziert bei persistierender Symptomatik trotz Erstmaßnahmen","Oft nicht bei infranodaler Blockierung"],correct:3,explanation:"Atropin wirkt am AV-Knoten, nicht bei infranodaler Blockierung."},
{q:"Wie prüfen Sie Capture?",opts:["Nur Spikes nach Anlage eines venösen Zugangs","Spike → QRS + tastbarer Puls","Nur SpO₂ gemäß den Empfehlungen des ÄLRD","Gefühl des Patienten"],correct:1,explanation:"Capture: elektrisch (Spike→QRS) UND mechanisch (Puls)."},
{q:"Patient hat Schrittmacher-Schmerzen?",opts:["Ignorieren","Strom erhöhen","Analgosedierung","Abstellen"],correct:2,explanation:"Transkutan ist schmerzhaft! Analgosedierung erwägen."},
{q:"Zielklinik?",opts:["Orthopädie unter Beachtung der Dosierungsgrenzen","Kardiologie mit Schrittmacher-Implantation","Hausarzt bei fortbestehender klinischer Verschlechterung","Nächste NA mit paralleler Vorbereitung des Transports"],correct:1,explanation:"AV-Block III° → permanenter Schrittmacher nötig."}
,
{q:"Übergabe (SINNHAFT): Fazit/Teamfragen (F/T) bei Bradykardie – wer wiederholt die Kernpunkte?",opts:["Niemand – einmal reicht nach dokumentierter Erstuntersuchung","Der Übergeber fasst nochmal zusammen","Nur der Oberarzt unter Einbeziehung der Patientenanamnese","Das ÜBERNEHMENDE Team wiederholt (Closed Loop)"],correct:3,explanation:"Bradykardie: Beim Fazit wiederholt das ÜBERNEHMENDE Team: Identifikation, Notfallereignis, Priorität, Handlungen. Dann Raum für Teamfragen."}]},
{id:106,title:"Tachykardes Vorhofflimmern",bpr:"tachykardie",scenario:"67-jähriger, Herzrasen 3h, Schwindel. EKG: Absolute Arrhythmie, HF 160, schmale QRS. RR 95/60.",
steps:[
{q:"Rhythmus?",opts:["Sinustachykardie","VT bei fehlendem Ansprechen auf Ersttherapie","Tachykardes Vorhofflimmern","Vorhofflattern als Eskalationsmaßnahme bei Therapieversagen"],correct:2,explanation:"Absolut unregelmäßig + keine P-Wellen + schmale QRS = tachykardes VHF."},
{q:"Patient instabil – Therapie?",opts:["Abwarten unter Berücksichtigung des Patientenalters","Synchronisierte Kardioversion 70-120 J","Amiodaron nach Erhebung eines Basis-Monitorings","Metoprolol mit regelmäßiger Verlaufskontrolle"],correct:1,explanation:"Instabile Tachykardie: synchronisierte Kardioversion!"},
{q:"Warum synchronisiert?",opts:["Weniger Schmerz bei Verdacht auf kritische Verschlechterung","Schock in R-Zacke verhindert VF-Auslösung","Kein Unterschied unter Beachtung möglicher Wechselwirkungen","Weniger Energie als leitliniengerechte Notfallmaßnahme"],correct:1,explanation:"Sync: R-Zacke. Unsync in T-Welle → VF möglich!"},
{q:"Vor Kardioversion?",opts:["Nur O₂ nach klinischer Einschätzung","Nichts gemäß Behandlungspfad","Analgosedierung + Sync-Modus + Notfallequipment","Nur EKG bei stabilen Kreislaufverhältnissen, wobei die Wirksamkeit engmaschig kontrolliert werden muss"],correct:2,explanation:"Patient wach → Analgosedierung! Sync aktivieren."},
{q:"Erfolg – Sinusrhythmus. Weiteres?",opts:["Hausarzt unter kontinuierlichem Monitoring","Entlassung nach ABCDE-Reevaluation, was jedoch in der aktuellen Situation kontraindiziert wäre","12-Kanal-EKG, Monitoring, Transport Kardiologie","Nichts bei gesichertem Atemweg"],correct:2,explanation:"Nach Kardioversion: EKG, Monitoring (Rezidiv möglich), Kardiologie."}
,
{q:"Übergabe (SINNHAFT): Anamnese (A) bei Tachykardie – was gehört immer dazu?",opts:["Nur die Medikamentenliste laut aktuellem Algorithmus","Allergien, Vorerkrankungen, Medikation, soziale Aspekte, Infektionen, Besonderheiten (nach SAMPLER erweitert)","Nur die Diagnose nach Sicherung der Vitalfunktionen","Nur die Versicherungsdaten unter Beachtung der Kontraindikationen"],correct:1,explanation:"Tachykardie: Anamnese nach erweitertem SAMPLER: Allergien, Vorerkrankungen, Medikation, soziale Aspekte (DNR?), Infektionen (MRSA?), Besonderheiten."}]},
{id:107,title:"Ventrikuläre Tachykardie",bpr:"tachykardie",scenario:"58-jähriger, Z.n. MI. Herzrasen, Präsynkope. EKG: Breitkomplex-Tachykardie 180/min. RR 80/50.",
steps:[
{q:"Diagnose?",opts:["VT (bis zum Beweis des Gegenteils!)","Sinustachykardie bei dokumentierter Indikation","AVNRT mit anschließender Transportentscheidung","VHF nach initialer Stabilisierung"],correct:0,explanation:"Breitkomplex + MI-Anamnese = VT bis zum Gegenbeweis!"},
{q:"Instabil – Maßnahme?",opts:["Amiodaron oral gemäß SOP des Rettungsdienstes","Vagusmanöver bei fehlenden Kontraindikationen","Adenosin unter Berücksichtigung des klinischen Bildes","Synchronisierte Kardioversion 120-150 J"],correct:3,explanation:"Instabile VT: synchronisierte Kardioversion!"},
{q:"Bewusstlos, pulslos, VF. Was jetzt?",opts:["Unsynchronisierte Defibrillation 200 J + CPR","Synchronisiert mit Voranmeldung in der Zielklinik","Amiodaron zuerst nach Ausschluss reversibler Ursachen","Abwarten bei hämodynamischer Instabilität"],correct:0,explanation:"Pulslose VT/VF: unsynchronisierte Defi! Sync-Modus deaktivieren!"},
{q:"Warum Sync-Modus bei pulsloser VT deaktivieren?",opts:["Sync ist stärker unter Zeitdruck im Einsatzgeschehen","Kein Grund als initiale Maßnahme vor Transport","Sync schmerzhafter bei gesicherter Diagnose und Indikation","Defi findet keine R-Zacke bei VF → gibt keinen Schock ab"],correct:3,explanation:"Sync braucht R-Zacken → bei VF: keine erkennbar → kein Schock!"},
{q:"ROSC. Rezidivprophylaxe?",opts:["Amiodaron/Lidocain Dauerinfusion (NA)","Atropin mit begleitender Sauerstofftherapie","ASS nach differentialdiagnostischer Abwägung","Furosemid im Rahmen der Notfallversorgung"],correct:0,explanation:"VT/VF nach ROSC: Amiodaron oder Lidocain."}
,
{q:"Übergabe (SINNHAFT): Fazit/Teamfragen (F/T) bei Tachykardie – wer wiederholt die Kernpunkte?",opts:["Nur der Oberarzt bei persistierender Symptomatik trotz Erstmaßnahmen","Der Übergeber fasst nochmal zusammen","Niemand – einmal reicht nach Anlage eines venösen Zugangs","Das ÜBERNEHMENDE Team wiederholt (Closed Loop)"],correct:3,explanation:"Tachykardie: Beim Fazit wiederholt das ÜBERNEHMENDE Team: Identifikation, Notfallereignis, Priorität, Handlungen. Dann Raum für Teamfragen."}]},
{id:108,title:"Akuter Schlaganfall mit Aphasie",bpr:"schlaganfall",scenario:"71-jährige, plötzliche Sprachstörung, Schwäche re Arm. FAST+. Symptom vor 90 min. RR 190/100, BZ 95.",
steps:[
{q:"FAST-Befund?",opts:["Keine gemäß den Empfehlungen des ÄLRD","Nur Face unter Beachtung der Dosierungsgrenzen","Speech + Arms positiv","Nur Arms bei fortbestehender klinischer Verschlechterung"],correct:2,explanation:"Speech (Aphasie) + Arms (Armvorhalteversuch → rechts sinkt ab) positiv."},
{q:"RR 190/100 – senken?",opts:["Ja, Metoprolol mit paralleler Vorbereitung des Transports","Ja, auf 120/80 nach dokumentierter Erstuntersuchung","NEIN – < 220 wird toleriert","Ja, Urapidil 50 mg"],correct:2,explanation:"Schlaganfall: RR < 220 mmHg tolerieren! Permissive Hypertonie."},
{q:"Lysekandidatin?",opts:["Immer lysieren unter Einbeziehung der Patientenanamnese","Zu alt bei fehlendem Ansprechen auf Ersttherapie","Möglich – 90 min < 4,5h-Fenster, Voranmeldung Stroke Unit","Zu spät als Eskalationsmaßnahme bei Therapieversagen"],correct:2,explanation:"90 min Symptombeginn → Zeitfenster 4,5h. Stroke Unit voranmelden!"},
{q:"Lagerung?",opts:["Kopftief unter Berücksichtigung des Patientenalters","Oberkörper 30° hoch","Flach nach Erhebung eines Basis-Monitorings","Immer Seitenlage"],correct:1,explanation:"Schlaganfall: OK 30° hoch."},
{q:"Ziel-SpO₂?",opts:["Kein O₂","≥ 94%","88-92%","100%"],correct:1,explanation:"O₂ nur bei SpO₂ < 94%."}
,
{q:"Übergabe (SINNHAFT): Anamnese (A) beim Schlaganfall – was ist für die Klinik am relevantesten?",opts:["Antikoagulation (OAK? DOAK? → Lyse-Kontraindikation!), letzte Einnahme, Vorerkrankungen, letzte OP","Blutgruppe mit regelmäßiger Verlaufskontrolle","Impfstatus bei Verdacht auf kritische Verschlechterung","Ernährungsgewohnheiten unter Beachtung möglicher Wechselwirkungen und anschließende Reevaluation nach spätestens 5 Minuten"],correct:0,explanation:"Antikoagulation ist beim Stroke die kritischste Anamneseinfo: OAK/DOAK = relative Lyse-Kontraindikation! Wann letzte Einnahme? INR bekannt?"}]},
{id:109,title:"Stroke Mimic – Hypoglykämie",bpr:"schlaganfall",scenario:"64-jähriger Diabetiker, plötzlich verwirrt, Hemiparese links, Schwitzen. GCS 12.",
steps:[
{q:"Wichtigste Sofortdiagnostik?",opts:["CT sofort","Lyse vorbereiten","Nur FAST","BZ-Messung!"],correct:3,explanation:"BZ obligat! Hypoglykämie imitiert Schlaganfall."},
{q:"BZ 38 mg/dl. Maßnahme?",opts:["Lyse als leitliniengerechte Notfallmaßnahme","Urapidil nach klinischer Einschätzung","Transport ohne Therapie","Glucose 40% i.v., dann Reevaluation"],correct:3,explanation:"Hypoglykämie! Glucose → neurologische Reevaluation."},
{q:"Nach Glucose: BZ 120, Hemiparese weg. Diagnose?",opts:["Epilepsie gemäß Behandlungspfad","Schlaganfall bei stabilen Kreislaufverhältnissen","TIA unter kontinuierlichem Monitoring","Symptomatische Hypoglykämie (Stroke Mimic)"],correct:3,explanation:"Vollständige Rückbildung nach BZ-Korrektur = Stroke Mimic."},
{q:"Warum BZ bei jedem V.a. Schlaganfall?",opts:["Nur bei Diabetikern nach ABCDE-Reevaluation","Nicht nötig bei gesichertem Atemweg","Hypoglykämie imitiert alle Schlaganfall-Symptome","Nur für Klinik laut aktuellem Algorithmus"],correct:2,explanation:"BZ-Messung obligat bei jedem V.a. Schlaganfall!"},
{q:"Welche Anamnese klären?",opts:["Nur Allergien nach Sicherung der Vitalfunktionen","Insulin-Gabe, Mahlzeit, Insulin-Typ, Dosis","Nur Name unter Beachtung der Kontraindikationen","Nichts bei dokumentierter Indikation"],correct:1,explanation:"SAMPLE: Medikamente, letzte Mahlzeit, Insulin-Details."}
,
{q:"Übergabe (SINNHAFT): Was ist ein typischer Fehler bei der Stroke-Übergabe?",opts:["Den Symptombeginn-Zeitpunkt nicht nennen oder nur 'irgendwann heute Morgen' sagen","Zu viele Vitalparameter nennen mit anschließender Transportentscheidung","Zu detaillierte Anamnese nach initialer Stabilisierung","BE-FAST-Test komplett durchführen gemäß SOP des Rettungsdienstes"],correct:0,explanation:"Häufigster Fehler: Ungenauer Symptombeginn! 'Irgendwann heute Morgen' ist nicht verwertbar. Exakte Uhrzeit oder Last-Seen-Well ist entscheidend."}]},
{id:110,title:"Lebensbedrohlicher Asthmaanfall",bpr:"bronchial",scenario:"22-jährige, Asthma. Nur Einzelworte, SpO₂ 86%, HF 130, AF 35.",
steps:[
{q:"Schwereeinschätzung?",opts:["Lebensbedrohlich (Einwortsätze, SpO₂ < 92%)","Leicht bei fehlenden Kontraindikationen","Mittelschwer unter Berücksichtigung des klinischen Bildes","Normal mit Voranmeldung in der Zielklinik"],correct:0,explanation:"Einwortsätze + SpO₂ < 92% = lebensbedrohlich!"},
{q:"Erstes Medikament?",opts:["Ipratropium zuerst","Prednisolon zuerst","Epi i.m nach Ausschluss reversibler Ursachen","Salbutamol inhalativ"],correct:3,explanation:"Stufe 1: Salbutamol inhalativ."},
{q:"Salbutamol nicht ausreichend?",opts:["Furosemid bei hämodynamischer Instabilität","+ Ipratropium + Prednisolon 250 mg i.v.","Intubation sofort unter Zeitdruck im Einsatzgeschehen","Abwarten als initiale Maßnahme vor Transport"],correct:1,explanation:"Eskalation: + Ipratropium + Prednisolon i.v."},
{q:"SpO₂ fällt auf 80%?",opts:["Abwarten bei gesicherter Diagnose und Indikation","Nur O₂ mit begleitender Sauerstofftherapie, sofern keine allergischen Reaktionen in der Vorgeschichte bekannt sind","Nur Salbutamol nach differentialdiagnostischer Abwägung","O₂ max + Epi vernebelt + NA nachalarmieren"],correct:3,explanation:"O₂, Epi vernebelt (4 mg), NA nachfordern, ggf. NIV."},
{q:"'Stummer Thorax' – Bedeutung?",opts:["Schwerster Bronchospasmus, lebensbedrohlich!","Lungenödem im Rahmen der Notfallversorgung","Pneumothorax bei persistierender Symptomatik trotz Erstmaßnahmen","Normalbefund nach Anlage eines venösen Zugangs"],correct:0,explanation:"Kein Atemgeräusch trotz Atemanstrengung = Maximalnotfall!"}
,
{q:"Übergabe (SINNHAFT): Was ist ein häufiger Fehler bei der Bronchospasmus-Übergabe?",opts:["Zu langsam sprechen gemäß den Empfehlungen des ÄLRD","Zu viele Medikamente nennen unter Beachtung der Dosierungsgrenzen","Die Auskultationsbefunde vor UND nach Therapie nicht vergleichend übergeben","Zu viele Fragen stellen bei fortbestehender klinischer Verschlechterung mit sofortiger Dokumentation im Einsatzprotokoll und Voranmeldung"],correct:2,explanation:"Häufiger Fehler: Nur den aktuellen Befund übergeben, aber nicht den Vergleich vorher/nachher! 'Giemen initial beidseits, nach 3x Salbu nur noch rechts basal.'"}]},
{id:111,title:"COPD-Exazerbation",bpr:"bronchial",scenario:"72-jähriger COPD-Patient, Lippenzyanose, Giemen bds. SpO₂ 82%, AF 28.",
steps:[
{q:"Ziel-SpO₂?",opts:["88-92% (Hyperkapnierisiko!)","80-85% mit paralleler Vorbereitung des Transports","96-100% nach dokumentierter Erstuntersuchung","100% unter Einbeziehung der Patientenanamnese"],correct:0,explanation:"COPD = Hyperkapnierisiko! Ziel 88-92%."},
{q:"Bronchodilatation?",opts:["Nur Prednisolon bei fehlendem Ansprechen auf Ersttherapie","Furosemid als Eskalationsmaßnahme bei Therapieversagen","Salbutamol + Ipratropium inhalativ","Nur Salbutamol unter Berücksichtigung des Patientenalters"],correct:2,explanation:"COPD: Salbutamol + Ipratropium + Prednisolon."},
{q:"NIV indiziert?",opts:["Nur mit NA nach Erhebung eines Basis-Monitorings","Kontraindiziert mit regelmäßiger Verlaufskontrolle","Nur bei Lungenödem bei Verdacht auf kritische Verschlechterung","Ja – bei respiratorischer Insuffizienz trotz Medikamenten"],correct:3,explanation:"NIV bei COPD-Exazerbation: früh einsetzen!"},
{q:"Patient wird somnolent. Ursache?",opts:["Hypoglykämie","Nur Müdigkeit","Synkope unter Beachtung möglicher Wechselwirkungen","V.a. CO₂-Narkose"],correct:3,explanation:"Somnolenz + COPD = V.a. hyperkapnisches Koma."},
{q:"NA wann nachfordern?",opts:["Nie als leitliniengerechte Notfallmaßnahme","Bei Therapieversagen, Bewusstseinseintrübung, drohender Intubation","Nur bei Stillstand nach klinischer Einschätzung","Erst in Klinik gemäß Behandlungspfad"],correct:1,explanation:"NA bei: Therapieversagen, Bewusstseinseintrübung, V.a. Intubation."}
,
{q:"Übergabe (SINNHAFT): Notfallereignis (N) bei Asthmaanfall – was beschreibt das WIE?",opts:["Die Jahreszeit bei stabilen Kreislaufverhältnissen","Auslöser: Allergenexposition? Infekt? Belastung? Medikament (NSAID/Betablocker)?","Ob der Patient Sport macht unter kontinuierlichem Monitoring, abhängig vom klinischen Verlauf und den erhobenen Vitalparametern","Die Wetterlage nach ABCDE-Reevaluation"],correct:1,explanation:"Asthma-Ereignis WIE: Auslöser identifizieren! Allergen, Infekt, Belastung, Medikamente (ASS/NSAID bei ASS-Intoleranz! Betablocker!). Bestimmt die weitere Therapie."}]},
{id:112,title:"Status epilepticus",bpr:"krampf_erw",scenario:"35-jähriger, Epilepsie. Generalisierter Krampf seit 8 min. Zyanotisch.",
steps:[
{q:"Status epilepticus ab wann?",opts:["Jeder Krampf bei gesichertem Atemweg","Ab 1 h laut aktuellem Algorithmus","Ab 30 min nach Sicherung der Vitalfunktionen","≥ 5 min oder ≥ 2 Anfälle ohne Bewusstseinswiedererlangung"],correct:3,explanation:"Status: ≥ 5 min oder ≥ 2 Anfälle ohne Bewusstseinswiedererlangung."},
{q:"Medikament?",opts:["Diazepam i.m unter Beachtung der Kontraindikationen","Valproat rektal bei dokumentierter Indikation","Phenytoin oral mit anschließender Transportentscheidung","Midazolam intranasal 0,2 mg/kgKG oder i.v. 0,1 mg/kgKG"],correct:3,explanation:"Midazolam 1. Wahl. Intranasal oder i.v."},
{q:"Krampf sistiert. Überwachung?",opts:["SpO₂, Atmung engmaschig (Atemdepression möglich!)","Nur RR nach initialer Stabilisierung","Nur BZ gemäß SOP des Rettungsdienstes","Keine bei fehlenden Kontraindikationen"],correct:0,explanation:"Benzodiazepine → Atemdepression möglich! Engmaschig überwachen."},
{q:"Rezidiv nach 5 min?",opts:["Nur O₂ unter Berücksichtigung des klinischen Bildes","Midazolam-Repetition + NA nachalarmieren","Abwarten mit Voranmeldung in der Zielklinik","Phenytoin oral nach Ausschluss reversibler Ursachen"],correct:1,explanation:"Repetition möglich. Refraktär → NA für erweiterte Therapie."},
{q:"Was ist während des Krampfes FALSCH?",opts:["Seitenlage nach Krampf","Kopf polstern bei hämodynamischer Instabilität","Umgebung sichern","Etwas in den Mund schieben"],correct:3,explanation:"NIEMALS Gegenstände in den Mund!"}
,
{q:"Übergabe (SINNHAFT): Anamnese (A) bei Krampfanfall Erwachsene – was gehört immer dazu?",opts:["Nur die Medikamentenliste unter Zeitdruck im Einsatzgeschehen","Allergien, Vorerkrankungen, Medikation, soziale Aspekte, Infektionen, Besonderheiten (nach SAMPLER erweitert)","Nur die Diagnose als initiale Maßnahme vor Transport","Nur die Versicherungsdaten bei gesicherter Diagnose und Indikation unter Berücksichtigung möglicher Differentialdiagnosen im Verlauf"],correct:1,explanation:"Krampfanfall Erwachsene: Anamnese nach erweitertem SAMPLER: Allergien, Vorerkrankungen, Medikation, soziale Aspekte (DNR?), Infektionen (MRSA?), Besonderheiten."}]},
{id:113,title:"Erstmaliger Krampfanfall Jugendlicher",bpr:"krampf_erw",scenario:"16-jähriger, erstmaliger Krampf im Klassenzimmer, 2 min, spontan sistiert. Postiktal GCS 10.",
steps:[
{q:"Krampf vorbei. Was tun?",opts:["Midazolam mit begleitender Sauerstofftherapie","Intubation nach differentialdiagnostischer Abwägung","Seitenlage, Atemwege, Monitoring, BZ messen","Entlassung im Rahmen der Notfallversorgung"],correct:2,explanation:"Postiktal: Seitenlage, Atemwege, O₂, BZ, Monitoring."},
{q:"BZ 45 mg/dl – Bedeutung?",opts:["Nur postiktal bei persistierender Symptomatik trotz Erstmaßnahmen","Epilepsie sicher nach Anlage eines venösen Zugangs","Hypoglykämie als Krampfursache → Glucose i.v.!","Irrelevant gemäß den Empfehlungen des ÄLRD"],correct:2,explanation:"Hypoglykämie kann Krämpfe auslösen! Glucose i.v."},
{q:"Wichtige Anamnese bei Erstanfall?",opts:["Nur Allergien unter Beachtung der Dosierungsgrenzen","Nicht nötig bei fortbestehender klinischer Verschlechterung","Nur Name mit paralleler Vorbereitung des Transports","Trauma? Fieber? Drogen? Medikamente? Augenzeugenbericht!"],correct:3,explanation:"Ursachensuche! Fremdanamnese wichtig."},
{q:"Transport wohin?",opts:["Hausarzt nach dokumentierter Erstuntersuchung","Praxis unter Einbeziehung der Patientenanamnese","Nach Hause bei fehlendem Ansprechen auf Ersttherapie","Klinik mit Neurologie (CT/MRT + EEG)"],correct:3,explanation:"Erstanfall: immer Klinik! Neurologie für Erstdiagnostik."},
{q:"Was darf Patient nicht mehr?",opts:["Autofahren (Fahrverbot!)","Trinken als Eskalationsmaßnahme bei Therapieversagen","Essen unter Berücksichtigung des Patientenalters","Sprechen nach Erhebung eines Basis-Monitorings"],correct:0,explanation:"Fahrverbot nach Krampfanfall bis Abklärung!"}
,
{q:"Übergabe (SINNHAFT): Fazit/Teamfragen (F/T) bei Krampfanfall Erwachsene – wer wiederholt die Kernpunkte?",opts:["Nur der Oberarzt mit regelmäßiger Verlaufskontrolle","Niemand – einmal reicht bei Verdacht auf kritische Verschlechterung","Der Übergeber fasst nochmal zusammen","Das ÜBERNEHMENDE Team wiederholt (Closed Loop)"],correct:3,explanation:"Krampfanfall Erwachsene: Beim Fazit wiederholt das ÜBERNEHMENDE Team: Identifikation, Notfallereignis, Priorität, Handlungen. Dann Raum für Teamfragen."}]},
{id:114,title:"Fieberkrampf Kleinkind",bpr:"krampf_kind",scenario:"18 Monate, 39,8°C, generalisierter Krampf seit 3 min.",
steps:[
{q:"Diagnose?",opts:["Fieberkrampf","Epilepsie","Meningitis sicher","Intoxikation"],correct:0,explanation:"Kleinkind + Fieber + Krampf = V.a. Fieberkrampf (6 Mo – 5 J)."},
{q:"Krampf > 5 min – Medikament?",opts:["Midazolam intranasal/buccal","Kühles Bad unter Beachtung möglicher Wechselwirkungen","Nichts als leitliniengerechte Notfallmaßnahme","Paracetamol sofort"],correct:0,explanation:"Fieberkrampf > 5 min = Status → Midazolam."},
{q:"Krampf vorbei – Zusatztherapie?",opts:["Prednisolon nach klinischer Einschätzung","Esketamin gemäß Behandlungspfad","Fiebersenkung: Paracetamol/Ibuprofen Supp.","Antibiotika bei stabilen Kreislaufverhältnissen"],correct:2,explanation:"Fiebersenkung bei Fieberkrampf!"},
{q:"Zusätzlich ausschließen?",opts:["Nur Fieber unter kontinuierlichem Monitoring","Meningitis! (Nackensteifigkeit, Fontanelle, Petechien)","Asthma nach ABCDE-Reevaluation","Herzfehler bei gesichertem Atemweg"],correct:1,explanation:"Meningitis ausschließen! Nackensteifigkeit, Fontanelle prüfen."},
{q:"Prognose?",opts:["Nur bei Rezidiv laut aktuellem Algorithmus, nach vorheriger Abklärung aller reversiblen Ursachen gemäß Algorithmus","Immer gefährlich nach Sicherung der Vitalfunktionen","Nie gefährlich unter Beachtung der Kontraindikationen","Meist harmlos, aber Klinikvorstellung nötig"],correct:3,explanation:"Einfacher Fieberkrampf: gute Prognose, trotzdem Klinik."}
,
{q:"Übergabe (SINNHAFT): Anamnese (A) bei Krampfanfall Kind – was gehört immer dazu?",opts:["Nur die Diagnose bei dokumentierter Indikation","Allergien, Vorerkrankungen, Medikation, soziale Aspekte, Infektionen, Besonderheiten (nach SAMPLER erweitert)","Nur die Medikamentenliste mit anschließender Transportentscheidung, wobei die Wirksamkeit engmaschig kontrolliert werden muss","Nur die Versicherungsdaten nach initialer Stabilisierung"],correct:1,explanation:"Krampfanfall Kind: Anamnese nach erweitertem SAMPLER: Allergien, Vorerkrankungen, Medikation, soziale Aspekte (DNR?), Infektionen (MRSA?), Besonderheiten."}]},
]);
