// NotSanTrainer 2025 - Fallsimulationen (Teil 1/4, Fälle 1-38)
// ═══════════════════════════════════════════════════════
// DATA: FALLSIMULATIONEN
// ═══════════════════════════════════════════════════════
var CASES = [
{id:1,title:"Plötzlicher Herztod im Büro",bpr:"rea_als",scenario:"Ein 58-jähriger Mann bricht während einer Besprechung plötzlich zusammen. Kollegen beginnen mit Laien-CPR. Bei Ihrem Eintreffen: bewusstlos, keine Atmung, kein Puls. Monitor: Kammerflimmern.",
steps:[
{q:"Was ist Ihre erste Maßnahme?",opts:["Amiodaron i.v.","Epinephrin i.v.","Defibrillation","Intubation"],correct:2,explanation:"Bei VF/pVT hat die Defibrillation oberste Priorität – so früh wie möglich!"},
{q:"Nach der 3. Defibrillation persistiert VF. Welche Medikamente geben Sie jetzt?",opts:["Atropin 3 mg bei hämodynamischer Instabilität","Nur Amiodaron 300 mg unter Zeitdruck im Einsatzgeschehen","Nur Epinephrin 1 mg als initiale Maßnahme vor Transport","Epinephrin 1 mg + Amiodaron 300 mg"],correct:3,explanation:"Nach der 3. Defi: Epinephrin 1 mg + Amiodaron 300 mg i.v. gleichzeitig."},
{q:"In welchem Intervall wird Epinephrin bei VF wiederholt?",opts:["Alle 4 min (nach jedem 2. Zyklus)","Alle 3-5 min bei gesicherter Diagnose und Indikation","Alle 10 min mit begleitender Sauerstofftherapie","Alle 2 min nach differentialdiagnostischer Abwägung"],correct:0,explanation:"Bei VF/pVT: Epinephrin alle 4 Minuten (entspricht jedem 2. CPR-Zyklus)."},
{q:"Welche reversiblen Ursachen müssen Sie bedenken?",opts:["OPQRST im Rahmen der Notfallversorgung","ABCDE bei persistierender Symptomatik trotz Erstmaßnahmen","4H und HITS","SAMPLER"],correct:2,explanation:"4H: Hypoxie, Hypovolämie, Hypo-/Hyperkaliämie, Hypothermie. HITS: Herzbeuteltamponade, Intoxikation, Thrombose (LAE/ACS), Spannungspneumothorax."},
{q:"Welche Kompressionstiefe und -frequenz gelten beim Erwachsenen?",opts:["7-8 cm, 140/min","5-6 cm, 100-120/min","4 cm, 60/min","3-4 cm, 80/min"],correct:1,explanation:"ALS: Kompressionstiefe 5-6 cm, Frequenz 100-120/min. Komplette Entlastung sicherstellen."}
,
{q:"Übergabe (SINNHAFT): Welche Information ist bei der Notfallpriorität (N) am wichtigsten für diesen Fall?",opts:["C: Reanimationspflichtig, VF/pVT vs. Asystolie/PEA, Dauer CPR","D: GCS 15, orientiert nach Anlage eines venösen Zugangs","A: Atemweg frei, B: beatmet gemäß den Empfehlungen des ÄLRD","E: Temperatur 36,5°C unter Beachtung der Dosierungsgrenzen"],correct:0,explanation:"Bei Reanimation ist C die kritische Priorität: Rhythmus (defibrillierbar?), CPR-Dauer und aktueller Zustand sind die Kerninfos für die Notaufnahme."}]},
{id:2,title:"Kreislaufstillstand bei PEA",bpr:"rea_als",scenario:"72-jährige Frau, Pflegeheim. Vom Personal bewusstlos aufgefunden. Keine Atmung, kein Puls. Monitor: schmale QRS-Komplexe sichtbar, aber kein tastbarer Puls – Pulslose Elektrische Aktivität (PEA).",
steps:[
{q:"Wird bei PEA defibrilliert?",opts:["Nein, nicht defibrillierbar","Nur bei breiten Komplexen, wobei die Wirksamkeit engmaschig kontrolliert werden muss","Ja, nach 2 min CPR","Ja, sofort bei fortbestehender klinischer Verschlechterung"],correct:0,explanation:"PEA ist ein nicht defibrillierbarer Rhythmus. CPR fortsetzen + reversible Ursachen suchen."},
{q:"Wann wird Epinephrin bei PEA erstmals gegeben?",opts:["Sofort, sobald Zugang vorhanden","Nach der 3. Rhythmusanalyse","Gar nicht bei PEA mit paralleler Vorbereitung des Transports","Nach 10 Minuten nach dokumentierter Erstuntersuchung"],correct:0,explanation:"Bei Asystolie/PEA: Epinephrin 1 mg i.v./i.o. sofort, sobald ein Zugang vorhanden ist."},
{q:"Welchen Zugang wählen Sie, wenn kein i.v.-Zugang gelingt?",opts:["Intranasale Gabe","Intraossärer Zugang","Intramuskuläre Gabe","Rektale Gabe"],correct:1,explanation:"Bei Reanimation und fehlgeschlagenem i.v.-Zugang: i.o.-Zugang (proximale Tibia)."},
{q:"Welche Ursache vermuten Sie bei einer älteren Pflegeheimpatientin mit PEA?",opts:["Nur Elektrolytstörung unter Einbeziehung der Patientenanamnese","Kammerflimmern bei fehlendem Ansprechen auf Ersttherapie","Hypovolämie, Hypoxie oder Lungenembolie","Nur Hypothermie als Eskalationsmaßnahme bei Therapieversagen"],correct:2,explanation:"Häufige PEA-Ursachen bei Älteren: Hypovolämie, Hypoxie, LAE, Myokardinfarkt. 4H und HITS systematisch prüfen!"},
{q:"Wie lange führen Sie die Reanimation mindestens fort?",opts:["5 Minuten unter Berücksichtigung des Patientenalters","Bis der Notarzt kommt nach Erhebung eines Basis-Monitorings","Maximal 10 Minuten mit regelmäßiger Verlaufskontrolle","Mindestens 20 Minuten, Abbruch nur nach definierten Kriterien"],correct:3,explanation:"Reanimation mindestens 20 min. Abbruch nur nach definierten Kriterien (z.B. sichere Todeszeichen, keine reversible Ursache)."}
,
{q:"Übergabe (SINNHAFT): Was gehört bei einem Reanimationsfall zu den Handlungen (H)?",opts:["Nur die Medikamentennamen bei Verdacht auf kritische Verschlechterung","Nur ob ROSC erreicht wurde unter Beachtung möglicher Wechselwirkungen","Ausschließlich die CPR-Dauer als leitliniengerechte Notfallmaßnahme","Anzahl Defis, Epi-Gaben mit Uhrzeit + Amiodaron-Dosis + Wirkung"],correct:3,explanation:"Handlungen bei Rea: Anzahl Defibrillationen, Epinephrin-Gaben (Zeitpunkte!), Amiodaron, Atemwegssicherung, und ob/wann ROSC erreicht wurde."}]},
{id:3,title:"Asystolie nach Ertrinken",bpr:"rea_als",scenario:"Ein 30-jähriger Mann wurde aus einem See gerettet. Submersionszeit ca. 5 Minuten. Bewusstlos, keine Atmung, kein Puls. Monitor: Asystolie.",
steps:[
{q:"Was ist bei Ertrinkungsunfällen die häufigste Ursache des Kreislaufstillstands?",opts:["Hypothermie","Elektrolytstörung","Kammerflimmern","Hypoxie"],correct:3,explanation:"Bei Ertrinkungsunfällen ist Hypoxie die führende Ursache. Daher: 5 initiale Beatmungen priorisieren!"},
{q:"Welche Besonderheit besteht bei der Reanimation nach Ertrinken?",opts:["Sofort Amiodaron geben","Keine Defibrillation möglich","Nur HDM, keine Beatmung","5 initiale Beatmungen vor HDM"],correct:3,explanation:"Bei hypoxischem Kreislaufstillstand (Ertrinken): 5 initiale Beatmungen, dann 30:2 CPR."},
{q:"Patient ist hypotherm (32°C). Wie beeinflusst das die Reanimation?",opts:["Medikamentengabe verdoppeln nach klinischer Einschätzung","Medikamentenintervalle verlängern, nie aufgeben","Reanimation abbrechen gemäß Behandlungspfad","Nur HDM, keine Medikamente bei stabilen Kreislaufverhältnissen"],correct:1,explanation:"Bei Hypothermie: Reanimation fortführen! 'Nobody is dead until warm and dead.' Medikamentenintervalle ggf. verlängern."},
{q:"Wie gehen Sie mit der nassen Kleidung des Patienten um?",opts:["Entfernen + Wärmeerhalt (Rettungsdecke, warme Umgebung)","Erst in Klinik entfernen unter kontinuierlichem Monitoring","Nur Rettungsdecke drüber nach ABCDE-Reevaluation","Anlassen bei gesichertem Atemweg"],correct:0,explanation:"Nasse Kleidung entfernen, Wärmeerhalt durch Rettungsdecke und warme Umgebung. Hypothermie verschlechtert Prognose."},
{q:"Welches etCO₂ spricht für eine effektive CPR?",opts:["etCO₂ ist irrelevant","< 10 mmHg","≥ 20 mmHg (idealerweise > 20)","10-20 mmHg (= CPR-Qualität schlecht)"],correct:2,explanation:"etCO₂ ≥ 20 mmHg zeigt effektive Thoraxkompressionen an. Ein plötzlicher Anstieg kann auf ROSC hinweisen."}
,
{q:"Übergabe (SINNHAFT): Welche Angabe zum Notfallereignis (N) ist bei Kreislaufstillstand besonders wichtig?",opts:["Familienstand laut aktuellem Algorithmus","Welches Krankenhaus angefahren wird nach Sicherung der Vitalfunktionen","WANN: Exakter Zeitpunkt des Zusammenbruchs + Laien-CPR ja/nein","Beruf des Patienten unter Beachtung der Kontraindikationen"],correct:2,explanation:"Beim Kreislaufstillstand ist der Zeitpunkt entscheidend (No-Flow-Time / Low-Flow-Time). Laien-CPR beeinflusst die Prognose erheblich."}]},
{id:4,title:"Reanimation Kleinkind",bpr:"rea_pls",scenario:"2-jähriges Kind, plötzlich schlaff und leblos beim Spielen. Keine Atmung, kein Puls tastbar. Monitor: Asystolie.",
steps:[
{q:"Wie beginnen Sie die Reanimation beim Kind?",opts:["Sofort 30 HDM, was jedoch in der aktuellen Situation kontraindiziert wäre","Epinephrin i.m.","Defibrillation","5 initiale Beatmungen"],correct:3,explanation:"PLS: 5 initiale Beatmungen, da kindlicher Kreislaufstillstand meist hypoxisch bedingt ist."},
{q:"Welches HDM:Beatmungs-Verhältnis gilt bei professionellen Helfern im PLS?",opts:["3:1","5:1","15:2","30:2"],correct:2,explanation:"PLS professionelle Helfer: 15:2 (im Gegensatz zu 30:2 bei Laien)."},
{q:"Welche Epinephrin-Dosis geben Sie dem 12 kg schweren Kind?",opts:["0,12 mg (0,01 mg/kgKG)","0,5 mg bei dokumentierter Indikation","1 mg mit anschließender Transportentscheidung","0,3 mg nach initialer Stabilisierung"],correct:0,explanation:"PLS Epinephrin: 0,01 mg/kgKG i.v./i.o. → 12 kg × 0,01 = 0,12 mg."},
{q:"Wo prüfen Sie den Puls beim Säugling?",opts:["A. temporalis gemäß SOP des Rettungsdienstes","A. radialis bei fehlenden Kontraindikationen","A. carotis unter Berücksichtigung des klinischen Bildes","A. brachialis oder A. femoralis"],correct:3,explanation:"Beim Säugling: Puls an A. brachialis (Oberarminnenseite) oder A. femoralis tasten. Carotis ist beim Säugling schwer tastbar."},
{q:"Welche Intubationsgröße wählen Sie für ein 2-Jähriges Kind?",opts:["Tubus 7,0","Tubus 6,0","Tubus 3,0","Tubus 4,0-4,5"],correct:3,explanation:"Tubusgröße: Alter/4 + 4 = 2/4 + 4 = 4,5 (ungeblockt) oder Alter/4 + 3,5 (geblockt). Alternativ EGA verwenden."}
,
{q:"Übergabe (SINNHAFT): Was ist bei der Identifikation (I) eines Kindes zusätzlich wichtig?",opts:["Blutgruppe mit Voranmeldung in der Zielklinik","Nur Name und Alter nach Ausschluss reversibler Ursachen","Schulklasse bei hämodynamischer Instabilität","Geschlecht, Name, Alter UND geschätztes Gewicht (für Medikamentendosierung)"],correct:3,explanation:"Bei Kindern: Gewicht ist essenziell für alle Dosierungen! Bei der Identifikation das geschätzte Gewicht mitzuteilen spart in der Klinik wertvolle Zeit."}]},
{id:5,title:"Kammerflimmern beim Jugendlichen",bpr:"rea_pls",scenario:"14-Jähriger bricht beim Fußballtraining zusammen. Keine Reaktion, keine Atmung. AED zeigt defibrillierbaren Rhythmus (VF).",
steps:[
{q:"Welche Defibrillationsenergie verwenden Sie beim Kind?",opts:["150 J fix","1 J/kgKG","4 J/kgKG","2 J/kgKG"],correct:2,explanation:"PLS Defibrillation: 4 J/kgKG. Bei einem 50 kg Jugendlichen = 200 J."},
{q:"Wann wird Amiodaron im PLS gegeben?",opts:["Nach der 1. Defi","Gar nicht bei Kindern","Nach der 3. Defi","Nach der 5. Defi"],correct:2,explanation:"PLS wie ALS: Amiodaron 5 mg/kgKG nach der 3. Defibrillation."},
{q:"An welche Ursache denken Sie bei plötzlichem VF beim Sport?",opts:["Hypoglykämie unter Zeitdruck im Einsatzgeschehen","Asthma als initiale Maßnahme vor Transport","Dehydratation bei gesicherter Diagnose und Indikation","Commotio cordis / Long-QT / HOCM"],correct:3,explanation:"Plötzlicher Herztod beim jungen Sportler: Commotio cordis, Long-QT-Syndrom, HOCM, Myokarditis."},
{q:"Welche Maßnahme ergreifen Sie nach erfolgreicher Reanimation?",opts:["Sofort entlassen mit begleitender Sauerstofftherapie","Medikamente absetzen nach differentialdiagnostischer Abwägung","Post-ROSC: SpO₂ 94-98%, RRsyst ≥ 80 mmHg, Transport zur Klinik","Nur beobachten im Rahmen der Notfallversorgung"],correct:2,explanation:"Post-ROSC-Management: Ziel-SpO₂ 94-98%, RRsyst ≥ 80 mmHg, 12-Kanal-EKG, BZ-Kontrolle, Transport."},
{q:"Was ist Commotio cordis?",opts:["Herzinfarkt bei persistierender Symptomatik trotz Erstmaßnahmen","Myokarditis nach Anlage eines venösen Zugangs","Herzstillstand durch stumpfes Thoraxtrauma in vulnerabler Phase","Herzbeuteltamponade gemäß den Empfehlungen des ÄLRD"],correct:2,explanation:"Commotio cordis: Schlag auf den Thorax in der vulnerablen Phase des Herzzyklus → VF. Häufig bei jungen Sportlern (Ball, Puck)."}
,
{q:"Übergabe (SINNHAFT): Welche Handlung (H) ist bei kindlicher Reanimation besonders zu dokumentieren?",opts:["Nur die CPR-Dauer unter Beachtung der Dosierungsgrenzen","Transportzeit bei fortbestehender klinischer Verschlechterung","Nur ob das Kind weint mit paralleler Vorbereitung des Transports und anschließende Reevaluation nach spätestens 5 Minuten","Medikamente mit gewichtsbezogener Dosis, Anzahl Defis (4 J/kgKG), Atemwegsgröße"],correct:3,explanation:"Kindliche Rea: Gewichtsbezogene Dosierungen nennen (mg/kgKG), Defibrillationsenergie (4 J/kgKG), IO-Zugang-Ort, Tubus-/EGA-Größe."}]},
{id:6,title:"Säugling Reanimation",bpr:"rea_pls",scenario:"4 Monate alter Säugling, morgens leblos im Bettchen aufgefunden. Keine Atmung, keine Reaktion, schlaffer Tonus.",
steps:[
{q:"Welche HDM-Technik verwenden Sie beim Säugling?",opts:["Beidhändig auf Sternum","2-Daumen-Technik","Keine HDM, nur Beatmung","Einhand-Technik"],correct:1,explanation:"Säugling: 2-Daumen-Technik (umfassendes Greifen des Thorax) ist bevorzugt."},
{q:"Wie tief komprimieren Sie bei einem Säugling?",opts:["1-2 cm nach dokumentierter Erstuntersuchung","5-6 cm unter Einbeziehung der Patientenanamnese","2 cm bei fehlendem Ansprechen auf Ersttherapie","Mindestens ⅓ des Thoraxdurchmessers"],correct:3,explanation:"PLS: Kompressionstiefe mindestens ⅓ des Thoraxdurchmessers bei Kindern und Säuglingen."},
{q:"Welcher Zugang ist bei fehlgeschlagenem i.v.-Zugang beim Säugling indiziert?",opts:["Nabelvenenkatheter","Sublingualer Zugang","Intranasaler Zugang, sofern keine allergischen Reaktionen in der Vorgeschichte bekannt sind","i.o.-Zugang proximale Tibia"],correct:3,explanation:"i.o.-Zugang an der proximalen Tibia. Bei Neugeborenen alternativ Nabelvenenkatheter."},
{q:"Ab welcher Herzfrequenz beginnen Sie beim Säugling mit HDM?",opts:["< 40/min als Eskalationsmaßnahme bei Therapieversagen","< 80/min unter Berücksichtigung des Patientenalters","< 60/min trotz effektiver Beatmung","< 100/min nach Erhebung eines Basis-Monitorings"],correct:2,explanation:"HDM beim Säugling erst bei HF < 60/min TROTZ effektiver Beatmung über 30 Sekunden."},
{q:"Welche Beatmungsfrequenz verwenden Sie beim Säugling?",opts:["10/min","40/min","60/min","20-25/min"],correct:3,explanation:"Beatmungsfrequenz beim Säugling/Kind: 20-25/min (ca. alle 3 Sekunden eine Beatmung)."}
,
{q:"Übergabe (SINNHAFT): Welches Notfallereignis (N) beschreiben Sie bei einem kindlichen Kreislaufstillstand?",opts:["Nur den Rhythmus mit regelmäßiger Verlaufskontrolle","Nur: Kind hatte Kreislaufstillstand bei Verdacht auf kritische Verschlechterung","Nur die Elterninformation unter Beachtung möglicher Wechselwirkungen","WAS: Kreislaufstillstand, WIE: V.a. Ursache (Hypoxie, SIDS, Ertrinken?), WANN: Zeitpunkt, WO: Auffindesituation"],correct:3,explanation:"Gerade beim Kind ist die Ursache entscheidend: Hypoxie (häufigste Ursache!), SIDS, Ertrinken, Trauma – bestimmt die Klinikstrategie."}]},
{id:7,title:"Erstickung beim Essen",bpr:"fk_aspiration",scenario:"68-jähriger Mann in einem Restaurant. Greift sich plötzlich an den Hals, kann nicht sprechen, kein Husten möglich. Zunehmende Zyanose.",
steps:[
{q:"Welchen Schweregrad der Atemwegsverlegung liegt vor?",opts:["Leichtgradig","Partiell","Kein A-Problem","Schwergradig"],correct:3,explanation:"Schwere Verlegung: Sprechen nicht möglich, kein effektiver Husten, Zyanose, inverse Atmung."},
{q:"Patient ist bei Bewusstsein. Was tun Sie zuerst?",opts:["Heimlich-Manöver","HDM beginnen","Laryngoskopie","5 Rückenschläge"],correct:3,explanation:"Bei schwerer Verlegung und wachem Patienten: Zunächst 5 Rückenschläge zwischen die Schulterblätter."},
{q:"Rückenschläge erfolglos. Was folgt beim Erwachsenen?",opts:["5 Oberbauchkompressionen (Heimlich)","Intubation als leitliniengerechte Notfallmaßnahme","Erneut 5 Rückenschläge mit sofortiger Dokumentation im Einsatzprotokoll und Voranmeldung","5 Thoraxkompressionen"],correct:0,explanation:"Nach erfolglosen Rückenschlägen beim Erwachsenen: 5 Oberbauchkompressionen (Heimlich-Manöver)."},
{q:"Patient wird bewusstlos. Was ist jetzt zu tun?",opts:["Seitenlage","Magillzange blind einführen","ALS-Algorithmus beginnen","Weitere Heimlich-Manöver"],correct:2,explanation:"Bei Bewusstlosigkeit: ALS-Algorithmus (HDM + Beatmung). Laryngoskopie + Magillzange zur Fremdkörperentfernung."},
{q:"Wann wird der Rettungsdienst bei Fremdkörperaspiration alarmiert?",opts:["Immer bei schwerer Atemwegsverlegung","Erst nach 10 Minuten nach klinischer Einschätzung","Nur wenn Heimlich nicht wirkt","Nur bei Bewusstlosigkeit"],correct:0,explanation:"Immer Rettungsdienst alarmieren bei schwerer Atemwegsverlegung – auch wenn Erstmaßnahmen laufen."}
,
{q:"Übergabe (SINNHAFT): Notfallereignis (N) bei Fremdkörperaspiration – was ist besonders wichtig?",opts:["Nur dass der Patient hustet gemäß Behandlungspfad","Nur ob der Patient noch spricht bei stabilen Kreislaufverhältnissen","Nur die SpO₂ unter kontinuierlichem Monitoring","WAS: Aspiration, WIE: Fremdkörperart (Nahrung, Spielzeug, Zahn?), WANN: Zeitpunkt, WO: Situation (Essen, Spielen)"],correct:3,explanation:"FK-Aspiration: Art des Fremdkörpers (organisch? Größe?), Zeitpunkt, Situation. Bestimmt das Vorgehen in der Klinik (Bronchoskopie? Chirurgie?)."}]},
{id:8,title:"Kleinkind verschluckt Spielzeug",bpr:"fk_aspiration",scenario:"18 Monate altes Kind, hat eine Murmel verschluckt. Inspiratorischer Stridor, ineffektiver Husten, wird zunehmend zyanotisch.",
steps:[
{q:"Was ist beim Kind unter 1 Jahr anders als beim Erwachsenen?",opts:["5 Thoraxkompressionen statt Heimlich","Sofort intubieren nach ABCDE-Reevaluation","Gar nichts bei gesichertem Atemweg","Nur Rückenschläge, kein Heimlich"],correct:0,explanation:"Kind < 1 Jahr: KEIN Heimlich-Manöver! Stattdessen 5 Rückenschläge, dann 5 Thoraxkompressionen."},
{q:"Das Kind (18 Monate) ist über 1 Jahr alt. Wie gehen Sie vor?",opts:["Sofort Laryngoskopie laut aktuellem Algorithmus","Nur Thoraxkompressionen","Nur Rückenschläge nach Sicherung der Vitalfunktionen","Rückenschläge, dann Heimlich-Manöver"],correct:3,explanation:"Kind > 1 Jahr: Wie Erwachsener – 5 Rückenschläge, dann 5 Oberbauchkompressionen (Heimlich)."},
{q:"Fremdkörper nicht entfernt, Kind wird bewusstlos. Nächster Schritt?",opts:["PLS-Algorithmus","Blind absaugen","Heimfahrt","Weitere Heimlich-Manöver"],correct:0,explanation:"Bewusstlos → PLS-Algorithmus starten. Unter Laryngoskopie Fremdkörper mit Magillzange entfernen."},
{q:"Welche Komplikation droht nach erfolgreicher Fremdkörperentfernung?",opts:["Schleimhautschwellung, Aspiration, erneute Verlegung","Keine unter Beachtung der Kontraindikationen","Nur Husten bei dokumentierter Indikation","Nur Heiserkeit mit anschließender Transportentscheidung"],correct:0,explanation:"Nach FK-Entfernung: V.a. Schleimhautverletzung, Aspiration, reaktive Schwellung → Kliniktransport obligat."},
{q:"Darf ein Säugling Heimlich-Manöver erhalten?",opts:["Ja nach initialer Stabilisierung","Nur modifiziert gemäß SOP des Rettungsdienstes","NEIN – nur Rückenschläge + Thoraxkompressionen bei Säuglingen","Nur durch Arzt bei fehlenden Kontraindikationen"],correct:2,explanation:"Säugling < 1 Jahr: KEIN Heimlich-Manöver (Organverletzungsgefahr). Nur Rückenschläge + Thoraxkompressionen."}
,
{q:"Übergabe (SINNHAFT): Notfallpriorität (N) bei FK-Aspiration – welcher ABCDE-Bereich?",opts:["C: Blutdruck unter Berücksichtigung des klinischen Bildes","E: Temperatur mit Voranmeldung in der Zielklinik","A: Atemweg: partiell/komplett verlegt? B: Auskultation (einseitig?), SpO₂, Stridor?","D: GCS nach Ausschluss reversibler Ursachen"],correct:2,explanation:"FK-Aspiration: A (Verlegungsgrad: partiell mit Husten vs. komplett → Erstickung!) und B (Auskultation: einseitig abgeschwächt? SpO₂, Stridor) dominieren."}]},
{id:9,title:"Aspiration bei Schlaganfallpatient",bpr:"fk_aspiration",scenario:"78-jährige Frau mit bekanntem Z.n. Schlaganfall. Während des Essens plötzlich schwere Dyspnoe, inspiratorischer Stridor, Schluckstörung. Kann noch schwach husten.",
steps:[
{q:"Leichtgradige Atemwegsverlegung (effektiver Husten). Was tun Sie?",opts:["Sofort Rückenschläge","Laryngoskopie bei hämodynamischer Instabilität","Zum Husten auffordern, beobachten","Heimlich-Manöver unter Zeitdruck im Einsatzgeschehen"],correct:2,explanation:"Bei leichtgradiger Verlegung (effektiver Husten): Zum Husten auffordern und engmaschig beobachten."},
{q:"Husten wird ineffektiv. Was nun?",opts:["Midazolam i.v.","Abwarten","Sauerstoff geben","5 Rückenschläge"],correct:3,explanation:"Sobald der Husten ineffektiv wird: 5 Rückenschläge, dann ggf. Heimlich-Manöver (Erwachsener)."},
{q:"Fremdkörper entfernt, Atmung suffizient. Was beachten Sie?",opts:["Nur dokumentieren als initiale Maßnahme vor Transport","Nichts weiter bei gesicherter Diagnose und Indikation","Sofort entlassen mit begleitender Sauerstofftherapie","Überwachung und Transport in Klinik"],correct:3,explanation:"Nach Fremdkörperentfernung: Überwachung, Transport in Klinik (V.a. Aspiration, Schleimhautverletzung)."},
{q:"Warum ist die Patientin besonders aspirationsgefährdet?",opts:["Medikamente nach differentialdiagnostischer Abwägung","Allergie im Rahmen der Notfallversorgung","Alter bei persistierender Symptomatik trotz Erstmaßnahmen","Z.n. Schlaganfall → Schluckstörung (Dysphagie)"],correct:3,explanation:"Nach Schlaganfall: Häufig Dysphagie (Schluckstörung) → erhöhtes Aspirationsrisiko beim Essen."},
{q:"Welche Lagerung nach erfolgreicher Fremdkörperentfernung?",opts:["Kopftieflage nach Anlage eines venösen Zugangs","Stabile Seitenlage bei Bewusstseinsstörung","Flach gemäß den Empfehlungen des ÄLRD, abhängig vom klinischen Verlauf und den erhobenen Vitalparametern","Bauchlage unter Beachtung der Dosierungsgrenzen"],correct:1,explanation:"Bei Bewusstseinsstörung: Stabile Seitenlage. Absaugbereitschaft. O₂-Gabe bedarfsgerecht."}
,
{q:"Übergabe (SINNHAFT): Handlungen (H) bei FK-Aspiration – was gehört dazu?",opts:["Rückenschläge/Heimlich-Manöver (erfolgreich?), Laryngoskopie+Magill-Zange (Ergebnis?), O₂, ggf. Intubation","Nur ob der FK entfernt wurde bei fortbestehender klinischer Verschlechterung","Nur die O₂-Gabe mit paralleler Vorbereitung des Transports","Nur die Lagerung nach dokumentierter Erstuntersuchung"],correct:0,explanation:"FK-Handlungen: Basismaßnahmen (Rückenschläge, Heimlich), erweitert (Laryngoskopie, Magill-Zange), Erfolg?, O₂-Gabe, Atemwegssicherung wenn nötig."}]},
{id:10,title:"Akuter Rückenschmerz mit Kreislaufinstabilität",bpr:"aortensyndrom",scenario:"52-jähriger Mann, bekanntes Marfan-Syndrom. Plötzlich einsetzender reißender Schmerz zwischen den Schulterblättern. RR rechts 180/100, links 140/80. HF 110.",
steps:[
{q:"Was ist der auffälligste Befund?",opts:["Hoher Blutdruck unter Einbeziehung der Patientenanamnese","Schmerz zwischen Schulterblättern","Blutdruckdifferenz > 20 mmHg an beiden Armen","Tachykardie bei fehlendem Ansprechen auf Ersttherapie"],correct:2,explanation:"Eine Blutdruckdifferenz > 20 mmHg an beiden Armen ist ein Schlüsselsymptom des akuten Aortensyndroms."},
{q:"Welches Blutdruckziel verfolgen Sie?",opts:["RRsyst < 140 mmHg","RRsyst < 180 mmHg","Keine RR-Senkung","RRsyst < 100 mmHg"],correct:0,explanation:"Beim akuten Aortensyndrom: Ziel RRsyst < 140 mmHg mittels Urapidil i.v."},
{q:"Welche Strategie wählen Sie?",opts:["Stay-and-play","Ambulante Behandlung","Load-go-and-treat","Vor Ort behandeln bis stabil"],correct:2,explanation:"Load-go-and-treat: Zeitkritische Situation, Transport in geeignetes Zentrum so schnell wie möglich."},
{q:"Welche Schmerztherapie wählen Sie?",opts:["Paracetamol rectal als Eskalationsmaßnahme bei Therapieversagen","Keine, erst in Klinik unter Berücksichtigung des Patientenalters","Morphin oder Esketamin i.v. nach BPR Schmerzen","Ibuprofen oral nach Erhebung eines Basis-Monitorings"],correct:2,explanation:"Starke Schmerzen: Analgesie nach BPR Schmerzen. Esketamin/Morphin i.v. titriert."},
{q:"Was dürfen Sie bei V.a. Aortensyndrom NICHT geben?",opts:["Sauerstoff","Urapidil mit regelmäßiger Verlaufskontrolle","ASS und Heparin","Morphin bei Verdacht auf kritische Verschlechterung"],correct:2,explanation:"ASS + Heparin sind kontraindiziert bei V.a. Aortensyndrom (Blutungsgefahr bei möglicher Ruptur)."}
,
{q:"Übergabe (SINNHAFT): Notfallereignis (N) bei akutem Aortensyndrom – welche WAS/WIE-Info?",opts:["Nur den Blutdruck unter Beachtung möglicher Wechselwirkungen","Nur ob der Patient blass ist als leitliniengerechte Notfallmaßnahme unter Berücksichtigung möglicher Differentialdiagnosen im Verlauf","WAS: V.a. Aortendissektion, WIE: reißender Schmerz zwischen Schulterblättern, plötzlich, wandernd","Nur: Patient hat Rückenschmerzen nach klinischer Einschätzung"],correct:2,explanation:"Aortensyndrom: Reißender, plötzlicher Schmerz (Rücken/Schulterblätter), wandernd. RR-Differenz >20 mmHg an Armen! Fehlende periphere Pulse."}]},
{id:11,title:"V.a. Aortendissektion bei Hypertoniker",bpr:"aortensyndrom",scenario:"65-jährige Frau, langjährige Hypertonie. Plötzlicher, wandernder Schmerz vom Rücken in den Bauch. RR 200/110. Fehlender Radialispuls links.",
steps:[
{q:"Welches Medikament setzen Sie zur RR-Senkung ein?",opts:["Urapidil i.v.","Metoprolol i.v.","Furosemid i.v.","Glyceroltrinitrat"],correct:0,explanation:"Urapidil i.v. zur kontrollierten RR-Senkung bei akutem Aortensyndrom."},
{q:"Warum ist ASS hier kontraindiziert?",opts:["V.a. akutes Aortensyndrom ist Kontraindikation für ASS","Wegen Allergie gemäß Behandlungspfad","ASS wirkt nicht schnell genug bei stabilen Kreislaufverhältnissen","ASS ist nie kontraindiziert unter kontinuierlichem Monitoring"],correct:0,explanation:"V.a. akutes Aortensyndrom ist eine explizite Kontraindikation für ASS (Blutungsgefahr!)."},
{q:"Das EKG zeigt ST-Hebungen. Was bedenken Sie?",opts:["Aortendissektion kann ST-Hebungen verursachen!","EKG-Gerät defekt nach ABCDE-Reevaluation","Irrelevant bei gesichertem Atemweg, nach vorheriger Abklärung aller reversiblen Ursachen gemäß Algorithmus","Sicher STEMI, ASS + Heparin geben"],correct:0,explanation:"Vorsicht: Auch beim Aortensyndrom können ST-Hebungen auftreten (Dissektion bis in Koronararterien)."},
{q:"Welche Urapidil-Dosis geben Sie initial?",opts:["250 mg laut aktuellem Algorithmus","100 mg nach Sicherung der Vitalfunktionen","12,5-25 mg langsam i.v.","5 mg unter Beachtung der Kontraindikationen"],correct:2,explanation:"Urapidil: 12,5-25 mg langsam i.v. (über 20 sec). RR-Kontrolle nach 5 min. Repetition möglich."},
{q:"Welches Transportkonzept?",opts:["Nächster Hausarzt bei dokumentierter Indikation","Ambulante Versorgung mit anschließender Transportentscheidung","Load-go-and-treat → geeignetes Zentrum","Stay and play nach initialer Stabilisierung"],correct:2,explanation:"Akutes Aortensyndrom: Load-go-and-treat. Zeitkritisch! Transport in geeignetes Zentrum (Gefäßchirurgie/Kardiochirurgie)."}
,
{q:"Übergabe (SINNHAFT): Notfallpriorität (N) bei Aortendissektion – entscheidende C-Befunde?",opts:["C: RR an BEIDEN Armen (Differenz?), HF, periphere Pulse tastbar?, Schockzeichen","Nur die HF gemäß SOP des Rettungsdienstes, wobei die Wirksamkeit engmaschig kontrolliert werden muss","Nur der RR bei fehlenden Kontraindikationen","Nur die Rekapzeit unter Berücksichtigung des klinischen Bildes"],correct:0,explanation:"Aortensyndrom C: RR beidseits (Differenz >20 mmHg!), periphere Pulse (fehlend?), Schockzeichen, Hämodynamik → bestimmt OP-Dringlichkeit."}]},
{id:12,title:"Junger Patient mit Kokainkonsum",bpr:"aortensyndrom",scenario:"28-Jähriger nach Kokainkonsum. Reißender Thoraxschmerz, wandernd. RR 220/130. Neurologische Ausfälle im linken Bein.",
steps:[
{q:"Welcher Risikofaktor liegt hier vor?",opts:["Kokainkonsum (Vasokonstriktion, Hypertonie)","Alter mit Voranmeldung in der Zielklinik","Keine erkennbaren nach Ausschluss reversibler Ursachen","Geschlecht bei hämodynamischer Instabilität, was jedoch in der aktuellen Situation kontraindiziert wäre"],correct:0,explanation:"Kokain/Amphetamine sind relevante Risikofaktoren für das akute Aortensyndrom (starker RR-Anstieg)."},
{q:"Die neurologischen Ausfälle am Bein sprechen für?",opts:["Periphere arterielle Embolie durch Dissektion","Drogeneffekt unter Zeitdruck im Einsatzgeschehen","Schlaganfall als initiale Maßnahme vor Transport","Unabhängige Nervenläsion bei gesicherter Diagnose und Indikation"],correct:0,explanation:"Neurologische Symptome und periphere Durchblutungsstörungen durch die Dissektion in die abdominelle Aorta."},
{q:"Was gehört zur erweiterten Diagnostik?",opts:["Kapnographie mit begleitender Sauerstofftherapie","Temperaturmessung nach differentialdiagnostischer Abwägung","Pulsstatus aller Extremitäten + Blutdruckdifferenzen","BZ-Messung im Rahmen der Notfallversorgung"],correct:2,explanation:"Erweiterte Diagnostik: Schmerzcharakter, Pulsdifferenz, Blutdruckdifferenzen, periphere Durchblutung, 12-Kanal-EKG."},
{q:"Welches RR-Ziel verfolgen Sie?",opts:["< 140 mmHg systolisch","< 100 mmHg bei persistierender Symptomatik trotz Erstmaßnahmen","Keine Senkung","< 180 mmHg nach Anlage eines venösen Zugangs"],correct:0,explanation:"Akutes Aortensyndrom: RRsyst < 140 mmHg. Kontrolliert senken mit Urapidil."},
{q:"Was gehört zur Anamnese bei Drogenkonsum?",opts:["Nur Zeitpunkt gemäß den Empfehlungen des ÄLRD","Substanz, Menge, Zeitpunkt, Mischkonsum, Vorerkrankungen","Nur Substanzname unter Beachtung der Dosierungsgrenzen","Nur Allergien bei fortbestehender klinischer Verschlechterung"],correct:1,explanation:"Anamnese: Welche Substanz? Menge? Zeitpunkt? Mischkonsum? Vorerkrankungen? Material asservieren!"}
,
{q:"Übergabe (SINNHAFT): Handlungen (H) bei Aortendissektion?",opts:["RR-Senkung: Urapidil (Dosis, Ziel-RR 100-120 systolisch), Analgesie (Morphin? Wirkung?), volumenrestriktiv!","Nur der Transport mit paralleler Vorbereitung des Transports","Nur der Venenzugang nach dokumentierter Erstuntersuchung","Nur Analgesie unter Einbeziehung der Patientenanamnese"],correct:0,explanation:"Aortensyndrom-Handlungen: RR-Senkung aggressiv (Ziel <120 sys!), Urapidil (Dosis+Wirkung), Analgesie, KEIN Volumen-Push, Gefäßchirurgie vorangemeldet?"}]},
{id:13,title:"Typischer STEMI",bpr:"acs",scenario:"62-jähriger Mann, retrosternaler Druck mit Ausstrahlung in den linken Arm seit 45 min. Kaltschweißig, RR 140/90, HF 88. EKG: ST-Hebungen in II, III, aVF.",
steps:[
{q:"Welcher Infarkttyp liegt vor?",opts:["Instabile AP","NSTEMI bei fehlendem Ansprechen auf Ersttherapie","Anteriorer STEMI und anschließende Reevaluation nach spätestens 5 Minuten","Inferiorer STEMI"],correct:3,explanation:"ST-Hebungen in II, III, aVF = Inferiorer STEMI (RCA-Versorgungsgebiet)."},
{q:"Welche Medikamente geben Sie?",opts:["Glyceroltrinitrat + Furosemid","Amiodaron + Epinephrin","Nur ASS oral als Eskalationsmaßnahme bei Therapieversagen","ASS 250 mg i.v. + Heparin 5.000 I.E."],correct:3,explanation:"STEMI: ASS 250 mg i.v. + Heparin 5.000 I.E. i.v. Transport PCI-Klinik direkt ins HKL."},
{q:"Was ist bei einem inferioren STEMI bezüglich Glyceroltrinitrat zu beachten?",opts:["Nur oral geben unter Berücksichtigung des Patientenalters","Immer geben nach Erhebung eines Basis-Monitorings","Doppelte Dosis mit regelmäßiger Verlaufskontrolle","Kontraindiziert bei V.a. rechtsventrikulärer Beteiligung"],correct:3,explanation:"Inferiorer Infarkt mit möglicher RV-Beteiligung: Glyceroltrinitrat kontraindiziert (Preload-Senkung → Schock)."},
{q:"Was bedeutet 'Time is muscle'?",opts:["Muskelkater bei Verdacht auf kritische Verschlechterung","Je schneller die PCI, desto mehr Myokard gerettet","Nur bei Trauma relevant unter Beachtung möglicher Wechselwirkungen","Sport ist wichtig als leitliniengerechte Notfallmaßnahme"],correct:1,explanation:"Time is muscle: Jede Minute Ischämie zerstört Myokard. Schnellstmögliche PCI rettet Herzmuskel."},
{q:"Welche Schmerztherapie beim ACS?",opts:["Ibuprofen nach klinischer Einschätzung","Esketamin gemäß Behandlungspfad","Paracetamol bei stabilen Kreislaufverhältnissen","Morphin 2-5 mg i.v. titriert"],correct:3,explanation:"ACS-Schmerztherapie: Morphin 2-5 mg i.v. titriert. Schmerzreduktion senkt auch den O₂-Verbrauch des Myokards."}
,
{q:"Übergabe (SINNHAFT): Welche Notfallereignis-Info (N) ist beim ACS zeitkritisch?",opts:["Ob der Patient geraucht hat unter kontinuierlichem Monitoring","Wo der Patient arbeitet nach ABCDE-Reevaluation","WANN: Exakter Schmerzbeginn (Minuten zählen für Katheter-Entscheidung!)","Wie der Transport war bei gesichertem Atemweg, sofern keine allergischen Reaktionen in der Vorgeschichte bekannt sind"],correct:2,explanation:"Beim ACS ist der Symptombeginn entscheidend: Contact-to-Balloon-Time! 'Pain-to-Door' und 'Door-to-Balloon' bestimmen das Outcome."}]},
{id:14,title:"ACS bei Diabetikerin",bpr:"acs",scenario:"75-jährige Diabetikerin. Seit 2 Stunden Übelkeit, Oberbauchschmerzen und Dyspnoe. Kein typischer Brustschmerz. EKG: neue ST-Senkungen V1-V4.",
steps:[
{q:"Warum ist dieser Fall atypisch?",opts:["Zu alt für ACS laut aktuellem Algorithmus","Diabetiker zeigen häufig atypische Symptome","EKG ist unauffällig nach Sicherung der Vitalfunktionen","Frauen bekommen kein ACS unter Beachtung der Kontraindikationen"],correct:1,explanation:"Atypische Beschwerden bei Diabetikern, Älteren, Frauen und Niereninsuffizienz – stille Ischämie!"},
{q:"ST-Senkungen V1-V4 können auf was hinweisen?",opts:["Normalbefund bei dokumentierter Indikation","Möglichen posterioren STEMI → erweiterte Ableitungen!","Perikarditis mit anschließender Transportentscheidung","Nur instabile AP nach initialer Stabilisierung"],correct:1,explanation:"ST-Senkungen V1-V4 können einen posterioren STEMI spiegeln → V7-V9 ableiten!"},
{q:"Welche Medikamentengabe erfolgt beim NSTE-ACS?",opts:["ASS + Amiodaron","Nur ASS","Heparin allein","ASS + Heparin"],correct:3,explanation:"NSTE-ACS: ASS + Heparin. Transport nach regionalem Zuweisungskonzept."},
{q:"Was bedeuten erweiterte Ableitungen V7-V9?",opts:["Nur in Klinik gemäß SOP des Rettungsdienstes","Nur für Kinder bei fehlenden Kontraindikationen","Posteriore Ableitungen zum Nachweis eines Hinterwandinfarkts","Standard-EKG unter Berücksichtigung des klinischen Bildes"],correct:2,explanation:"V7-V9: Posteriore Ableitungen. ST-Hebungen dort = posteriorer STEMI (oft übersehen im Standard-12-Kanal-EKG)."},
{q:"Wie transportieren Sie diese Patientin?",opts:["Hausarzt mit Voranmeldung in der Zielklinik","PCI-Klinik nach regionalem Zuweisungskonzept","Ambulant nach Ausschluss reversibler Ursachen","Nächstes Krankenhaus bei hämodynamischer Instabilität"],correct:1,explanation:"ACS-Patienten: Transport nach regionalem Zuweisungskonzept (PCI-Klinik). Voranmeldung!"}
,
{q:"Übergabe (SINNHAFT): Notfallpriorität (N) bei STEMI – welcher ABCDE-Bereich hat Vorrang?",opts:["E: Temperatur unter Zeitdruck im Einsatzgeschehen","A: Atemweg immer zuerst als initiale Maßnahme vor Transport","D: GCS bei gesicherter Diagnose und Indikation","C: EKG-Befund (ST-Hebung wo?), RR, HF, Troponin-Wert, Rhythmusstörungen"],correct:3,explanation:"Beim STEMI ist C zentral: WELCHE ST-Hebung (Lokalisation!), Hämodynamik (kardiogener Schock?), Rhythmus (VT/VF-Episoden?)."}]},
{id:15,title:"ACS mit Lungenödem",bpr:"acs",scenario:"70-Jähriger mit ACS-Symptomen. RR 170/100, HF 110, SpO₂ 88%. Beidseits feuchte Rasselgeräusche, Orthopnoe. EKG: ST-Hebungen V1-V4.",
steps:[
{q:"Welches Problem hat der Patient zusätzlich zum STEMI?",opts:["Anaphylaxie mit begleitender Sauerstofftherapie","Kardiales Lungenödem","Bronchialobstruktion","Pneumonie nach differentialdiagnostischer Abwägung"],correct:1,explanation:"Feuchte RG beidseits + Orthopnoe + ACS = Kardiales Lungenödem bei akutem Myokardinfarkt."},
{q:"Wie lagern Sie den Patienten?",opts:["Oberkörper hoch, Beine tief","Seitenlage im Rahmen der Notfallversorgung","Flach bei persistierender Symptomatik trotz Erstmaßnahmen","Schocklage nach Anlage eines venösen Zugangs"],correct:0,explanation:"Kardiales Lungenödem: Oberkörperhochlagerung, Beine tief (Reduktion der Vorlast)."},
{q:"Welche zusätzliche Therapie neben ACS-Behandlung?",opts:["Nur Sauerstoff gemäß den Empfehlungen des ÄLRD","Volumentherapie 1000 ml unter Beachtung der Dosierungsgrenzen","Nur Furosemid bei fortbestehender klinischer Verschlechterung","NIV/CPAP + Glyceroltrinitrat + ggf. Furosemid"],correct:3,explanation:"Kardiales Lungenödem: CPAP (PEEP 5-10), Glyceroltrinitrat sublingual, Furosemid 20 mg i.v."},
{q:"Welche Furosemid-Dosis geben Sie?",opts:["5 mg mit paralleler Vorbereitung des Transports","200 mg","100 mg","20 mg i.v."],correct:3,explanation:"Furosemid 20 mg i.v. beim kardialen Lungenödem. Senkt Vorlast und fördert Diurese."},
{q:"Welche CPAP-Einstellung wählen Sie?",opts:["PEEP 2 cmH₂O","PEEP 5-10 cmH₂O","Kein PEEP","PEEP 20 cmH₂O"],correct:1,explanation:"CPAP mit PEEP 5-10 cmH₂O. Verbessert Oxygenierung und reduziert Vorlast (intrathorakaler Druck)."}
,
{q:"Übergabe (SINNHAFT): Handlungen (H) beim ACS – was muss unbedingt mit Zeitpunkt übergeben werden?",opts:["Nur die Transportart nach dokumentierter Erstuntersuchung mit sofortiger Dokumentation im Einsatzprotokoll und Voranmeldung","Nur dass EKG geschrieben wurde unter Einbeziehung der Patientenanamnese","ASS + Heparin + ggf. Morphin/Nitro mit Uhrzeit UND Wirkung (Schmerzreduktion? RR-Änderung?)","Nur die ASS-Gabe bei fehlendem Ansprechen auf Ersttherapie"],correct:2,explanation:"ACS-Handlungen: ASS-Gabe (Uhrzeit!), Heparin, Analgesie + Wirkung, Nitro + RR-Effekt, 12-Kanal-EKG-Befund, ggf. Katheteralarmierung."}]},
{id:16,title:"Anaphylaxie nach Wespenstich",bpr:"anaphylaxie",scenario:"35-jähriger Mann, Wespenstich. Urtikaria, Atemnot, exspiratorisches Giemen, RR 80/50, HF 130, SpO₂ 88%.",
steps:[
{q:"Welcher Schweregrad liegt vor?",opts:["Grad III","Grad I","Grad II","Grad IV"],correct:0,explanation:"Grad III: Kreislaufinstabilität (Hypotonie/Tachykardie) + Bronchospasmus + Hautreaktionen."},
{q:"Erste medikamentöse Maßnahme?",opts:["Prednisolon i.v.","Epinephrin 0,5 mg i.m.","Salbutamol als Eskalationsmaßnahme bei Therapieversagen","Dimetinden i.v, abhängig vom klinischen Verlauf und den erhobenen Vitalparametern"],correct:1,explanation:"Epinephrin i.m. ist die wichtigste und zeitkritischste Maßnahme ab Grad II!"},
{q:"Wann repetieren Sie Epinephrin?",opts:["Nie unter Berücksichtigung des Patientenalters","Nur durch Notarzt nach Erhebung eines Basis-Monitorings","Alle 5 Minuten bei Instabilität","Nach 30 Minuten mit regelmäßiger Verlaufskontrolle"],correct:2,explanation:"Repetition alle 5 Minuten möglich bei anhaltender Instabilität."},
{q:"Wo injizieren Sie Epinephrin i.m.?",opts:["Bauch bei Verdacht auf kritische Verschlechterung unter Berücksichtigung möglicher Differentialdiagnosen im Verlauf","Gesäß unter Beachtung möglicher Wechselwirkungen","Unterarm als leitliniengerechte Notfallmaßnahme","M. vastus lateralis (Oberschenkel, anterolateral)"],correct:3,explanation:"Epinephrin i.m. in den M. vastus lateralis (Oberschenkel, anterolateral). Beste Resorption dort."},
{q:"Welche Volumentherapie gehört dazu?",opts:["NaCl 0,9% 100 ml nach klinischer Einschätzung","VEL 500-1000 ml Bolus bei Hypotonie","Glucose 5% gemäß Behandlungspfad","Keine bei stabilen Kreislaufverhältnissen"],correct:1,explanation:"Bei Hypotonie/Schock: VEL-Bolus (500-1000 ml). Volumentherapie ist essenziell bei distributivem Schock."}
,
{q:"Übergabe (SINNHAFT): Notfallereignis (N) bei Anaphylaxie – was ist die wichtigste WIE-Information?",opts:["WIE: Auslöser identifiziert? (Wespe, Erdnuss, Medikament?) + Zeitpunkt der Exposition","Ob der Patient oft allergisch reagiert unter kontinuierlichem Monitoring, nach vorheriger Abklärung aller reversiblen Ursachen gemäß Algorithmus","Transportdauer nach ABCDE-Reevaluation","Welche Farbe das Allergen hatte bei gesichertem Atemweg"],correct:0,explanation:"Bei Anaphylaxie: Auslöser ist entscheidend für die Klinik (Nachbeobachtung, Allergiepass, spezifische Therapie). Zeitpunkt der Exposition für Verlauf."}]},
{id:17,title:"Medikamentenallergie im RTW",bpr:"anaphylaxie",scenario:"45-jährige Frau nach Antibiotikagabe. Gesichtsschwellung, Uvulaödem, inspiratorischer Stridor, RR 95/60, HF 115.",
steps:[
{q:"Was ist das A-Problem hier?",opts:["Pneumothorax laut aktuellem Algorithmus","Bronchospasmus nach Sicherung der Vitalfunktionen","Uvulaödem mit inspiratorischem Stridor","Fremdkörper unter Beachtung der Kontraindikationen"],correct:2,explanation:"Uvulaödem verursacht obere Atemwegsobstruktion → inspiratorischer Stridor = A-Problem!"},
{q:"Was tun Sie neben Epinephrin i.m. bei Stridor?",opts:["Intubation bei dokumentierter Indikation","Salbutamol vernebeln","Prednisolon i.v mit anschließender Transportentscheidung","Epinephrin vernebeln (4 mg)"],correct:3,explanation:"Bei Stridor/Schwellung: Epinephrin-Vernebelung 4 mg zusätzlich zum i.m.-Epinephrin."},
{q:"Welche weiteren Medikamente gehören zum Schema?",opts:["Dimetinden i.v. + Prednisolon i.v. + VEL","Furosemid + Glyceroltrinitrat","Amiodaron + Atropin nach initialer Stabilisierung","Midazolam + Esketamin gemäß SOP des Rettungsdienstes"],correct:0,explanation:"Kompletttherapie: Dimetinden (H1-Blocker), Prednisolon (Glukokortikoid), VEL (Volumengabe)."},
{q:"Prednisolon-Dosis bei Anaphylaxie?",opts:["Keine bei fehlenden Kontraindikationen","1-2 mg/kgKG i.v.","10 mg unter Berücksichtigung des klinischen Bildes","500 mg mit Voranmeldung in der Zielklinik"],correct:1,explanation:"Prednisolon 1-2 mg/kgKG i.v. (Erwachsene ca. 100-250 mg). Wirkt erst verzögert (Stunden), verhindert biphasische Reaktion."},
{q:"Was ist eine biphasische Reaktion?",opts:["Zwei Allergene nach Ausschluss reversibler Ursachen","Unmöglich bei hämodynamischer Instabilität","Erneute Anaphylaxie-Symptome nach symptomfreiem Intervall (4-12h)","Nur bei Kindern unter Zeitdruck im Einsatzgeschehen"],correct:2,explanation:"Biphasische Reaktion: Erneute Anaphylaxie nach symptomfreiem Intervall (4-12h). Daher immer Kliniktransport + Überwachung!"}
,
{q:"Übergabe (SINNHAFT): Handlungen (H) bei Anaphylaxie – was muss mit Uhrzeit übergeben werden?",opts:["Nur die Lagerung als initiale Maßnahme vor Transport","Nur der Venenzugang bei gesicherter Diagnose und Indikation, wobei die Wirksamkeit engmaschig kontrolliert werden muss","Epinephrin (i.m./i.v.? Dosis? Repetition?), Volumen, Prednisolon, Antihistaminika + Wirkung","Nur ob es besser wurde mit begleitender Sauerstofftherapie"],correct:2,explanation:"Anaphylaxie-Handlungen: Epi-Dosis + Weg + Uhrzeit + Repetition, Volumenmenge, Prednisolon, Antihistaminika, Wirkung (Besserung der Symptome?)."}]},
{id:18,title:"Anaphylaxie Grad IV",bpr:"anaphylaxie",scenario:"8-jähriges Kind, bekannte Erdnussallergie. Versehentlich Erdnüsse gegessen. Initial Urtikaria, dann Bewusstlosigkeit. Kein Puls tastbar.",
steps:[
{q:"Welcher Schweregrad liegt vor?",opts:["Grad I nach differentialdiagnostischer Abwägung","Grad III im Rahmen der Notfallversorgung","Grad II bei persistierender Symptomatik trotz Erstmaßnahmen","Grad IV – Kreislaufstillstand"],correct:3,explanation:"Grad IV = Kreislaufstillstand / Atem-/Kreislaufstillstand. Sofort CPR beginnen!"},
{q:"Was ist die initiale Maßnahme?",opts:["Epinephrin i.m, was jedoch in der aktuellen Situation kontraindiziert wäre","BPR Reanimation (PLS)","Dimetinden i.v.","Salbutamol nach Anlage eines venösen Zugangs"],correct:1,explanation:"Grad IV = Kreislaufstillstand → BPR Reanimation. Epinephrin wird i.v./i.o. im Rahmen der CPR gegeben."},
{q:"Welche Epinephrin-Dosis geben Sie bei Reanimation (25 kgKG)?",opts:["0,25 mg i.v.","0,15 mg i.m.","0,5 mg i.m.","1 mg i.v."],correct:0,explanation:"PLS Reanimation: 0,01 mg/kgKG i.v. = 25 × 0,01 = 0,25 mg Epinephrin i.v./i.o."},
{q:"Welches HDM:Beatmungs-Verhältnis verwenden Sie beim Kind?",opts:["15:2","3:1","30:2","5:1"],correct:0,explanation:"PLS: 15:2 bei professionellen Helfern. 5 initiale Beatmungen, da hypoxischer Kreislaufstillstand wahrscheinlich."},
{q:"Was tun Sie nach erfolgreicher Reanimation?",opts:["Nur beobachten gemäß den Empfehlungen des ÄLRD","Nichts unter Beachtung der Dosierungsgrenzen","Entlassen bei fortbestehender klinischer Verschlechterung","Post-ROSC-Protokoll: SpO₂ 94-98%, BZ-Kontrolle, Monitoring, Kliniktransport"],correct:3,explanation:"Post-ROSC: ABCDE, SpO₂ 94-98%, BZ kontrollieren, kontinuierliches Monitoring, Transport Kinderklinik."}
,
{q:"Übergabe (SINNHAFT): Notfallpriorität bei Anaphylaxie – welche ABCDE-Befunde haben Vorrang?",opts:["A: Schwellung Oropharynx + B: Bronchospasmus + C: Schock (RR, HF, Rekapzeit)","D: GCS ist entscheidend mit paralleler Vorbereitung des Transports","E: Hautbefund ist am wichtigsten nach dokumentierter Erstuntersuchung und anschließende Reevaluation nach spätestens 5 Minuten","Nur B: SpO₂ unter Einbeziehung der Patientenanamnese"],correct:0,explanation:"Anaphylaxie-Priorität: A (Glottisödem? Stridor?), B (Bronchospasmus, SpO₂, Giemen), C (Schock: Hypotonie, Tachykardie). Lebensbedrohung ABC!"}]},
{id:19,title:"Akuter Beinarterienverschluss",bpr:"art_verschluss",scenario:"68-jähriger Mann mit Vorhofflimmern. Plötzlich einsetzender Schmerz im rechten Bein. Bein blass, kühl, kein Fußpuls tastbar, Sensibilitätsstörungen.",
steps:[
{q:"Welches Symptomenmuster liegt vor?",opts:["Tiefe Venenthrombose bei fehlendem Ansprechen auf Ersttherapie","Ischialgie als Eskalationsmaßnahme bei Therapieversagen","6P: Pain, Pallor, Pulselessness, Paresthesia","Kompartmentsyndrom unter Berücksichtigung des Patientenalters"],correct:2,explanation:"Die 6P sind klassisch für den akuten arteriellen Verschluss: Pain, Pallor, Pulselessness, Paresthesia, Paralysis, Prostration."},
{q:"Welches Medikament geben Sie bei wahrscheinlichem arteriellen Verschluss?",opts:["Amiodaron 300 mg","ASS 250 mg nach Erhebung eines Basis-Monitorings","Heparin 5.000 I.E. i.v.","Furosemid 20 mg"],correct:2,explanation:"Bei wahrscheinlichem arteriellen Verschluss: Heparin 5.000 I.E. i.v. (Antikoagulation)."},
{q:"Wie lagern Sie die betroffene Extremität?",opts:["Hochlagerung mit regelmäßiger Verlaufskontrolle","Tieflagerung + Immobilisation","Wickelung bei Verdacht auf kritische Verschlechterung","Schocklage unter Beachtung möglicher Wechselwirkungen"],correct:1,explanation:"Tieflagerung der betroffenen Extremität + Immobilisation + Polsterung gegen Druckstellen."},
{q:"Was dürfen Sie bei akutem arteriellem Verschluss NICHT tun?",opts:["Heparin geben als leitliniengerechte Notfallmaßnahme","Monitoring nach klinischer Einschätzung","Betroffene Extremität wärmen, massieren oder hochlagern","Schmerztherapie gemäß Behandlungspfad"],correct:2,explanation:"KEINE Wärme, KEIN Massieren, KEINE Hochlagerung! Tieflagerung, Polsterung, Immobilisation."},
{q:"Welche Schmerzmittel eignen sich?",opts:["Diclofenac bei stabilen Kreislaufverhältnissen","Ibuprofen oral unter kontinuierlichem Monitoring","Paracetamol rektal nach ABCDE-Reevaluation","Morphin oder Esketamin i.v. titriert"],correct:3,explanation:"Starke ischämische Schmerzen: Morphin oder Esketamin i.v. titriert nach BPR Schmerzen."}
,
{q:"Übergabe (SINNHAFT): Notfallereignis (N) bei Arterieller Verschluss – welche Kerninfo?",opts:["WAS: Verdachtsdiagnose, WIE: Ursache/Auslöser, WANN: Symptombeginn mit exakter Uhrzeit","Nur ob der Patient Schmerzen hat bei gesichertem Atemweg","Nur die Diagnose nennen laut aktuellem Algorithmus","Nur den Transportweg nach Sicherung der Vitalfunktionen"],correct:0,explanation:"Arterieller Verschluss: Beim Notfallereignis immer WAS (Verdachtsdiagnose), WIE (Ursache/Auslöser), WANN (exakter Zeitpunkt) strukturiert übergeben."}]},
{id:20,title:"Akuter Armarterienverschluss",bpr:"art_verschluss",scenario:"72-jährige Frau, Z.n. Herzklappenersatz. Plötzlich kalter, blasser linker Arm. Kein Radialispuls tastbar. Starke Schmerzen.",
steps:[
{q:"Welcher Risikofaktor ist am relevantesten?",opts:["Herzklappenersatz (Emboliequelle)","Geschlecht unter Beachtung der Kontraindikationen","Alter bei dokumentierter Indikation","Schmerzen mit anschließender Transportentscheidung"],correct:0,explanation:"Klappenersatz ist ein Risikofaktor für arterielle Embolien."},
{q:"Was geben Sie neben Heparin?",opts:["ASS nach initialer Stabilisierung","Furosemid gemäß SOP des Rettungsdienstes","Schmerztherapie (BPR Schmerzen)","Amiodaron bei fehlenden Kontraindikationen"],correct:2,explanation:"Schmerztherapie nach BPR Schmerzen – die Ischämie verursacht starke Schmerzen."},
{q:"Wie dringlich ist der Transport?",opts:["Kann warten unter Berücksichtigung des klinischen Bildes","Nächster Tag mit Voranmeldung in der Zielklinik","Zeitkritisch – drohende Nekrose!","Ambulant nach Ausschluss reversibler Ursachen"],correct:2,explanation:"Der akute arterielle Verschluss ist ein Notfall mit drohendem Extremitätenverlust bei Zeitverzögerung!"},
{q:"Was dokumentieren Sie an der betroffenen Extremität?",opts:["Nur Farbe bei hämodynamischer Instabilität, sofern keine allergischen Reaktionen in der Vorgeschichte bekannt sind","Pulsstatus, Hautfarbe, Temperatur, Sensibilität, Motorik","Nur Puls unter Zeitdruck im Einsatzgeschehen","Nur Temperatur als initiale Maßnahme vor Transport"],correct:1,explanation:"Dokumentation: Pulsstatus, Hautfarbe/Temperatur, Sensibilität, Motorik → 6P-Schema."},
{q:"Wohin transportieren Sie?",opts:["Klinik mit Gefäßchirurgie","Nächstes KH bei gesicherter Diagnose und Indikation","Hausarzt mit begleitender Sauerstofftherapie","Ambulant nach differentialdiagnostischer Abwägung"],correct:0,explanation:"Akuter arterieller Verschluss → Klinik mit Gefäßchirurgie. Zeitkritisch (6-8h Ischämietoleranz)."}
,
{q:"Übergabe (SINNHAFT): Notfallpriorität (N) bei Arterieller Verschluss – nach welcher Struktur?",opts:["Nach dem (x)ABCDE-Schema mit pathologischen Befunden und Vitalparametern","Nach Dringlichkeit der Diagnostik im Rahmen der Notfallversorgung","Nach persönlichem Ermessen bei persistierender Symptomatik trotz Erstmaßnahmen","Alphabetisch nach Befunden nach Anlage eines venösen Zugangs"],correct:0,explanation:"Arterieller Verschluss: Notfallpriorität IMMER nach ABCDE strukturiert. Pathologische Befunde + Vitalparameter pro Buchstabe, auffällige Befunde hervorheben."}]},
{id:21,title:"Embolie bei Endokarditis",bpr:"art_verschluss",scenario:"45-Jähriger, i.v.-Drogengebrauch. Fieber seit Tagen, nun plötzlicher Schmerz linkes Bein mit Blässe und Pulslosigkeit. HF 105 unregelmäßig.",
steps:[
{q:"Welche Grunderkrankung vermuten Sie als Emboliequelle?",opts:["Lungenembolie gemäß den Empfehlungen des ÄLRD","Vorhofflimmern allein","Endokarditis bei i.v.-Drogenkonsum","Aortenstenose unter Beachtung der Dosierungsgrenzen"],correct:2,explanation:"Fieber + i.v.-Drogenkonsum + arterieller Verschluss → V.a. septische Embolie bei Endokarditis."},
{q:"Was ist hier anders als beim typischen arteriellen Verschluss?",opts:["Zusätzlich V.a. Sepsis → BPR Sepsis beachten","Kein Transport nötig bei fortbestehender klinischer Verschlechterung","Schmerztherapie nicht nötig","Heparin nicht indiziert mit paralleler Vorbereitung des Transports"],correct:0,explanation:"Hier liegt wahrscheinlich auch eine Sepsis vor → zusätzlich Volumentherapie, Temperaturmessung."},
{q:"Geben Sie trotzdem Heparin?",opts:["Ja, bei wahrscheinlichem arteriellen Verschluss","Nein, nur ASS nach dokumentierter Erstuntersuchung","Nein, nie bei Fieber unter Einbeziehung der Patientenanamnese","Nur wenn Notarzt da bei fehlendem Ansprechen auf Ersttherapie"],correct:0,explanation:"Ja, Heparin 5.000 I.E. i.v. bei wahrscheinlichem arteriellen Verschluss – auch bei septischer Embolie."},
{q:"Welches Monitoring ist hier besonders wichtig?",opts:["12-Kanal-EKG (Endokarditis → HRST), Temperatur, Blutdruck","Nur BZ als Eskalationsmaßnahme bei Therapieversagen","Nur SpO₂ unter Berücksichtigung des Patientenalters","Nur Temperatur nach Erhebung eines Basis-Monitorings"],correct:0,explanation:"Endokarditis: 12-Kanal-EKG (HRST, Klappenvitien), Temperatur, RR-Monitoring. V.a. Sepsis parallel behandeln."},
{q:"Volumentherapie bei V.a. Sepsis?",opts:["Keine mit regelmäßiger Verlaufskontrolle","Zurückhaltend bei Verdacht auf kritische Verschlechterung","Glucose 5% unter Beachtung möglicher Wechselwirkungen","VEL großzügig über i.v.-Zugang"],correct:3,explanation:"Bei V.a. Sepsis: Großzügige VEL-Gabe. Möglichst 2 großlumige i.v.-Zugänge."}
,
{q:"Übergabe (SINNHAFT): Handlungen (H) bei Arterieller Verschluss – was wird oft vergessen?",opts:["Die Einsatznummer als leitliniengerechte Notfallmaßnahme","Bewusst unterlassene Maßnahmen und deren Begründung","Der Name des Fahrers nach klinischer Einschätzung","Die Transportzeit gemäß Behandlungspfad"],correct:1,explanation:"Arterieller Verschluss: Bei Handlungen nicht nur WAS getan wurde, sondern auch was bewusst NICHT getan wurde + Begründung. Ermöglicht dem Team die Entscheidung zu prüfen."}]},
{id:22,title:"Schwerer Asthmaanfall",bpr:"bronchial",scenario:"22-jährige Patientin, bekanntes Asthma. AF 32/min, SpO₂ 86%, exspiratorisches Giemen beidseits, kann kaum sprechen.",
steps:[
{q:"Erste Therapiemaßnahme?",opts:["Esketamin bei stabilen Kreislaufverhältnissen","Prednisolon i.v unter kontinuierlichem Monitoring","Sauerstoff + Salbutamol-Vernebelung","Intubation nach ABCDE-Reevaluation"],correct:2,explanation:"Hochdosierte O₂-Gabe + Salbutamol-Vernebelung als initiale Basistherapie."},
{q:"Welche inhalative Therapie ergänzen Sie?",opts:["Furosemid bei gesichertem Atemweg","Ipratropiumbromid","Dimetinden laut aktuellem Algorithmus","Epinephrin nach Sicherung der Vitalfunktionen"],correct:1,explanation:"Ipratropiumbromid-Vernebelung ergänzend zur Salbutamol-Vernebelung bei schwerer Obstruktion."},
{q:"SpO₂ weiter 82%, drohende Erschöpfung. Was erwägen Sie?",opts:["Schocklage","Thoraxentlastungspunktion","Glyceroltrinitrat","CPAP"],correct:3,explanation:"CPAP bei Hypoxie und drohender Erschöpfung. Bei Hyperkapnie: NIV."},
{q:"Prednisolon-Dosis beim Asthmaanfall?",opts:["500 mg unter Beachtung der Kontraindikationen","Nicht indiziert","1-2 mg/kgKG i.v.","10 mg bei dokumentierter Indikation"],correct:2,explanation:"Prednisolon 1-2 mg/kgKG i.v. bei akuter Bronchialobstruktion. Wirkt antientzündlich (verzögert)."},
{q:"Wann ist eine Intubation beim Asthmaanfall indiziert?",opts:["Nur bei Erschöpfung/Bewusstlosigkeit trotz maximaler Therapie","Sofort mit anschließender Transportentscheidung","Nie nach initialer Stabilisierung","Bei jedem Anfall gemäß SOP des Rettungsdienstes"],correct:0,explanation:"Intubation nur als Ultima Ratio bei drohender/manifester Erschöpfung trotz maximaler medikamentöser Therapie."}
,
{q:"Übergabe (SINNHAFT): Notfallpriorität (N) bei Asthma/COPD – welcher ABCDE-Bereich dominiert?",opts:["C: Blutdruck bei fehlenden Kontraindikationen","E: Temperatur unter Berücksichtigung des klinischen Bildes","A: Atemweg mit Voranmeldung in der Zielklinik","B: AF, SpO₂, Auskultation (Giemen? Stilles Segment?), Sprechdyspnoe, Einsatz Atemhilfsmuskulatur"],correct:3,explanation:"Bronchospasmus: B dominiert! AF, SpO₂, Auskultation (Giemen = obstruktiv, stilles Segment = sehr ernst!), Sprechdyspnoe, Atemhilfsmuskulatur."}]},
{id:23,title:"COPD-Exazerbation",bpr:"bronchial",scenario:"70-jähriger COPD-Patient, Fieber 38,5°C, zunehmende Dyspnoe seit 3 Tagen. Giemen und Brummen beidseits. SpO₂ 85%, AF 28.",
steps:[
{q:"Handelt es sich primär um ein hypoxisches oder hyperkapnisches Problem?",opts:["Hypoxisch nach Ausschluss reversibler Ursachen mit sofortiger Dokumentation im Einsatzprotokoll und Voranmeldung","Hyperkapnisch (schleichend + Giemen + Fieber = inf. COPD)","Mischform bei hämodynamischer Instabilität","Keines unter Zeitdruck im Einsatzgeschehen"],correct:1,explanation:"Schleichender Beginn + Giemen/Brummen + Fieber → V.a. infektexazerbierte COPD = primär hyperkapnisch."},
{q:"Wie dosieren Sie den Sauerstoff?",opts:["Nur über Nasensonde als initiale Maßnahme vor Transport","Angepasste O₂-Gabe (Ziel SpO₂ 88-92%)","Kein Sauerstoff bei gesicherter Diagnose und Indikation","Hochdosiert (15 l/min) mit begleitender Sauerstofftherapie"],correct:1,explanation:"Bei COPD/Hyperkapnie: Angepasste O₂-Gabe, Ziel SpO₂ 88-92%. Keine unkontrollierte High-Flow-Gabe!"},
{q:"Welche Beatmungsform wählen Sie bei drohender Erschöpfung?",opts:["CPAP nach differentialdiagnostischer Abwägung","Beutel-Maske im Rahmen der Notfallversorgung","NIV (mit Druckunterstützung)","Intubation bei persistierender Symptomatik trotz Erstmaßnahmen"],correct:2,explanation:"Bei Hyperkapnie: NIV = PEEP + inspiratorische Druckunterstützung (PS/ASB)."},
{q:"Warum ist unkontrollierte O₂-Gabe bei COPD gefährlich?",opts:["Nur bei Kindern nach Anlage eines venösen Zugangs","Kann den Atemantrieb supprimieren (CO₂-Narkose)","Nie gefährlich gemäß den Empfehlungen des ÄLRD","Zu teuer unter Beachtung der Dosierungsgrenzen, abhängig vom klinischen Verlauf und den erhobenen Vitalparametern"],correct:1,explanation:"Bei chronischer Hyperkapnie: Atemantrieb teils O₂-gesteuert. Unkontrolliert hoher O₂ kann Atemantrieb supprimieren → CO₂-Narkose."},
{q:"Welche NIV-Einstellung wählen Sie?",opts:["CPAP ohne PS bei fortbestehender klinischer Verschlechterung","Nur PEEP mit paralleler Vorbereitung des Transports","Nur PS nach dokumentierter Erstuntersuchung","PEEP + inspiratorische Druckunterstützung (IPAP/PS)"],correct:3,explanation:"NIV bei Hyperkapnie: PEEP (5-8) + inspiratorische Druckunterstützung (IPAP/PS 10-15). Nicht nur CPAP!"}
,
{q:"Übergabe (SINNHAFT): Handlungen (H) bei schwerem Asthmaanfall?",opts:["Nur die Sauerstoffgabe unter Einbeziehung der Patientenanamnese","Nur die Medikamentennamen bei fehlendem Ansprechen auf Ersttherapie","Salbutamol-Verneblung (Dosis, Häufigkeit), Ipratropium, Prednisolon, Magnesium, Epi s.c. – jeweils mit Wirkung (Besserung SpO₂/AF?)","Nur ob inhaliert wurde als Eskalationsmaßnahme bei Therapieversagen"],correct:2,explanation:"Asthma-Handlungen: Salbutamol (Dosis+Häufigkeit), Ipratropium, Prednisolon (Dosis), ggf. Magnesium/Epi, PLUS Wirkung (SpO₂-Verbesserung? AF-Rückgang?)."}]},
{id:24,title:"Asthma bei Kind",bpr:"bronchial",scenario:"5-jähriges Kind, bekanntes Asthma. Exspiratorisches Giemen, SpO₂ 89%, sichtbare Einziehungen interkostal. Eigenes Salbutamol-Spray mehrfach benutzt.",
steps:[
{q:"Welche Salbutamol-Dosis vernebeln Sie beim Kind?",opts:["5 mg unter Berücksichtigung des Patientenalters","10 mg nach Erhebung eines Basis-Monitorings","0,5 mg mit regelmäßiger Verlaufskontrolle","1,25-2,5 mg"],correct:3,explanation:"Kinder: 1,25-2,5 mg Salbutamol vernebeln (halbe Erwachsenendosis)."},
{q:"Welches Medikament geben Sie systemisch?",opts:["Dimetinden","Amiodaron bei Verdacht auf kritische Verschlechterung","Prednisolon i.v.","Morphin unter Beachtung möglicher Wechselwirkungen"],correct:2,explanation:"Prednisolon 1-2 mg/kgKG i.v. bei akuter Bronchialobstruktion."},
{q:"Repetition Salbutamol?",opts:["Nie als leitliniengerechte Notfallmaßnahme","Nur durch Notarzt unter Berücksichtigung möglicher Differentialdiagnosen im Verlauf","Ja, Repetition möglich","Nach 1 Stunde nach klinischer Einschätzung"],correct:2,explanation:"Salbutamol-Vernebelung kann repetiert werden bei anhaltender Obstruktion."},
{q:"Ab welchem Alter ist Salbutamol-Vernebelung zugelassen?",opts:["Ab Geburt (dosisadaptiert)","Ab 6 Jahre gemäß Behandlungspfad","Ab 12 Jahre bei stabilen Kreislaufverhältnissen","Ab 18 Jahre unter kontinuierlichem Monitoring"],correct:0,explanation:"Salbutamol-Vernebelung ist ab Geburt möglich. Dosisanpassung: Kinder 1,25-2,5 mg, Erwachsene 5 mg."},
{q:"Was beobachten Sie nach Salbutamol-Gabe?",opts:["Nur Temperatur nach ABCDE-Reevaluation","Nur Pupillen bei gesichertem Atemweg","SpO₂, Atemarbeit, Giemen, HF (Tachykardie als UAW)","Nur SpO₂ laut aktuellem Algorithmus"],correct:2,explanation:"Nach Salbutamol: SpO₂, Atemarbeit, Giemen beurteilen. Cave: Tachykardie als UAW (β₂-Effekt)."}
,
{q:"Übergabe (SINNHAFT): Anamnese (A) bei COPD-Exazerbation – was ist besonders relevant?",opts:["Nur die Diagnose COPD nach Sicherung der Vitalfunktionen","Nur die Medikamentenliste unter Beachtung der Kontraindikationen","Heim-O₂? LTOT-Dosis? Vorherige Intubationen/NIV? COPD-Stadium? Aktuelle Infekte? CO₂-Retainer?","Nur die Rauchgewohnheiten bei dokumentierter Indikation"],correct:2,explanation:"COPD-Anamnese: Heim-O₂ (LTOT-Dosis!), Z.n. Intubation/NIV (Schweregrad!), COPD-Stadium (GOLD), Infektexazerbation?, CO₂-Retainer (Vorsicht mit O₂!)."}]},
{id:25,title:"Dehydratation bei Senioren",bpr:"dehydratation",scenario:"82-jährige Patientin, Pflegeheim. Seit Tagen schlecht getrunken. Desorientiert, trockene Schleimhäute, stehende Hautfalten. RR 90/60, HF 110.",
steps:[
{q:"Welcher Schock-Typ liegt hier am wahrscheinlichsten vor?",opts:["Kardiogener Schock mit anschließender Transportentscheidung","Hypovolämischer Schock durch Dehydratation","Anaphylaktischer Schock nach initialer Stabilisierung","Septischer Schock gemäß SOP des Rettungsdienstes"],correct:1,explanation:"Trockene Schleimhäute + Hypotonie + Tachykardie bei mangelnder Flüssigkeitsaufnahme → hypovolämisch."},
{q:"Muss eine Sepsis ausgeschlossen werden?",opts:["Nur bei Fieber bei fehlenden Kontraindikationen","Nein unter Berücksichtigung des klinischen Bildes","Nur bei jungen Patienten, nach vorheriger Abklärung aller reversiblen Ursachen gemäß Algorithmus","Ja, immer – BPR Sepsis beachten"],correct:3,explanation:"Immer Sepsis ausschließen! Dehydratation und Sepsis haben überlappende Symptome."},
{q:"Patientin ist nicht wach. Wie substituieren Sie Volumen?",opts:["i.v.-Zugang → Vollelektrolytlösung","NaCl 0,9% 2 Liter Bolus","Glucose 5% mit Voranmeldung in der Zielklinik","Zum Trinken animieren"],correct:0,explanation:"Nicht wach/schluckfähig: i.v.-Zugang → VEL. Bedarfsgerecht substituieren."},
{q:"Wie viel Volumen geben Sie initial?",opts:["250-500 ml VEL, dann Re-Evaluation","Kein Volumen nach Ausschluss reversibler Ursachen","50 ml bei hämodynamischer Instabilität","2 Liter Bolus unter Zeitdruck im Einsatzgeschehen"],correct:0,explanation:"VEL bedarfsgerecht: 250-500 ml initial, dann Re-Evaluation (RR, HF, Bewusstsein). Nicht blind 2 Liter bolus."},
{q:"Wann ist ein i.o.-Zugang indiziert?",opts:["Nie bei Alten als initiale Maßnahme vor Transport","Immer bei gesicherter Diagnose und Indikation","Bei fehlgeschlagenem i.v.-Zugang und Zeitdruck","Nur bei Kindern mit begleitender Sauerstofftherapie"],correct:2,explanation:"i.o.-Zugang wenn i.v.-Zugang nicht zeitnah gelingt und Volumengabe dringend erforderlich ist."}
,
{q:"Übergabe (SINNHAFT): Notfallereignis (N) bei Dehydratation – welche Kerninfo?",opts:["Nur ob der Patient Schmerzen hat nach differentialdiagnostischer Abwägung","Nur den Transportweg im Rahmen der Notfallversorgung","Nur die Diagnose nennen bei persistierender Symptomatik trotz Erstmaßnahmen, wobei die Wirksamkeit engmaschig kontrolliert werden muss","WAS: Verdachtsdiagnose, WIE: Ursache/Auslöser, WANN: Symptombeginn mit exakter Uhrzeit"],correct:3,explanation:"Dehydratation: Beim Notfallereignis immer WAS (Verdachtsdiagnose), WIE (Ursache/Auslöser), WANN (exakter Zeitpunkt) strukturiert übergeben."}]},
{id:26,title:"Kindliche Dehydratation",bpr:"dehydratation",scenario:"3-jähriges Kind, seit 3 Tagen Durchfall und Erbrechen. Apathisch, eingesunkene Fontanelle, Augen haloniert, trockene Schleimhäute. HF 160.",
steps:[
{q:"Wie schwer schätzen Sie die Dehydratation ein?",opts:["Schwer – deutliche Kreislaufzentralisierung","Keine nach Anlage eines venösen Zugangs, was jedoch in der aktuellen Situation kontraindiziert wäre","Leicht gemäß den Empfehlungen des ÄLRD","Moderat unter Beachtung der Dosierungsgrenzen"],correct:0,explanation:"Apathie + eingesunkene Fontanelle + halonierte Augen + Tachykardie = schwere Dehydratation."},
{q:"Richtige Therapie?",opts:["NaCl 0,9% Bolus 500 ml bei fortbestehender klinischer Verschlechterung","i.v.-Zugang → VEL, ggf. i.o. wenn i.v. nicht gelingt","Zum Trinken animieren mit paralleler Vorbereitung des Transports","Furosemid nach dokumentierter Erstuntersuchung"],correct:1,explanation:"Schwere Dehydratation beim Kind: i.v.-Zugang → VEL bedarfsgerecht. Bei fehlgeschlagenem i.v. → i.o."},
{q:"Worauf achten Sie besonders beim Transport?",opts:["Nur Sauerstoff","Temperaturerhalt","Nur Seitenlage","EKG-Monitoring unwichtig"],correct:1,explanation:"Kinder kühlen schnell aus → Temperaturerhalt! Plus regelmäßige Re-Evaluation ABCDE."},
{q:"Welche VEL-Menge geben Sie dem 15 kgKG Kind?",opts:["1 Liter/h unter Einbeziehung der Patientenanamnese","20 ml/h bei fehlendem Ansprechen auf Ersttherapie","Max. 10 ml/kgKG/h = max. 150 ml/h","500 ml Bolus als Eskalationsmaßnahme bei Therapieversagen"],correct:2,explanation:"Kinder: max. 10 ml/kgKG/h. 15 kg × 10 = max. 150 ml/h VEL."},
{q:"Was ist die gefährlichste Komplikation der Dehydratation beim Kind?",opts:["Nur Müdigkeit unter Berücksichtigung des Patientenalters","Fieber nach Erhebung eines Basis-Monitorings","Kopfschmerzen mit regelmäßiger Verlaufskontrolle","Hypovolämischer Schock → Organversagen"],correct:3,explanation:"Kinder dekompensieren rasch: Hypovolämischer Schock → Multiorganversagen. Frühzeitig behandeln!"}
,
{q:"Übergabe (SINNHAFT): Notfallpriorität (N) bei Dehydratation – nach welcher Struktur?",opts:["Alphabetisch nach Befunden bei Verdacht auf kritische Verschlechterung","Nach Dringlichkeit der Diagnostik unter Beachtung möglicher Wechselwirkungen","Nach persönlichem Ermessen als leitliniengerechte Notfallmaßnahme","Nach dem (x)ABCDE-Schema mit pathologischen Befunden und Vitalparametern"],correct:3,explanation:"Dehydratation: Notfallpriorität IMMER nach ABCDE strukturiert. Pathologische Befunde + Vitalparameter pro Buchstabe, auffällige Befunde hervorheben."}]},
{id:27,title:"Hitzekollaps mit Dehydratation",bpr:"dehydratation",scenario:"25-Jähriger, Marathon bei 35°C Außentemperatur. Zusammengebrochen. Verwirrt, trockene Haut, RR 85/50, HF 130, Temp 39,5°C.",
steps:[
{q:"Was ist das führende Problem?",opts:["Dehydratation + Hyperthermie","ACS nach klinischer Einschätzung","Nur Dehydratation","Sepsis gemäß Behandlungspfad"],correct:0,explanation:"Extreme Hitze + körperliche Belastung → Dehydratation + Hyperthermie (Hitzschlag möglich)."},
{q:"Was ist die wichtigste Sofortmaßnahme neben Kühlung?",opts:["Prednisolon bei stabilen Kreislaufverhältnissen","Volumentherapie (i.v.-Zugang → VEL)","Furosemid unter kontinuierlichem Monitoring","Midazolam nach ABCDE-Reevaluation"],correct:1,explanation:"i.v.-Zugang → VEL-Gabe ist essenziell bei hypovolämischem Schock durch Dehydratation."},
{q:"Hinweise auf Sepsis bei Fieber 39,5°C?",opts:["Sepsis nur im Winter bei gesichertem Atemweg und anschließende Reevaluation nach spätestens 5 Minuten","Nur bei älteren Patienten laut aktuellem Algorithmus","Ja, immer Sepsis bedenken bei Fieber + Hypotonie","Nein, klar Hitzeursache nach Sicherung der Vitalfunktionen"],correct:2,explanation:"Auch wenn die Ursache klar erscheint: Immer an Sepsis denken, besonders bei Hypotonie + Fieber."},
{q:"Welche Körpertemperatur ist ein Hitzschlag?",opts:["≥ 40°C mit ZNS-Dysfunktion","39°C unter Beachtung der Kontraindikationen","37,5°C bei dokumentierter Indikation","38°C mit anschließender Transportentscheidung"],correct:0,explanation:"Hitzschlag: Kerntemperatur ≥ 40°C + ZNS-Symptome (Verwirrtheit, Bewusstlosigkeit, Krampfanfall). Lebensbedrohlich!"},
{q:"Wie kühlen Sie den Patienten?",opts:["Eiswasser nach initialer Stabilisierung","Nur Schatten gemäß SOP des Rettungsdienstes","Kleidung entfernen, feuchte Tücher, Ventilator, kühle Infusionen","Gar nicht bei fehlenden Kontraindikationen"],correct:2,explanation:"Kühlung: Kleidung entfernen, feuchte Tücher + Luftbewegung, kühle (nicht eiskalte) Infusionen. Ziel: Temp < 39°C."}
,
{q:"Übergabe (SINNHAFT): Handlungen (H) bei Dehydratation – was wird oft vergessen?",opts:["Die Transportzeit unter Berücksichtigung des klinischen Bildes","Bewusst unterlassene Maßnahmen und deren Begründung","Die Einsatznummer mit Voranmeldung in der Zielklinik","Der Name des Fahrers nach Ausschluss reversibler Ursachen"],correct:1,explanation:"Dehydratation: Bei Handlungen nicht nur WAS getan wurde, sondern auch was bewusst NICHT getan wurde + Begründung. Ermöglicht dem Team die Entscheidung zu prüfen."}]},
{id:28,title:"Diabetische Ketoazidose",bpr:"hyperglyk",scenario:"19-jährige Typ-1-Diabetikerin. Polyurie, Polydipsie seit 2 Tagen, nun Übelkeit, Bauchschmerzen, Kussmaul-Atmung. BZ >500 mg/dl (Gerät: HI). GCS 12.",
steps:[
{q:"Was ist die Kussmaul-Atmung?",opts:["Tiefe, regelmäßige Atmung zur CO₂-Abatmung bei Azidose","Cheyne-Stokes-Atmung bei hämodynamischer Instabilität","Inverse Atmung unter Zeitdruck im Einsatzgeschehen","Flache Atmung als initiale Maßnahme vor Transport"],correct:0,explanation:"Kussmaul-Atmung: vertiefte, regelmäßige Atmung als Kompensation der metabolischen Azidose bei DKA."},
{q:"Welche Therapie erfolgt präklinisch?",opts:["Glucose i.v bei gesicherter Diagnose und Indikation","Bikarbonat i.v mit begleitender Sauerstofftherapie","Symptomatisch: i.v.-Zugang, VEL, ABCDE","Insulin i.v nach differentialdiagnostischer Abwägung"],correct:2,explanation:"Präklinisch: Symptomatische Therapie, VEL, ABCDE. Insulin ist präklinisch schlecht praktikabel."},
{q:"BZ >500 mg/dl, GCS 12. Worauf achten Sie trotzdem?",opts:["Nur Hyperglykämie behandeln im Rahmen der Notfallversorgung","Weitere Ursachen der Bewusstseinsstörung erwägen!","Glucagon geben bei persistierender Symptomatik trotz Erstmaßnahmen","ASS geben nach Anlage eines venösen Zugangs"],correct:1,explanation:"Bei Bewusstseinseinschränkung immer weitere Ursachen erwägen – nicht nur den hohen BZ!"},
{q:"Was unterscheidet DKA von hyperosmolarem Koma?",opts:["Nur das Alter gemäß den Empfehlungen des ÄLRD","Nur der BZ-Wert unter Beachtung der Dosierungsgrenzen","DKA: Typ 1, Ketoazidose, Kussmaul. Hyperosmolar: Typ 2, kaum Ketone, extreme Dehydratation","Nichts bei fortbestehender klinischer Verschlechterung, sofern keine allergischen Reaktionen in der Vorgeschichte bekannt sind"],correct:2,explanation:"DKA (Typ 1): Ketonkörper → Azidose → Kussmaul-Atmung. Hyperosmolar (Typ 2): Wenig Ketone, extreme Dehydratation."},
{q:"Welche Lagerung bei GCS 12?",opts:["Stabile Seitenlage bei Bewusstseinsstörung, Aspirationsschutz","Oberkörper hoch mit paralleler Vorbereitung des Transports","Flach nach dokumentierter Erstuntersuchung","Kopftieflage unter Einbeziehung der Patientenanamnese"],correct:0,explanation:"GCS 12 = bewusstseinsgetrübt → Aspirationsschutz! Stabile Seitenlage, Absaugbereitschaft."}
,
{q:"Übergabe (SINNHAFT): Notfallereignis (N) bei Hyperglykämie/DKA – welche Kerninfo?",opts:["Nur ob der Patient Schmerzen hat bei fehlendem Ansprechen auf Ersttherapie","WAS: Verdachtsdiagnose, WIE: Ursache/Auslöser, WANN: Symptombeginn mit exakter Uhrzeit","Nur die Diagnose nennen als Eskalationsmaßnahme bei Therapieversagen","Nur den Transportweg unter Berücksichtigung des Patientenalters"],correct:1,explanation:"Hyperglykämie/DKA: Beim Notfallereignis immer WAS (Verdachtsdiagnose), WIE (Ursache/Auslöser), WANN (exakter Zeitpunkt) strukturiert übergeben."}]},
{id:29,title:"Hyperglykämie durch Insulinpumpen-Defekt",bpr:"hyperglyk",scenario:"42-jähriger Typ-1-Diabetiker mit Insulinpumpe. Seit Stunden zunehmende Schwäche. BZ 380 mg/dl. Übelkeit, trockene Schleimhäute. Insulinpumpe piept Alarm.",
steps:[
{q:"Was ist die wahrscheinliche Ursache?",opts:["Neue Medikation nach Erhebung eines Basis-Monitorings","Insulinpumpen-Defekt (Katheter, Batterie, Reservoir)","Diätfehler mit regelmäßiger Verlaufskontrolle","Infektion bei Verdacht auf kritische Verschlechterung"],correct:1,explanation:"Alarmierende Insulinpumpe → V.a. technischer Defekt (häufig Katheterdislokation, leeres Reservoir)."},
{q:"Dürfen Sie als NotSan Insulin geben?",opts:["Ja, immer unter Beachtung möglicher Wechselwirkungen","Nur oral als leitliniengerechte Notfallmaßnahme","Nein, nicht präklinisch","Nur bei BZ > 600"],correct:2,explanation:"Insulin ist präklinisch schlecht praktikabel. Symptomatische Therapie + Transport."},
{q:"Was gehört zur erweiterten Anamnese?",opts:["Nur EKG nach klinischer Einschätzung","Nur Temperatur gemäß Behandlungspfad","Pumpenstatus, letzte Insulingabe, Infektzeichen, Diätfehler","Nur BZ messen bei stabilen Kreislaufverhältnissen mit sofortiger Dokumentation im Einsatzprotokoll und Voranmeldung"],correct:2,explanation:"Erweiterte Anamnese: Bekannter Diabetes? Pumpenstörung? Infektzeichen? Diätfehler? Steroidmedikation?"},
{q:"Was machen Sie mit der defekten Insulinpumpe?",opts:["Selbst reparieren unter kontinuierlichem Monitoring","Entfernen nach ABCDE-Reevaluation","Ignorieren bei gesichertem Atemweg","Dokumentieren, NICHT entfernen (Klinik braucht die Daten!)"],correct:3,explanation:"Insulinpumpe dokumentieren und belassen. Klinik kann Pumpendaten auslesen → Therapieoptimierung."},
{q:"Welche Differentialdiagnosen bedenken Sie?",opts:["Nur Diabetes laut aktuellem Algorithmus","Sepsis, ACS, Intoxikation, Schlaganfall","Nur Allergie nach Sicherung der Vitalfunktionen","Nur Hypoglykämie unter Beachtung der Kontraindikationen"],correct:1,explanation:"BZ-Entgleisung kann Begleiterscheinung sein: Sepsis, ACS, Intoxikation, Schlaganfall als DD erwägen."}
,
{q:"Übergabe (SINNHAFT): Notfallpriorität (N) bei Hyperglykämie/DKA – nach welcher Struktur?",opts:["Nach Dringlichkeit der Diagnostik bei dokumentierter Indikation, abhängig vom klinischen Verlauf und den erhobenen Vitalparametern","Nach dem (x)ABCDE-Schema mit pathologischen Befunden und Vitalparametern","Alphabetisch nach Befunden mit anschließender Transportentscheidung","Nach persönlichem Ermessen nach initialer Stabilisierung"],correct:1,explanation:"Hyperglykämie/DKA: Notfallpriorität IMMER nach ABCDE strukturiert. Pathologische Befunde + Vitalparameter pro Buchstabe, auffällige Befunde hervorheben."}]},
{id:30,title:"Hyperosmolares Koma beim Älteren",bpr:"hyperglyk",scenario:"78-jährige Typ-2-Diabetikerin. Seit Tagen zunehmend verwirrt. Heute nicht mehr ansprechbar. BZ 620 mg/dl. Keine Kussmaul-Atmung. Massiv dehydriert.",
steps:[
{q:"Warum fehlt die Kussmaul-Atmung?",opts:["Hyperosmolares Koma → geringe Ketonkörperproduktion, keine schwere Azidose","Messfehler gemäß SOP des Rettungsdienstes","Immer Kussmaul bei hohem BZ bei fehlenden Kontraindikationen","Patientin atmet nicht unter Berücksichtigung des klinischen Bildes"],correct:0,explanation:"Hyperosmolares hyperglykämisches Syndrom bei Typ 2: Wenig Ketonkörper, keine schwere Azidose → keine Kussmaul-Atmung."},
{q:"Was ist präklinisch vorrangig?",opts:["Bikarbonat mit Voranmeldung in der Zielklinik","Volumentherapie mit VEL + ABCDE","Glucose nach Ausschluss reversibler Ursachen","Insulin bei hämodynamischer Instabilität"],correct:1,explanation:"Massive Dehydratation steht im Vordergrund → VEL-Gabe, Atemwegssicherung bei GCS-Abfall, Transport."},
{q:"12-Kanal-EKG – warum?",opts:["Nur bei Brustschmerz unter Zeitdruck im Einsatzgeschehen","Standard bei jedem Einsatz als initiale Maßnahme vor Transport","Hyperkaliämie/Hypokaliämie möglich, ACS als DD","Nicht indiziert bei gesicherter Diagnose und Indikation"],correct:2,explanation:"EKG: Elektrolytstörungen (K⁺), begleitender Myokardinfarkt als Auslöser möglich."},
{q:"Wie schnell dürfen Sie den BZ senken?",opts:["Egal mit begleitender Sauerstofftherapie","Nur mit Insulin schnell nach differentialdiagnostischer Abwägung","Sofort normalisieren im Rahmen der Notfallversorgung","Langsam und kontrolliert (in Klinik) – zu schnelle Senkung → Hirnödem"],correct:3,explanation:"BZ-Senkung nur langsam und kontrolliert (klinisch). Zu rasche Senkung → osmotisches Hirnödem-Risiko."},
{q:"Was beachten Sie bezüglich Kalium?",opts:["Hyperkaliämie initial möglich, Hypokaliämie unter Therapie → EKG-Überwachung","Irrelevant bei persistierender Symptomatik trotz Erstmaßnahmen unter Berücksichtigung möglicher Differentialdiagnosen im Verlauf","Nur in Klinik relevant nach Anlage eines venösen Zugangs","Immer normal gemäß den Empfehlungen des ÄLRD"],correct:0,explanation:"K⁺-Verschiebungen bei Hyperglykämie/DKA. EKG-Überwachung essenziell (breite QRS, Spitz-T, HRST)."}
,
{q:"Übergabe (SINNHAFT): Handlungen (H) bei Hyperglykämie/DKA – was wird oft vergessen?",opts:["Der Name des Fahrers unter Beachtung der Dosierungsgrenzen","Bewusst unterlassene Maßnahmen und deren Begründung","Die Transportzeit bei fortbestehender klinischer Verschlechterung","Die Einsatznummer mit paralleler Vorbereitung des Transports"],correct:1,explanation:"Hyperglykämie/DKA: Bei Handlungen nicht nur WAS getan wurde, sondern auch was bewusst NICHT getan wurde + Begründung. Ermöglicht dem Team die Entscheidung zu prüfen."}]},
{id:31,title:"Hypertensive Krise mit Kopfschmerzen",bpr:"hypertensiv",scenario:"55-jähriger Mann, plötzlich stärkste Kopfschmerzen, Schwindel, Sehstörungen. RR 240/130. Keine fokalen neurologischen Ausfälle.",
steps:[
{q:"Welches Medikament setzen Sie ein?",opts:["Metoprolol","Glyceroltrinitrat","Furosemid","Urapidil i.v."],correct:3,explanation:"Urapidil i.v. ist das Mittel der Wahl beim hypertensiven Notfall im Rettungsdienst."},
{q:"Wie stark darf der RR gesenkt werden?",opts:["Max. 20-25% Senkung","Um 50% nach dokumentierter Erstuntersuchung","Auf Normalwerte","Gar nicht unter Einbeziehung der Patientenanamnese"],correct:0,explanation:"Ziel: Kontrollierte RR-Senkung um max. 20-25%. Keine abrupte Normalisierung!"},
{q:"Wann setzen Sie Glyceroltrinitrat ein?",opts:["Nur oral bei fehlendem Ansprechen auf Ersttherapie","Nur bei kardialer Symptomatik (Dyspnoe, pectanginöse Beschwerden)","Nie bei Hypertonie als Eskalationsmaßnahme bei Therapieversagen","Immer unter Berücksichtigung des Patientenalters, nach vorheriger Abklärung aller reversiblen Ursachen gemäß Algorithmus"],correct:1,explanation:"Glyceroltrinitrat nur bei hypertensivem Notfall MIT kardialer Symptomatik (Lungenödem, ACS)."},
{q:"Wie schnell applizieren Sie Urapidil?",opts:["Sofort als Kurzinfusion","Als Bolus nach Erhebung eines Basis-Monitorings","Oral mit regelmäßiger Verlaufskontrolle","Langsam i.v. über 20 Sekunden"],correct:3,explanation:"Urapidil 12,5-25 mg langsam i.v. über 20 Sekunden. Kontrollierte Senkung, nicht abrupt!"},
{q:"Was sind Endorganschäden beim hypertensiven Notfall?",opts:["Nur Kopfschmerzen bei Verdacht auf kritische Verschlechterung","Nur Nasenbluten unter Beachtung möglicher Wechselwirkungen","Hirnblutung, Lungenödem, Aortendissektion, Nierenversagen, Retinopathie","Nur Schwindel als leitliniengerechte Notfallmaßnahme"],correct:2,explanation:"Endorganschäden: ZNS (Blutung, Enzephalopathie), Herz (Lungenödem, ACS), Aorta (Dissektion), Niere, Augen."}
,
{q:"Übergabe (SINNHAFT): Notfallereignis (N) bei Hypertensiver Notfall – welche Kerninfo?",opts:["Nur die Diagnose nennen nach klinischer Einschätzung","WAS: Verdachtsdiagnose, WIE: Ursache/Auslöser, WANN: Symptombeginn mit exakter Uhrzeit","Nur ob der Patient Schmerzen hat gemäß Behandlungspfad","Nur den Transportweg bei stabilen Kreislaufverhältnissen"],correct:1,explanation:"Hypertensiver Notfall: Beim Notfallereignis immer WAS (Verdachtsdiagnose), WIE (Ursache/Auslöser), WANN (exakter Zeitpunkt) strukturiert übergeben."}]},
{id:32,title:"Hypertensiver Notfall mit Lungenödem",bpr:"hypertensiv",scenario:"68-jährige Frau, RR 260/140, massive Dyspnoe, feuchte RG beidseits, SpO₂ 82%. Schaumiges Sputum.",
steps:[
{q:"Was liegt hier zusätzlich vor?",opts:["Pneumonie unter kontinuierlichem Monitoring","Asthma nach ABCDE-Reevaluation","COPD bei gesichertem Atemweg","Kardiales Lungenödem"],correct:3,explanation:"Schaumiges Sputum + feuchte RG + schwere Hypertonie = hypertensiver Notfall mit kardialem Lungenödem."},
{q:"Welche Therapie kombinieren Sie?",opts:["Urapidil + Glyceroltrinitrat + CPAP + Furosemid","Volumen + Epinephrin laut aktuellem Algorithmus, wobei die Wirksamkeit engmaschig kontrolliert werden muss","Nur Sauerstoff nach Sicherung der Vitalfunktionen","Nur Urapidil unter Beachtung der Kontraindikationen"],correct:0,explanation:"Kombination: Urapidil (RR-Senkung) + Glyceroltrinitrat (Vorlastsenkung) + CPAP + Furosemid."},
{q:"Wann geben Sie Furosemid?",opts:["Erst wenn RR gesenkt und CPAP läuft","Nie","Sofort","Nur wenn Notarzt da"],correct:2,explanation:"Furosemid 20 mg i.v. beim kardialen Lungenödem – zeitnah beginnen."},
{q:"Warum ist CPAP hier besonders wichtig?",opts:["Nur O₂-Gabe bei dokumentierter Indikation, was jedoch in der aktuellen Situation kontraindiziert wäre","Nur Komfort mit anschließender Transportentscheidung","PEEP drückt Lungenödem-Flüssigkeit zurück + verbessert Oxygenierung","Verhindert Hyperventilation nach initialer Stabilisierung"],correct:2,explanation:"CPAP/PEEP: Verbessert Oxygenierung, drückt intraalveoläre Flüssigkeit zurück, reduziert Vorlast und Nachlast."},
{q:"Glyceroltrinitrat-Dosis?",opts:["0,4 mg sublingual, Repetition nach 5 min möglich","2 mg gemäß SOP des Rettungsdienstes","0,1 mg bei fehlenden Kontraindikationen","5 mg i.v unter Berücksichtigung des klinischen Bildes"],correct:0,explanation:"Glyceroltrinitrat 0,4 mg sublingual (2 Hübe). Repetition nach 5 min möglich. Cave: RR < 100 mmHg = KI."}
,
{q:"Übergabe (SINNHAFT): Notfallpriorität (N) bei Hypertensiver Notfall – nach welcher Struktur?",opts:["Nach dem (x)ABCDE-Schema mit pathologischen Befunden und Vitalparametern","Alphabetisch nach Befunden mit Voranmeldung in der Zielklinik","Nach Dringlichkeit der Diagnostik nach Ausschluss reversibler Ursachen und anschließende Reevaluation nach spätestens 5 Minuten","Nach persönlichem Ermessen bei hämodynamischer Instabilität"],correct:0,explanation:"Hypertensiver Notfall: Notfallpriorität IMMER nach ABCDE strukturiert. Pathologische Befunde + Vitalparameter pro Buchstabe, auffällige Befunde hervorheben."}]},
{id:33,title:"Hypertension ohne Symptome",bpr:"hypertensiv",scenario:"50-Jähriger, Routineeinsatz. RR 210/110, aber keine Kopfschmerzen, keine Sehstörungen, keine Dyspnoe. Fühlt sich wohl.",
steps:[
{q:"Ist dies ein hypertensiver NOTFALL?",opts:["Irrelevant unter Zeitdruck im Einsatzgeschehen","Immer Notfall ab 200 als initiale Maßnahme vor Transport","Nein – keine klinischen Symptome = hypertensive Krise/Dringlichkeit, kein Notfall","Ja, RR > 200 bei gesicherter Diagnose und Indikation"],correct:2,explanation:"Hypertensiver Notfall = erhöhter RR MIT Endorgansymptomen. Ohne Symptome: hypertensive Krise/Dringlichkeit."},
{q:"Was tun Sie?",opts:["Glyceroltrinitrat mit begleitender Sauerstofftherapie","Sofort Urapidil i.v nach differentialdiagnostischer Abwägung","Furosemid im Rahmen der Notfallversorgung","Verordnete antihypertensive Dauermedikation vorziehen lassen"],correct:3,explanation:"Ohne Symptome: Vorziehen der verordneten Dauermedikation, Überwachung, ggf. Transport."},
{q:"Wann ist der Transport indiziert?",opts:["Bei persistierend hohen Werten oder neuen Symptomen","Sofort Hubschrauber bei persistierender Symptomatik trotz Erstmaßnahmen","Nur wenn Patient will nach Anlage eines venösen Zugangs","Nie bei fehlenden Symptomen gemäß den Empfehlungen des ÄLRD"],correct:0,explanation:"Regelmäßige Re-Evaluation. Transport bei persistierender Hypertension oder neuen Symptomen."},
{q:"Was bedeutet 'hypertensive Dringlichkeit' vs. 'Notfall'?",opts:["Notfall = immer RR > 250 unter Beachtung der Dosierungsgrenzen","Gleiches bei fortbestehender klinischer Verschlechterung","Dringlichkeit: erhöhter RR OHNE Endorganschaden. Notfall: MIT Endorganschaden","Nur zeitlicher Unterschied mit paralleler Vorbereitung des Transports"],correct:2,explanation:"Dringlichkeit: RR erhöht, aber keine akuten Endorganschäden. Notfall: RR erhöht MIT akuten Endorganschäden."},
{q:"Wann alarmiert der Patient den Rettungsdienst erneut?",opts:["Nur bei RR > 300 nach dokumentierter Erstuntersuchung","Nie unter Einbeziehung der Patientenanamnese","Morgen bei fehlendem Ansprechen auf Ersttherapie","Bei neuen Symptomen: Kopfschmerzen, Sehstörungen, Brustschmerz, Atemnot"],correct:3,explanation:"Wiedervorstellungskriterien: Neue Kopfschmerzen, Sehstörungen, Brustschmerz, Atemnot, neurologische Ausfälle."}
,
{q:"Übergabe (SINNHAFT): Handlungen (H) bei Hypertensiver Notfall – was wird oft vergessen?",opts:["Bewusst unterlassene Maßnahmen und deren Begründung","Die Einsatznummer als Eskalationsmaßnahme bei Therapieversagen","Der Name des Fahrers unter Berücksichtigung des Patientenalters","Die Transportzeit nach Erhebung eines Basis-Monitorings"],correct:0,explanation:"Hypertensiver Notfall: Bei Handlungen nicht nur WAS getan wurde, sondern auch was bewusst NICHT getan wurde + Begründung. Ermöglicht dem Team die Entscheidung zu prüfen."}]},
{id:34,title:"Hypoglykämischer Krampfanfall",bpr:"hypoglyk",scenario:"45-jährige Diabetikerin (Typ 1). Verwirrtheit, dann generalisierter Krampfanfall. BZ 28 mg/dl, SpO₂ 91%, GCS 3.",
steps:[
{q:"Was hat Priorität?",opts:["BZ-Korrektur mit regelmäßiger Verlaufskontrolle","Krampfdurchbrechung mit Midazolam","Intubation bei Verdacht auf kritische Verschlechterung","EKG unter Beachtung möglicher Wechselwirkungen"],correct:1,explanation:"Aktiver Krampfanfall zuerst durchbrechen! Dann BZ-Korrektur."},
{q:"Kein i.v.-Zugang möglich. Wie behandeln Sie die Hypoglykämie?",opts:["Glucagon 1 mg i.m.","Glucose 40% rectal","Abwarten als leitliniengerechte Notfallmaßnahme","Orale Glucose"],correct:0,explanation:"Ohne i.v.-Zugang und bei bewusstlosem Patienten: Glucagon 1 mg i.m. (>25 kgKG)."},
{q:"i.v.-Zugang gelingt. Welche Glucose-Dosis?",opts:["8-10 g i.v. (max. 20%ig)","100 ml Glucose 5%","2-3 g nach klinischer Einschätzung","50 g gemäß Behandlungspfad"],correct:0,explanation:"Erwachsene: 8-10 g Glucose i.v., max. 20%ig, mit VEL zusammen applizieren."},
{q:"Wann kontrollieren Sie den BZ?",opts:["In der Klinik","Nach ca. 5 Minuten","Sofort bei stabilen Kreislaufverhältnissen","Nach 30 Minuten"],correct:1,explanation:"BZ-Kontrolle nach ca. 5 min. Ziel: > 90 mg/dl. Bei Nichterreichen: Repetition."},
{q:"Warum ist Glucose i.v. besser als Glucagon bei möglichem Alkoholmissbrauch?",opts:["Glucagon benötigt Glykogenreserven – die bei Alkoholikern erschöpft sein können","Schmeckt besser unter kontinuierlichem Monitoring","Kein Unterschied nach ABCDE-Reevaluation","Glucagon ist immer besser bei gesichertem Atemweg"],correct:0,explanation:"Glucagon wirkt über Glykogenolyse. Bei erschöpften Glykogenreserven (Alkohol, Hunger) wirkungslos → Glucose i.v. bevorzugt."}
,
{q:"Übergabe (SINNHAFT): Notfallereignis (N) bei Hypoglykämie – welche WANN-Info zählt?",opts:["Wann die letzte Insulingabe regulär fällig war laut aktuellem Algorithmus","Wann der Patient zuletzt beim Arzt war nach Sicherung der Vitalfunktionen","Wann der Diabetes diagnostiziert wurde unter Beachtung der Kontraindikationen, sofern keine allergischen Reaktionen in der Vorgeschichte bekannt sind","WANN: Zeitpunkt der BZ-Messung + niedrigster gemessener Wert + letzte Nahrungsaufnahme"],correct:3,explanation:"Hypoglykämie-Ereignis: Zeitpunkt + niedrigster BZ-Wert + letzte Nahrungsaufnahme. Ursache: Insulin-Überdosis? Mahlzeit ausgelassen? Alkohol?"}]},
{id:35,title:"Leichte Hypoglykämie beim Diabetiker",bpr:"hypoglyk",scenario:"60-jähriger Diabetiker (Typ 2). Zitterig, schweißig, verwirrt. BZ 45 mg/dl. Ansprechbar, Schluckfähigkeit erhalten.",
steps:[
{q:"Patient ist wach und schluckfähig. Was ist die richtige Therapie?",opts:["Infusion VEL bei dokumentierter Indikation","Orale Glucose (Traubenzucker, Saft)","Glucagon i.m mit anschließender Transportentscheidung","Glucose i.v nach initialer Stabilisierung"],correct:1,explanation:"Wach + schluckfähig = orale Glucosegabe bevorzugt! Einfach, schnell, effektiv."},
{q:"Wann kontrollieren Sie den BZ nach oraler Gabe?",opts:["Nach ca. 10 Minuten","Gar nicht gemäß SOP des Rettungsdienstes","Nach 1 Stunde","Sofort bei fehlenden Kontraindikationen"],correct:0,explanation:"BZ-Kontrolle nach ca. 10 Minuten bei oraler Gabe. Ziel: > 90 mg/dl."},
{q:"BZ nach 10 min: 95 mg/dl. Darf der Patient zu Hause bleiben?",opts:["Nur wenn Notarzt zustimmt unter Berücksichtigung des klinischen Bildes","Nie mit Voranmeldung in der Zielklinik","Nur mit Aufklärung, regelmäßigen Kontrollen und gesicherter Betreuung","Ja, immer nach Ausschluss reversibler Ursachen"],correct:2,explanation:"Verbleib zu Hause möglich bei unauffälliger Rekompensation, gesicherter Betreuung und Aufklärung."},
{q:"Was muss bei sulfonylharnstoff-induzierter Hypoglykämie beachtet werden?",opts:["Sofort entlassen bei hämodynamischer Instabilität","Lange Wirkdauer → Rückfallgefahr über Stunden, immer Kliniktransport","Einmalige Glucose reicht unter Zeitdruck im Einsatzgeschehen","Nichts Besonderes als initiale Maßnahme vor Transport mit sofortiger Dokumentation im Einsatzprotokoll und Voranmeldung"],correct:1,explanation:"Sulfonylharnstoffe wirken lang → Rückfall-Hypoglykämie über Stunden möglich. IMMER Kliniktransport!"},
{q:"Was raten Sie dem Patienten bei Verbleib vor Ort?",opts:["Insulin spritzen bei gesicherter Diagnose und Indikation","Nichts mit begleitender Sauerstofftherapie","Kohlenhydratreiche Mahlzeit einnehmen, Kontrolle sicherstellen","Sport treiben nach differentialdiagnostischer Abwägung"],correct:2,explanation:"Nach BZ-Normalisierung: Kohlenhydratreiche Mahlzeit, regelmäßige BZ-Kontrollen, Betreuungsperson informieren."}
,
{q:"Übergabe (SINNHAFT): Handlungen (H) bei Hypoglykämie – welche Info braucht die Klinik?",opts:["Nur dass Glucose gegeben wurde im Rahmen der Notfallversorgung","Nur der aktuelle BZ bei persistierender Symptomatik trotz Erstmaßnahmen","Glucose: Menge + Applikationsweg (oral/i.v.) + Zeitpunkt + BZ-Verlauf (Kontroll-BZ nach Gabe!)","Nur ob der Patient wieder wach ist nach Anlage eines venösen Zugangs"],correct:2,explanation:"Hypoglykämie-Handlungen: Glucose (Menge, Weg, Zeitpunkt) + Kontroll-BZ-Werte! + Ansprechen auf Therapie (GCS-Verbesserung?). Bei Sulfonylharnstoff: Rezidivgefahr!"}]},
{id:36,title:"Hypoglykämie beim Kind",bpr:"hypoglyk",scenario:"8-jähriges Kind (Typ-1-Diabetes). Bewusstlos, tonuslos. BZ 32 mg/dl. Kein i.v.-Zugang möglich.",
steps:[
{q:"Wie geben Sie Glucagon bei einem Kind >25 kgKG?",opts:["1 mg i.m.","0,5 mg i.m.","3 mg nasal","2 mg i.m."],correct:0,explanation:"Kinder > 25 kgKG: 1 mg Glucagon i.m. Alternative: 3 mg Glucagon nasal (ab 4 Jahren)."},
{q:"Alternativ nasal – welche Dosis?",opts:["1 mg gemäß den Empfehlungen des ÄLRD","3 mg Glucagon nasal (Baqsimi®)","2 mg unter Beachtung der Dosierungsgrenzen","0,5 mg bei fortbestehender klinischer Verschlechterung"],correct:1,explanation:"Baqsimi® 3 mg intranasal ab 4 Jahren möglich."},
{q:"i.v.-Zugang gelingt. Glucose-Dosis für 25 kgKG?",opts:["5 g (0,2 g/kgKG)","1 g mit paralleler Vorbereitung des Transports","20 g nach dokumentierter Erstuntersuchung","8-10 g unter Einbeziehung der Patientenanamnese"],correct:0,explanation:"Kinder: 0,2 g/kgKG Glucose i.v. → 25 × 0,2 = 5 g. Max. 20%ig mit VEL applizieren."},
{q:"Welche Glucose-Konzentration verwenden Sie bei Kindern?",opts:["Glucose 50% bei fehlendem Ansprechen auf Ersttherapie","Max. Glucose 20% (mit VEL verdünnen)","Glucose 40% als Eskalationsmaßnahme bei Therapieversagen","Glucose 5% unter Berücksichtigung des Patientenalters"],correct:1,explanation:"Kinder: Max. Glucose 20%! Höhere Konzentrationen → Gewebeschäden bei Paravasation. Mit VEL verdünnen."},
{q:"Was tun Sie, wenn BZ nach 5 min noch < 90 mg/dl?",opts:["Transport ohne weitere Therapie","Insulin geben nach Erhebung eines Basis-Monitorings","Abwarten mit regelmäßiger Verlaufskontrolle","Repetition der Glucose-Gabe (0,2 g/kgKG)"],correct:3,explanation:"Ziel > 90 mg/dl nicht erreicht → Repetition. Kinder: 0,2 g/kgKG Glucose i.v. erneut."}
,
{q:"Übergabe (SINNHAFT): Anamnese (A) bei Hypoglykämie – was ist klinisch entscheidend?",opts:["Nur ob der Patient Insulin spritzt bei Verdacht auf kritische Verschlechterung","Nur die Diagnose Diabetes unter Beachtung möglicher Wechselwirkungen","Diabetestyp, Insulinart + Dosis, Sulfonylharnstoff (Rezidivgefahr!), Alkoholkonsum, Niereninsuffizienz","Nur der HbA1c als leitliniengerechte Notfallmaßnahme"],correct:2,explanation:"Hypoglykämie-Anamnese: Diabetestyp, Insulinschema, Sulfonylharnstoff (→ prolongierte Hypo!), Alkohol, Nierenfunktion (verminderte Insulin-Clearance)."}]},
{id:37,title:"Hypothermie Stadium II",bpr:"hypothermie",scenario:"65-jähriger Obdachloser, im Winter draußen aufgefunden. Bewusstsein beeinträchtigt, kein Kältezittern mehr. Kerntemperatur ca. 31°C.",
steps:[
{q:"Welchem Hypothermie-Stadium entspricht dieser Befund?",opts:["Stadium III nach klinischer Einschätzung","Stadium IV gemäß Behandlungspfad","Stadium I bei stabilen Kreislaufverhältnissen","Stadium II (beeinträchtigtes Bewusstsein, kein Frieren)"],correct:3,explanation:"Stadium II: Beeinträchtigtes Bewusstsein ohne Frieren/Kältezittern."},
{q:"Was ist die wichtigste Erstmaßnahme?",opts:["Aktive Wiedererwärmung mit heißem Wasser","Sofort ins warme Fahrzeug tragen","Warme Infusion als Bolus unter kontinuierlichem Monitoring","Immobilisation + Wärmeerhalt (passive Isolation)"],correct:3,explanation:"Stadium II/III: Immobilisation + passive Wärmeisolation. Vorsichtiger Umgang (Bergungstod-Gefahr!)."},
{q:"Warum ist Immobilisation so wichtig?",opts:["Keine Bewegung bei Kälte nach ABCDE-Reevaluation","Frakturgefahr bei gesichertem Atemweg","Zur Dokumentation laut aktuellem Algorithmus","Kaltes Blut kann bei Bewegung zum Herzen gelangen → Herzrhythmusstörungen"],correct:3,explanation:"Afterdrop: Kaltes peripheres Blut strömt bei Bewegung zum Herzen → Kammerflimmern möglich!"},
{q:"Was dürfen Sie bei Hypothermie Stadium II NICHT tun?",opts:["Aktiv bewegen, reiben oder heiße Getränke geben","Monitoring nach Sicherung der Vitalfunktionen, abhängig vom klinischen Verlauf und den erhobenen Vitalparametern","Rettungsdecke unter Beachtung der Kontraindikationen","Transport bei dokumentierter Indikation"],correct:0,explanation:"KEINE aktive Bewegung, KEIN Reiben, KEINE heißen Getränke bei Stadium II+. Afterdrop-Gefahr!"},
{q:"Welche HRST drohen?",opts:["Keine mit anschließender Transportentscheidung","Nur Tachykardie nach initialer Stabilisierung","VF, VT, Asystolie bei < 30°C","Nur Vorhofflimmern"],correct:2,explanation:"Bei Kerntemperatur < 30°C: Hohes Risiko für VF, VT, Asystolie. Vorsichtiger Umgang essenziell."}
,
{q:"Übergabe (SINNHAFT): Notfallereignis (N) bei Hypothermie – welche Kerninfo?",opts:["WAS: Verdachtsdiagnose, WIE: Ursache/Auslöser, WANN: Symptombeginn mit exakter Uhrzeit","Nur ob der Patient Schmerzen hat gemäß SOP des Rettungsdienstes","Nur den Transportweg bei fehlenden Kontraindikationen","Nur die Diagnose nennen unter Berücksichtigung des klinischen Bildes unter Berücksichtigung möglicher Differentialdiagnosen im Verlauf"],correct:0,explanation:"Hypothermie: Beim Notfallereignis immer WAS (Verdachtsdiagnose), WIE (Ursache/Auslöser), WANN (exakter Zeitpunkt) strukturiert übergeben."}]},
{id:38,title:"Hypothermie Stadium IV mit Kreislaufstillstand",bpr:"hypothermie",scenario:"Skifahrer nach Lawinenverschüttung, 45 min unter Schnee. Keine Vitalzeichen. Kerntemperatur geschätzt < 28°C.",
steps:[
{q:"Wird reanimiert?",opts:["Ja – niemand ist tot, solange er nicht warm und tot ist","Nur wenn VF im EKG mit Voranmeldung in der Zielklinik","Nur kurz nach Ausschluss reversibler Ursachen","Nein, sicher tot bei hämodynamischer Instabilität"],correct:0,explanation:"'Nobody is dead until warm and dead.' Bei Hypothermie wird reanimiert und in eine Klinik mit Herz-Lungen-Maschine transportiert."},
{q:"Medikamentengabe bei Hypothermie <30°C?",opts:["Normal dosieren unter Zeitdruck im Einsatzgeschehen","Keine Medikamente je als initiale Maßnahme vor Transport","Doppelte Dosis bei gesicherter Diagnose und Indikation","Medikamentenintervalle verlängern / zurückhalten"],correct:3,explanation:"Bei Kerntemperatur < 30°C: Medikamentengabe zurückhalten oder Intervalle deutlich verlängern."},
{q:"Defibrillation bei Hypothermie?",opts:["Max. 3 Versuche, dann erst nach Erwärmung weitere","Nur mit AED mit begleitender Sauerstofftherapie","Nie nach differentialdiagnostischer Abwägung","Unbegrenzt im Rahmen der Notfallversorgung"],correct:0,explanation:"Bei VF und Hypothermie: Max. 3 Defibrillationsversuche. Weitere Schocks erst nach Wiedererwärmung."},
{q:"Wo wird der Patient transportiert?",opts:["Klinik mit Möglichkeit der extrakorporalen Wiedererwärmung (ECLS/ECMO)","Ambulant bei persistierender Symptomatik trotz Erstmaßnahmen, nach vorheriger Abklärung aller reversiblen Ursachen gemäß Algorithmus","Nächstes Krankenhaus nach Anlage eines venösen Zugangs","Hausarzt gemäß den Empfehlungen des ÄLRD"],correct:0,explanation:"Schwere Hypothermie mit Kreislaufstillstand → Klinik mit ECLS/ECMO zur extrakorporalen Wiedererwärmung."},
{q:"Ab welcher Temperatur gelten die Defi-Einschränkungen?",opts:["< 25°C","< 35°C","< 30°C","< 20°C"],correct:2,explanation:"< 30°C: Max. 3 Defi-Versuche, Medikamente zurückhalten/Intervalle verlängern. Zwischen 30-35°C: Intervalle verlängern."}
,
{q:"Übergabe (SINNHAFT): Notfallpriorität (N) bei Hypothermie – nach welcher Struktur?",opts:["Nach Dringlichkeit der Diagnostik unter Beachtung der Dosierungsgrenzen","Nach persönlichem Ermessen bei fortbestehender klinischer Verschlechterung","Nach dem (x)ABCDE-Schema mit pathologischen Befunden und Vitalparametern","Alphabetisch nach Befunden mit paralleler Vorbereitung des Transports"],correct:2,explanation:"Hypothermie: Notfallpriorität IMMER nach ABCDE strukturiert. Pathologische Befunde + Vitalparameter pro Buchstabe, auffällige Befunde hervorheben."}]},
];
